### ISSUE TITLE
Minetest/Luanti naming

### ISSUE THREAD

**Issue by contrarybaton60** [ivan-hc/AM#1005]
Recently, the Minetest team announced that they will be renaming to "Luanti".

https://blog.minetest.net/2024/10/13/Introducing-Our-New-Name/

It would be best for the minetest package to accept both minetest and luanti names when trying to installing it.

Choices:

rename minetest to luanti and make minetest name redirect to it

or...

keep minetest name and make luanti redirect to it

**Comment by ivan-hc** [comment]
The installation script redirects to this repo https://github.com/An0n3m0us/Minetest-AppImages, and also if they rename the repo, github allows redirections from old URL to the new one. In case the script does not downloads anythng anymore, let me know, I'll try to correct it ASAP. If they decide to build the AppImage on a new repo, its enough to change the download reference in the script... and maybe I'll rename the app if the name is changed. Until then, we have time enough. You can open the issue when they release the new build with the new name.

**Comment by prodigalshadow** [comment]
Good day! as per the maintainer, he will retire the minetest AppImage unless he sees a large demand for it (https://github.com/An0n3m0us/Minetest-AppImages/issues/19). Fortunately, I found a repo that houses the latest one (https://github.com/rollerozxa/luanti-appimage/). Maybe you can redirect the script to this repo? Thanks!
