### ISSUE TITLE
Migu

### ISSUE THREAD

**Issue by GeoBoi254** [ivan-hc/AM#1013]
To help us make adding AppImages quicker and easier, please try to follow the following two syntaxes.

## If available on Github.com
- name (lowercase, this will be the command to use)
- repository (URL, DO NOT use direct download link)

## If available on other sites
- name (lowercase, this will be the command to use)
- main site, repository or reference web page (URL, DO NOT use direct download link)
- download page (if different from the main page)
- description of the application

--------------------------------------------------

# List of AppImages to add
migu
https://github.com/NoCrypt/migu

**Comment by contrarybaton60** [comment]
~~You didn't do the bare minimum~~

To help us make adding AppImages quicker and easier, please try to follow the following two syntaxes.
# If available on Github.com

- migu (lowercase, this will be the command to use)
- https://github.com/NoCrypt/migu (URL, DO NOT use direct download link)
- Stream anime torrents, real-time with no waiting for downloads  (description)
