### ISSUE TITLE
install manual downloaded appimage

### ISSUE THREAD

**Issue by Mike710Shine** [ivan-hc/AM#1015]
Hi,
i have one question, is it possible to install a manually downloaded appimage?

**Comment by ivan-hc** [comment]
If you mean to go to the site and download the app manually, yes, you must navigate the catalogue https://portable-linux-apps.github.io/

If you mean to integrate appimages downloaded by drag/drop the way you do with appimagelauncher and gearlever, yes, we have a `--launcher` option, see https://github.com/ivan-hc/AM#integrate-local-appimages-into-the-menu-by-dragging-and-dropping-them
