### ISSUE TITLE
light weight  epub reader  like zathura

### ISSUE THREAD

**Issue by anycloudcm** [ivan-hc/AM#1016]
I like calibre but its little bit heavy i wany something like zathura ,i have debian 12 in which few  dependency  like pdf support but no epub support  (like in https://wiki.archlinux.org/title/Zathura mentioned  just like in  arch all zathura depencies like ps poppler epub mupdf ...,etc is there)  is it possible so that we can have a portable Appimage zatura Pdf/epub with all depencies  ,refer links: 1. https://packages.debian.org/search?keywords=zathura&searchon=names&suite=all&section=all 2.https://archlinux.org/packages/?q=Zathura 3.https://aur.archlinux.org/packages?O=0&SeB=nd&K=zathura&outdated=&SB=p&SO=d&PP=50&submit=Go

**Comment by ivan-hc** [comment]
Hi, I no longer build AppImage packages, especially when it comes to programs I don't use personally. In fact, I'm gradually closing my repositories if the upstream developers provide a working official AppImage.

By the way, I'm encouraging users interested in some specific apps to try Archimage https://github.com/ivan-hc/ArchImage , I can suggest another issue as a reference to start building your own, for example https://github.com/ivan-hc/AM/issues/996 , the same videos and examples are present in the README of the Archimage repo, under [Tutorial](https://github.com/ivan-hc/ArchImage#tutorial)

If you are looking for alternative PDF readers, you can run `am -q pdf` or `am -q document`, or consult the dedicated category directly in the catalog https://portable-linux-apps.github.io/office.html
