### ISSUE TITLE
Universal Media Server

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1021]
To help us make adding applications quicker and easier, please try to follow the following two syntaxes.

## If available on Github.com
- name (lowercase, this will be the command to use)
- ums
- repository (URL, DO NOT use direct download link)
https://github.com/UniversalMediaServer/UniversalMediaServer

## If available on other sites
- name (lowercase, this will be the command to use)
universal media server
- main site, repository or reference web page (URL, DO NOT use direct download link)
https://www.universalmediaserver.com/
- download page (if different from the main page)
- https://www.universalmediaserver.com/download/
- description of the application
- A DLNA, UPnP and HTTP(S) Media Server.

(Sorry I cant really write the .desktop file)
# Important!
The two syntaxes mentioned above are enough for programs that can only be used from the command line.

However, for graphical programs and programs that require integration into the menu, and therefore a launcher, also add the following two pieces of information:
- URL to the application icon
- https://avatars.githubusercontent.com/u/1840565?s=280&v=4
- the .desktop* file, you can choose whether...
  - add a URL to the .desktop file, if it exists
  - paste the content of the file directly
  - drag a text file into your comment
  - provide only the following desktop entries, so that we can create a minimal and unofficial launcher
    - Name=Universal Media Server
    - Exec=UMS.sh
    - Categories=AudioVideo;Network

--------------------------------------------------

# List of portable applications to add
Universal Media Server

**Comment by Twig6943** [comment]
@ivan-hc hold on, have a look at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1701

**Comment by ivan-hc** [comment]
> @ivan-hc hold on, have a look at [UniversalMediaServer/UniversalMediaServer#1701](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1701)

ok, in the meantime I'll take the dog out... see you later

**Comment by Twig6943** [comment]
> @ivan-hc hold on, have a look at [UniversalMediaServer/UniversalMediaServer#1701](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1701)

@ivan-hc use this https://github.com/Twig6943/Universal-Media-Server

**Comment by ivan-hc** [comment]
thank you
