### ISSUE TITLE
[Portable Package Request] FluffyChat

### ISSUE THREAD

**Issue by contrarybaton60** [ivan-hc/AM#1023]
To help us make adding applications quicker and easier, please follow the syntax below (**NOTE that if point 2 is a github repository, you can remove points 3 and 4**, and **if the program is a CLI you can remove point 5 and 6**).

1. fluffychat (lowercase, this will be the command to use)
2. https://fluffychat.im/
3. https://github.com/krille-chan/fluffychat/releases
4. The cutest instant messenger in the [matrix]
5. https://github.com/krille-chan/fluffychat/blob/main/assets/logo.svg (ugh there is a background tho)
6. https://github.com/krille-chan/fluffychat/blob/main/appimage/FluffyChat.desktop

There are instructions on making .AppImage builds of FluffyChat, though I haven't anyone making any. Perhaps I make some through github actions. for now let's just use the portable builds.

**Comment by ivan-hc** [comment]
done
