### ISSUE TITLE
Teamviewer

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1024]
To help us make adding applications quicker and easier, please follow the syntax below (**NOTE that if point 2 is a github repository, you can remove points 3 and 4**, and **if the program is a CLI you can remove point 5 and 6**).

1. name: teamviewer
3. main site: https://www.teamviewer.com
4. download page: https://www.teamviewer.com/en-mea/download/linux/
5. description of the application: A secure and scalable remote connectivity platform for your business.
6. URL to the application icon: https://play-lh.googleusercontent.com/kiuamHjSKvVwS2fZ9c3dgPBPLDNQhExfw_8_vWhTdFMIQp1Lnf5gl5ZPbO2R55BzBk4=w240-h480-rw
7. the .desktop* file (choose whether to add a URL, to paste the content of the file, to drag a text file into your comment or to provide only the following 3 desktop entries, `Name=`, `Exec=` and `Categories=`

The "teamviewer" binary auto creates a .desktop file upon launch.

**Comment by ivan-hc** [comment]
> The "teamviewer" binary auto creates a .desktop file upon launch.

if this is not an AppImage, this is an issue I can't suppress https://github.com/ivan-hc/AM#stop-appimage-prompt-to-create-its-own-launcher-desktop-integration-and-doubled-launchers

**Comment by Twig6943** [comment]
what does -H do? 
(Sandboxing might not be what we're looking for cuz this is a remote desktop software)

**Comment by ivan-hc** [comment]
> what does -H do? (Sandboxing might not be what we're looking for cuz this is a remote desktop software)

as I said, if it is not an AppImage, `-H` and `-C` wont work

**Comment by Twig6943** [comment]
What about a launch script like this?
./teamviewer
 rm teamviewer.desktop # (delete the .desktop file it creates upon launch)

**Comment by ivan-hc** [comment]
you should investigate on an internal option of that binary to prevent creating the launcher

**Comment by ivan-hc** [comment]
what if you run the app with `DESKTOPSHORTCUTS=0` or the flag `--daemon disable`? I'm googleing/startpageing for solutions https://www.startpage.com/sp/search

**Comment by Twig6943** [comment]
Turns out the same issue is also present in the windows version https://community.teamviewer.com/English/discussion/135501/teamviewer-to-stop-creating-automatic-desktop-shortcuts-windows-exe#:~:text=Every%20time%20the%20TeamViewer%20Host,every%20time%20the%20software%20updates.

**Comment by ivan-hc** [comment]
from my test, I have found several files in this package and the binary is small... maybe we need to hack a script or a configuration file during the installation/update

**Comment by ivan-hc** [comment]
> from my test, I have found several files in this package and the binary is small... maybe we need to hack a script or a configuration file during the installation/update

in the tv_bin/script directory there are two text files with some instructions about a .desktop file, I think they are surced from another script.... also I see a .service file and other scripts, I think they are responsible of this somehow... you should investigate on these, maybe by removing the affected files

in the meantime I'm going uploading the apps for this and the other issue opened

**Comment by Twig6943** [comment]
@ivan-hc 
![image](https://github.com/user-attachments/assets/e17adc43-e42c-4983-85a4-af6428d77e49)

**Comment by ivan-hc** [comment]
if so, I've not understand the sense of that binary in the main directory

**Comment by ivan-hc** [comment]
now it should run

**Comment by Twig6943** [comment]
it does but could you please rename the package to teamviewer-qs (this is the quicksupport app there's also a full app which is the one most people use)
![image](https://github.com/user-attachments/assets/a74a2158-6ebd-49df-af30-3ff38b72cdf3)

**Comment by Twig6943** [comment]
Also please change the binary's name (or maybe remove the quicksupport app entirely from the db) as the full version (the one most people use) also has the binary name "teamviewer"

**Comment by Twig6943** [comment]
Like I said we def need the main app more than teamviwerqs (I don't think theres a way to make both exist)

**Comment by ivan-hc** [comment]
ok, find it and I'll upload it

**Comment by Twig6943** [comment]
Same link
https://www.teamviewer.com/en-mea/download/linux/

![image](https://github.com/user-attachments/assets/1ca53744-18f4-40f7-b158-65cc4a262750)

**Comment by ivan-hc** [comment]
ok, I'll fix it later

**Comment by ivan-hc** [comment]
just noticed that there are three versions in the same page, I've done a mistake in reading, sorry

**Comment by ivan-hc** [comment]
@Twig6943 done https://github.com/ivan-hc/AM/commit/0912671526e58c0725eedece0b7c2886c719a928
