### ISSUE TITLE
Samrewritten

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1038]
An AppImage package for this app by you would be appreciated. I couldnt build one myself. (skill issue) Could you please build one? (This project doesn't really get updates frequently anymore. The last commit is from a year ago so maintaining the pkg shouldnt be an issue) (https://github.com/Twig6943/SamRewrittenBinaries/releases/tag/2.1 requires user to install some libraries manually)
1. name samrewritten
2. main site: https://github.com/PaulCombal/SamRewritten (The AppImage on this repo is broken, check github issues if you want to see for yourself)
3. download page: https://github.com/Twig6943/SamRewrittenBinaries/releases/tag/2.1 (Doesn't include all dependencies tho)
4. description of the application: Steam Achievement Manager For Linux. Rewritten in C++.
5. URL to the application icon: https://raw.githubusercontent.com/PaulCombal/SamRewritten/refs/heads/master/assets/icon_256.png

Desktop entry;

[Desktop Entry]
Name=SamRewritten
Exec=/usr/bin/samrewritten
Terminal=false
Type=Application
Icon=samrewritten
Comment=Steam Achievement Manager
Categories=Game;
StartupWMClass=samrewritten;

(Add this pkg if you're not down to package it yourself cuz like I said the pkg above requires the user to install libraries manually)

**Comment by Twig6943** [comment]
Also have a look at this PR https://github.com/ivan-hc/AM/pull/1039

**Comment by ivan-hc** [comment]
What this Appimage has to be wrong (apart that it is from 2020). Also, the last commit is 1 year old and the developer seems to be active past week.

The official AppImage seems good to me. For any issue, just contact the upstream developer.
