### ISSUE TITLE
Add BibleMultiTheLife

### ISSUE THREAD

**Issue by hotlittlewhitedog** [ivan-hc/AM#1046]
To help us make adding AppImages quicker and easier, please follow the syntax below (**NOTE that if point 2 is a github repository, you can remove points 3 and 4**).

1. name (lowercase, this will be the command to use)
biblemultithelife
2. main site, repository or reference web page (URL, DO NOT use direct download link)
https://gitlab.com/hotlittlewhitedog/BibleTheLife
3. download page
https://gitlab.com/hotlittlewhitedog/BibleTheLife/-/releases
4. description of the application
Bible multi languages, free, offline, no advertising, in English, French, Italian, Spanish, Portuguese

---
I'm the owner of the app. 
Category: Education
My domain: https://www.BibleMulti.org 
An appImage was added in the release tag called: note-appimage*
I don't know if it's the way to do it, but it worked for flatpak.  
The app is also on Snapcraft.io, Mac... and appImageHub.com

I tried several: appman -t biblemultithelife ++ appman -I --debug ... but it doesn't work. 
There was a problem of invalid host name!

Thanks a lot to help me to include this app in your repo, there is no bible app yet 👍

**Comment by ivan-hc** [comment]
Sorry for the long wait, I have been busy with the next release of AM, in the "dev" branch. I'll take are of this request ASAP

**Comment by ivan-hc** [comment]
sadly, github has some apis that are difficult to analyze, so the better way to download via command line is to use the ID of the repo, in your case it is 17175284 (from any JSON file in "releases"). This is the output of the command I use for other scripts and applied for your case:
```
$ curl -Ls https://gitlab.com/api/v4/projects/17175284/releases/ | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i .appimage | head -1
https://gitlab.com/hotlittlewhitedog/BibleTheLife/-/archive/note-appimage-1.27.4/BibleTheLife-note-appimage-1.27.4.zip
```
for me its enough to add a `[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip` to extract the archive and integrate the AppImage in the system.

The script is ready, but I have also other issues opened with similar requests. Normally I take care of these in few minutes, but again, I was a bit busy latelly.

You will see the app uploaded here and on the catalogue in about 1 hour.

**Comment by ivan-hc** [comment]
Just noticed that the .zip file does not contain the AppImage. I need another way to download it.

**Comment by ivan-hc** [comment]
you have a lot of URLs but nthing of easy to download to get the AppImage

![Istantanea_2024-10-29_04-17-35 png](https://github.com/user-attachments/assets/a29f0144-f295-4074-bf5b-33a5e3694979)

**Comment by ivan-hc** [comment]
Just found the correct command
```
echo "https://gitlab.com/api/v4/projects/17175284$(curl -Ls https://gitlab.com/api/v4/projects/17175284/releases/ | tr '><" ()' '\n' | grep -i appimage$)"
```

**Comment by hotlittlewhitedog** [comment]
@ivan-hc  Thanks a lot Ivan 👍  
It works. The key was to check the JSON file where it says "/upload.... .AppImage.

**Comment by ivan-hc** [comment]
Hi @hotlittlewhitedog , AM have issues in downloading `biblemultithelife`

This is the last of 4 workflows failed https://github.com/ivan-hc/amcheck/actions/runs/28268074292/job/83759384666

This is the command that the script uses to download it
```
version="https://gitlab.com/api/v4/projects/17175284$(curl -Ls https://gitlab.com/api/v4/projects/17175284/releases/ | tr '{}()' '\n' | grep -i "appimage$" | head -1)"
wget "$version"
```

According with the API page, there is no AppImage among your builds, or if it was, it is old and under all new releases.

**Comment by ivan-hc** [comment]
I have just checked and the AppImage is on appimagehub (which is a source I avoid), and the last verasion dates back to 2024. I have compared the version with the Snap and the Flatpak, and I noticed that is something you decided to leave back. OK.

As always say, if an app is already portable, it is already an AppImage that only need to be packaged. In case you decide to bring back the AppImage, consider to read this brief guide I wrote https://github.com/ivan-hc/AppImage-tips

I'll remove the script for now.

If you wish, you can contact me here or directly open a pull request.

**Comment by hotlittlewhitedog** [comment]
Hi Ivan-Hc/Am,

The old appImage is still on gitlab.
Does your script changed! :)
As I have a lot of apps (3), packages and I'm alone (as human lol), it's
difficult to follow everything.
I don't have a CI for appImage, all has to be done by hand.
Indeed it's now time to recreate an appImage :)
I also have a copy on https://www.appimagehub.com/p/2218351 , of your
friend Probono.
The difference is the app name and maybe the namespace, if I remember
correctly.
Could be the right moment to merge things to only have one appImage for
both.
++

**Comment by hotlittlewhitedog** [comment]
@ivan-hc

**Comment by ivan-hc** [comment]
> The old appImage is still on gitlab.

it is far and far, behind releases, my old script was not able to get it

also, gitlab is already a tricky platform for this kind of scipts

> Does your script changed! :)

I had to remove it, it was the same in 2 years, from the day you asked me to submit it

> As I have a lot of apps (3), packages and I'm alone (as human lol), it's
> difficult to follow everything.

Don't tell me, I understand you

> I don't have a CI for appImage, all has to be done by hand.

I have no experience with CI in gitlab, sorry. I only work on github.

> Indeed it's now time to recreate an appImage :)

👍 

> I also have a copy on https://www.appimagehub.com/p/2218351 , of your
> friend Probono.

That is not the platform of Probono (probono have no platform, but a catalogue with broken links, used to validate AppImages via workflows, not a centralized repo then, Probono hates them), that is Pling.com based, so near to normal people like you, there are some user that steal other's projects and spam the site of outdated/broken/fake AppImages, often malicious software. In brief, its a thrash site, far from open source philosophy and near to Window's download+click+install+infect+destroy garbage that they call "programs".

> The difference is the app name and maybe the namespace, if I remember
> correctly.
> Could be the right moment to merge things to only have one appImage for
> both.

WDYM? Supporting appimagehub.com/pling.com? Sorry, but it will never happen, as I have explained.

Or better, I suggest you to publish your software on a less malicious platform.

**Comment by hotlittlewhitedog** [comment]
@ivan-hc/AM
***@***.***>
I didn't know about pling. Ok thanks for warning me, I will avoid them in
the future.

Indeed it wasn't the website of Probono;
https://appimage.github.io/BibleMultiTheLife/

On gitlab we can add Releases, there is the equivalent on github.

Can I repost the old appImage on github in the meantime I build an update?

**Comment by ivan-hc** [comment]
> @ivan-hc/AM
> ***@***.***>
> I didn't know about pling. Ok thanks for warning me, I will avoid them in
> the future.
> 
> Indeed it wasn't the website of Probono;
> https://appimage.github.io/BibleMultiTheLife/

👍 correct, they are two different sites

> On gitlab we can add Releases, there is the equivalent on github.
> 
> Can I repost the old appImage on github in the meantime I build an update?

Better if you take your time, so you have time to organize your repository.

I'll add the AppImage when available in your main source, so we have to not do the job 2 times.

**Comment by hotlittlewhitedog** [comment]
Ok, after my current pypi and flatpak update, you are next 😸😓🤗

The work never ends! 😆

👋
