### ISSUE TITLE
Harmonoid

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1050]
To help us make adding applications quicker and easier, please follow the syntax below (**NOTE that if point 2 is a github repository, you can remove points 3 and 4**, and **if the program is a CLI you can remove point 5 and 6**).

1. name: harmonoid
2. main site: https://github.com/harmonoid/harmonoid
3. download page: https://harmonoid.com/downloads/ (Raw Executable [.tar.gz] )
4. description of the application:🎵 Plays & manages your music library. Looks beautiful & juicy. Playlists, visuals, synced lyrics, pitch shift, volume boost & more. 

(Omit the 🎵 emoji if needed)

6. URL to the application icon: https://raw.githubusercontent.com/harmonoid/harmonoid/refs/heads/master/assets/images/project.png

8. the .desktop* file (choose whether to add a URL, to paste the content of the file, to drag a text file into your comment or to provide only the following 3 desktop entries, `Name=`, `Exec=` and `Categories=`

[Desktop Entry]
Type=Application
Name=Harmonoid
Comment=Plays music
Exec=harmonoid
Icon=harmonoid.png
Terminal=false
Categories=AudioVideo;Player;Qt;Audio;
Keywords=Audio;Player;
StartupNotify=false
StartupWMClass=harmonoid

**Comment by ivan-hc** [comment]
I think this app must wait even more, since they have not a regular download URL

**Comment by ivan-hc** [comment]
To let you understand, this is the URL where https://harmonoid.com/downloads/# will redirect

https://objects.githubusercontent.com/github-production-release-asset-2e65be/517078563/50f9def6-2f3e-4253-a9fa-dd7d6832d4f0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241031%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241031T022544Z&X-Amz-Expires=300&X-Amz-Signature=e93e629ff94ae92269b9adef45c2cf7d9970ec716b9f20a66997f2a0a4c6581a&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dharmonoid-linux-x86_64.tar.gz&response-content-type=application%2Foctet-stream

This is almost the same issue as Webcamoid... but this time I'll not create an AppImage for it. Sorry.

If you have a more "human friendly" source where we can download the damn archive, let me know. Else feel free to close this issue.

**Comment by Azathothas** [comment]
They seem to be pulling the binary from one of their dev's GH account
![image](https://github.com/user-attachments/assets/bfa4a166-e5f5-457d-9f97-c5172267cafd)


```bash
https://harmonoid.com/downloads/ --> https://github.com/alexmercerind2/_/releases/latest/download/harmonoid-linux-x86_64.tar.gz --> A few more redirects until GH Bucket
```

You can do 
```bash
wget "https://github.com/alexmercerind2/_/releases/latest/download/harmonoid-linux-x86_64.tar.gz"
```

**Comment by Azathothas** [comment]
> EDIT: also "[oh-my-git](https://harmonoid.com/downloads/#)" have a similar issue... and in fact it is not in this database.

haha, all this time I thought you meant: https://github.com/arialdomartini/oh-my-git

The itchio files are hosted on cloudflare r2 bucket, you can get this url by doing a post request
```bash
curl -qfsSL -X "POST" "https://blinry.itch.io/oh-my-git/file/3317841" | grep -o '"[^"]*cloudflarestorage[^"]*"' | grep -o 'https[^"]*' | tr -d '\\' | wget -i - -O "oh-my-git.zip"
```

You can get this file-id this way:
```bash
curl -qfsSL "https://blinry.itch.io/oh-my-git" | grep -oP 'data-upload_id="\d+"(?=.*oh-my-git-linux\.zip)'
data-upload_id="3317841"

```

**Comment by ivan-hc** [comment]
hi @Azathothas you have solved 2 issues in one! Thanks!

Sorry if I bother... have you got a solution also for the latest development builds of Olive Editory? https://www.olivevideoeditor.org/download

**Comment by Azathothas** [comment]
Hello, I tried to do a PR some months ago
https://github.com/ivan-hc/Olive-appimage-downloaded/pull/1/files

Unfortunately, it needs access to the actions api

**Comment by ivan-hc** [comment]
@Azathothas leave alone my repo, it is a (dirty) workaround I did by opening an old firefox to open the cursed page

the Olive artifacts are stored here https://github.com/olive-editor/olive/actions
