### ISSUE TITLE
Portable app suggestions

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#1054]
- [Ntfy Desktop](https://github.com/emmaexe/ntfyDesktop).
The `.tar.gz`  in Release section has the following structure:
```
Downloads/Compressed/ntfyDesktop-1.2.0 
❯ z bin

Compressed/ntfyDesktop-1.2.0/bin 
❯ x
ntfyDesktop
```
Desktop file entry:
```
[Desktop Entry]
Type=Application
Name=Ntfy Desktop
Categories=Utility;Network;
Keywords=notifications;
Comment=@CMAKE_PROJECT_DESCRIPTION@
Exec=@CMAKE_PROJECT_NAME@ %u
Icon=moe.emmaexe.ntfyDesktop
MimeType=x-scheme-handler/ntfy;
```

---

- [AudioRelay](https://audiorelay.net/). [Download link](https://audiorelay.net/downloads).
The [`.tar.gz`](https://dl.audiorelay.net/setups/linux/audiorelay-0.27.5.tar.gz) file has the following structure:
```
Downloads/Compressed/audiorelay-0.27.5 
❯ z bin

Compressed/audiorelay-0.27.5/bin 
❯ x
AudioRelay
```
There is no `.desktop` file that I could find, but you can use it as comment: `Stream audio between your devices`

---

- [WireframeSketcher](https://wireframesketcher.com/). [Download link](https://wireframesketcher.com/download.html).
The [`.tar.gz`](https://wireframesketcher.com/downloads/WireframeSketcher-latest-linux.x86_64.tar.gz) has the following structure:

```
Downloads/Compressed/WireframeSketcher-latest-linux.x86_64 
❯ z WireframeSketcher

Compressed/WireframeSketcher-latest-linux.x86_64/WireframeSketcher 
❯ x
about.html     configuration  features  p2       WireframeSketcher
artifacts.xml  dropins        icon.xpm  plugins  WireframeSketcher.ini
```

---

- [Cortex Command Community Project](https://github.com/cortex-command-community/Cortex-Command-Community-Project) - [Website](https://cortex-command-community.github.io/)
There is a [nightly release](https://github.com/cortex-command-community/Cortex-Command-Community-Project/releases/tag/nightly) and stable releases as well.
The release file has the following structure:

```
Downloads/Compressed/CortexCommand.linux 
❯ x
CortexCommand.AppImage  Data  libfmod.so  libfmod.so.13  libfmod.so.13.20
```

**Comment by ivan-hc** [comment]
Hi @Sush-ruta have you seen the new "Add portable apps (NOT AppImages)" issue template?

https://github.com/ivan-hc/AM/issues/new/choose

**Comment by Sush-ruta** [comment]
I apologise @ivan-hc , I did not keep any eye on this repo (real life). I think I only missed icon and description. I am listing it for every app in the next comment.

**Comment by Sush-ruta** [comment]
### Icon
- [Ntfy Desktop](https://raw.githubusercontent.com/emmaexe/ntfyDesktop/main/assets/ntfyDesktop.svg)
- [AudioRelay](https://audiorelay.net/assets/images/icon-512.png)
- [WireframeSketcher](https://img.apponic.com/239/4/479168be57f81384b3d646fe6fbff71e.png)
- [Cortex Command Community Shield](https://raw.githubusercontent.com/cortex-command-community/Cortex-Command-Community-Project/refs/heads/development/Resources/ccicon1024.png)

### Desktop file:
- `cccp.desktop` (Cortex Command Community Shield)
```
[Desktop Entry]
Categories=Game;
Type=Application
Icon=cccp
Name=Cortex Command (Community Project)
Comment=Choose between different factions, with their own set of expendable soldiers, mechas, and weapons. Protect your brain, mine gold, and destroy the enemy cortex in his bunker complex!
Exec=@EXERUNNER@
```

**Comment by ivan-hc** [comment]
> I apologise @ivan-hc , I did not keep any eye on this repo (real life). I think I only missed icon and description. I am listing it for every app in the next comment.

Don't worry, its not a problem.

Latelly I'm a bit busy with the next release, "AM" 9, so I don't know when I can start take care of these issues. You knw, normally I solve quickly these issues. Now its a bit different, I'd like to release the new build in the weekend.

**Comment by Sush-ruta** [comment]
All the best @ivan-hc ; looking forward to the new release.

**Comment by ivan-hc** [comment]
> All the best @ivan-hc ; looking forward to the new release.

You can already test it by entering the developer mode: 
```
am --devmode-enable
am -s
```
this might help me with bug reporting too, I'm currently investigating any issues that might be there. I'd be more interested in hearing from AppMan users if they run into any issues, in theory they shouldn't notice any differences. It's an update that will allow AM to do everything AppMan does, without changing the CLI.

See https://github.com/ivan-hc/AM/pull/1036

**Comment by Sush-ruta** [comment]
I will do that in the morning (midnight here). If I run into any bugs, I'll let you know duly. Not that I'm expecting bugs 😆. @ivan-hc

**Comment by ivan-hc** [comment]
> ### Desktop file:
> 
>     * `cccp.desktop` (Cortex Command Community Shield)
> 
> 
> ```
> [Desktop Entry]
> Categories=Game;
> Type=Application
> Icon=cccp
> Name=Cortex Command (Community Project)
> Comment=Choose between different factions, with their own set of expendable soldiers, mechas, and weapons. Protect your brain, mine gold, and destroy the enemy cortex in his bunker complex!
> Exec=@EXERUNNER@
> ```

don't worry, it is an AppImage into an archive... the .desktop file will be extracted from there.

PS: yes, I started taking care of this an half hour ago. Sorry for the delay.

**Comment by ivan-hc** [comment]
cccp has not a stable build if not on flathub... this means that I'll provide a generic one

![Istantanea_2024-10-31_02-40-28](https://github.com/user-attachments/assets/02966bde-e730-4eab-8841-93ce8c9bc40f)

**Comment by ivan-hc** [comment]
the nightly version has... no version, this means I'll use the id of the more recent asset
