### ISSUE TITLE
Optimize Portable Linux Apps Website

### ISSUE THREAD

**Issue by hotlittlewhitedog** [ivan-hc/AM#1055]
Hi all 😄 👍 

I would suggest you to optimize the load of Portable Linux Apps website, because it's too heavy (on mobile data...), not user friendly. I don't remember the exact max allowed size of a page but it should be less than 1MB. 

Check following screenshot:   

<img width="1521" alt="Screenshot 2024-10-30 at 18 36 28" src="https://github.com/user-attachments/assets/698b01be-88f0-48e4-a593-6bfb30ae0e45">

- Total download of 24 MB
- Load of 1.71 min 
- 2100 pictures of 128x128 not useful

Some solutions:
- Personally, I would remove the pictures of the main page,  
let's say: 2100 apps x ~7000 bytes (there are some pictures > 11000 bytes) => 14 MB. (24 - 14 => 10MB)
- I would also suggest you to create subcategories for AppImage section.
- Put the logo in the app description page 
- It's maybe also possible to compress the download page

Could be a good start and doesn't ask too much effort.

**Comment by ivan-hc** [comment]
I need an expert of GitHub Pages for this.

I don't know how to handle them, I'm a total newbie here.

If you know how to configure the site in a way that the pictures will not be loaded on mobile view, let me know. Maybe something to add here https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/blob/main/_config.yml or here https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/tree/main/assets/css ...but again, I'm not an expert.

Please open an issue or a PR at https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io next time, it would be helpful for those that want to help me mprove the site.

Thanks for reporting it.

I'll close but pin this in the meantime.

**Comment by hotlittlewhitedog** [comment]
OK 👍 I installed Ruby & compiled the site but it's not the last version of Ruby (on AntiX), got some errors and the server doesn't start. I install another machine and will try again... 😄

**Comment by ivan-hc** [comment]
thank you very much

**Comment by ivan-hc** [comment]
I move this to the dedicated repo, as I said, I think we need help on the JS/CSS/HTML level rather than a SHELL intervention.

**Comment by ivan-hc** [comment]
OK, I don't know how to transfer this issue to https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io

@hotlittlewhitedog it is better that you re-open the issue there, there is someone that can help much more in this.
