### ISSUE TITLE
I can't access https://repology.org in my country, so can't install apps that require it to check their version (i.e. tutanota and inkscape)

### ISSUE THREAD

**Issue by tuchanemo** [ivan-hc/AM#1056]
# Premise
"AM"/"AppMan" is just a tool to provide applications easily and quickly and is only responsible for integrating the AppImages into the system and installing the various programs available, respecting the following order (refer to the option "-d" to download the installation script without installing it):
- creation of the base directories and the removal script
- download of the package
- creation of the version file and the update script
- possibly, extraction of the icons and .desktop files, if needed

The malfunction of the installation scripts will then be taken into account. On the contrary, any malfunction related to individual applications is the responsibility of the related developer or packager. Refer to the option "-a" to know the sources of each program listed here, so you can contact them to report the bug.

--------------------------------------------------

## Please, describe the bug

Hi, can't install the tutanota app.
The script runs, the app downloads, then it asks: [sudo] password for xxxx:
and after entering the password: 💀 ERROR DURING INSTALLATION, REMOVED “TUTANOTA”!

Same for the inkscape application.
The script is executed, the application is downloaded, then before the password request it gives the following:
💀 ERROR DURING INSTALLATION, REMOVED “INKSCAPE”!

**Comment by Samueru-sama** [comment]
Can't replicate

![image](https://github.com/user-attachments/assets/1eb02eb5-e635-4d37-bafd-39fb17ee3e0f)

However those two apps parse https://repology.org/ to get their versions, maybe you hit some API limit there?

**Comment by ivan-hc** [comment]
> The script runs, the app downloads, then it asks: [sudo] password for xxxx: and after entering the password

this is really strange. Why it should ask for password after the download and not at start?

What version of AM are you using?

Have you done a non-standard setup or something?

**Comment by tuchanemo** [comment]
Please forgive me, I messed up with the password, am version 8.4.1.  I didn't do any custom settings. electron-mail, bastyon are installed normally. Here are the screenshots.
![Screenshot_1](https://github.com/user-attachments/assets/197f0d0f-067e-4fa0-8f7f-045e54faf998)
![Screenshot_am-f](https://github.com/user-attachments/assets/05bf02f1-8886-4098-aeca-ea3f0367628e)

**Comment by ivan-hc** [comment]
> I can't access https://repology.org in my country.

I'm not sure that this is the problem :face_with_diagonal_mouth:, you should get an empty $version variable.

To be sure, download the two scripts with the `-d` option and remove the content of the "version=" entry, for example
```
version=$(wget -q https://repology.org/project/tutanota/versions -O - | grep "newest version" | head -1 | grep -o -P '(?<=">).*(?=</a)' | sed 's/^.*>//')
```
must be
```
version=""
```

once you have done run the , drag-drop the two scripts in the terminal after `am -i` and press enter.

![Istantanea_2024-10-31_15-14-49 png](https://github.com/user-attachments/assets/a5eeb08d-0cff-48a6-9ecf-70cb91653261)

"Scrivania" means "Desktop" in italian.

**Comment by ivan-hc** [comment]
or at least edit the scripts by adding `torsocks` before `wget`
```
version=$(torsocks wget -q https://repology.org/project/tutanota/versions -O - | grep "newest version" | head -1 | grep -o -P '(?<=">).*(?=</a)' | sed 's/^.*>//')
```

**Comment by tuchanemo** [comment]
после добавления torsocks оба приложения успешно установились. Запись version="" не сработала.
![Screenshot_tutanota_trosocks](https://github.com/user-attachments/assets/97c00e56-bd7d-41c9-864a-00e8ddd6ca8e)

**Comment by ivan-hc** [comment]
If there is an alternative way to fetch the database of repology, please let me know. I'll convert all the scripts with that method to the new one.

**Comment by tuchanemo** [comment]
OK. Thank you.

**Comment by ivan-hc** [comment]
Allow me to change the title of this issue

**Comment by tuchanemo** [comment]
Okay, I agree.

**Comment by tuchanemo** [comment]
![curl](https://github.com/user-attachments/assets/3add6933-be64-44ac-9f74-e4dd00e1ef99)

**Comment by ivan-hc** [comment]
do `echo "$(curl -Ls https://repology.org/)"`

**Comment by ivan-hc** [comment]
I see an output there, I hope to have an empty variable instead

Sorry, try
```
repology=$(curl -Ls https://repology.org/)
echo "$repology"
```
or maybe
```
repology=$(curl -Ls https://repology.org/ | head -1)
echo "$repology"
```
its important to me to have an empty variable

**Comment by tuchanemo** [comment]
![curl2](https://github.com/user-attachments/assets/c89c7ce3-ad1b-44d5-a741-90453246eaae)

**Comment by ivan-hc** [comment]
perfect

**Comment by ivan-hc** [comment]
please, tell me the output of
```
torsocks wget -q --no-verbose --show-progress --progress=bar -q https://repology.org/project/inkscape/related -O - | grep "version-newest" | head -1 | grep -Eo "([0-9]{1,}\.)+[0-9]{1,}"
```

**Comment by aljustiet** [comment]
The same issue with the zen-browser.
```
❯ am -i zen-browser
============================================================================

                  START OF ALL INSTALLATION PROCESSES

============================================================================

 ◆ "ZEN-BROWSER": starting installation script

1730403180 PERROR torsocks[1120312]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:202)
1730403180 PERROR torsocks[1120319]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:202)

 Choose which version of Zen Browser to use:
 
	1. Zen Browser Generic
	Official generic build, targets x86-64 generic.
	source: https://github.com/zen-browser

	2. Zen Browser Specific
	Official optimized build, targets x86-64 v3.
	Only works on CPUs equal or newer than Haswell/Excavator.
	source: https://github.com/zen-browser

 Which version you choose (type a number and press ENTER)?: 2

 💀 ERROR DURING INSTALLATION, REMOVED "ZEN-BROWSER"!
____________________________________________________________________________
```

**Comment by ivan-hc** [comment]
@tuchanemo You can test this by replacing your "install.am" module with this

[install.am.txt](https://github.com/user-attachments/files/17592449/install.am.txt)

remember to remove the extension .txt

**Comment by tuchanemo** [comment]
![torsocks](https://github.com/user-attachments/assets/9af172cf-ad71-41ae-83a3-2debcdeaedf8)

**Comment by aljustiet** [comment]
> @tuchanemo You can test this by replacing your "install.am" module with this
> 
> [install.am.txt](https://github.com/user-attachments/files/17592449/install.am.txt)
> 
> remember to remove the extension .txt


https://github.com/user-attachments/assets/b312e14a-8c63-4ee6-a37c-1cde792b96b8

**Comment by ivan-hc** [comment]
@aljustiet your issue is another one:

the script of Zen Browser only have api.github.com references, so in case you reach github API limit and torsocks is instaled on the system, "AM" will run the script using `torsocks`

And for you I'm already investigating... it seems to be an issue with torsocks https://www.reddit.com/r/linuxquestions/comments/19cyftc/perror_torsocks_socks5_libc_connect_connection/ maybe on google or other web searches you will find similar results.

**Comment by ivan-hc** [comment]
> @aljustiet your issue is another one:
> 
> the script of Zen Browser only have api.github.com references, so in case you reach github API limit and torsocks is instaled on the system, "AM" will run the script using `torsocks`
> 
> And for you I'm already investigating... it seems to be an issue with torsocks https://www.reddit.com/r/linuxquestions/comments/19cyftc/perror_torsocks_socks5_libc_connect_connection/ maybe on google or other web searches you will find similar results.

That said, you should investigate on your Torsocks installation.

**Comment by ivan-hc** [comment]
@tuchanemo have you tested the module I provided (I hope you are not in developer mode now, this is the module from "main")?

**Comment by tuchanemo** [comment]
With the new install.am module the applications installed (inkscape, zen-browser, tutanota)
![zen](https://github.com/user-attachments/assets/7611d7b6-127e-4bb6-b550-d1999cea32c2)

**Comment by ivan-hc** [comment]
As I said, Torsocks is activated by default if api.github.com is not reachable... in the case of Inkscape and Tutanota, there is no such reference, but there is repology.org which is not reachable.

My module only adds the patch for repology.org, and I don't think you reached the github API limit, so Zen Browser would have worked just fine without any changes.

@aljustiet 's problem is that Torsocks uses random IPs via the TOR network. So be careful, it could happen that downloads work or not, depending on the IP obtained.

In your case, I see that you are in Ukraine, if Torsocks had assigned a random IP from your country, probably repology.org would not have worked, and you would have had to repeat the installation or reboot and try again, hoping for a lucky IP.

I will add this patch to "main" to fix this issue, and then add it in the next "AM" release, the 9, which is coming soon.

**Comment by Azathothas** [comment]
Hi, just to let you know, that repology blocks you if your user agents contains curl.
So use a fake browser user agent wherever possible.
Though that may not have been the issue here.

**Comment by ivan-hc** [comment]
> Hi, just to let you know, that repology blocks you if your user agents contains curl. So use a fake browser user agent wherever possible. Though that may not have been the issue here.

All is solved, I only needed to have an empty variable.

I have no restrictions in Italy, so ...

![Istantanea_2024-11-01_03-35-32 png](https://github.com/user-attachments/assets/22f89729-b6cc-4f2e-b264-15c5100c206f)

...is enough for me to have a full variable.

**Comment by aljustiet** [comment]
> As I said, Torsocks is activated by default if api.github.com is not reachable... in the case of Inkscape and Tutanota, there is no such reference, but there is repology.org which is not reachable.
> 
> My module only adds the patch for repology.org, and I don't think you reached the github API limit, so Zen Browser would have worked just fine without any changes.
> 
> @aljustiet 's problem is that Torsocks uses random IPs via the TOR network. So be careful, it could happen that downloads work or not, depending on the IP obtained.
> 
> In your case, I see that you are in Ukraine, if Torsocks had assigned a random IP from your country, probably repology.org would not have worked, and you would have had to repeat the installation or reboot and try again, hoping for a lucky IP.
> 
> I will add this patch to "main" to fix this issue, and then add it in the next "AM" release, the 9, which is coming soon.

I'm not from Ukraine.

**Comment by ivan-hc** [comment]
@aljustiet I was talking with @tuchanemo
