### ISSUE TITLE
Is the a bitwarden app image official?

### ISSUE THREAD

**Issue by Ranko-Saotome** [ivan-hc/AM#1057]
I just want to make sure it's coming from a reputable place

**Comment by ivan-hc** [comment]
Please see https://github.com/ivan-hc/AM#spyware-malware-and-dangerous-software

**Comment by Ranko-Saotome** [comment]
➜  ~ appman -d bitwarden 
curl: option --no-clobber: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by ivan-hc** [comment]
> ➜ ~ appman -d bitwarden curl: option --no-clobber: is unknown curl: try 'curl --help' or 'curl --manual' for more information

what version of AppMan are you running?

**Comment by ivan-hc** [comment]
anyway, you have this error because it does not find the installation script... it seems that you don't update the list from a lot of time... maybe months and months

**Comment by ivan-hc** [comment]
I'll keep talk there https://github.com/ivan-hc/AM/issues/1058

**Comment by Ranko-Saotome** [comment]
8.4.1
