### ISSUE TITLE
curl error?

### ISSUE THREAD

**Issue by Ranko-Saotome** [ivan-hc/AM#1058]
# Premise
"AM"/"AppMan" is just a tool to provide applications easily and quickly and is only responsible for integrating the AppImages into the system and installing the various programs available, respecting the following order (refer to the option "-d" to download the installation script without installing it):
- creation of the base directories and the removal script
- download of the package
- creation of the version file and the update script
- possibly, extraction of the icons and .desktop files, if needed

The malfunction of the installation scripts will then be taken into account. On the contrary, any malfunction related to individual applications is the responsibility of the related developer or packager. Refer to the option "-a" to know the sources of each program listed here, so you can contact them to report the bug.

--------------------------------------------------

## Are you using "AM" or "AppMan"?
appman
## What GNU/Linux distribution are you using it on?
zorin os 17
## Please, describe the bug
I can't currently get the scripts to download using the d flag 
I get this curl error
```curl: option --no-clobber: is unknown```

## What are the steps/commands to perform?
```appman -d bitwarden```

## What is the expected behavior?
```I would expect the installation script to be downloaded so I could view it```

**Comment by Ranko-Saotome** [comment]
8.4.1

**Comment by Ranko-Saotome** [comment]
I literally just did a `appman -s` before I even started messing with it

**Comment by ivan-hc** [comment]
sorry, this is an issue related to `curl` instead

**Comment by ivan-hc** [comment]
the command responsible of the script downloads is this
```
curl --no-clobber -Os "$APPSDB/$arg"
```

**Comment by Ranko-Saotome** [comment]
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18

**Comment by ivan-hc** [comment]
is seems to be 2 years old https://curl.se/docs/vuln-7.81.0.html

**Comment by ivan-hc** [comment]
from my `man curl`
```
       --no-clobber
              When  used  in  conjunction  with  the  -o,  --output,  -J, --re‐
              mote-header-name, -O,  --remote-name,  or  --remote-name-all  op‐
              tions, curl avoids overwriting files that already exist. Instead,
              a  dot  and  a  number gets appended to the name of the file that
              would be created, up to filename.100 after which it does not cre‐
              ate any file.

              Note that this is the negated option  name  documented.  You  can
              thus  use  --clobber to enforce the clobbering, even if -J, --re‐
              mote-header-name is specified.

              Providing --no-clobber multiple times has no extra effect.   Dis‐
              able it again with --clobber.

              Example:
              curl --no-clobber --output local/dir/file https://example.com

              Added in 7.83.0. See also -o, --output and -O, --remote-name.
```

this is why it don't works for you

**Comment by Ranko-Saotome** [comment]
zorin os 17 is based on ubuntu 22.04

**Comment by ivan-hc** [comment]
ok, I have a simple fix for this, don't worry

**Comment by Ranko-Saotome** [comment]
```
curl is already the newest version (7.81.0-1ubuntu1.18).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
```

**Comment by ivan-hc** [comment]
just replaced with `wget`

**Comment by Ranko-Saotome** [comment]
It works thanks for all the help
