### ISSUE TITLE
Add zen browser specific

### ISSUE THREAD

**Issue by aljustiet** [ivan-hc/AM#1064]
Can you add zen-browser specific release too?
For now, I use the zen-browser-avx2-bin package from the AUR because there isn't appimage in the AppMan repos.

**Comment by ivan-hc** [comment]
RE:

> Can you add zen-browser specific release too? [ ... ] there isn't appimage in the AppMan repos.

Are you sure?

https://github.com/user-attachments/assets/f849c62d-3118-4971-b382-7926d12d2e7e
