### ISSUE TITLE
Funkin-psych (game)

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1070]
name: funkin-psych
main site: https://github.com/Munoida/FNF-PsychEngine-Linux-Releases
download page: https://github.com/Munoida/FNF-PsychEngine-Linux-Releases/releases
description of the application: Engine originally used on Mind Games mod.
URL to the application icon: https://dl.flathub.org/media/io/github/shadowmario.fnf-psychengine/0d14a27c0c61c3175a11815841d5552a/icons/128x128/io.github.shadowmario.fnf-psychengine.png
the .desktop* file (choose whether to add a URL, to paste the content of the file, to drag a text file into your comment or to provide only the following 3 desktop entries, Name=, Exec= and Categories=

Desktop entry;

[Desktop Entry]
Name=Friday Night Funkin'
Exec=PsychEngine
Terminal=false
Type=Application
Icon=io.github.shadowmario.fnf-psychengine.png
Comment=Engine originally used on Mind Games mod.
Categories=Game;

**Comment by ivan-hc** [comment]
I had to remove this app, since the repo has been removed today.
