### ISSUE TITLE
[AppImage Request] PINCE

### ISSUE THREAD

**Issue by contrarybaton60** [ivan-hc/AM#1076]
1. pince
2. https://github.com/korcankaraokcu/PINCE

**Comment by ivan-hc** [comment]
The AppImage exists

![Istantanea_2024-11-03_23-33-39 png](https://github.com/user-attachments/assets/b464ea95-2bb6-4022-a6d4-80778c82490c)

**Comment by contrarybaton60** [comment]
oop

**Comment by ivan-hc** [comment]
@contrarybaton60 I'm rewriting the guide on how to create installation scripts, something like this is the easier thing to upload... do you want to take a look at the guide? Maybe if you find something more complicated, I can try to improve it. https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/template.md I'm also adding videos for this.

**Comment by contrarybaton60** [comment]
there doesn't seem to be much documentation on the firefox profiles

**Comment by contrarybaton60** [comment]
other than that I think it's good... anyway, I've been thinking about a FOSS-only repo for AM/AppMan, I know it's a pain to delete a bunch of installation scripts for proprietary programs (especially for  x86_64) but I think it can be done.

also I've been fooling around with junest, it's pretty fun having a portable arch on my linux mint, but I don't have much use for it

**Comment by contrarybaton60** [comment]
![image](https://github.com/user-attachments/assets/6b7b25f3-d37b-4c56-a0de-c9f624cf34ca)

**Comment by ivan-hc** [comment]
> there doesn't seem to be much documentation on the firefox profiles

try now https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/template.md#option-three-firefox-profiles any reference to "someone" is totally casual

**Comment by ivan-hc** [comment]
> other than that I think it's good... anyway, I've been thinking about a FOSS-only repo for AM/AppMan,

I only share PKGBUILD-like scripts, no matter what app is downloaded. Is it to read the content of each script not enough "open source"?

**Comment by contrarybaton60** [comment]
> > other than that I think it's good... anyway, I've been thinking about a FOSS-only repo for AM/AppMan,
> 
> I only share PKGBUILD-like scripts, no matter what app is downloaded. Is it to read the content of each script not enough "open source"?

I meant like the apps themselves, not the scripts

**Comment by ivan-hc** [comment]
> I meant like the apps themselves, not the scripts

this is something that big distributions do, that have their own communities, their own storage spaces... and above all the **MONEY** to maintain all this.

As a good unemployed bum that I am, I'm happy to have the scripts.

**Comment by contrarybaton60** [comment]
I think I said it wrong, I meant to say a separate repo as you stated in this https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/newrepo.md

**Comment by ivan-hc** [comment]
> I think I said it wrong, I meant to say a separate repo as you stated in this https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/newrepo.md

Well, no one is stopping you from creating one. I wrote that option specifically "for posterity", when I can no longer maintain "AM".

**Comment by ivan-hc** [comment]
You can already fork this repo and create a separate branch, with just the FOSS programs. Anyone would acceede to it. You can uload apps there as well.

I'm improving the Templates guide to "educate" you all on how to create these scripts by yourself. I'm doing my best to made the guide as much newbie-friendly as possible.

**Comment by ivan-hc** [comment]
I have finished with the guide. I hope what I wrote is clear enough.
