### ISSUE TITLE
Github API

### ISSUE THREAD

**Issue by Graninius** [ivan-hc/AM#1077]
Hi, everyone!

When I tried to install Stacer today, I received the following error:

`'STACER': starting installation script.
Cannot install "stacer", you have reached the GitHub API limit.
Install "torsocks" from your system package manager and retry!`

I’m not sure what this means. My API key is validated and works fine with the Obtainium project (Android), so I’m unclear on what went wrong and why I need to install torsocks.
Manjaro KDE unstable, VPN
Appman 9

**Comment by ivan-hc** [comment]
hi, this is the function responsible of this error
```
	if grep -q "api.github.com" ./"$arg"; then
		GH_API_ALLOWED=$(curl -Ls $HeaderAuthWithGITPAT https://api.github.com/repos/ivan-hc/AM/releases/latest | sed 's/[()",{} ]/\n/g' | grep "^ivan-hc" | head -1)
		if [ -z "$GH_API_ALLOWED" ]; then
			if command -v torsocks 1>/dev/null; then
				$SUDOCMD torsocks ./"$arg"
			else
				echo " 💀 Cannot install \"$arg\", you have reached GitHub API limit." \
				| fold -sw 72 | sed 's/^/   /g; s/   ✖/✖/g'
				echo ""
				echo "   Install \"torsocks\" from your system package manager and retry!" 
				return 0
			fi
		else
			$SUDOCMD ./"$arg"
		fi
	else
		$SUDOCMD ./"$arg"
	fi
```
it detects if the script contain `api.github.com` as a reference
```
if grep -q "api.github.com" ./"$arg"; then
```
if so, it will test if "api.github.com" is reachable by contacting a URL

![Istantanea_2024-11-04_13-34-56 png](https://github.com/user-attachments/assets/d566416b-77d6-49e0-8bda-48b2e0e32c82)

I've not reached the limit yet

NOTE, there is an unquoted variable `$HeaderAuthWithGITPAT`, you need to set the value using the command
```
appman apikey $YourAlphanumericGithubAPIKey
```
this will be saved into a file under ~/.local/share/AM, allowing you to use it to contact api.github.com

If you don't set it first, the script will not use your API key and you wont be able to download the program.

Alternativelly, you can use `torsocks` from your package manager https://repology.org/project/torsocks/versions (on Manjaro it is the 2.4.0 version), see more at https://gitlab.torproject.org/tpo/core/torsocks/

NOTE that torsocks uses the TOR network and random IPs, so in most cases you can reach a slow download speed, but not always. This is my attempt to bypass reaching API limit.

-------------------------------

Tha tsaid, to solve you should add your API key with the option `apikey` in AppMan.

Alternativelly, install Torsocks from your package manager and hope for a quite fast connection.

**Comment by ivan-hc** [comment]
You can find the above function for Torsocks in the install.am module

The function to use the API key is instead in `appman` itself (APP-MANAGER on this repo)
```
ghapikey_file="$AMDATADIR/ghapikey.txt"
# Set header authorization if GitHub API key file exists
[ -f "$ghapikey_file" ] && HeaderAuthWithGITPAT=" --header \"Authorization: token $(<"$ghapikey_file")\" "

function _use_apikey() {
	case $2 in
	'del'|'delete'|'remove')
		[ -f "$ghapikey_file" ] || { echo " ✖ No file named $ghapikey_file has been found"; exit 1; }
		rm -f "$ghapikey_file" && echo " ✔ $ghapikey_file has been removed" 
		exit 0
	esac
	if [[ "$2" =~ ^(gh[ps]_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59})$ ]]; then
		test_apikey_output_with_wget=$(curl -Ls --header "Authorization: token $2" 'https://api.github.com/repos/ivan-hc/AM/releases' | head -1)
		[ -n "$test_apikey_output_with_wget" ] && echo "$2" > "$ghapikey_file" \
			&& echo "Validation successful!" || echo "ERROR: This is not a valid key!"
	else
		echo "ERROR: Wrong expression, validation failed!"
	fi
}

function _update_github_api_key_in_the_updater_files() {
	if [ -f "$ghapikey_file" ]; then
		ghapikey=$(<"$ghapikey_file")
		updater_files=("$APPSPATH"/*/AM-updater) # Assuming AM-updater is one level deeper
		for f in "${updater_files[@]}"; do
			if [ -f "$f" ] && grep -q "https://api.github.com" "$f"; then
				# Check if the file already contains a valid API key
				if ! grep -qE "(gh[ps]_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59})" "$f"; then
					# Insert HeaderAuthWithGITPAT before the GitHub API URL
					sed -i "s#https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" "$f"
				else
					# Replace existing API key with the one from ghapikey.txt
					sed -i "s#\(gh[ps]_[a-zA-Z0-9]\{36\}\|github_pat_[a-zA-Z0-9]\{22\}_[a-zA-Z0-9]\{59\}\)#$ghapikey#g" "$f"
				fi
			fi
		done
    	fi
}
```

**Comment by Graninius** [comment]
As I mentioned before, the API key was added and validated (I also checked this key in another project, and it's working fine). Despite the key being present, I still received the error. However, today the error is gone without me doing anything to resolve it

**Comment by ivan-hc** [comment]
@Graninius can you confirm that the ~/.local/share/AM/ghapikey.txt file exists and that the GH API key is correct into it?

**Comment by Graninius** [comment]
Yes, the file exists and API key is present.

**Comment by ivan-hc** [comment]
> Yes, the file exists and API key is present. That mistake didn’t occur today. Hopefully, it was a one-time issue

To be sure you should "abuse" of API calls for 50 times in one hour or more.

Normally you can contact github APIs again after 1 hour.

**Comment by Graninius** [comment]
> > Yes, the file exists and API key is present. That mistake didn’t occur today. Hopefully, it was a one-time issue
> 
> To be sure you should "abuse" of API calls for 50 times or more in one hour.
> 
> Normally you can contact github APIs again after 1 hour.

Hmm... When I start an update procedure with appman -u, does that mean AppMan makes 31 calls to GitHub (since I have 31 apps installed)? One call for each app? So, if I do it again, would it 'abuse' the API with over 50 calls?

**Comment by ivan-hc** [comment]
yes, you can try 2-3 time os more... use `appman -u --apps`, you are testing just the apps

**Comment by Graninius** [comment]
Tried three times in a row—no errors!

**Comment by Graninius** [comment]
One-time issue

**Comment by ivan-hc** [comment]
ok, thanks

**Comment by Graninius** [comment]
Hmm... It's happening again. The ~/.local/share/AM/ghapikey.txt file exists, and the API key is present
![Снимок экрана_20241117_144041](https://github.com/user-attachments/assets/0710740a-5c6e-464d-b067-77e7f6e57fef)

**Comment by Graninius** [comment]
Will try to change the API key (

**Comment by Azathothas** [comment]
We ([`PkgForge`](https://github.com/orgs/pkgforge/repositories)) ran into this issue some time ago while trying to add more features to [`Soar`](https://github.com/pkgforge/soar).
We considered:
- Let user's specify `GITHUB_TOKEN` & use it
> - Nice and works, problem is not all users find it easy to generate a token & it gets exposed to any scripts we run, so unless the user created a least privileged token, it's very unsafe.

- Introduce TorSocks & Similar Free Proxies
> - Barely works. All of these proxies are already used/abused by other people and thus are blacklisted by Github.

We then came across:
 https://github.com/wp-cli/wp-cli/issues/3426
 
 So the idea of having our own dedicated reverse proxy to GitHub was born.
 It was meant to be used only by `Soar` but we decided to let the community use it too.
 All you have to do is replace `api.github.com` with `api.gh.pkgforge.dev`, and no other change is necessary.
 Our API has a dozen tokens, along with auto IP rotation (Cloudflare Workers) and can handle 100K reqs (users) per hr.
 
 
 You can solve this and also GitLab (`api.gl.pkgforge.dev`), Codeberg (`api.cb.pkgforge.dev`) & Repology (`api.rl.pkgforge.dev`) all at once. 
 You will also notice faster speed, even when compared to official api because we use [Cloudflare's edge CDN](https://www.cloudflare.com/network/) which is [Geo-Distributed](https://www.cloudflare.com/network/).
