### ISSUE TITLE
Option to suppress update notifications

### ISSUE THREAD

**Issue by sandboiii** [ivan-hc/AM#1086]
Hey, when I update my applications I get a lot of these annoying notifications. Are there any options to disable them?

![2024-11-07-122938_3840x1080_scrot](https://github.com/user-attachments/assets/41e85ab8-2a91-451c-a97a-4b957bc74e07)

**Comment by Samueru-sama** [comment]
I also wanted this a while ago, what I ended up doing is this: 

go to the dir where you have the applications and run `sed -i 's|notify-send|echo|g' ./*/AM-updater`

that will disable all the notifications, however be aware that undoing this change is going to be a bit more difficult.

**Comment by ivan-hc** [comment]
New release is out https://github.com/ivan-hc/AM/releases/tag/9.0.1

**Comment by sandboiii** [comment]
Wow, that was fast! Thank you a lot!

**Comment by ivan-hc** [comment]
And this will be not the last release... get ready for the next https://github.com/ivan-hc/AM/issues/1089
