### ISSUE TITLE
Install option with themed icon

### ISSUE THREAD

**Issue by rauldipeas** [ivan-hc/AM#1089]
# Is your feature request related to a problem? Please describe.
No.

# Describe the solution you'd like
Would be great to install with themed icon in only one command.

# Describe alternatives you've considered
Actually i'm installing and then run `am icons $APP`, I've created a function in bash for this.
```
aminst() {
    am -i "$@"
    am icons "$@"
}
```

**Comment by ivan-hc** [comment]
This is what I worked on
```
_if_icons() {
	if echo "$FLAGS" | grep -q -- '--icons'; then
		# Install the app so that it can rely on an icon theme (if available)
		sed -i "s#Icon=/opt/\$APP/icons/#Icon=#g" ./"$arg"
	fi
}
```
usage
```
am -i --icons {PROGRAM}
```
or
```
am -i --user --icons {PROGRAM}
```

the only disadvantage is that if you have not an icon theme, the icon in the launcher is missing.

**Comment by ivan-hc** [comment]
> the only disadvantage is that if you have not an icon theme, the icon in the launcher is missing.

Anyway, if you know that you have an icon theme for that appname, you can do it safe.

If the icon is missing from the theme, just use `am --icons`

**Comment by ivan-hc** [comment]
Done https://github.com/ivan-hc/AM/releases/tag/9.0.2
