### ISSUE TITLE
Wrong and missing window classes

### ISSUE THREAD

**Issue by rauldipeas** [ivan-hc/AM#1090]
## Please, describe the bug
I've installed alot of apps (more than 50, probably) that don't have a `StartupWMClass=$APP` declared on laucher, some of then came with the wrong value, so I propose to run the $APP in background someway and `xprop WM_CLASS` (or something that working on Wayland too) to get the class be added on launcher at the installation time.

It's possible or all the scripts should be updated with the right class?

**Comment by rauldipeas** [comment]
Maybe you can create an option to change the class.

Ex: `am -class $CLASS $APP`

**Comment by ivan-hc** [comment]
Sorry, but I told you what the solution is. Also, I would prefer not to alter the work of the developers upstream.

If the launcher is included in the script, we can intervene as much as we want. If it is not and is extracted from the downloaded package, and the entry is missing, the same problem will manifest itself in all installation methods, therefore AM and all the others. Reporting bugs is part of improving individual software, and AM cannot always patch up the shortcomings of others. This is precisely why many Windows programs do not work on Linux. And WINE doesn't work miracles either.

**Comment by Samueru-sama** [comment]
What's `StartupWMClass=` for? if the apps are AppImages, `appimagetool` runs `desktop-file-validate` before creating the AppImage, so the AppImage already has to contain a valid .desktop file.

**Comment by rauldipeas** [comment]
> What's `StartupWMClass=` for? if the apps are AppImages, `appimagetool` runs `desktop-file-validate` before creating the AppImage, so the AppImage already has to contain a valid .desktop file.

If you don't have a window class in the launcher, the app can't be pinned on GNOME o KDE panels, for example.

**Comment by rauldipeas** [comment]
> Sorry, but I told you what the solution is. Also, I would prefer not to alter the work of the developers upstream.
> 
> If the launcher is included in the script, we can intervene as much as we want. If it is not and is extracted from the downloaded package, and the entry is missing, the same problem will manifest itself in all installation methods, therefore AM and all the others. Reporting bugs is part of improving individual software, and AM cannot always patch up the shortcomings of others. This is precisely why many Windows programs do not work on Linux. And WINE doesn't work miracles either.

I completely understand, for now i'll do it for myself and later i'll report all the apps to the original developers, certainly this is the right way.

Closing.
