### ISSUE TITLE
SchilbidiChat (Sorry I dont really have time to learn scripting for AM)

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1094]
1. name: schilbidi-chat
2. main site: https://github.com/SchildiChat/schildichat-desktop
3. download page: https://github.com/SchildiChat/schildichat-desktop/releases
4. description of the application: Matrix client / Element Web/Desktop fork

**Comment by ivan-hc** [comment]
what should you learn? :point_down: 

https://github.com/user-attachments/assets/51827a11-97d8-4f27-90be-2ec8505d07a5

**Comment by ivan-hc** [comment]
I hope you have the time to see a 1 minute video :point_up_2: 

for now it is so https://github.com/ivan-hc/AM/commit/7e30dbc8540b475fdbcd37fab5f3f10757a49a05 but the next time I want a pull request from you.
