### ISSUE TITLE
Mullvad-browser

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1116]
the mullvad-browser pkg doesn't create a desktop file
The browser does run when I type "mullvad-browser" to a terminal tho
![image](https://github.com/user-attachments/assets/ed23c8b8-d9b1-4874-bded-e3d85ca099cd)

**Comment by ivan-hc** [comment]
try now

**Comment by Samueru-sama** [comment]
The portable build of mullvad is such a mess, you might wanna ask them to provide an appimage instead.

**Comment by Twig6943** [comment]
> try now

Works (The upper one is the flatpak)
![image](https://github.com/user-attachments/assets/eb183d36-23d0-465b-98eb-e2f329c5b450)
