### ISSUE TITLE
Genymotion

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1121]
I don't know if this can be added to AM default repo (Its prob possible to add it to an external repo tho)
Repos:

[Aur pkg](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=genymotion) for reference

1. name : genymotion
2. main site: genymotion.com
3. download page: https://www.genymotion.com/product-desktop/download/
4. description of the application: Android emulator for app development and testing
5. URL to the application icon: https://img.utdstc.com/icon/3c7/e45/3c7e454c7df2c0dd44ce51d7d0af35fd8f6930b57ec199caceb79a8c60e2cf98:100
6. the .desktop* file (choose whether to add a URL, to paste the content of the file, to drag a text file into your comment or to provide only the following 3 desktop entries, `Name=`, `Exec=` and `Categories=`

[Desktop Entry]
Name=Genymotion
Comment=Android emulator for app development and testing
Exec=/path/to/genymotion %U
Icon=/path/to/genymotion-icon.png
Terminal=false
Type=Application
Categories=Development;IDE;Emulator;

**Comment by Twig6943** [comment]
Also @ivan-hc could u update the pince pkg (enable terminal=true & add icon to the .desktop file )

Ik youve said earlier that youre not really intrested and expected me to do it but could you please update this one real quick (Im still in the phase of getting used to "am -t" Ive sent my first [PR ](https://github.com/ivan-hc/AM/pull/1108) and will hopefully send out more in the near future

**Comment by ivan-hc** [comment]
> Also @ivan-hc could u update the pince pkg (enable terminal=true & add icon to the .desktop file )
> 
> Ik youve said earlier that youre not really intrested and expected me to do it but could you please update this one real quick (Im still in the phase of getting used to "am -t" Ive sent my first [PR ](https://github.com/ivan-hc/AM/pull/1108) and will hopefully send out more in the near future

Enable? It is already on "true"
```
[Desktop Entry]
Name=PINCE
Exec=/home/ivan/.local/bin/pince
Icon=/home/ivan/.local/share/appman/pince/icons/pince
Type=Application
Terminal=true
Categories=Development;
```

**Comment by ivan-hc** [comment]
About the icon, this is an issue they have, you must contact them. I refuse to always fix others mistakes.

![Istantanea_2024-11-15_15-54-40](https://github.com/user-attachments/assets/0fe63c19-ab64-4df5-82ea-6489134c81e9)
![Istantanea_2024-11-15_15-54-58](https://github.com/user-attachments/assets/2c41685f-9810-4e24-9cd2-67baba96b6d8)

**Comment by Twig6943** [comment]
@ivan-hc Where did you get that blank .svg from?

**Comment by Twig6943** [comment]
Here's the logo as a .png:
https://raw.githubusercontent.com/korcankaraokcu/PINCE/refs/heads/master/media/logo/ozgurozbek/pince_big_transparent.png
Here's the logo as a .svg:
https://oto.lv.tab.digital/s/jmXr6E9nABwJM8x

**Comment by Twig6943** [comment]
@ivan-hc I've figured it out
https://oto.lv.tab.digital/s/NxwDCCiNFK3cMzo

**Comment by Twig6943** [comment]
Also should we enable or disable "StartupNotify"

**Comment by Twig6943** [comment]
Next time I'll create its own issue in order to not cause something like this (as you know I've never created a separate issue for pince)

**Comment by ivan-hc** [comment]
> @ivan-hc Where did you get that blank .svg from?

have you looked inside the AppImage?

To extract an AppImage you must run `./*AppImage --appimage-extract`, I got that icon from there.

Also, all you are asking for must be inside the AppImage, and being this a project on github, go ask them for this.

Now stop spamming these requests, I have said that I refuse to always fix others mistakes.
