### ISSUE TITLE
could you add my game conqueror AppImage to you package manager

### ISSUE THREAD

**Issue by lucasmz1** [ivan-hc/AM#1126]
gameconqueror
https://github.com/lucasmz1/Game_Conqueror_AppImage/releases/tag/0.17_2
this is an application for cheat in games, basically it change memory values.

**Comment by ivan-hc** [comment]
hi @lucasmz1 thanks for submitting.

Please, add a description in your repository. My workflow also creates a page for the catalog and lists the app in the dedicated category, and lists it.

You lack of description for your project. What is gameconqueror? What it does? Add all this in the repo description and on your README.

I also suggest you to add the scripts and the code you use to build it, in your repo, its a matter of transparency. I mark as "spooky" all apps that come from repositories without a clear code used to build the program.

**Comment by ivan-hc** [comment]
I just saw that you have quite a few AppImage packages, including K3B (what great memories you brought back!)... I'd be happy to include more if you could add descriptions and code to the other repositories as well. Thanks.

**Comment by lucasmz1** [comment]
Ok. can you give me some exaple to make a good description in my repositories, It's a matter of do what's correctly in order to fufil your requirements.

**Comment by lucasmz1** [comment]
oh I forgot to say some of them I've by hand, which means I have the code the recipes for it, but some codes I had made by hand.
for example I have a certainly way to remove libs that gives for example conflict with others libs on the system. It's a simple command line that I use that removes source libs that in other words give an erro like memory dump etc.

**Comment by lucasmz1** [comment]
do you have telegram for we discuss more of this details. mine is @zainotel

**Comment by ivan-hc** [comment]
> Ok. can you give me some exaple to make a good description in my repositories, It's a matter of do what's correctly in order to fufil your requirements.

you can take one of my repos as an example https://github.com/ivan-hc/GIMP-appimage

![Istantanea_2024-11-15_22-47-15](https://github.com/user-attachments/assets/ec78a902-27a5-46cf-ab89-3b578cddba2d)

> oh I forgot to say some of them I've by hand, which means I have the code the recipes for it, but some codes I had made by hand. for example I have a certainly way to remove libs that gives for example conflict with others libs on the system. It's a simple command line that I use that removes source libs that in other words give an erro like memory dump etc.

interesting... maybe I can help you set up some workflows on github, so you don't have to do everything manually. I'll be happy to help you with that.

> do you have telegram for we discuss more of this details. mine is @zainotel

sorry, I don't use Telegram

**Comment by lucasmz1** [comment]
ok thank you my friend. closing this issue.

**Comment by ivan-hc** [comment]
@lucasmz1 you are welcome. These are just suggestions to make your projects more transparent and at the same time more popular. I already have your QEMU AppImage, I would like to promote more of the works you provided, but at the same time I would like to give peace of mind to my users, when I choose the apps to add to the database.

Feel free to contact me whenever you want, I'll wait for you.
