### ISSUE TITLE
why is there no clear information on how to set environment variables in the Linux

### ISSUE THREAD

**Issue by candrapersada** [ivan-hc/AM#1130]
> NOTE, the default location for the sandboxed homes is at $HOME/.local/am-sandboxes, but that location can be changed by setting the $SANDBOXDIR environemt variable.

how to set environment variables in the Linux
https://github.com/ivan-hc/AM/blob/main/docs/guides-and-tutorials/sandbox.md

**Comment by ivan-hc** [comment]
because exists google for this https://www.google.com/search?client=firefox-b-d&q=set+environment+variable+linux
