### ISSUE TITLE
Rebos [CLI]

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1134]
1. name: rebos
2. main site: https://lib.rs/crates/rebos
3. download page: https://gitlab.com/Oglo12/oglo-arch-repo/-/blob/main/x86_64
4. description of the application: Rebos is a tool that aims at mimicking what NixOS does (repeatability), for any Linux distribution.
5. URL to the application icon: N/A

The latest release as of writing this: https://gitlab.com/Oglo12/oglo-arch-repo/-/blob/main/x86_64/rebos-r97.4818a33-1-any.pkg.tar.zst?ref_type=heads

rebos-versionnumbers-any.pkg.tar.zst

**Comment by Oglo12** [comment]
Hi, I'm the creator of Rebos, I just want to say that a better main site link is the actual GitLab repository: https://gitlab.com/Oglo12/rebos

**Comment by ivan-hc** [comment]
hi @Oglo12 where can I get the releases? I use `curl` and `wget` to detect the latest release from a website

**Comment by Twig6943** [comment]
@ivan-hc FYI the developer went to sleep or something (went offline on discord)
![image](https://github.com/user-attachments/assets/987b9145-4ef4-457a-8033-334a5d2d1ac7)

Do you have matrix or signal? Would be cool if we had a way of communucation outside of github.

**Comment by ivan-hc** [comment]
reddit and discord

**Comment by Twig6943** [comment]
could u add me on discord? my discord: twig6843

**Comment by ivan-hc** [comment]
So there is no way to get this program from a raw site or repo? Gitlab APIs without a releases page or a repo ID are no way usable with `curl` an `wget`.

**Comment by ivan-hc** [comment]
I decided to use the build number provided in the PKGBUILD as a version
