### ISSUE TITLE
Icon is not displayed

### ISSUE THREAD

**Issue by aljustiet** [ivan-hc/AM#1136]
## Are you using "AM" or "AppMan"?
AppMan
## What GNU/Linux distribution are you using it on?
Arch/Hyprland
## Please, describe the bug
Generated desktop files doesn't display icon. If I change the icon file to png variant it starts displaying again.
## What are the steps/commands to perform?
Open app launcher e.g. rofi, and search for the app.
## What is the expected behavior?
The icon to be displayed.

**Comment by Samueru-sama** [comment]
>Generated desktop files doesn't display icon. If I change the icon file to png variant it starts displaying again.

>Open app launcher e.g. rofi, and search for the app.

Looks like a problem with rofi, specially with libgdk-pixbuf which is used for svg icons.

Do you have this problem if you use this [appimage of rofi](https://github.com/Samueru-sama/rofi-AppImage)? `appman -i rofi`

**Comment by aljustiet** [comment]
> > Generated desktop files doesn't display icon. If I change the icon file to png variant it starts displaying again.
> 
> > Open app launcher e.g. rofi, and search for the app.
> 
> Looks like a problem with rofi, specially with libgdk-pixbuf which is used for svg icons.
> 
> Do you have this problem if you use this [appimage of rofi](https://github.com/Samueru-sama/rofi-AppImage)? `appman -i rofi`

Does it support wayland?

**Comment by aljustiet** [comment]
Fuzzel has the same behavior.

**Comment by aljustiet** [comment]
https://github.com/user-attachments/assets/178ed27c-14e9-447f-86ab-4da5c0946eed

**Comment by aljustiet** [comment]
> > > Generated desktop files doesn't display icon. If I change the icon file to png variant it starts displaying again.
> > 
> > 
> > > Open app launcher e.g. rofi, and search for the app.
> > 
> > 
> > Looks like a problem with rofi, specially with libgdk-pixbuf which is used for svg icons.
> > Do you have this problem if you use this [appimage of rofi](https://github.com/Samueru-sama/rofi-AppImage)? `appman -i rofi`
> 
> Does it support wayland?

Seems not.

**Comment by aljustiet** [comment]
I use the [rofi-wayland](https://archlinux.org/packages/extra/x86_64/rofi-wayland/) version.

**Comment by aljustiet** [comment]
Adding png extension to icons fixes the issue.

**Comment by Samueru-sama** [comment]
> I use the [rofi-wayland](https://archlinux.org/packages/extra/x86_64/rofi-wayland/) version.

You likely have this [bug](https://github.com/davatorium/rofi/issues/1977). Which rofi fixed but it seems the wayland forks haven't. 

>Adding png extension to icons fixes the issue.

because the issue happens when there isn't a dot in the path to the icon, it is a weird bug, if you change the directory where the icon is located to have a `.` like `~/.Applications` it will also be fixed.

**Comment by Samueru-sama** [comment]
Indeed it is the same bug, just installed rofi-wayland

![image](https://github.com/user-attachments/assets/f9a9e555-85e1-425e-8e77-978b4af6dc4e)

And here is with the the rofi appimage:

![image](https://github.com/user-attachments/assets/88e53761-49bd-4f67-b7fc-f99c193f066c)

Note that the stable releases of rofi also have the bug, you have to use `rofi-git` or the appimage that I build.

(Just in case that error about android-tools is because the file isn't an image, it is just a dummy icon lol).

**Comment by aljustiet** [comment]
I installed the rofi-lbonn-wayland-only-git package, and it fixed the issue too.

**Comment by twnaing** [comment]
[jgmenu](https://github.com/jgmenu/jgmenu) also does not work with current icon file (without file extension).

Adding extension to the icon file (and add extension in generated desktop file) works in both rofi and jgmenu.

**Comment by Samueru-sama** [comment]
> [jgmenu](https://github.com/jgmenu/jgmenu) also does not work with current icon file (without file extension).
> 
> Adding extension to the icon file (and add extension in generated desktop file) works in both rofi and jgmenu.

Is it really the extension or that it expects the path to have a dot? 

Try changing the icon dir to `.icons` and the path in the .desktop to also have `.icons` and see if it also displays the icon that way, without extension.

**Comment by twnaing** [comment]
> Try changing the icon dir to `.icons` and the path in the .desktop to also have `.icons` and see if it also displays the icon that way, without extension.

For jgmenu

- `icons/app-name` -> does not work
- `.icons/app-name` -> does not work
- `icons/app-name.png` -> works

**Comment by Samueru-sama** [comment]
> > Try changing the icon dir to `.icons` and the path in the .desktop to also have `.icons` and see if it also displays the icon that way, without extension.
> 
> For jgmenu
> 
>     * `icons/app-name` -> does not work
> 
>     * `.icons/app-name` -> does not work
> 
>     * `icons/app-name.png` -> works

Just tested it and indeed it needs the extension, this is a separate issue then.
