### ISSUE TITLE
GameConqueror [We need help]

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1137]
1. name: GameConqueror
2. main site: https://github.com/scanmem/scanmem
3. download page: https://github.com/lucasmz1/Game_Conqueror_AppImage/releases
4. description of the application: Memory scanner designed to isolate the adress of an arbitrary variable in an executing process (gtk GUI) 

Soo unlike pince this one actually supports the usage of polkit (pince is still working on it) and the distro-native pkgs works flawlessly.
I've added description and other stuff to @lucasmz1 's [GameConqueror_AppImage](https://github.com/lucasmz1/Game_Conqueror_AppImage) repository like you said. But here's the thing @lucasmz1 built a pkg with pkg2appimage but the polkit doesn't work with that one. I built a pkg with Archimage but both pkgs give errors related to polkit (the workaround is to use sudo but yea thats a workaround)  

Could you please help us out here? (This is a skill issue both of us dont know how to make it work with polkit)

**Comment by ivan-hc** [comment]
> Could you please help us out here? (This is a skill issue both of us dont know how to make it work with polkit)

you should create a wrapper that redirects to polkit, I'm not good in these things, sorry
