### ISSUE TITLE
If you install the topgrade from am/appman whether when renewing the topgrade using am/appman or Topgrade during the clilk topgrade from terminal 

### ISSUE THREAD

**Issue by candrapersada** [ivan-hc/AM#1141]

**Comment by ivan-hc** [comment]
I have not understand your question

**Comment by ivan-hc** [comment]
if you install Topgrade from AM/AppMan, you can manage updates also for Topgrade. All program installed that have an AM-updater script into the directory of the installed app can be updated using AM/AppMan.

https://github.com/user-attachments/assets/11414a0e-d749-4c97-bf96-cb901ffaaebc

also, Topgrade detects if AM is installed (path to the command, /usr/local/bin/am) and if AppMan is in $HOME/.local/bin, and it can update them as well.

They update each other.

Is this what you wanted to know?

**Comment by candrapersada** [comment]
what I mean is to use `topgrade --no-self-update` if you install topgrade from AM/Appman

**Comment by ivan-hc** [comment]
uhm... now I understand. Do you know if Topgrade updates itself first or as latest in the list?

**Comment by candrapersada** [comment]
> Do you know if Topgrade updates itself first

yes but AM/Appman updates Topgrade again when updating AM/Appman from Topgrade

**Comment by ivan-hc** [comment]
What do you suggest I do? Should I remove the AM-updater?

**Comment by candrapersada** [comment]
https://github.com/topgrade-rs/topgrade/blob/4f4dcbb6430dc228ce80eb12370c3c68ec99633f/config.example.toml#L215

**Comment by ivan-hc** [comment]
good to know, how can I use this?

**Comment by candrapersada** [comment]
create no-self-update from `CONFIG_DIR/topgrade.toml` or use `topgrade --no-self-update`

**Comment by ivan-hc** [comment]
so in my case its enough to add a `self_rename = true` to `"$CONFIGDIR"/topgrade.toml`, that's right? If so, I can add this directli in AM and AppMan, as a security check.

**Comment by candrapersada** [comment]
Yes

**Comment by ivan-hc** [comment]
I'm not enough experienced with this kind of configuration file, should I add also `[windows]`? Is it necessary? Or its enough that I add `self_rename = true`?

**Comment by ivan-hc** [comment]
this check should be enough
```
if command -v topgrade &>/dev/null; then
	if [ -f "$CONFIGDIR"/topgrade.toml ] && ! grep -q "^self_rename = true" "$CONFIGDIR"/topgrade.toml || [ ! -f "$CONFIGDIR"/topgrade.toml ]; then
		echo "self_rename = true" >> "$CONFIGDIR"/topgrade.toml
	fi
fi
```
it detects if the `topgrade` command exists, if so, it checks if the `"$CONFIGDIR"/topgrade.toml` file exists, and if so it will check if there is a line starting with `self_rename = true`, if not, it will be added.

I installed Topgrade for this test, it was enough to run any command of AM, for example `am -v` to see the version of AM, and the file will be created with this content

![Istantanea_2024-11-19_06-23-19 png](https://github.com/user-attachments/assets/cdd3ad5d-1b1f-457b-8572-4dc5e7dfee28)

is this enough?

**Comment by candrapersada** [comment]
yes

**Comment by candrapersada** [comment]
> topgrade will look for the configuration file in the following places, in order of priority:
> 
> CONFIG_DIR/topgrade.toml
> CONFIG_DIR/topgrade/topgrade.toml
> If the file with higher priority is present, no matter it is valid or not, the other configuration files will be ignored.
> 
> On the first run(no configuration file exists), topgrade will create a configuration file at CONFIG_DIR/topgrade.toml for you.

https://github.com/topgrade-rs/topgrade?tab=readme-ov-file#configuration-path

**Comment by ivan-hc** [comment]
in order of priority... so I've done well. It seems that `"$CONFIGDIR"/topgrade.toml` is the way to go.

**Comment by ivan-hc** [comment]
please keep this opened until the changes are in "main"

in the meantime it would be useful if you test this in developer mode
```
am --devmode-enable
am -s
am -v
```
with this sequence of commands you enter the developer mode, update AM and sow the version (in developer mode it is `9.1.1-11`). The last command, `am -v`, is a random one, you can run any command and the above function will add that line to the file or will create the file with that line inside.

You should run Topgrade and see if the changes take effects.... but **before you proceede** I suggest to change the value in /opt/optgrade/version, to made the comparison detecting diffierent versions between the online one and the one installed, "updating" Topgrade via AM, when AM is called by Topgrade.

Also, enter the /opt/topgrade directory to see any moving of files and folders when the update is called.

Of course, I talked about an AM installation, but if you have AppMan, enter the related paths.

**Comment by ivan-hc** [comment]
to exit the developer mode, run
```
am --devmode-disable
```

**Comment by candrapersada** [comment]
ERROR Failed to deserialize /home/username/.config/topgrade.toml: TOML parse error at line 268, column 1
    |
268 | self_rename = true
    | ^^^^^^^^^^^
unknown field `self_rename`, expected `use_sudo`

**Comment by candrapersada** [comment]
ERROR Failed to deserialize /home/username/.config/topgrade.toml: TOML parse error at line 2, column 1
  |
2 | self_rename = true
  | ^^^^^^^^^^^
unknown field `self_rename`, expected one of `pre_sudo`, `sudo_command`, `disable`, `ignore_failures`, `remote_topgrades`, `remote_topgrade_path`, `ssh_arguments`, `tmux_arguments`, `set_title`, `display_time`, `assume_yes`, `no_retry`, `run_in_tmux`, `tmux_session_mode`, `cleanup`, `notify_each_step`, `skip_notify`, `bashit_branch`, `only`, `no_self_update`, `log_filters`


── 13:48:00 - Topgrade 16.0.0 Breaking Changes ─────────────────────────────────
# Containers step

* New default behavior: In the previous versions, if you have both Docker and 
  Podman installed, Podman will be used by Topgrade. Now the default option
  has been changed to Docker. This can be overridden by setting the 
  `containers.runtime` option in the configuration TOML to "podman".

**Comment by ivan-hc** [comment]
ok, so that setting is wrong. Maybe its better to handle this issue in an alternative way. I will see how to do.

**Comment by ivan-hc** [comment]
exit the developer mode and update AM only
```
am --devmode-disable
am -s
```
the remove the content of the topgrade.toml file and add this line instead
```
no_self_update = true
```
then retry to update with Topgrade

**Comment by ivan-hc** [comment]
@candrapersada why :-1: ?

![Istantanea_2024-11-20_01-59-22 png](https://github.com/user-attachments/assets/c22cabe9-eb26-4938-b1ba-4325966b5eca)

until proven otherwise, you are the one who gave me the wrong path in $CONFIG_DIR/topgrade.d https://github.com/ivan-hc/AM/issues/1141#issuecomment-2484745697

> yes but "$CONFIGDIR"/topgrade.d/topgrade.toml

...and you received the following messages :point_down: 

> ERROR Failed to deserialize /home/username/.config/topgrade.toml: TOML parse error at line 268, column 1 | 268 | self_rename = true | ^^^^^^^^^^^ unknown field `self_rename`, expected `use_sudo`

> ERROR Failed to deserialize /home/username/.config/topgrade.toml: TOML parse error at line 2, column 1 | 2 | self_rename = true | ^^^^^^^^^^^ unknown field `self_rename`, expected one of `pre_sudo`, `sudo_command`, `disable`, `ignore_failures`, `remote_topgrades`, `remote_topgrade_path`, `ssh_arguments`, `tmux_arguments`, `set_title`, `display_time`, `assume_yes`, `no_retry`, `run_in_tmux`, `tmux_session_mode`, `cleanup`, `notify_each_step`, `skip_notify`, `bashit_branch`, `only`, `no_self_update`, `log_filters`

... as a result of adding the line you suggested here :point_down: 

> https://github.com/topgrade-rs/topgrade/blob/4f4dcbb6430dc228ce80eb12370c3c68ec99633f/config.example.toml#L215

and in the error message you showed me, the `no_self_update` entry I suggested exists. I assumed that this is the element to add to the configuration file, since it is the only one with the "sensible" name, but I could be wrong. And because of this, I would like you to comment on your opinion. In words please, not with "reactions to comments".

Since you opened this issue and it is in your interest that this problem is solved.

**Comment by candrapersada** [comment]
is it possible to create a symlink with custom arguments
```
echo '
    #!/bin/sh
    /opt/topgrade/topgrade --no-self-update "$@"
' > /usr/local/bin/topgrade 
```

**Comment by ivan-hc** [comment]
> is it possible to create a symlink with custom arguments
> 
> ```
> echo '
>     #!/bin/sh
>     /opt/topgrade/topgrade --no-self-update "$@"
> ' > /usr/local/bin/topgrade 
> ```
> 
> `chmod +x /usr/local/bin/topgrade `

of course

**Comment by ivan-hc** [comment]
remove and reinstall Topgrade, I added this directly in the installation script
