### ISSUE TITLE
`am -t ` adds personal git token in the template script.

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/AM#1146]
issue title should suffice. 

if you need further explanation please let me know.

**Comment by ivan-hc** [comment]
you are right, the function responsible is this
```
function _template_if_github() {
	SITE="https://github.com"
	RESPONSE=$(echo "$RESPONSE" | sed 's#https://github.com/##g' | cut -f1,2 -d'/')
	COMMENT=$(curl $HeaderAuthWithGITPAT https://api.github.com/repos/"$RESPONSE" 2>/dev/null | grep description | sed 's/"description": "//' | sed 's/",//' | cut -c 3-)
	CURL_COMMAND_REF="curl -Ls $HeaderAuthWithGITPAT https://api.github.com/repos"
}
```
"CURL_COMMAND_REF" is needed to apply the command bothe when testing the URL and when adding the command.

I need to use a different variable for this. Thanks for reporting this.
