### ISSUE TITLE
Icon not working with jgmenu

### ISSUE THREAD

**Issue by twnaing** [ivan-hc/AM#1150]
> > Try changing the icon dir to `.icons` and the path in the .desktop to also have `.icons` and see if it also displays the icon that way, without extension.
> 
> For jgmenu
> 
>     * `icons/app-name` -> does not work
> 
>     * `.icons/app-name` -> does not work
> 
>     * `icons/app-name.png` -> works

Just tested it and indeed it needs the extension, this is a separate issue then.

_Originally posted by @Samueru-sama in https://github.com/ivan-hc/AM/issues/1136#issuecomment-2489198056_

**Comment by ivan-hc** [comment]
Try the command `am icons --all` to change all .desktop files and have all icons symlinked locally, so it also supports icon themes.

Regarding the directory, can you symlink to $HOME/.local/share/.icons?

**Comment by Samueru-sama** [comment]
I don't think we can do much other than using the recent mode that Ivan added that allows using the icons from your icon theme. 

On unix the file extension isn't required and instead apps check the file with `file` or similar means to determine what it is.

**Comment by twnaing** [comment]
> Try the command `am icons --all` to change all .desktop files and have all icons symlinked locally, so it also supports icon themes.
> 
> Regarding the directory, can you symlink to $HOME/.local/share/icons?

After running this command, jgmenu shows the correct icons.

Regarding support for the icon themes, is it possible to automatically derive app name from AppImage (if I omit the name)? 

If I install 

$ appman install -e username/repo_name not-standard-name

there is high chance to miss the icon themes even if the themes have the icon.

**Comment by ivan-hc** [comment]
the icon will get the name you provide in `-e`, so it will rely on the icon name

NOTE, with `-e` you must run the `am icons --all` or `am icons {NEW-PROGRAM}` each time you install an app not listed if you want the icon

On the contrary, `-i` has a flag `--icons` that will do this authomatically in one step

**Comment by twnaing** [comment]
> On the contrary, -i has a flag --icons that will do this authomatically in one step

But `-i` does not allow installation of AppImage from GitHub. Am I right?

**Comment by ivan-hc** [comment]
AM has a database including 2100+ AppImages, plus other 400+ portable formats.

Use `am -q {KEYWORD}` to search the one you prefer, and `am -a {PROGRAM}` to have more details about that app, including the source site/repository.

NOTE, all pages for `-a` come from this catalogue https://portable-linux-apps.github.io that lists all installable programs.

Option `-e` is for apps that are not listed on that catalogue (or that are listed but you don't like the name, for example if you want call `simplescreenrecorder` as `ssr`).
