### ISSUE TITLE
`am -t` adds GH secrets to script

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#1152]
# Premise
"AM"/"AppMan" is just a tool to provide applications easily and quickly and is only responsible for integrating the AppImages into the system and installing the various programs available, respecting the following order (refer to the option "-d" to download the installation script without installing it):
- creation of the base directories and the removal script
- download of the package
- creation of the version file and the update script
- possibly, extraction of the icons and .desktop files, if needed

The malfunction of the installation scripts will then be taken into account. On the contrary, any malfunction related to individual applications is the responsibility of the related developer or packager. Refer to the option "-a" to know the sources of each program listed here, so you can contact them to report the bug.

--------------------------------------------------

## Are you using "AM" or "AppMan"?
`am`

## What GNU/Linux distribution are you using it on?
elementaryOS

## Please, describe the bug
I create scripts using `am -t` (you know already). I tried pushing today a few scripts I had made some time ago, but I got an error that my commit contains secrets. After some googling, I saw that the NEWER scripts (made this month) had added the github tokens in the script itself in two places (both checking for version) in this format:

```
version=$(curl -Ls  --header "Authorization: token xxxxxxx"  https://api.github.com/repos/Materialious/Materialious/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
wget "$version" || exit 1
```
and
```
version=$(curl -Ls  --header "Authorization: token xxxxxxx"  https://api.github.com/repos/Materialious/Materialious/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -vi "i386\|i686\|aarch64\|arm64\|armv7l" | head -1)
[ -n "$version" ] || { echo "Error getting link"; exit 1; }
```
Even removing the tokens manually installs but the program fine but I am unable to upload the scripts even after removing the secrets (I keep on getting the same error). I removed the local repo and will try pulling again (fresh) and copy pasting the script myself to see if it works, but please do look into it. Maybe I am making some mistake? The two scripts I had made earlier (one-two months ago) were committed just fine.

## What are the steps/commands to perform?
`am -t xyz`
(I tried [Flowinity](https://github.com/Flowinity/Desktop) and [Materialious](https://github.com/Materialious/Materialious))

## What is the expected behavior?
Scripts will not have secrets lol

**Comment by Sush-ruta** [comment]
UPDATE: Freshly cloning the repo, copy pasting the code from the `am -t` script manually (without the secret of course) allows commit, @ivan-hc

**Comment by ivan-hc** [comment]
hi, this was fixed https://github.com/ivan-hc/AM/issues/1146 you should update
