### ISSUE TITLE
Portables/Appimages to add

### ISSUE THREAD

**Issue by GeoBoi254** [ivan-hc/AM#116]
Artix Launcher
https://www.artix.com/downloads/artixlauncher/

Thorium AVX2
https://github.com/Alex313031/Thorium-Linux-AVX2/releases

Mortrix
https://motrix.app/download

Mercury
https://github.com/Alex313031/Mercury/releases

**Comment by ivan-hc** [comment]
- Artix, Mercury and Thorium-avx2 are been added in the repository right now https://github.com/ivan-hc/AM-Application-Manager/commit/1cf8c3e136e47501001207c4f58c28e399846324 I have created the launcher for Thorium-avx2 by myself, using the one of Firefox;
- Motrix already exists in the repository (its taken from the oggicial github repository)

**Comment by GeoBoi254** [comment]
qBittorrent Enhanced
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases

**Comment by ivan-hc** [comment]
@GeoBoi254 I remembered of this "Enhanced version of qBittorrent"... it never worked for me
```
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, xcb.
```
but if it works for you, I'll add it.

**Comment by GeoBoi254** [comment]
LM Studio
https://lmstudio.ai/beta-releases.html#linux-beta

**Comment by ivan-hc** [comment]
Better to keep the matter open, maybe someone will want to make requests from here

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM/commit/a726772fcdb229c607bb677a189e9d2844bf95ea

**Comment by Graninius** [comment]
**Hiddify-Next**
https://github.com/hiddify/hiddify-next

**ChatGPT-Next-Web)**
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web

**Mercury**
https://github.com/Alex313031/Mercury

**Floorp**
https://github.com/Floorp-Projects/Floorp

**Comment by tuchanemo** [comment]
The file /opt/mercury/mercury is missing after installation

**Comment by Graninius** [comment]
Hm... I have bin vers. installed and the path is */opt/mercury-browser/*

вс, 11 февр. 2024 г. в 10:24, Alex ***@***.***>:

**Comment by Graninius** [comment]
Oh... It's my mistake. I misunderstood you. It wasn't an AppImage in those
screenshots. I removed it and then installed AppImage using Appman. Now I'm
encountering the same error with missing files

вс, 11 февр. 2024 г. в 15:09, Igor Minaev ***@***.***>:

**Comment by ivan-hc** [comment]
> ChatGPT-Next-Web

OK

The others are bundled in archives (only the .zip contain an AppImages).

When they are so, tell me at least the sequence of `tar`/`zip` commands you use to install them, so I can easily create a script from templates instead of learn everything by myself about apps I don't know and I'll never use. I've done a `-t` option for this purpose.

Talking about Mercury (already fixed) and Floorp (not uploaded yet), when they are not AppImages, I have to manually create a .desktop file, add an icon, I have to find a sequence of commands to extract the archives... and more often the developers can change the name of the archive or its content, read my answer here https://github.com/ivan-hc/AM/issues/125

I want to add them, but don't leave me alone when there is all this stuff to work on.

**Comment by ivan-hc** [comment]
@Graninius done https://github.com/ivan-hc/AM/commit/aff38f7015590515fe74d75242907e7917b25fbf

**Comment by Graninius** [comment]
> @Graninius done [aff38f7](https://github.com/ivan-hc/AM/commit/aff38f7015590515fe74d75242907e7917b25fbf)

Oh... This is one of the most useful projects I've ever come across. Thank you so much!

**Comment by Graninius** [comment]
> **Floorp** https://github.com/Floorp-Projects/Floorp

It seems there's something wrong with it. I can't open it using the Desktop shortcut, only through the console. Maybe this log can help:
`❯ floorp

(floorp:16453): Gtk-WARNING **: 22:21:06.775: Theme directory 16x16/panel of theme Mkos-Big-Sur has no size field


(floorp:16453): Gtk-WARNING **: 22:21:06.781: Theme directory 16x16@2x/places of theme Mkos-Big-Sur has no size field


(floorp:16453): Gtk-WARNING **: 22:21:06.785: Theme directory 24x24/apps of theme Mkos-Big-Sur has no size field

console.error: ({})
JavaScript error: resource://gre/modules/ExtensionSettingsStore.sys.mjs, line 113: Error: The ExtensionSettingsStore was accessed before the initialize promise resolved.
JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.`

**Comment by ivan-hc** [comment]
@Graninius Errors related to the app itself are not of my responsibility but of the author of it. All I can do here is to fix the launcher https://github.com/ivan-hc/AM/commit/f2858ed37b20c5a51d46f354fb9e01f3f87e3a46 that was my mistake

**Comment by Graninius** [comment]
> @Graninius Of course, I understand it. Thank you for fixing the launcher. Everything is working like a charm now! Great job!

**Comment by GeoBoi254** [comment]
Thorium SSE3
https://github.com/Alex313031/thorium/releases

Mercury SSE3/SSE4/AVX2
https://github.com/Alex313031/Mercury/releases

- SSE3/SSE4 are for older CPUs

**Comment by ivan-hc** [comment]
@GeoBoi254 the following releases will overwrite existing version of Mercury/Thorium if they exist https://github.com/ivan-hc/AM/commit/13f386d61337bbc326dcea2c7273091c6fa4f3df

**Comment by GeoBoi254** [comment]
Celeste64
https://github.com/ExOK/Celeste64

Vesktop
https://github.com/Vencord/Vesktop

Ricochlime
https://github.com/adil192/ricochlime

Nyrna
https://github.com/Merrit/nyrna

jGRASP
https://www.jgrasp.org/index.html

**Comment by ivan-hc** [comment]
I can't add jGRASP, there is not an easy downloadabe link to reach

**Comment by GeoBoi254** [comment]
> I can't add jGRASP, there is not an easy downloadabe link to reach

My mistake, you can replace that with Eclipse IDE
https://www.eclipse.org/downloads/packages/

**Comment by ivan-hc** [comment]
what is the desktop file for Celeste64?

**Comment by ivan-hc** [comment]
Possibly, when you provide me with applications in .zip or .tar format that are not AppImage, you must also provide me with links to the icon and the .desktop file, otherwise you will open the applications from the command line, not from the menu.

**Comment by ivan-hc** [comment]
I've uploaded only the other four https://github.com/ivan-hc/AM/commit/d49826da13a2a2b3e27ccd67d655bfa6acaead0f and I've provided manually to create the missing .desktop file and icon for Celeste64.

As for the last app you suggested as an alternative, Eclipse IDE, the download link redirects to another page.

When this is the case, look for other sources that are different and are reachable (or at least findable) with `wget` and `curl`. I can't do magic.

So jGRASP and Eclipse IDE are not been uploaded.

I could use a hard, direct link, but then it would have to be updated with each version, and I don't want that. I have to use a command that remains, like in all other scripts in this database. But for that type of pages it's difficult. Among the templates that you can find with the `am -t $YOUR-APP` command, there are some that rely on the AUR to find the URL or at least locate the latest version. I could use those, but in my experience, many users who upload PKGBUILD to the AUR are untrustworthy, as they don't update the scripts, causing them to be removed. I would like to avoid AUR as a source.

Packages from sites outside of Github are a pain in the ass. Really. I hate them.

**Comment by ivan-hc** [comment]
@GeoBoi254  Just discovered a way to have jGRASP and Eclipse IDE, but in first you should provide me a .destop file (if does not exists, you can create it manually) and a URL to the icon.

**Comment by Graninius** [comment]
**Reor**
https://github.com/reorproject/reor

**Comment by ivan-hc** [comment]
@GeoBoi254 Eclipse IDE is not a portable app, it is an INSTALLER

**Comment by rusberiaosa** [comment]
hades-emu https://github.com/hades-emu/Hades
mauikit-apps https://mauikit.org/apps/

**Comment by rusberiaosa** [comment]
@ivan-hc I think qbittorrent-enhanced doesn't work because you need to add an environment variable i.e `export QT_QPA_PLATFORM="xcb" `  to bashrc or bash_profile and also making sure qt5-wayland and qt6-wayland packages are installed if you're using wayland.

**Comment by zen0bit** [comment]
[SweetHome3D](https://www.sweethome3d.com/)

**Comment by ivan-hc** [comment]
> @ivan-hc I think qbittorrent-enhanced doesn't work because you need to add an environment variable i.e export QT_QPA_PLATFORM="xcb" to bashrc or bash_profile and also making sure qt5-wayland and qt6-wayland packages are installed if you're using wayland.

@rusberiaosa if so, I can replace the symlink with a script like this
```
#!/usr/bin/env bash

APP=qbittorrent-enhanced
export QT_QPA_PLATFORM="xcb"
/opt/$APP/$APP "$*"
```
its the same scheme I use in Kdenlive and Avidemux

**Comment by ivan-hc** [comment]
@zen0bit is this an installer? Is here the risk that once launched it installs stuff in the $HOME?

**Comment by ivan-hc** [comment]
@zen0bit @rusberiaosa https://github.com/ivan-hc/AM/commit/c56f1c318372a0a7aa90ceb1c1c7186570af1f40

**Comment by ivan-hc** [comment]
@rusberiaosa thanks https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/7b045ecdc087bb16cd4bb266eff4a5cd29b4850c

unless the authors decide to follow the path of the Coreapps developer (for which I had to remove 15 Appimages, https://github.com/ivan-hc/AM/commit/29d2b9b04b9013c6e4996d9ca290fd66278523cb), today we have reached 1901 installation scripts for x86_64 applications.

:pray:  May this work of ours not be in vain! :pray:

**Comment by ivan-hc** [comment]
> unless the authors decide to follow the path of the Coreapps developer (for which I had to remove 15 Appimages, https://github.com/ivan-hc/AM/commit/29d2b9b04b9013c6e4996d9ca290fd66278523cb), today we have reached 1901 installation scripts for x86_64 applications.

About https://gitlab.com/cubocore , is there anyone that can find old artifacts in AppImage format?

**Comment by rusberiaosa** [comment]
@ivan-hc thank you so much and hooray!! less than an 100 more to go for 2000 :tada: 
note: I think kdenlive doesn't need the variable it works without any interference. Some mauikit apps work wihout any work but some need the env-variables.

**Comment by ivan-hc** [comment]
> note: I think kdenlive doesn't need the variable it works without any interference

Kdenlive/Avidemux user here, I don't like to have fonts smaller than the ones of my default configuration.

> Some mauikit apps work wihout any extra hassle but some need the env-variables.

OK, tell me what of them and I'll patch them (it should be the upstream developer's job to patch the AppRun inside the AppImage to make it work correctly).

**Comment by rusberiaosa** [comment]
my initial guess was wrong; all of them pretty much need the xcb variable to work on wayland.
**the list of all apps tested and work (on x11)**

1.  communicator
2. clip 
3. index 
4. station
5. buho
6. nota
7. fiery
8. vvave
9. bonsai
10. strike

**the list of apps that don't work on neither x11 nor wayland.(due to improper packaging, not including dependencies, etc..)**

1. Pix 
2. shelf

**the list of apps that don't have appimages (so they should be ignored).**

1. agenda
2. arca
3. booth
4. era
5. mauiman

I tested all of them and none of them work without xcb variable on **wayland** but this should be fine with xwayland though.
Sorry for my incorrect estimation previously.
the appimages can be found at https://download.kde.org/stable/maui/

**Comment by ivan-hc** [comment]
oh, ok... so this is a problem of the developer itself, not mine. Should I add the variable or not? I've not understand.

**Comment by rusberiaosa** [comment]
don't add it

**Comment by fiftydinar** [comment]
XL Converter:
https://github.com/JacobDev1/xl-converter

- Notable for supporting JPEG-XL format for converting, which other GUI apps don't support (I used a lot of them).

Also, my advice is to pin this issue in GitHub, if you decided it's good for mass AppImages addition requestst.

**Comment by ivan-hc** [comment]
@fiftydinar done https://github.com/ivan-hc/AM/commit/2ed8c089dc179a94c6b02e1bab0d0dcbd2088dda

> Also, my advice is to pin this issue in GitHub, if you decided it's good for mass AppImages addition requests.

I was thinking of a form for this type of request.

**Comment by GeoBoi254** [comment]
Tenacity
https://codeberg.org/tenacityteam/tenacity

SeriousSamClassic
https://github.com/tx00100xt/SeriousSamClassic

CosmicCosmics
https://github.com/Nytuo/CosmicComics

Gopeed
https://github.com/GopeedLab/gopeed

Hypersomnia
https://hypersomnia.xyz/

**Comment by rusberiaosa** [comment]
I went through the list of every opensource emulators available on linux and picked out the ones that have an appimage. The ones which are not in the AM-REPO are: 

1. Vita3k https://github.com/Vita3K/Vita3K
2. xm8 https://github.com/bubio/xm8mac
3. desmume https://www.appimagehub.com/p/1411229
4. Snes9x https://github.com/snes9xgit/snes9x
5. RMG https://github.com/Rosalie241/RMG
6. EKA2L1 https://github.com/EKA2L1/EKA2L1
7. zxpoly https://github.com/raydac/zxpoly/
8. ES_DE https://es-de.org/#Download
9. JRomManager https://github.com/optyfr/JRomManager/

**Comment by ivan-hc** [comment]
### New "AM" / AppMan 6.0.3 is out! 
### *https://github.com/ivan-hc/AM/releases/tag/6.0.3*

I have improved in all respects the use of the "-t" option, the one used to create installation scripts.

This change will certainly help me much more to load the new apps that you want to report to me... but I invite all of you to run the tests and gain experience with the creation of custom installation scripts, and then, possibly, send me a Pull Request directly (and consequently, become [contributors](https://github.com/ivan-hc/AM/graphs/contributors)... I will be happy to help you directly in the "[pull requests](https://github.com/ivan-hc/AM/pulls)" section, in case of problems with your works).

You can test new scripts directly using the `-i` or `install` option.

**Comment by fiftydinar** [comment]
DeaDBeeF music player:
https://deadbeef.sourceforge.io/download.html

It contains stable portable builds, which is perfect for this submission.

**Comment by ivan-hc** [comment]
> DeaDBeeF music player

faster like never before (thanks to my new "templates" or "-t" option)

https://github.com/ivan-hc/AM/commit/03978a77924bade2a6c4c085330219890a4ef870

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/2d9e59bce3e3d23197a30657dac87d7a41c7fa97

**Comment by DimastaKi** [comment]
**Fastfetch**
[https://github.com/fastfetch-cli/fastfetch](https://github.com/fastfetch-cli/fastfetch)

**Translate Shell**
[https://github.com/soimort/translate-shell](https://github.com/soimort/translate-shell)

**Comment by ivan-hc** [comment]
@DimastaKi done

https://github.com/ivan-hc/AM/commit/c2547a4e23752f5e0164cb3641940582ce065bba

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/7ee96f19869508fdaacf742438ae1ae51883aa49

**Comment by zen0bit** [comment]
BambuStudio
AppImages [provided](https://github.com/bambulab/BambuStudio/releases)

**Comment by ivan-hc** [comment]
Sorry @zen0bit , latelly I have some issues in compiling [Bottles AppImage](https://github.com/ivan-hc/Bottles-appimage)

![Istantanea_2024-02-28_04-35-39](https://github.com/ivan-hc/AM/assets/88724353/3429f4b6-a643-496e-8dad-578efe4a9948)

I'll be back here to upload apps as soon as possible

**Comment by ivan-hc** [comment]
@zen0bit done

https://github.com/ivan-hc/AM/commit/5fef74128f0bbad94c3c36a16bcbdef4cea2937e

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/cc0c92cfa2d1f9c26ef73544ccb772f4a88ff46e

**Comment by ivan-hc** [comment]
UPDATE https://github.com/ivan-hc/AM/commit/9a5576e4e8f89fa6f23e94f897b6722f30e40554

If you use the command `am -t $PROGRAM` and select 2 (any archive 7z/deb/*tar*/zip, and now also scripts and standalone binary files) you don't need to specify the commands to extract/move the app anymore!

This is a quick example (don't take it seriously):

https://github.com/ivan-hc/AM/assets/88724353/2ed69ce5-1d22-4a7b-8724-90bda0694a46

Are you able to do the same?

**Comment by zen0bit** [comment]
[emby](https://emby.media/index.html)

**Comment by ivan-hc** [comment]
@zen0bit 
> [emby](https://emby.media/index.html)

this has not a portable version, the .deb package require the installation (the internal binary may be not standalone), the Arch Linux archive may be compiled only for newer GLIBC dependences (and maybe it have dependences as well).

Or maybe its me that have not seen a portable version.

**Comment by fiftydinar** [comment]
RQuickShare

Has AppImage:
https://github.com/Martichou/rquickshare

**Comment by ivan-hc** [comment]
> RQuickShare

done https://github.com/ivan-hc/AM/commit/7ecc0e1c3b8e6fcf2161eec08cc7e3971ad25182

**Comment by ivan-hc** [comment]
Do you remember my previous answer where I was wary of appimagehub?

https://www.appimagehub.com/p/2106184

That Appimage of GIMP is mine.

The thing that pisses me off though is that there is a link to the sources for all the other AppImages... **except mine**.

And meanwhile there are those who ask for "support" (in money) on the pages of that shitty site at the expense of the original developers.

**Comment by zen0bit** [comment]
agregore-browser

[AgregoreWeb/agregore-browser](https://github.com/AgregoreWeb/agregore-browser/releases)

**Comment by zen0bit** [comment]
> @zen0bit done
> 
> https://github.com/ivan-hc/AM/commit/87c8c0972e85257c61e484f063e466676f152654
> 
> https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/21966fb92deb86509fc653e3c48f0b82bea29b39

ERROR: YOU CANNOT INSTALL ""AGREGORE"" WITHOUT INSTALLING "ZSYNC"!
/opt/am/modules/install.am: line 87: break: only meaningful in a `for', `while', or `until' loop
 ◆ "AGREGORE": starting installation script

But is installed..

**Comment by ivan-hc** [comment]
@zen0bit add bug fix in install.am https://github.com/ivan-hc/AM/commit/edcb8c781a42b422322aac8c5a8ede78750fbab5

**Comment by ivan-hc** [comment]
@zen0bit this is the last fix about apps asking for zsync. If the app requires zsync as an option, AM/AppMan will proceed with the installation (after a warning message), but if its strictly required, it will abort the installation.

https://github.com/ivan-hc/AM/assets/88724353/76297568-8377-4155-96da-be85a5074117

or should I make it mandatory anyway?

About 80-90 installation scripts require "zsync", whether it is mandatory or not.

But in the future, other existing scripts may need the latest template, as many compare the upstream version even though a .zsync file already exists (my fault, I had some oversights).

**Comment by zen0bit** [comment]
Good as is

**Comment by ivan-hc** [comment]
Folks, I've thought about it again.

Since a single issue for all requests could become too long and wasteful... it would be better to report a new issue for each app.

Also, there's no point in keeping this open and inactive. It could be confusing, on long term.

At least, if any of you are interested. could create "templates" to submit requests of this type. I know these are MarkDown files. If you understand how troubleshooting works... you're welcome. I'll gladly accept a PR.

Grouping a single request for each issue would help, even in case of debugging and reporting problems related to the newly uploaded app.

I don't know how many apps we have loaded into this issue, but it's best to keep one dedicated to each app.

-----------------------------

Finally, I have an important OFF-TOPIC announcement to make. I have converted almost all my AppImages (there are more than 60 in total) to Type3: no `libfuse2` required to run them!

Obviously each app can have its own problems in being created (that's why I left only 4 for x86_64 and the 4 32bit ones at Type2 state).

Archimages are ALL Type3, so you are safe. The full list is on my github profile.

I'm closing. See you in other Issues.

If you need me, I'm here.
