### ISSUE TITLE
Windsurf 

### ISSUE THREAD

**Issue by sbucek** [ivan-hc/AM#1165]
1. windsurf
2. [https://codeium.com/windsurf](https://codeium.com/windsurf)
3. [download page](https://codeium.com/windsurf/download)
4. The first agentic IDE
5. [URL to the application icon](https://codeium.com/logo/windsurf_teal_logo.svg)
6. the .desktop* file not found

**Comment by ivan-hc** [comment]
I'm traying to find and alternative source to get the download URL for the TAR archive and fount the AUR https://aur.archlinux.org/packages/windsurf-bin only that I can't find the maintainer on github anymore, "ZorinArch", it seems was active until few days ago and now its profile has been removed https://github.com/ZorinArch

I don't know if this is temporary, but I'd like to use a reliable source that will not be removed so easily.

**Comment by ivan-hc** [comment]
OK, it is still active

![Istantanea_2024-11-29_01-46-51 png](https://github.com/user-attachments/assets/a2fcf3e5-8583-406e-b072-89679d242da0)

I'll rely on its AUR page for the download URL

**Comment by ivan-hc** [comment]
Bad news, I must remove the app. The AUR reference has been removed too. I can't download it anymore and the url fails. Sorry
