### ISSUE TITLE
2 MC launchers

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1176]
1. name: x-minecraft-launcher
2. main site: https://github.com/Voxelum/x-minecraft-launcher/
3. download page: https://github.com/Voxelum/x-minecraft-launcher/releases
4. description of the application: An Open Source Minecraft Launcher with Modern UX. Provide a Disk Efficient way to manage all your Mods!

**Comment by Twig6943** [comment]
1. name: helioslauncher
2. main site: https://github.com/dscalzi/HeliosLauncher
3. download page: https://github.com/dscalzi/HeliosLauncher/releases
4. description of the application: ☀ Custom launcher for modded minecraft written in Electron and Node.js

**Comment by ivan-hc** [comment]
these two apps are already in this database

![Istantanea_2024-12-02_00-17-57](https://github.com/user-attachments/assets/1315982f-bce9-4cf3-89b4-36e91caef0fc)

always make sure they exist by consulting the lists with `-l` or searching the lists with `-q` or even just hitting TAB multiple times if you have shell completion enabled... before sending a request
