### ISSUE TITLE
Better specify colors ❗❗❗

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#121]
𝙋𝙇𝙀𝘼𝙎𝙀 𝙎𝙃𝘼𝙍𝙀 𝙏𝙃𝙄𝙎 𝙋𝙍𝙊𝙅𝙀𝘾𝙏 & 𝙎𝙋𝙍𝙀𝘼𝘿 𝙄𝙏 𝙏𝙊 𝙏𝙃𝙀 𝙇𝙄𝙉𝙐𝙓 𝙒𝙊𝙍𝙇𝘿❗❗❗

 𝙃𝙀𝙇𝙋 𝙈𝙀 𝙆𝙀𝙀𝙋 𝙏𝙃𝙄𝙎 𝙋𝙍𝙊𝙅𝙀𝘾𝙏 𝘼𝙇𝙄𝙑𝙀❗❗❗

The red ! ! ! don't work for me in terminal

Don't use it, or specify dependency

**Comment by zen0bit** [comment]
But using color (by default, or check if terminal support it, switchable) for help message would be nice. Could improve readability a lot.

**Comment by ivan-hc** [comment]
[Again](https://github.com/ivan-hc/AM/issues/120#issuecomment-1931017102), I can remove this message, it may be not so important if you all continue share/spread my works to the people. Facebook, Reddit, Twitter, Youtube... anywhere. I'm not a spammer...and even if I were, I wouldn't be credible, being the developer of this program.

I did my part by providing you the software, now you, the users, have to do your part by keeping me alive. I think that's the case with all existing projects.
