### ISSUE TITLE
UltimMC

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#1222]
1. name:ultimmc
2. main site:https://github.com/UltimMC/Launcher
3. download page: https://nightly.link/UltimMC/Launcher/workflows/main/develop/mmc-cracked-lin64.zip
4. description of the application: Offline Minecraft launcher
5. URL to the application icon: [ICON](https://private-user-images.githubusercontent.com/62727185/311068678-48d60c15-23ae-4d48-84b8-813f72db6cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNzUzNTgsIm5iZiI6MTczNDE3NTA1OCwicGF0aCI6Ii82MjcyNzE4NS8zMTEwNjg2NzgtNDhkNjBjMTUtMjNhZS00ZDQ4LTg0YjgtODEzZjcyZGI2Y2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDExMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjAyYTZhM2ZhZjBhZDAzZGM5ZjVkMmQxNDIwNTZlMTc3YTdkOTJkOWM5NzVkNzE2MmNjZDM2MDc4MzA3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y_iMRL93QgvUEVmpzPUIUzJao5tzAlrk07RSsJAuzPM)
6. the .desktop* file (choose whether to add a URL, to paste the content of the file, to drag a text file into your comment or to provide only the following 3 desktop entries, `Name=`, `Exec=` and `Categories=`

[Desktop Entry]
Name=UltimMC
Exec=UltimMC
Terminal=false
Icon=ultimmc
StartupWMClass=UltimMC
Type=Application
Categories=Application;Game;

**Comment by ivan-hc** [comment]
Removed https://github.com/ivan-hc/AM/commit/b150b225a6fd19d2b6486e65047633f486305d13

The dev seems to be disappeared, and releases (or better, the artifacts in github actions) are unmaintained and left buid stuff on their own.

Its useless to open an issue there, you will not get answered. It is enough that you navigate the section.

**Comment by Twig6943** [comment]
> Removed [b150b22](https://github.com/ivan-hc/AM/commit/b150b225a6fd19d2b6486e65047633f486305d13)
> 
> The dev seems to be disappeared, and releases (or better, the artifacts in github actions) are unmaintained and left buid stuff on their own.
> 
> Its useless to open an issue there, you will not get answered. It is enough that you navigate the section.

@ivan-hc you're right about that. I've stopped using it anyways. Could you add fjord launcher instead? https://github.com/unmojang/FjordLauncher/releases
