### ISSUE TITLE
COLORS

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#123]
My last issues with color was just about that three red !!! Used. I am seing strange letters instead. On computer without installed nerd/awesome font.

If you want use colors (Good idea)
Set colors in bash, without needing for extra font installed.

PS: Don't close issues to quickly. I don't wanna spam your repo with new issue if old isn't resolved but closed. Thank you

**Comment by ivan-hc** [comment]
The message you are talking about does not exsts anymore https://github.com/ivan-hc/AM/commit/6d05a8278ab03db90df1f038f4efc116923d049e

**Comment by ivan-hc** [comment]
> PS: Don't close issues to quickly. I don't wanna spam your repo with new issue if old isn't resolved but closed. Thank you

Let talk at https://github.com/ivan-hc/AM/pull/122
