### ISSUE TITLE
Haveno-Reto

### ISSUE THREAD

**Issue by aljustiet** [ivan-hc/AM#1239]
1. haveno-reto
2. https://github.com/retoaccess1/haveno-reto
3. [download page](https://github.com/retoaccess1/haveno-reto/releases)
4. Decentralised P2P exchange built on Monero and Tor - unofficial Reto network

**Comment by aljustiet** [comment]
❯ gio launch ~/.local/share/applications/haveno-reto-AM.desktop
gio: Unable to launch application ‘/home/aljustiet/.local/share/applications/haveno-reto-AM.desktop’: Desktop file didn’t specify Exec field
❯ /home/aljustiet/.local/bin/haveno-reto -c "PATH=\"\\$HOME/.local/bin:\\$PATH\"; bin/Haveno %u"
haveno.common.config.ConfigException: The specified config file '/home/aljustiet/.local/share/Haveno-reto/PATH="\/home/aljustiet/.local/bin:\/home/aljustiet/.cargo/bin:/home/aljustiet/.local/share/zinit/polaris/bin:"/home/aljustiet/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/aljustiet/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/aljustiet/.local/bin":/home/aljustiet/.local/bin:/home/aljustiet/Documents/platform-tools:/home/aljustiet/go/bin"; bin/Haveno %u' does not exist.
	at haveno.common.config.Config.parseOptionsFrom(Config.java:763)
	at haveno.common.config.Config.<init>(Config.java:672)
	at haveno.core.app.HavenoExecutable.execute(HavenoExecutable.java:116)
	at haveno.desktop.app.HavenoAppMain.main(HavenoAppMain.java:64)
error: The specified config file '/home/aljustiet/.local/share/Haveno-reto/PATH="\/home/aljustiet/.local/bin:\/home/aljustiet/.cargo/bin:/home/aljustiet/.local/share/zinit/polaris/bin:"/home/aljustiet/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/aljustiet/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/aljustiet/.local/bin":/home/aljustiet/.local/bin:/home/aljustiet/Documents/platform-tools:/home/aljustiet/go/bin"; bin/Haveno %u' does not exist.

**Comment by ivan-hc** [comment]
I'm investigating, this is the contento of the original .desktp file
```
Comment=A decentralized, Tor-based, P2P Monero exchange network.
Exec=sh -c "PATH=\"\\$HOME/.local/bin:\\$PATH\"; bin/Haveno %u"
GenericName[en_US]=Monero Exchange
GenericName=Monero Exchange
Icon=haveno
Categories=Office;Finance;Java;P2P;
Name[en_US]=Haveno
Name=Haveno
Terminal=false
Type=Application
MimeType=
X-AppImage-Name=Haveno
StartupWMClass=Haveno
```
and this is how appman changes it
```
[Desktop Entry]
Comment=A decentralized, Tor-based, P2P Monero exchange network.
Exec=/home/ivan/.local/bin/haveno-reto -c "PATH=\"\\$HOME/.local/bin:\\$PATH\"; bin/Haveno %u"
GenericName[en_US]=Monero Exchange
GenericName=Monero Exchange
Icon=/home/ivan/.local/share/appman/haveno-reto/icons/haveno-reto
Categories=Office;Finance;Java;P2P;
Name[en_US]=Haveno
Name=Haveno
Terminal=false
Type=Application
MimeType=
X-AppImage-Name=Haveno
StartupWMClass=Haveno
```

**Comment by ivan-hc** [comment]
this should solve the issue

**Comment by ivan-hc** [comment]
@aljustiet let me know if it works now

**Comment by azizsayfiddin** [comment]
It doesn't launch again.
```
❯ gio launch .local/share/applications/haveno-reto-AM.desktop
gio: Unable to launch application ‘.local/share/applications/haveno-reto-AM.desktop’: Desktop file didn’t specify Exec field
❯ cat .local/share/applications/haveno-reto-AM.desktop
[Desktop Entry]
Comment=A decentralized, Tor-based, P2P Monero exchange network.
Exec=/home/aljustiet/.local/bin/haveno-reto -c "PATH=\"\\$HOME/.local/bin:\\$PATH\"; bin/Haveno %u"
GenericName[en_US]=Monero Exchange
GenericName=Monero Exchange
Icon=/home/aljustiet/Applications/haveno-reto/icons/haveno-reto
Categories=Office;Finance;Java;P2P;
Name[en_US]=Haveno
Name=Haveno
Terminal=false
Type=Application
MimeType=
X-AppImage-Name=Haveno
StartupWMClass=Haveno
```

**Comment by ivan-hc** [comment]
> It doesn't launch again.

Sorry, for some reason I don't remember, the custom launcher was removed in a commit. It should work again now. Reinstall.
