### ISSUE TITLE
Haveno

### ISSUE THREAD

**Issue by aljustiet** [ivan-hc/AM#1240]
1. haveno
2. [main site, repository or reference web page (URL, DO NOT use direct download link)](https://haveno.exchange/)
3. [download page](https://github.com/haveno-dex/haveno/releases)
4. Decentralised P2P exchange built on Monero and Tor.

**Comment by ivan-hc** [comment]
Same as https://github.com/ivan-hc/AM/issues/1241, but with instructions to compile the program. No portable version at all.
