### ISSUE TITLE
Lime3DS to change address

### ISSUE THREAD

**Issue by YogiGemini** [ivan-hc/AM#1251]
When installing Lime3DS, the program indicates that the host name is incorrect, because the current link refers to "https://github.com/azahar-emu/azahar" which will be the next 3ds emulator to come.

![Capture d’écran du 2024-12-24 01-42-59](https://github.com/user-attachments/assets/2bb48abb-9c70-410d-96c3-01b5c1da99c0)

The new link is "https://github.com/Lime3DS/lime3ds-archive" with an appimage compressed in tar.gz.

**Comment by ivan-hc** [comment]
I see, they changed the repository name and user.

Also, I noticed that the new repo you suggest was archivied in november. Is this the only official source available?

**Comment by ivan-hc** [comment]
I noticed that the archive have two appimages, now the script will install and upfate both

![Istantanea_2024-12-24_03-24-43](https://github.com/user-attachments/assets/5c91a47b-033f-4102-a7ac-00b91a0e745a)

**Comment by ivan-hc** [comment]
Wait a second that I must disable the appimageupdatetool support for this, since the apps are two and in archive.

**Comment by ivan-hc** [comment]
> Wait a second that I must disable the appimageupdatetool support for this, since the apps are two and in archive.

done https://github.com/ivan-hc/AM/commit/c64ef0e0e0d504fd21a5569f6f3fbc08da2f6451

**Comment by YogiGemini** [comment]
Thank you very much, everything is working perfectly :D

> Also, I noticed that the new repo you suggest was archivied in november. Is this the only official source available?

Yes, after a lot of research, I think it's the only one and the most complete for the moment.

However, the creators of Lime3DS should soon be releasing a new emulator on this repo :
[https://github.com/azahar-emu/azahar](url)

> I noticed that the archive have two appimages, now the script will install and update both

Apparently, the ‘Lime3DS Room’ application doesn't launch from the dock, but directly from the emulator's multiplayer option.

So I wonder if it's necessary to keep this launcher?
