### ISSUE TITLE
Add label SteamDeck compatible

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#126]
Not a issue

Today I am trying AM on steamdeck.
And everything seems to work fine.

Not tested everything yet but...
👍

**Comment by ivan-hc** [comment]
OK, I'm waiting your feedback.

**Comment by ivan-hc** [comment]
However, AM is ment to work on any architecture. It is just a script.

I use AM/AppMan also on a 32bit distribution in VM and on an old WinXP compatible laptop.

The only thing, I'm focused more on x86_64, if someone wants to add apps for other architectures, its wellcome.

**Comment by zen0bit** [comment]
But steamdeck have SteamOS (Arch) but immutable filesystem. On every system update is whole system except home wiped out..

**Comment by ivan-hc** [comment]
AM already provides to this.
```
 if [[ $(grep "[[:space:]]ro[[:space:],]" /proc/mounts) ]]; then
              $SUDOCOMMAND mkdir -p /usr/local/share/applications
              sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
fi
```
this is part of `install`

**Comment by zen0bit** [comment]
Will see
waiting for update

**Comment by Utopiah** [comment]
Any update on this? Traveling soon without desktop (obviously) nor laptop, writing this from SteamDeck but wondering how it went to avoid surprises later on.

**Comment by Utopiah** [comment]
Seems fine minus some details, cf https://github.com/ivan-hc/AM/issues/1687#issuecomment-3027454839 in case anybody else is wondering.
