### ISSUE TITLE
Proposal for Making APP-MANAGER Modular

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/AM#130]
The ${ProjectName}=APP-Manager, a command-line interface (CLI) tool for managing AppImage packages and other standalone programs on GNU/Linux, has grown significantly in size and complexity. With around  3000 lines of code, maintaining and extending the tool has become challenging. This proposal outlines a strategy to refactor APP-Manager into a modular architecture, which will improve maintainability, extensibility, and readability of the codebase.

## Current State of naz.${ProjectName}=APP-Manager

The current APP-Manager is a **monolithic script** that handles a wide range of functionalities, including installation, removal, updates, and management of applications. While this has been effective for a small number of applications, the complexity has grown to the point where it is difficult to manage and understand the entire codebase.

## Modular Architecture

A modular architecture breaks down the APP-Manager into smaller, independent components, each responsible for a specific functionality. This approach allows for easier maintenance, testing, and extension of individual components without affecting the entire system. Here are the key components that can be modularized:

1. **Application Management**: Separate the logic for installing, updating, and removing applications into distinct modules.
2. **Dependency Management**: Create a module to handle the installation and management of dependencies required by applications. (Ex. libfuse2)
3. **User Interface**: Abstract the user interface into a separate module to allow for different interfaces (CLI, GUI, etc.).
4. **Configuration Management**: Encapsulate configuration settings and preferences in a dedicated module.
5. **Update Mechanism**: Implement a module to handle updates for both AppImages and other standalone programs.
6. **Sandboxing**: Develop a module for sandboxing applications using tools like Firejail.
7. **Backup and Restore**: Create a module for managing snapshots of applications.
8. **Integration with External Tools**: Modularize the integration with external tools like appimagetool, appimageupdatetool, and pkg2appimage.

## Benefits of Modularization

- **Maintainability**: Smaller, focused modules are easier to understand, test, and maintain.
- **Extensibility**: New features and integrations can be added as new modules without modifying existing code.
- **Reusability**: Common functionality can be reused across different modules, reducing code duplication.
- **Scalability**: The system can scale more easily as new components can be added without overwhelming the core application.
- **Flexibility**: Different modules can be developed and maintained independently, allowing for parallel development and contributions from the community.

## Implementation Plan

1. **Identify Core Functionalities**: Begin by identifying the core functionalities that can be modularized. This includes the installation, removal, and update processes, as well as any other distinct features.
2. **Design Module Interfaces**: Define clear interfaces for each module to ensure they can operate independently and interact with each other when necessary.
3. **Refactor Existing Code**: Gradually refactor the existing codebase into modules, ensuring that each module is self-contained and has a single responsibility.
4. **Testing**: Implement unit tests for each module to ensure that they function correctly in isolation and in conjunction with other modules.
5. **Documentation**: Update documentation to reflect the new modular structure and provide clear guidelines for contributors.
6. **Community Involvement**: Encourage community contributions to develop and maintain modules for different applications and functionalities.

## Example Module Structure

Here's an example of how the installation module might be structured:

```bash
#!/usr/bin/env bash

# Module: Installation

# Dependencies: coreutils, wget, curl, grep, sed


# Function: install_app
install_app() {
    # Logic for installing an application
}

# Function: update_app
update_app() {
    # Logic for updating an application
}

# Function: remove_app
remove_app() {
    # Logic for removing an application
}

# Main Entry Point
main() {
    # Parse command-line arguments and call the appropriate function
}

# Execute the main function
main "$@"
```

By adopting a modular architecture, APP-Manager can become a more robust, scalable, and maintainable tool. This proposal outlines the initial steps towards modularization, but the actual implementation will require careful planning, design, and execution. The goal is to create a system where each module can be developed, tested, and maintained independently, leading to a more sustainable and collaborative development process.

## Next Steps

1. **Assess Current Codebase**: Analyze the current codebase to identify the most critical areas for modularization.
2. **Define Modules**: Define the scope and responsibilities of each module.
3. **Design Interfaces**: Design the interfaces between modules to ensure they can work together seamlessly.
4. **Refactor**: Begin refactoring the codebase into modules, starting with the most critical functionalities.
5. **Test**: Implement comprehensive testing for each module to ensure reliability.
6. **Document**: Update documentation to reflect the new modular structure.
7. **Community Engagement**: Encourage community contributions to develop and maintain modules.

**Comment by ivan-hc** [comment]
The problem here is the use of AppMan, it no more become a portable script if it needs to bring withy it other script. This can be solved by bundle everything into an AppImage, but I haverandom ideas, so I can change the script more often.

For example, in the last hour I have removed options `dev`/`devmode` and `test` and added a new sub-option of `install` named `--debug`, so I have removed to options by merging everything into `install` with less strings.

Two releases in 1 hour (5.8.1 and 5.8.2). This script cannot sleep.

But If you take a look to the script, the bigger part of it is taken by the option `-t`, I'm planning to change it and made the script smaller. And lately I just don't have time to think about that feature.

Last and not less important thing: I'm still learning. Until three years ago I started scripting by myself, being a non-professional user development was not in my things.

I like your ideas, more professional. But mine are others and not ready for all this.

I wrote AM to made it updated daily, following my ideas, using what I learned day by day. To change and learn a new scheme is too much for me now.

An as I said at https://github.com/ivan-hc/AM/issues/128 ,  I spend hours and hours trying to make things work as best as possible, and I know how each line works, could be it wrote bad or well... I'm still learning by myself.

For example, none has told me how to made the installation output better in these years. I was using `xterm`, then `less -E`, and now I'm using another thing... all this in 2-3 years that I become mad for this, without any informatic background. That was an help I was asking for, in forums and on Reddit orissues I opened/closed by myself.

The best help I had until now was "to clean the syntax". But when something that works for AM does not work for AppMan and viceversa, the only thing that can be cleaned are the users.

I really appreciate your effort and your plans, but they are not what I need right now.

About documentation, I gradually add / remove things in both the README of AM and AppMan, so a start point is that.

About "Community Engagement", the best help here would to be start with a bit of marketing. Why Gear Lever and other tools are growning? Because they are on Flathub and AUR or are shared on Twitter or other social networks. 

Me, here, apart from someone who comes to tell me what to do or not to do to make the script more beautiful in the eyes of IT, as if this were a toy for computer science graduates, I have not seen any reviews or quotes (apart from the video of DistroTube, also done badly). Result? AppImages are being adopted less and less and Flatpak is growing more and more.

That said, if you want to continue with these plans, I'm fine with that, and if they're well done I'll be happy to test them. But my plan remains the same. “AM” is who I am, I put my blood and soul into what I do, and in the name of re-adopting the AppImage packaging format. So it's not syntax cleanliness and modularity that I need now, but a bit of visibility. That's all.

You tell me that the code will attract developers, you say... until now most of the Github users who contacted me were for Requests (without Pulls) to upload applications or introduce features. The few developers who want to contribute to the code want to "clean" it. Do you know what they cleaned? Or AM, or AppMan. They didn't even test the trouble they caused. Today, for example, if I hadn't sent you that video, would you have noticed that an essential line was missing to make the options work? Knowing you, I'm sure you would have noticed... but not right away. Being my creature, I am careful to test any changes you make, to avoid trouble. Just one small mistake is enough to lose 100 users who trusted me, Ivan. I don't want to disappoint them.

I don't know what developers need from my code, I know what ordinary people need though, a centralized AppImage manager, which has never existed in 20 years. If it's really that simple for professional developers to build an application manager... why did they wait for an ex-butcher who writes scripts as a hobby and without any studies or certification just because he doesn't have shit to do but doesn't even want to expect others to build software for him?

That former butcher is me.

**Comment by zen0bit** [comment]
The few developers who want to contribute to the code want to "clean" it.

That will hunt you down. You need to accept this. Any developer who want contribute, MUST clean mess first. So your script is readable to anyone, not just you. You mentioned in our conversation, that you want something to stay after you died. But this script, will die with you, or will be rewritten to comply with linting, so anyone can more easily contribute.

Since I like this project, I wanna help you. But this must be solved...

**Comment by zen0bit** [comment]
You must choose for who you are writting this script. If just for yourself. No problem. But if you writting it for us. You have to listen to our complains...

Linting is the only way for succesfull widely use open source project.

**Comment by ivan-hc** [comment]
@zen0bit I'm not saying it's wrong to clean code. If you can do better, so be it. I'm just saying that it doesn't have to be something that's a priority.

From what I've seen, contributors relies more on syntax correction, but for practical purposes when you use the script something goes wrong. Instead you should test what you change, in both modes, AM and AppMan.

You can't present a PR to me as "finished" when then, going to test it, it breaks everything.

If I write to you, "CIAO", "HAIL" or "ARIGATÒ", I am simply saying "HI" to you in other languages... but if you only speak English, it is difficult to understand what I am saying in Italian, German or Japanese. Even Google Translate can make mistakes in translations, and therefore communication breaks down. Do you understand what I mean? The same, more seriously, applies to a BASH script.

Therefore, the changes must first be made on your local client, then tested on the PC.

For example, I have both AM and AppMan. Do I modify AppMan? I'll test what I've done with AppMan. If everything works, then I copy/paste all my changes into AM (/opt/am/APP-MANAGER) and I test them with AM too. If there are no errors, I'll publish them. That's how anyone should do it.

It's like telling a girl "I LOVE YOU", depending on the context, she understands whether it's affection from a friend or boyfriend. In Italian we use "TI AMO" for love and "TI VOGLIO BENE" for friendship. In the case of the BASH script we need to be able to convert everything into "I LOVE YOU". I don't know if the comparison I just made is clear.

**Comment by nazdridoy** [comment]
> This can be solved by bundling everything into an AppImage, but I have random ideas, so I can change the script more often.

No, you don't have to bundle everything into an AppImage; you can always use a "src" folder to develop and modify modular functions of AM and use a small script or GitHub workflow to merge every module neatly into a portable bash script following a predefined scheme. It will make it easier not only for you but for everyone who wants to contribute to the project, making it easier to analyze bugs and, most importantly, test smaller portions of the script.

> But mine are others and not ready for all this.

Sure, if you are not ready for the change, it's okay. Let's keep this issue open, and when you feel ready or when others who want this project to live have cleaned up the script and committed time to make it modular, let it happen. (I plan to continue refactoring the script before attempting to create modules.)

> I know how each line works.

Exactly! I'm sure you do. But others may find it difficult to understand what a variable or function does by scrolling through thousands of lines of a case statement. For example, at some point, I lost interest in contributing to this project, seeing that I have to constantly jump from line 10 or 12 to 1956 or 2176 or scroll through endless walls of case statements. But FWIW, I came back, as I like this project, and I want AppImages to live.

> So it's not syntax cleanliness and modularity that I need now, but a bit of visibility.

IMHO, cleanliness is probably the first thing that is needed to attract new developers or simple Linux users who know a bit of bash scripting. Scaring or confusing them with wall of  a thousand-line, AM will just lose them, missing another one who could spread some good word. (Oh good or not, I myself found this project because of DistroTube's video.)

> The few developers who want to contribute to the code want to "clean" it.

@zen0bit : That will hunt you down.

> Today, for example, if I hadn't sent you that video, would you have noticed that an essential line was missing to make the options work? Knowing you, I'm sure you would have noticed... but not right away.

Yes, maybe 'not right away,' because I was working on the next 200 lines of AM. To be honest, that commit 46ff4977a14877ced3dfc6e2772ac017adfc80f5 shouldn't even have been needed if it were modular and everything should work. I've tested it but as a module. Let me give you some context: 'break' should be used to break out of a loop, not in an 'if' clause. It should throw a syntax error, so one should use 'exit' to close the program. However, there was a 'break' for some reason, and if you exit, the script closes itself. https://github.com/ivan-hc/AM/pull/132 removes this unnecessary break. Do you know what could prevent this?

```bash 
  if [[ ! -f ~/.config/appman/appman-config ]]; then
`````
Instead of

```bash
	if test -f ~/.config/appman/appman-config; then
		break 2>/dev/null
	else 
	        #.......
```

> Ex-butcher who writes scripts as a hobby and without any studies or certification.

Dude, give yourself some credit. You have built a very useful tool. Certification has nothing to do with programming in general.

In the end, if you want people to know about AM and make it theirs, you can't just keep it for yourself. You should at least listen to what others want to say if you want them to speak about it in their forum.

Don't get offended or hurt; trust me, I do respect your dedication and commitment to this project and what you have built as a solo developer.

**Comment by ivan-hc** [comment]
I think that I can start exporting the function "template" into an external script that can be called from $AMPATH, being it the big one. I'll save it into a new /modules directory on this repository

**Comment by ivan-hc** [comment]
@nazdridoy is this OK?

- https://github.com/ivan-hc/AM/commit/fda25239c9061af9d9a2097d4c4514f8ce67eebc
- https://github.com/ivan-hc/AM/tree/main/modules

**Comment by ivan-hc** [comment]
Take a look to my latest commits, there is a lot of work around modules-system implementation

**Comment by ivan-hc** [comment]
Is there an easier way to export all variables to the modules?

**Comment by nazdridoy** [comment]
I am writing some doc for AM_modules. I think this will help you a bit.


`draft doc_AM_modules`

To modularize APP-MANAGER, you can follow these steps:

1. **Create a naz.vol.${AM_modules}=`modules` directory**: This directory will contain all the modules. Each module will be a separate script file.

2. **Define a common interface for modules**: Each module should have a function that takes command line arguments and returns a result. The function can access global variables from APP-MANAGER.

    To define a common interface for modules, you can create a function in each module that takes command line arguments and returns a result. This function can access global variables from APP-MANAGER by using the `global` keyword in Bash. 
    
    example:
    ```bash
    # modules/about.am

    function about() {
    # Access global variables from APP-MANAGER
    global APPSPATH

    # Access command line arguments
    local args=("$@")
    echo "Arguments are ${args[@]}"

    # Do something...

    # Return a result
    return 0
    }
    ```


    In this example, `global APPSPATH` allows the `about` function to access the `APPSPATH` global variable from `APP-MANAGER`. The `local args=("$@")` line creates a local array variable `args` that contains all the command line arguments. The `return 0` line returns a result of 0, which indicates success.

    You can create similar functions in other modules. The function name should be the same in all modules, but the function body can be different. This allows you to call the same function in the main script (`APP-MANAGER`) to execute different modules.

    To export a variable from a module to APP-MANAGER, you can use the export keyword in Bash. For example:

    ```bash
    # modules/about.am

    function about() {
    # Export a variable to APP-MANAGER
    export MY_VARIABLE="some value"

    # Rest of the function...
    }
    ```


    In this example, `export MY_VARIABLE="some value"` exports a variable named naz.gen.${gen_var}=`MY_VARIABLE` with the value `"some value"` to the environment. This variable can be accessed by `APP-MANAGER` and any other scripts that are executed after the module.

    Please note that this only exports the variable to scripts that are executed after the module. If you want to export the variable to the current shell (which includes `APP-MANAGER`), you can use the `source` command to execute the module in the current shell. Here's an example:

    ```bash
    source ./modules/about.sh
    ```


    After executing this command, the naz.gen.${gen_var}=`MY_VARIABLE` variable will be available in the current shell.

3. **Modify the main script APP-MANAGER to load and execute modules**: The main script should load the module corresponding to the command line option and execute it.

4. **Pass global variables and command line arguments to modules**: You can pass **global variables** and **command line arguments** to modules as function parameters.

5. **Handle errors and return values carefully**: It's important to handle errors and return values carefully in a modularized Bash script (in fact, in any interpreted language script in general). Here are a few techniques you can use:

   - Use the `set -e` option to exit the script if any command fails. This can help prevent unexpected behavior and potential system damage since AM **runs as root**.
   - Use the `trap` command to handle signals. For example, you can use `trap 'echo "Script interrupted"; exit 1' INT` to exit the script gracefully when it receives an interrupt signal.
   - Use the `exit` command to exit the script with a specific exit code. This can be useful for indicating the success or failure of the script to other programs.
   - Use the `return` command to return a value from a function. This can be useful for passing information back to the main script from a module.

6. **Use the `source` command to execute modules in the current shell**: This allows modules to export variables to the current shell.

Here's a  example of how you can modify the main script to load and execute a module:

```bash
case "$1" in
  '-a'|'about')
    # Load the about module
    source ./modules/about.am
    # Execute the about module
    about "$@"
    ;;
  '-b'|'backup')
    # Load the backup module
    source ./modules/backup.am
    # Execute the backup module
    backup "$@"
    ;;
  # Add more cases for other options...
esac
```
or 

```bash
# APP-MANAGER script

# Import the modules
source modules/backup.am
source modules/clean.am
# ... and so on for other modules

# Call the appropriate module function based on the command line arguments
case "$1" in
    'backup') backup_function "$2" ;;
    'clean') clean_function "$2" ;;
    # ... and so on for other commands
esac
```

And here's an example of how a module might look:

```bash
# modules/about.sh

function about() {
  # Access global variables from APP-MANAGER
  echo "APPSPATH is $APPSPATH"

  # Access command line arguments
  echo "Arguments are $@"

  # Do something...

  # Return a result
  return 0
}
```

## TO DO 

naz.doc.${doc_AM_modules_tesing}
naz.doc.${doc_AM_modules_security}

**Comment by zen0bit** [comment]
Added some changes to INSTALL

But why not use some make instead.

PS: Think you already mention...
But not your oppinion

**Comment by ivan-hc** [comment]
@nazdridoy I've a doubt on this, may github API limit be an obstacle when it check for multiple files to download?

Now the option `-s` will download all files with extension .am in modules, in my experience, downloading too many times from github APIs has its limits.

This is why my script was monolitic and not modular.

@zen0bit thanks, but your INSTALL does not works for me. I've accepted only the PR on cleaning spaces, the installer does not work for me (even I was unable to remove AM). Why to break something that works?

**Comment by nazdridoy** [comment]
>github APIs has its limits.

Unauthenticated (with out GIT_PAT) requests are limited to 60 requests per hour, whereas authenticated (GIT_PAT) requests are much higher, typically around 5000 requests per hour. that shouldn't be an issue

**Comment by ivan-hc** [comment]
> that shouldn't be an issue

Nope, it is. Normal people (not us) do not have a github account. Many people are fanatics of apps and updates (I'm a  fanatic of the latter). When github stops me from using my tools for an hour, I get pissed off. I don't want to use an authentication key every time I need to do something.

**Comment by ivan-hc** [comment]
@nazdridoy I propose to use the modules only for non-essential and bulkier things. In the previous comments you complained about having to go from line 2 to line 2999. Now there are 1700. The script can be even more compact.

Nobody uses the `-t` option, `-h` is updatable. I have already implemented them in external podules. We only remove things that are non-essential and that you think can be used less.

**Comment by nazdridoy** [comment]
> > that shouldn't be an issue
> 
> Nope, it is. Normal people (not us) do not have a github account. Many people are fanatics of apps and updates (I'm a fanatic of the latter). When github stops me from using my tools for an hour, I get pissed off. I don't want to use an authentication key every time I need to do something.

You are calling the API once and storing all URLs in an array. Why are you so concerned about the rate limit? Am I missing something?

```bash
MODULES=$(wget -q https://api.github.com/repos/ivan-hc/AM/contents/modules -O - | grep download_url | cut -d '"' -f 4)

```

**Comment by ivan-hc** [comment]
@nazdridoy Sometimes, when I test a new change (for example) to `install`, I select 2-3 installation scripts, and repeat the operation dozens of times... but at some point I'm forced to use `torsocs` or make myself a game of 0AD to wait for an hour to pass. It's frustrating. I hate having to generate a new key every week.

**Comment by nazdridoy** [comment]
![2024-02-14_01-30](https://github.com/ivan-hc/AM/assets/45564804/0296c4fb-a8d9-4e9a-b6b2-ebf93864a9d1)

**Comment by nazdridoy** [comment]
again you are calling the api for modules ONLY A SINGLE TIME....!

**Comment by nazdridoy** [comment]
https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28

**Comment by ivan-hc** [comment]
OK, sorry, I'm ignorant, I only see that when I download apps from api.github.com sometime the installation is stuck. Also downloads from raw.githubusercontent.com are blocked.

**Comment by nazdridoy** [comment]
> OK, sorry, I'm ignorant, I only see that when I download apps from api.github.com sometime the installation is stuck. Also downloads from raw.githubusercontent.com are blocked.

that's probably because of your ISP. Sometimes I have to reset my IP to access GitHub. Then again, since you are developing and heavily using APIs, I'd suggest you use a Git PAT token. you can't exhaust your hourly limit unless you do some crazy stuff. Trust me, I can't, yet I do many crazy shit!

**Comment by ivan-hc** [comment]
I'm going work on these modules now... today its impossible with all these notifications (and tests).

Thank you for thaking care of that installation script, before.

**Comment by nazdridoy** [comment]
>Thank you for thaking care of that installation script, before.

It's okay, man. I get frustrated when, for some reason, I encounter errors while installing things from AUR. So, I know it was probably very frustrating for that guy.So, I just pushed a quick fix, then updated the script.

By the way, at some point, existing install scripts need to be updated. Many of them are extremely outdated, without updated routines or proper download sources. I'm going to create a new issue for update requests and gradually update those.

> I'm going work on these modules now

sure, you do that. Don't worry about code cleanliness for now. Exporting and breaking down every important component into smaller chunks without ruining user experiences should be the priority. Then, refactoring and cleaning up shouldn't be too difficult. In fact, contributors can choose to maintain a portion of the codebase or one specific module if they want. So, keep doing what you're doing; you're doing great.

**Comment by ivan-hc** [comment]
@nazdridoy is this version 6 enough?

https://github.com/ivan-hc/AM/blob/main/APP-MANAGER

https://github.com/ivan-hc/AM/tree/main/modules (26 modules)

**Comment by zen0bit** [comment]
> @nazdridoy is this version 6 enough?
> 
> [`main`/APP-MANAGER](https://github.com/ivan-hc/AM/blob/main/APP-MANAGER?rgh-link-date=2024-02-13T23%3A23%3A54Z)
> 
> [`main`/modules](https://github.com/ivan-hc/AM/tree/main/modules?rgh-link-date=2024-02-13T23%3A23%3A54Z) (26 modules)

You are done?
That was quick

**Comment by ivan-hc** [comment]
> You are done?
That was quick

I didn't have sh*t to do. :laughing:

**Comment by ivan-hc** [comment]
> I plan to group these 26 modules into some core modules according to the scope and responsibilities of each module so that instead of 26 module imports, we can have 6 or 9!

:fearful: 

If I had known this before, I would have avoided making all this unnecessary mess.

Now modules are 27, no more 26, the new one is completion.am, that works the way you just said (it includes two different options).

What if I add to them the same comparisation model I apply to installation scripts in sync.am?
```
for arg in $ARGS; do
	for var in $arg; do

		function _sync_installation_scripts(){
			if test -d $APPSPATH/$arg/.am-installer; then
				INSTALLER=$(ls -A1 $APPSPATH/$arg/.am-installer)
				CURRENT=$(cat $APPSPATH/$arg/.am-installer/$INSTALLER)
				rm -R -f $AMPATH/.cache/$arg
				wget -q $AMREPO/programs/$arch/$INSTALLER -O $AMPATH/.cache/$INSTALLER
				SOURCE=$(cat $AMPATH/.cache/$INSTALLER)
				if [ "$CURRENT" == "$SOURCE" ]; then
					echo -ne "\r" 2> /dev/null
				else
					echo -e "\n ◆ $INSTALLER : The installer has changed, consider reinstalling! \n See https://github.com/ivan-hc/AM/blob/main/programs/$arch/$INSTALLER"
				fi
				rm -R -f $AMPATH/.cache/$INSTALLER
			else
				echo -e "\n ◆ No installation script for $arg...\n downloading one to $APPSPATH/$arg/.am-installer for this entry"
				mkdir -p $APPSPATH/$arg/.am-installer
				wget -q $AMREPO/programs/$arch/$arg -O /$APPSPATH/$arg/.am-installer/$arg
			fi
		}

		_sync_installation_scripts

	done
done
```
this should keep updated only the updated modules

**Comment by ivan-hc** [comment]
This will update only changed modules

```
echo "-----------------------------------------------------------------------------"
echo -e " Check for updates in modules..."
function _sync_modules(){
	MODULES=$(wget -q https://api.github.com/repos/ivan-hc/AM/contents/modules -O - | grep download_url | cut -d '"' -f 4)
	for module in $MODULES; do
		for v in $module; do
			cd $AMPATH/modules
			MODULENAME=$(echo "$v" | sed 's:.*/::')
			CURRENT=$(cat ./$MODULENAME)
			SOURCE=$(wget -q "$v" -O -)
			if [ "$CURRENT" == "$SOURCE" ]; then
				echo -ne "\r" 2> /dev/null
			else
				echo -e "\n ◆ Updating $MODULENAME..."
				mkdir tmp
				cd tmp
				wget -q "$v"
				cd ..
				mv tmp/*.am ./
				chmod a+x ./*.am
				rmdir tmp
			fi
		done
	done
}

_sync_modules
```

**Comment by ivan-hc** [comment]
> jq

I've not `jq`, stop implementing unneeded dependences.

**Comment by ivan-hc** [comment]
I've already improved the module for `sync`

https://github.com/ivan-hc/AM/blob/main/modules/sync.am

however, I'll never, never, never implement unneeded dependences out of those listed on the README. Never. Basic Linux installation have already all everyone needs to run AM

**Comment by zen0bit** [comment]
> however, I'll never, never, never implement unneeded dependences out of those listed on the README. Never. Basic Linux installation have already all everyone needs to run AM. Should I also implement python and make in the future? Forget it.

Depends what you see as unneeded. Any dependency could be treated as unneeded, but a lot of them can save you a lot of fiddling around.

But this decission is up to you..
(Should be dependencies available in most repos OK or NOT. that's the question.) But less you use dependencies, more you will learn bash..

**Comment by ivan-hc** [comment]
Yes, I want to avoid including other dependencies, even at the cost of having to overcome these shortcomings by using longer functions and commands to write. I never had `jq`, although, reading the guides, many programmers used it. There are people with much more minimal systems than mine (I have 1737 .deb packages installed), I don't want to force anyone to install anything else, not even for myself.

**Comment by nazdridoy** [comment]
> > jq
> 
> I've not `jq` installed, stop implementing unneeded dependences.

i'm not sure if it's a language barrier. that's kind of rude. I haven't implemented anything; it's just a suggestion. whether you accept it or not is up to you. Have you even tried to understand what I suggested?https://github.com/ivan-hc/AM/issues/130#issuecomment-1943824014  Stop being so jumpy. Using `jq` wasn't even the main point."

> I've already improved the module for sync
> however, what are these nesting for loops? i don't see the use of 2 for loop here. 

** help me understand this **
```bash 
for arg in $ARGS; do
	for var in $arg; do

		function _sync_installation_scripts(){
			mkdir -p $APPSPATH/$arg/.am-installer
			if test -f $APPSPATH/$arg/.am-installer/$arg; then
				CURRENT=$(cat $APPSPATH/$arg/.am-installer/$arg)
				SOURCE=$(wget -q $AMREPO/programs/$arch/$arg -O -)
				if [ "$CURRENT" == "$SOURCE" ]; then
					echo -ne "\r" 2> /dev/null
				else
					echo -e " ◆ Changed https://github.com/ivan-hc/AM/blob/main/programs/$arch/$arg"
				fi
			else
				echo -e " ◆ No installation script for $arg, downloading one..."
				mkdir -p $APPSPATH/$arg/.am-installer
				wget -q $AMREPO/programs/$arch/$arg -O $APPSPATH/$arg/.am-installer/$arg
			fi
		}

		_sync_installation_scripts

	done
done

```

**Comment by ivan-hc** [comment]
@nazdridoy you're right, my way of expressing myself, in writing, clashes with my real intentions, leaving people to misunderstand.

About two cicles is because too many times I have tried with one and didn't worked for me.

**Comment by ivan-hc** [comment]
Update: the strange thing is that this time I reduced the `for` cicles and all works correctly... I don't know why this wont worked in the past

**Comment by zen0bit** [comment]
It's just because after cleanup you will much better see all unneeded/doubled or not nice code 😎

**Comment by ivan-hc** [comment]
I've finished... almost finished.

I've left some where I need to remove some spaces, and "template.am" is the one I want to change completelly. I should only have the time to do this.

**Comment by ivan-hc** [comment]
> I've left some where I need to remove some spaces (all those without commits in the latest 24 hours)

are there volunteers? :laughing:

**Comment by nazdridoy** [comment]
> change of plan. i'll have to go all through modules and make sure they are compitable with marge,

1. about.am:  https://github.com/ivan-hc/AM/pull/144

**Comment by ivan-hc** [comment]
You've closed the PR

**Comment by nazdridoy** [comment]
https://github.com/ivan-hc/AM/pull/145

**Comment by ivan-hc** [comment]
I see... merged

**Comment by nazdridoy** [comment]
> I see... merged

nice. but maybe rather than marging you can git check out PR then marge with the dev. finally to main.

**Comment by ivan-hc** [comment]
@ I get this error
```
/opt/am/modules/about.am: riga 81: return: è possibile eseguire "return" solo da una funzione o da uno script chiamato
```

**Comment by ivan-hc** [comment]
I've tested without `return`, what is the use you do with this command?

**Comment by nazdridoy** [comment]
easy fix.. wait a bit. don't marge... test then marge...

**Comment by nazdridoy** [comment]
> I've tested without `return`, what is the use you do with this command?

future proofing, for now we can ignore that,. should be fixed now https://github.com/ivan-hc/AM/pull/146

**Comment by zen0bit** [comment]
> The ${ProjectName}=APP-Manager, a command-line interface (CLI) tool for managing AppImage packages and other standalone programs on GNU/Linux, has grown significantly in size and complexity. With around 3000 lines of code, maintaining and extending the tool has become challenging. This proposal outlines a strategy to refactor APP-Manager into a modular architecture, which will improve maintainability, extensibility, and readability of the codebase.

Borrowing modular post also for quickemu project Thank you

**Comment by nazdridoy** [comment]
sure

**Comment by nazdridoy** [comment]
Well, there still are many things to be done... but I guess moving these to discussion is fine too

**Comment by nazdridoy** [comment]
> > jq
> 
> I've not `jq` installed, stop implementing unneeded dependences.

what about "https://github.com/ivan-hc/AM/releases/tag/6.6.4" ?

**Comment by ivan-hc** [comment]
@nazdridoy you are right, this is because latelly Fedora 40 have replaced wget with wget2 that works completelly different, from the options to the kind of user agent used recognized from sites such as api.github.com

Tthi is why I've changed idea. You know, what Fedora/Red Hat decides now will become law in the future. I had no choice.

**Comment by ivan-hc** [comment]
@nazdridoy I could implement a package to install additional dependencies, also "wget" is stored in this repository, "jq" is available as a standalone binary. We just need to evaluate how to resolve this situation.

**Comment by nazdridoy** [comment]
> @nazdridoy you are right, this is because latelly Fedora 40 have replaced wget with wget2 that works completelly different, from the options to the kind of user agent used recognized from sites such as api.github.com
> 
> Tthi is why I've changed idea. You know, what Fedora/Red Hat decides now will become law in the future. I had no choice.

thats is why (to make AM future ready) i've suggested to add jq as a dependency.... besides, jq is by far the most lightweight, powerfull and unfriendly tool to parse api response....
 whatever the reason maybe, i do appreciate this change...

**Comment by nazdridoy** [comment]
> @nazdridoy I could implement a package to install additional dependencies, also "wget" is stored in this repository, "jq" is available as a standalone binary. We just need to evaluate how to resolve this situation.

about that, serving random binary as a  "package manager" is  big NO NO! some may find it unprofessional and risky. I'd suggest pulling these from a reputed upstream or if you have to serve binary checksum seem like a must.

**Comment by nazdridoy** [comment]
> @nazdridoy if you want join the discussion, let talk at #529

sure, if i fine enough time... thsnks

**Comment by ivan-hc** [comment]
> about that, serving random binary as a "package manager" is big NO NO! some may find it unprofessional and risky. I'd suggest pulling these from a reputed upstream or if you have to serve binary checksum seem like a must.

@nazdridoy this is exactly what I'm saying at https://github.com/ivan-hc/AM/discussions/524#discussioncomment-9265075

**Comment by Samueru-sama** [comment]
> unfriendly tool to parse api response....

I suggested to use gron which makes working with json much much easier than with jq. However Ivan found a way to use jq to force the json human readable so that the older greps and seds still work. It is still a hack since it is parsing json with those tools though. 

Gron breaks it into plain text that can be used without problems with the coreutils.  

>about that, serving random binary as a "package manager" is big NO NO! 

The jq binary is from jq themselves.

**Comment by nazdridoy** [comment]
> > unfriendly tool to parse api response....
> 

meant to write "user-friendly"..  damn autocorrection

> The jq binary is from jq themselves.

yeah since then Ivan went with pulling from upstream instead of hosting prebuilt binary..
