### ISSUE TITLE
QownNotes install error

### ISSUE THREAD

**Issue by Graninius** [ivan-hc/AM#133]
It looks like there's something wrong with it
`appman -i qownnotes
 ############################################################################
 ##                                                                        ##
 ##                  START OF ALL INSTALLATION PROCESSES                   ##
 ##                                                                        ##
 ############################################################################

 ◆ "QOWNNOTES": starting installation script
https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/AppImage/QOwnNotes-latest-x86_64.AppImage
 "QOWNNOTES" INSTALLED (34 MB OF DISK SPACE)                              
 💀 ERROR DURING INSTALLATION, REMOVED "QOWNNOTES"!`

**Comment by nazdridoy** [comment]
will be fixed as soon as @ivan-hc marges https://github.com/ivan-hc/AM/pull/134
