### ISSUE TITLE
add a way to get latest version (quick fix) of AM

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/AM#156]
currently am -s only sync AM if it has a new release. so, users can't get quick fixes until the next release.

let `sync.am` always sync with latest commit. `update.am` update only if a new version available

**Comment by ivan-hc** [comment]
???

https://github.com/ivan-hc/AM/blob/3afd6228b23552d76eb06d6e7059c1f0e00d63c6/modules/update.am#L24

**Comment by nazdridoy** [comment]
> ???
> 
> https://github.com/ivan-hc/AM/blob/3afd6228b23552d76eb06d6e7059c1f0e00d63c6/modules/update.am#L24

you are using sync to update!?

**Comment by ivan-hc** [comment]
yes, all-incusive :+1:

**Comment by nazdridoy** [comment]
so, does am -u or am -s update AM main script to the latest commit? or it updates AM only if there is new release?

**Comment by ivan-hc** [comment]
- `-s` : only AM, modules and check for updates in the installation scripts of the apps installed (maybe one of them has been improved, by replacing the symlink with a script, see kdenlive and avidemux...);
- `-u` : updates all the installed apps and also calls `-s`, it is an all-in-one option.

In both cases, AM and all the modules are always updated to the latest version.

About AM numbes, this is my personal scheme (and thinking):
- x = structural changes of APP-MANAGER (see the last 6, with modularity and 5, where AM and AppMan were one thing);
- x.x = new feauture (options);
- x.x.x = improved new feature;
- x-x or x.x-x or x.x.x-x = not major/minor releases, but bug fixes or a way to notice people that something is changed.

**Comment by nazdridoy** [comment]
> AM and all the modules are always updated to the latest version.

by version, do you mean release version? or commit?

**Comment by nazdridoy** [comment]
>commit

if thats the case than the issue is solved. i can't test this as i've already updated manually. but i'm gonna take your word for it. since you have solved it, i'm not gonna einvent the wheel!
