### ISSUE TITLE
gimp and audacity appimages not running on Debian 12 (bookworm) 

### ISSUE THREAD

**Issue by bert003** [ivan-hc/AM#158]
When running both appimages, I get the following error:

> dlopen(): error loading libfuse.so.2
> AppImages require FUSE to run.
> You might still be able to extract the contents of this AppImage if you run it with the --appimage-extract option.
> See https://github.com/AppImage/AppImageKit/wiki/FUSE for more information

When I install fuse and libfuse2, audacity manages to run, but gimp still fails with the error above.

Any solution please? It seems that gimp is not detecting libfuse.so.2 but audacity detects it fine.

**Comment by bert003** [comment]
I am using the latest. What I noticed is that if you just download the AppImage file and run it, it runs fine. However through AM, it complains about libfuse.

**Comment by ivan-hc** [comment]
Have you installed libfuse2 from Debian repositories or from AM?

**Comment by bert003** [comment]
I installed from Debian repositories.

**Comment by ivan-hc** [comment]
The `fuse` package should be deprecated, you should install `fuse3`

**Comment by bert003** [comment]
I have fuse3 installed already. Still it complains. The curious thing is if you just download the AppImage file and run it, it runs fine. However through AM, it complains about libfuse.

**Comment by ivan-hc** [comment]
First step, try to load the library in ld-cache normally, maybe ld-linux has not detected the new library
```
sudo ldconfig
```
If this not works, try to reboot.

**Comment by ivan-hc** [comment]
However, it seems that you have installed something like AppimageLauncher previously, isn't it? It contrasts with the workflow of AM due to background daemon.

**Comment by bert003** [comment]
No. I have not installed AppImageLauncher previously. What I did was install `fuse` and `libfuse2` and now everything works. It seems that the appimages are still demanding to have libfuse2.

**Comment by ivan-hc** [comment]
I've nut understand, are they working and asking for libfuse2 at the same time?

**Comment by bert003** [comment]
I rushed to say that it works. I tested again using a Debian Live distribution.

When I run the appimage, it fails with libfuse.so.2 error.

Then I installed strace and executed `strace -f -o out.txt ./gimp` and instead of the libfuse.so.2 error, I get `fusermount: mount failed: Operation not permitted`

**Comment by ivan-hc** [comment]
OK, it seems that you require some permissions

Have you read the guide suggested above? https://github.com/AppImage/AppImageKit/wiki/FUSE

Probably your user have not premissions to use FUSE

**Comment by ivan-hc** [comment]
Also, have you installed `fuse3` instead of `fuse`?
```
sudo apt install fuse3 && sudo apt remove --purge fuse
```

**Comment by bert003** [comment]
No I do not think it is a permission issue. I used strace -f as shown here https://github.com/AppImage/AppImageKit/issues/1120#issuecomment-805634013

I have u+s permission for fusermount.... no luck unfortunately using a Debian Live distro.

**Comment by ivan-hc** [comment]
I have Debian 64bit and 32bit on both PC and laptop and GIMP AppImages for both 64bit and 32bit work normally (and I'm the developer of both the packages).

Also, I use Debian Testing that "should be quite unstable" if compared with Debian Stable. I cannot reproduce the issue.

Again, you have not answered my  previous question have you replaced `fuse` with `fuse3`? Also the guide says that `fuse` may brick the compatibility.

**Comment by bert003** [comment]
Yes I did replace fuse with fuse3. No luck. Did you try using a LIVE cd though and not an actual installation?  I appreciate if you could download a Debian Live ISO and test yourself.

**Comment by ivan-hc** [comment]
What is the sense of installing AM on a live session? You should use AM on an already installed system.

**Comment by ivan-hc** [comment]
> I am saving everything in my home directory in ~/Programs not in /opt

are you talking about AppMan?

**Comment by bert003** [comment]
> What is the sense of installing AM on a live session?
Portability

Yes it's appman I guess. It is part of AM right?

**Comment by ivan-hc** [comment]
Yes, it requires to be named as `appman` to work like this.

Also, it has a function to patch ~/.profile and ~/.bashrc to place ~/.local/bin at the end of `echo $PATH` to give it the right priority. So if you use a "persistent" environment, I don't think it will work.

For what I have understand, you're trying to create a persistent enviroment to use into a Live session (i.e. you can start a new session but with the same $HOME directory).

I lost the thread of the conversation. We started with `libfuse2` which is not detected by an application, now we are talking about using AppMan in a Live session (a whole day has passed).

I think, with the right configuration, you can use AppMan on a USB stick that sees the same drive as a `/home/$USER` path

But a Live system is not permanently set up and configured to work 100% with all the libraries you need. Likewise, `ld-linux.so` must detect all linked libraries, including `libfuse2`, in order to better mount AppImages, which are nothing more than portable filesystems to be mounted on another filesystem.

I don't know how this level of portability that you want to use works. If you can, send me a video or screenshots so I can see what's going wrong. The way you tell me things is confusing.

**Comment by bert003** [comment]
Hi @ivan-hc - sorry for the confusion but I got confused myself as well with this strange issue.

I finally managed to find the cause of the issue though.

Basically everything breaks when you create a symlink from /home/user/.local/bin/gimp -> /home/user/Programs/gimp/gimp.

Therefore when I do: `ln -s /home/user/Programs/gimp/gimp /home/user/.local/bin/gimp`, it starts triggering the libfuse.so.2 error. If the symlink is not created, everything works fine.

Personally I cannot explain why this happens. Maybe you have an idea why?

**Comment by ivan-hc** [comment]
I think that the big issue here is that you're using a volatile environment, so BASH configuration will reset at each start. This is why thi does not work for you. I don't think that you can use my tools this way.

**Comment by bert003** [comment]
I am using persistence so not volatile as such. However the issue is solved I guess. There must be a valid reason though as regards the symlink. If I manage to find why, I will post an update. Thanks.

**Comment by ivan-hc** [comment]
What if you do `echo $PATH`? The result should put $HOME/.local/bin at the end.

Also, someone had the same issue but because previously him have installed AppimageLauncher and some .service files where not been removed (check your ~/.config or ~/.local directory for unneeded files).

**Comment by ivan-hc** [comment]
What if you run AppMan with a new user?

**Comment by bert003** [comment]
I will test your suggestions using a Debian Live distribution (without persistence) so that it is a clean boot. Will get back to you with the results then. Please allow me some time since I am quite busy with work this week.

**Comment by ivan-hc** [comment]
don't worry

**Comment by bert003** [comment]
Hi @ivan-hc - I have just created a new Debian 12.4 virtual machine - what exactly do you want me to test as regards AppMan?

**Comment by ivan-hc** [comment]
@bert003 Have you forgotten why you opened this issue?

**Comment by bert003** [comment]
No I didn't of course :) however I told you earlier that I found the cause of the issue (even though I cannot explain it)

> Therefore when I do: ln -s /home/user/Programs/gimp/gimp /home/user/.local/bin/gimp, it starts triggering the libfuse.so.2 error. If the symlink is not created, everything works fine.

So you just want me to run AppMan as a standard user and test using gimp and audacity right?

**Comment by ivan-hc** [comment]
yes

**Comment by bert003** [comment]
Everything works just fine with appman. Even symlinking from /usr/local/bin:

gimp -> /home/test/Programs/gimp/gimp

Shall I test again with AM (same scenario)?

**Comment by ivan-hc** [comment]
As you wish, but I think there is no need. AM and AppMan are not for Live ISO and persistent environments. If you consider it resolved, close this issue.

**Comment by bert003** [comment]
Ok then. Yes closing issue as it can be considered as resolved.
