### ISSUE TITLE
AppMan tries to modify .profile in $HOME, which doesn't exist

### ISSUE THREAD

**Issue by fiftydinar** [ivan-hc/AM#185]
Command output after downloading AppMan & setting alias:
```sh
am --user -i xl-converter
grep: /home/gidro/.profile: No such file or directory
This function only works for AM
```

This permits me from using AM as --user.

OS: Fedora Silverblue 39

If it helps, Fedora has `.bash_profile` with this file content:
```sh
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs
```

**Comment by fiftydinar** [comment]
I made a mistake in installation command.

After inputting alias command, it is not needed to use `--user` flag for apps installation.

I got used to:
`flatpak install --user package-name`

Compared to this, which is just:
`am install package-name`

Hence why I made this mistake.

**Comment by ivan-hc** [comment]
you can't use --user with other options:
```
am --user
```
this will allow you to use the command "am" from now on as "appman". To fall back (and use "am" as "am") just `rm /opt/am/appman`

its better if you have both, "am" and "appman" installed if you want apps installed at system level (with "AM") and locally (with "AppMan").

About patching ~/.profile, this is needed to give ~/.local/bin the right priority in `echo $PATH`

About your suggestion, try to replace 
```
function _patch_bashrc_and_profile(){
	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
	if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
	fi
	# Correct the order of .local/bin in .profile if necessary
	if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
	fi
}
```
with
```
function _patch_bashrc_and_profile(){
	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
	if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
	fi
	# Correct the order of .local/bin in .profile if necessary
	if test -f "$HOME/.profile"; then
		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
		fi
	elif test -f "$HOME/.bash_profile"; then
		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.bash_profile"; then
			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.bash_profile"
		fi
	fi
}
```
in AppMan

the function above uses (in both cases) `sed` to replace the line `PATH="$HOME/.local/bin:$PATH"` with `PATH="$PATH:$HOME/.local/bin"` (normally this happen in Debian's ~/.profile file, I don't what is the content of ~/.bash_profile in Fedora).

**Comment by fiftydinar** [comment]
> you can't use --user with other options:
> 
> ```
> am --user
> ```
> 
> this will allow you to use the command "am" from now on as "appman". To fall back (and use "am" as "am") just `rm /opt/am/appman`
> 
> its better if you have both, "am" and "appman" installed if you want apps installed at system level (with "AM") and locally (with "AppMan").
> 
> About patching ~/.profile, this is needed to give ~/.local/bin the right priority in `echo $PATH`
> 
> About your suggestion, try to replace
> 
> ```
> function _patch_bashrc_and_profile(){
> 	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
> 	if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
> 		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
> 		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
> 	fi
> 	# Correct the order of .local/bin in .profile if necessary
> 	if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
> 		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
> 	fi
> }
> ```
> 
> with
> 
> ```
> function _patch_bashrc_and_profile(){
> 	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
> 	if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
> 		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
> 		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
> 	fi
> 	# Correct the order of .local/bin in .profile if necessary
> 	if test -f "$HOME/.profile"; then
> 		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
> 			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
> 		fi
> 	elif test -f "$HOME/.bash_profile"; then
> 		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.bash_profile"; then
> 			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.bash_profile"
> 		fi
> 	fi
> }
> ```
> 
> in AppMan
> 
> the function above uses (in both cases) `sed` to replace the line `PATH="$HOME/.local/bin:$PATH"` with `PATH="$PATH:$HOME/.local/bin"` (normally this happen in Debian's ~/.profile file, I don't what is the content of ~/.bash_profile in Fedora).

With this one, I don't have the error anymore.

I provided .bash_profile file content in 1st post, which just points out to .bashrc anyways, which is modified correctly.
