### ISSUE TITLE
Use `--home` flag by default when installing AppImages

### ISSUE THREAD

**Issue by fiftydinar** [ivan-hc/AM#187]
This would centralize home file content used by AppImages, which would be otherwise scattered & often difficult to find manually.

It would also allow most AppImages to be cleanly removed from the system.

However, AppImages made before 2017 do not support this functionality:
https://docs.appimage.org/user-guide/portable-mode.html

It is not clear how to automatically detect if this functionality is present, so we can just allow `--home` flag for all AppImages & document possible rare exceptions in README.

We can also do slow manual testing of this 1 by 1 package.
I can participate in that testing if necessary.

**Comment by ivan-hc** [comment]
This is not a task that other apps other than AppImages can perform easily using a CLI like AM/AppMan:

- The mechanics for an AppImage is "create a directory .home with the same name of the AppImage, near the AppImage";
- Universally its enough to run the app into a dedicated directory to use as a $HOME.

For example, create a new directory
```
mkdir test
cd test
```
then you can run
```
HOME=./
```
or better
```
HOME="$(dirname "$(readlink -f $0)")"
```
from now and for the whole terminal session you can run any app into that directory that will be used as a custom $HOME directory.

If we want to implement such a feature, we should change all the installation scripts for portable apps (non AppImages), add a script that will be symlinked to /usr/local/bin that runs the app into a dedicated directory. This would be an huge work to do.

Easier solution? Push more to convert all the portable apps to the AppImage format. I've done this for many of my apps (see the ones built from .deb or archive, at https://github.com/ivan-hc#my-appimage-packages , fr example Dropbox, Skype, Whatsapp Nativefier, Anydesk...). It was not difficult for some of these, but to convert them in AppImage should not be my task. I'de prefer that the upstream developers take care of this.

**Comment by fiftydinar** [comment]
This is a copy-pasted reply, but I assume that you think that it's the upstream issue, like in similar issue I posted?

I agree.

I just opened the issue to open discussion regarding this.

**Comment by ivan-hc** [comment]
@fiftydinar  If you wish, you can open a discussion here https://github.com/ivan-hc/AM/discussions

These isolation-related threads are... threads, more than issues : )
