### ISSUE TITLE
Allow preferred application format configuration

### ISSUE THREAD

**Issue by fiftydinar** [ivan-hc/AM#188]
For example, I want to install AppImage packages only.

I set that option in config & when i run `am --list`, I am presented with AppImage packages only.

Same can be done with standalone applications if set.

Another thing, which can happen, is if package is available as both AppImage & standalone (.tar.gz or extracted .deb),
It would be nice if you can set a format preference order.
Like this:
1. AppImage
2. Standalone

**Comment by ivan-hc** [comment]
This is a huge work too, I've already covered with the options -a and -d:
- with the option `-a` you can get more info about the app an the sources where it is taken from;
- with the option `-d` you can download the script and see by yourself how it is installed.

Another way is to visit https://portable-linux-apps.github.io/apps and open the link "blob" or "raw" to see the installation script without downloading it.

Yet another way is to install the app and then use the option `-f` to see the kind of apps you have installed.

**Comment by fiftydinar** [comment]
> This is a huge work too, I've already covered with the options -a and -d:
> 
>     * with the option `-a` you can get more info about the app an the sources where it is taken from;
> 
>     * with the option `-d` you can download the script and see by yourself how it is installed.
> 
> 
> Another way is to visit https://portable-linux-apps.github.io/apps and open the link "blob" or "raw" to see the installation script without downloading it.
> 
> Yet another way is to install the app and then use the option `-f` to see the kind of apps you have installed.

Understandable.

It is not the ideal way of viewing that information, but if it's hard to do, I can get used to it.

I just had in my had how Gnome Software package preference functions, so I made an issue.

**Comment by Samueru-sama** [comment]
> For example, I want to install AppImage packages only.
> 
> I set that option in config & when i run `am --list`, I am presented with AppImage packages only.
> 
> Same can be done with standalone applications if set.
> 
> Another thing, which can happen, is if package is available as both AppImage & standalone (.tar.gz or extracted .deb), It would be nice if you can set a format preference order. Like this:
> 
> 1. AppImage
> 2. Standalone

Now you can list appimages only with `am -l --appimages` and search with `am -q --appimages searchterm`, example with fastfetch which is not an appimage:

![image](https://github.com/user-attachments/assets/163ddd95-7ad4-419e-b911-fe965e9df003)
