### ISSUE TITLE
Wayland electron support

### ISSUE THREAD

**Issue by AmmarHaddadi** [ivan-hc/AM#210]
for electron apps to run natively on **wayland** you need to pass this flag: `--ozone-platform-hint=wayland`  otherwise it runs on **xwayland**, apps are pixelated if the user uses screen scaling since **xwayland** doesn't support that.

however, you can't just add it to templates, you need some kind of logic that checks if the app is running on electron or not and add `--ozone-platform-hint=auto` if the do _(**auto** so that if the user has **xorg** and **wayland** WMs on his pc it leaves it up to the electron to decide)_ which I couldn't do sadly, I'll leave it up to anyone reading this.

currently I do the work manually of editing the `/usr/share/applications/AM-APP.desktop`
It's worth mentioning that I created a `~/.config/electron-flags.conf` and added the flag in it but it didn't work for some reason, maybe because appimages are separate from the system?

**Comment by ivan-hc** [comment]
Apart from the fact that the functioning or failure of an application depends on its developer, not on "AM", which is just a package distribution method, like many others... you could copy/paste the .desktop file in ~ /.local/share/applications and make the changes without needing root privileges.

There would be a way to solve the problem completely: replace in the installation scripts the "LINK" in /usr/local/bin with a script that checks if the section is in Wailand, "else" start the app without the option proposed by you. See the kdenlive and avidemux scripts, essy don't create a link but a script (to scale the DPI and try to use the system theme), you could take inspiration from those.

I saw you forked the repository, you could locate the Electron apps and make the change yourself. You should replace the line...
```
ln -s /opt/$APP/$APP /usr/local/bin/$APP
```
...of such scripts with something like this...
```
cat >> /usr/local/bin/$APP << 'EOF`
#!/usr/bin/env bash
APP=SAMPLE
if "test if the session is Wayland"; then
        /opt/$APP/$APP --ozone-platform-hint=wayland "$@"
else
        /opt/$APP/$APP "$@"
fi
EOF
chmod a+x /usr/local/bin/$APP
sed -i "s/SAMPLE/$APP/g" /usr/local/bin/$APP
```
the last two commands are needed to made the app executable and to replace SAMPLE with the name of the app, respectivelly, so you have a copy/paste method to replace those links.

Now, I don't know how to determine if we are running a Wayland environment (I'm an XFCE user), maybe you should replace...
```
if "test if the session is Wayland"; then
```
with
```
if [ $(echo "$XDG_SESSION_TYPE") == wayland ]; then
```
or something.

**Comment by ivan-hc** [comment]
If you want, you can list the apps you are interested in here and I will make the necessary changes.

In the meantime, I'm closing this issue.
