### ISSUE TITLE
"am nolibfuse bitwarden" wipes all home directory and disk

### ISSUE THREAD

**Issue by diogogomes** [ivan-hc/AM#273]
Hello,

I was testing your application with Bitwarden and when I tested **`am nolibfuse bitwarden`**, it **wipped all the home partition and tried to wipe all the system**.

**If someone runs as sudo it will be the same of `rm -rf /`**.

Best regards

**Comment by ivan-hc** [comment]
Thank you for this, I've tested it several time without problems... but with bitwarden I had the same issue... and also my backups are gone :( dammit

I don't really know how this woulfd be happened. The `find` command was set to find the directory "metainfo" isnide the "squashfs-root" directory!

**Comment by ivan-hc** [comment]
I just can't explain how this happened, I tested this option with over 10 different apps and it always worked, even when it couldn't convert.

From now on the module will try to convert only the first time, without trying to automatically remove the contents of the "metainfo" directory inside the AppImage. This step was necessary in case we had errors with Appstream.

The function was as follows, all the work was done while in /opt/$APP (and "$APP" = "$2"):
```
metainfodir=$(find ./squashfs-root -type d -name metainfo | grep "share/metainfo")
rm -R -f "$metainfodir"/*
echo -ne " ...found Appstream errors, I'm trying to fix them...\r"
ARCH="$(uname -m)" VERSION=$(./appimagetool -v | grep -o '[[:digit:]]*') ./appimagetool -s ./squashfs-root > /dev/null 2> /dev/null
```

**Comment by ivan-hc** [comment]
I think I've found the bug
```
rm -R -f "$metainfodir"/*
```
only sees /, not $metaintodir... I'm ashamed of what I wrote

**Comment by ivan-hc** [comment]
I think I've solved with this
```
metainfodir=$(find ./squashfs-root -type d -name metainfo | grep "share/metainfo")
if [ -z "$metainfodir" ]; then
	echo " 💀Errors while trying to export $(echo $2 | tr a-z A-Z) from Type2 AppImage. Aborted."
	rm -R -f ./appimagetool ./squashfs-root; exit
else
	cd "$metainfodir"
	rm -R -f ./*.xml
	cd - > /dev/null
fi
```
check if the variable is empty, if so, exit the process, else `cd` into the directory and ony remove xml files into it, then come back and finish the process

**Comment by ivan-hc** [comment]
@diogogomes Really, I'm mortified by what happened.

**Comment by ivan-hc** [comment]
Here you are a new release https://github.com/ivan-hc/AM/releases/tag/6.1.3

**Comment by ivan-hc** [comment]
I really thank you instead. I'm the one here that must thank you for all patience you had
