### ISSUE TITLE
Issue with the desktop entry of ppsspp

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/AM#303]
I tested installing by doing `am -i ppsspp` and it installed, however the desktop entry is broken because it contains a `Exec=PPSSPPSDL` line instead of pointing to the path to appimage or using the name in PATH, which is `ppsspp`. 

Should be an easy fix, sorry if this is an upstream issue and shouldn't be here.

**Comment by ivan-hc** [comment]
try now

**Comment by Samueru-sama** [comment]
> try now

It works! thank you!
