### ISSUE TITLE
es-de doesn't create plasma menu shortcut

### ISSUE THREAD

**Issue by ppvnf** [ivan-hc/AM#306]

**Comment by ivan-hc** [comment]
I ca't reproduce the issue (i use XFCE), for me it appears in Games and the .desktop file is this (in AppMan)
```
[Desktop Entry]
Version=1.0
Exec=/home/ivan/.local/bin/es-de
Icon=/home/ivan/.local/share/appman/es-de/icons/es-de
Terminal=false
Type=Application
StartupNotify=true
Hidden=false
Categories=Game;Emulator;
Name=ES-DE
GenericName=Emulator Frontend
Keywords=emulator;emulation;front-end;frontend;
```
what should I do here?

is this not an issue that may be solved by the upstream developer?

**Comment by ivan-hc** [comment]
This seems to be an issue of KDE Plasma only:

https://www.google.com/search?client=firefox-b-d&q=launcher+not+show+in+plasma+linux

**Comment by ppvnf** [comment]
I am not sure this is a problem with kde, because I never had this problem before. I actually was using gnome and the icon was not added to the menu as well, but if my memory is correct I got the .desktop, but maybe it was in the wrong place. In KDE I am not even finding it.

I looked a few of my installed apps .desktop files and most are located in
` /usr/share/applications/`
A few are in` ~/.local/share/applications/`
and some in `/usr/local/share/applications/`

By the way, I installed 86Box through AM and the .desktop file was placed in `/usr/local/share/applications/`, in this cases it shows up in the menu correctly. I had previously installed ES-DE through gear lever and the shortcut was appearing as well.

**Comment by ivan-hc** [comment]
is your distro an immutable one? Maybe there is an additional check I should do in the installation process to install launchers in /usr/local/share applications instead (by default, AM installs launchers in /usr/share/applications, immutable distros have /usr/share set as a read only path)

**Comment by ivan-hc** [comment]
> A proposito, ho installato 86Box tramite AM e il file .desktop è stato inserito `/usr/local/share/applications/`, in questi casi viene visualizzato correttamente nel menu. In precedenza avevo installato ES-DE tramite la leva del cambio e veniva visualizzato anche il collegamento.

If so, in the module [install.am](https://github.com/ivan-hc/AM/blob/main/modules/install.am) (the responsible of the installation of programs) there is a check:
```
if [ $AMCLI == appman ] 2>/dev/null; then
	_install_common_patch
	_install_appman_local_patch
else
	if [[ $(grep "[[:space:]]ro[[:space:],]" /proc/mounts) ]]; then
		$SUDOCOMMAND mkdir -p /usr/local/share/applications
		sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
	fi
	_install_common_patch
fi
```
in particular the step:
```
if [[ $(grep "[[:space:]]ro[[:space:],]" /proc/mounts) ]]; then
	$SUDOCOMMAND mkdir -p /usr/local/share/applications
	sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
fi
```
that checks for read only mountpoints in the system. If they exist, the path of the launcher will be changed and the launcher will be placed in  /usr/local/share/applications

I don't know much about immutable distributions, the step above was suggestef by another user of Fedora or something... I forgot.

However, if for "86box" workded... why this has not worked for "es-de"? The scripts are similar and the steps to extract/edit/move the .desktop file are the same.

**Comment by ivan-hc** [comment]
In the meantime, I've shared my question on Reddit:

https://www.reddit.com/r/linuxquestions/comments/1bsjfvq/how_to_check_if_the_distro_in_use_is_immutable/

**Comment by ivan-hc** [comment]
If we compare the scripts of [86box](https://github.com/ivan-hc/AM/blob/main/programs/x86_64/86box) and [es-de](https://github.com/ivan-hc/AM/blob/main/programs/x86_64/es-de) use the same steps to extract the launcher...
```
# LAUNCHER & ICON
app=$(echo $APP | cut -c -3)
cd /opt/$APP
./$APP --appimage-extract *.desktop 1>/dev/null
./$APP --appimage-extract share/applications/*.desktop 1>/dev/null
./$APP --appimage-extract usr/share/applications/*.desktop 1>/dev/null
mv squashfs-root/*.desktop ./$APP.desktop
mv squashfs-root/share/applications/*.desktop ./$APP.desktop
mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract usr/share/applications/*$app*.desktop 
	mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop
fi
if [ ! -e ./$APP.desktop ]; then 
	rm ./$APP.desktop; ./$APP --appimage-extract share/applications/*$app*.desktop 1>/dev/null
	mv squashfs-root/share/applications/*.desktop ./$APP.desktop
fi
```
...patch it...
```
CHANGEEXEC=$(cat ./$APP.desktop | grep Exec= | tr ' ' '\n' | tr '=' '\n' | tr '/' '\n' | grep $app | head -1)
sed -i "s#$CHANGEEXEC#$APP#g" ./$APP.desktop
sed -i "s#AppRun#$APP#g" ./$APP.desktop
sed -i "s#Exec=/bin/#Exec=#g" ./$APP.desktop
sed -i "s#Exec=/usr/bin/#Exec=#g" ./$APP.desktop
CHANGEICON=$(cat ./$APP.desktop | grep Icon= | head -1)
sed -i "s#$CHANGEICON#Icon=/opt/$APP/icons/$APP#g" ./$APP.desktop
```
...and move it
```
rm -R -f /opt/$APP/squashfs-root
mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop
```
then the install.am module of "AM"/AppMan changes the path, depending if you're using "AppMan" (in $HOME/.local/share/applications) or "AM" on an immutable distro (to /usr/local/share/applications).

**Comment by ivan-hc** [comment]
And from what they said on Reddit, there are several ways to check if the distro is an immutable one, so I can change the function
```
if [[ $(grep "[[:space:]]ro[[:space:],]" /proc/mounts) ]]; then
	$SUDOCOMMAND mkdir -p /usr/local/share/applications
	sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
fi
```
to
```
if [[ $(grep "[[:space:]]ro[[:space:],]" /proc/mounts) ]]; then
	$SUDOCOMMAND mkdir -p /usr/local/share/applications
	sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
elif "some other command"; then
	$SUDOCOMMAND mkdir -p /usr/local/share/applications
	sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
elif "some other new command"; then
	$SUDOCOMMAND mkdir -p /usr/local/share/applications
	sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
[...]
fi
```
until we have covered all immutable distros.

**Comment by ppvnf** [comment]
And this problem seems specific to ES-DE as vs codium and powershell also appear in the menu on my Fedora install. For ES-DE it is strange because I got all the icons instracted and the /bin link created, only the .desktop was missing. Hang on, I will share the results of OpenSUSE Tumbleweed

**Comment by ivan-hc** [comment]
please, reinstall with the command:
```
am -i --debug es-de
```
and share the output. Also check if the AM-es-de.desktop file is in /usr/local/share/applications or /usr/share/applications, if so also copy/paste the content of that .desktop file.

**Comment by ivan-hc** [comment]
I've installed Fedora KDE spin on Virtualbox and then installed AM and es-de... no problems here.

Also, the launcher is in /usr/share/applications

**Comment by ivan-hc** [comment]
I don't really know why it wont work for you:

https://github.com/ivan-hc/AM/assets/88724353/342898f2-9cb4-484a-bbd5-13e1a4002f56

I had not to add AM dependences (maybe `libfuse2`, I've not tested, but the option `nolibfuse` of AM to convert it to Type3 without the needing of `libfuse2` works too on this Appimage)

I've installed it on Fedora 39 KDE Spin, from https://fedoraproject.org/spins/kde/download

**Comment by ppvnf** [comment]
usrz@fedora:~$ am -i --debug es-de

 ############################################################################
 ##                                                                        ##
 ##                  START OF ALL INSTALLATION PROCESSES                   ##
 ##                                                                        ##
 ############################################################################


 ◆ "ES-DE": starting installation script
--2024-04-01 22:25:12--  https://gitlab.com/es-de/emulationstation-de/-/package_files/117882100/download
Resolving gitlab.com (gitlab.com)... 2606:4700:90:0:f22e:fbec:5bed:a9b9, 172.65.251.78
Connecting to gitlab.com (gitlab.com)|2606:4700:90:0:f22e:fbec:5bed:a9b9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 153720000 (147M) [application/octet-stream]
Saving to: ‘es-de.AppImage’

es-de.AppImage         100%[============================>] 146.60M  5.61MB/s    in 25s     

2024-04-01 22:25:37 (5.79 MB/s) - ‘es-de.AppImage’ saved [153720000/153720000]

mv: cannot stat 'squashfs-root/share/applications/*.desktop': No such file or directory
mv: cannot stat 'squashfs-root/usr/local/share/applications/*.desktop': No such file or directory
mv: cannot stat 'squashfs-root/usr/local/share/applications/*.desktop': No such file or directory
rm: cannot remove './es-de.desktop': No such file or directory
mv: cannot stat 'squashfs-root/share/applications/*.desktop': No such file or directory
cat: ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
cat: ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
mv: cannot stat './es-de.desktop': No such file or directory
 "ES-DE" INSTALLED (147 MB OF DISK SPACE)                                 
 ____________________________________________________________________________
 ############################################################################

                  END OF ALL INSTALLATION PROCESSES

             The following new programs have been installed:

 ◆ es-de

 ############################################################################

**Comment by ppvnf** [comment]
no desktop file on  /usr/share/applications and /usr/local/share/applications

**Comment by ivan-hc** [comment]
its really strange... now I've changed the check method for this installation script. I hope this would fix the issue (and sorry if the commit has closed the issue in authomatic).

Try now or at least wait few minutes, just the time that this github repo is in sync with your zone.

**Comment by ivan-hc** [comment]
> the problem still remains for me, but it is not really a big deal since I can manually create the menu entry easily. The command to install AM is `wget https://raw.githubusercontent.com/ivan-hc/AM/main/INSTALL && chmod a+x ./INSTALL && sudo ./INSTALL`, right?. Maybe I am missing a library or have some conflict

the way AM is installed is not a reason because the icon of one single app does not appear. If you have seen the video above, I've installed Fedora KDE Spin 39, and out of the box I have installed AM and es-de.

Just one thing that (for me) was strange, I'm not a Fedora user, but... during the installation of Fedora I've seen that the root account may be set as "hidden" or something. I've allowed root account near the regular one. I don't know if this may be the reason because for me has worked. Have you enabled the root account during the installation process?

**Comment by ivan-hc** [comment]
> Just one thing that (for me) was strange, I'm not a Fedora user, but... during the installation of Fedora I've seen that the root account may be set as "hidden" or something. I've allowed root account near the regular one. I don't know if this may be the reason because for me has worked. Have you enabled the root account during the installation process?

up

**Comment by ppvnf** [comment]
Sorry, I have been somewhat busy lately. I have the root account enabled. I have both Flatpak and Snap enabled. I have no idea left of what could be the cause of this issue. The only non standard package I have is Packet Tracer, but I think it has nothing to do. I am gonna disable snaps since I am no longer using it, but I don't know what could be related to this issue. Is there some kinda of log I could provide to help?

**Comment by ivan-hc** [comment]
> Is there some kinda of log I could provide to help?

No, unfortunately... you've done it before.

The best you could do is open a terminal, run the command `set -x` and try again with `am -i --debug es-de`

**Comment by ppvnf** [comment]
usrz@fedora:~$ set -x
++ printf '\033]0;%s@%s:%s\007' usrz fedora '~'
usrz@fedora:~$ am -i --debug es-de
+ am -i --debug es-de

 ############################################################################
 ##                                                                        ##
 ##                  START OF ALL INSTALLATION PROCESSES                   ##
 ##                                                                        ##
 ############################################################################


 ◆ "ES-DE": starting installation script
--2024-04-04 20:21:50--  https://gitlab.com/es-de/emulationstation-de/-/package_files/117882100/download
Resolving gitlab.com (gitlab.com)... 2606:4700:90:0:f22e:fbec:5bed:a9b9, 172.65.251.78
Connecting to gitlab.com (gitlab.com)|2606:4700:90:0:f22e:fbec:5bed:a9b9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 153720000 (147M) [application/octet-stream]
Saving to: ‘es-de.AppImage’

es-de.AppImage         100%[============================>] 146.60M  5.64MB/s    in 25s     

2024-04-04 20:22:16 (5.93 MB/s) - ‘es-de.AppImage’ saved [153720000/153720000]

mv: cannot stat 'squashfs-root/usr/local/share/applications/*.desktop': No such file or directory
cat: ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
cat: ./es-de.desktop: No such file or directory
sed: can't read ./es-de.desktop: No such file or directory
mv: cannot stat './es-de.desktop': No such file or directory
 "ES-DE" INSTALLED (147 MB OF DISK SPACE)                                 
 ____________________________________________________________________________
 ############################################################################

                  END OF ALL INSTALLATION PROCESSES

             The following new programs have been installed:

 ◆ es-de

 ############################################################################
++ printf '\033]0;%s@%s:%s\007' usrz fedora '~'
usrz@fedora:~$

**Comment by ivan-hc** [comment]
I'm really sorry for that. I hope we'll catch the reason as soon as possible

**Comment by Samueru-sama** [comment]
I installed es-de on my arch setup, when using appman it has no issues and the icon and desktop entry are present. 

![image](https://github.com/ivan-hc/AM/assets/36420837/09c07274-bf03-406f-94b2-f9a1b7feba5e)

However if I use am and install it system wide then it does not have a desktop icon on rofi for some reason, but if I go to /usr/share/applications the desktop entry thumbnail does show the icon lol. 

![image](https://github.com/ivan-hc/AM/assets/36420837/8d523413-af9f-44bf-9717-2c0b75433ed6)

**Comment by ppvnf** [comment]
I managed to get it to work. Apparently I had to use a custom install folder by modifying `~/.config/appman/appman-config`. Strangely the prompt to set it up did not appear when doing the regular install with `wget https://raw.githubusercontent.com/ivan-hc/AM/main/INSTALL && chmod a+x ./INSTALL && sudo ./INSTALL`

**Comment by ppvnf** [comment]
I think the default path of /opt/ create some permission issue

**Comment by ivan-hc** [comment]
By default, AM (the APP-MANAGER script) is installed in /opt/am, with symlink to /usr/local/bin/am , to respect of Linux Standard Base.

If renamed as "appman" it works in a portable way and installs apps locally, in your $HOME

See https://github.com/ivan-hc/AM#differences-between-am-and-appman

However, yours is a strange case, we had the same system installed, Fedora KDE, you on your PC and me in Virtualbox, and the same script is installed differently. Mine had no issues, it worked out of the box, after a fresh Fedora installation. Why not yours?

**Comment by ppvnf** [comment]
I get AM being installed on /opt, but shouldn't the downloaded app images themselves be placed by default on another folder?

**Comment by ppvnf** [comment]
Also I don't get why I got prompted to choose a custom folder only now and not when I installed it

**Comment by ivan-hc** [comment]
each app has its own directory, with its scripts to be removed and updated.

> Also I don't get why I got prompted to choose a custom folder only now and not when I installed it

so you're talking about AppMan, it asks you where to install your apps in your $HOME directory

You can made AM work like AppMan if you run the command `am --user` or `am appman`, after that you must use the suggested "alias" for each terminal session... or to put in ~/.bashrc to made it permanent. Then it switches to AM if you install apps with `sudo` (and nothing more, you have to unset the alias to made AM act normally).

**Comment by ppvnf** [comment]
somehow am started acting like appman for me out of nowhere

**Comment by ppvnf** [comment]
but it is working so I can't complain

**Comment by ivan-hc** [comment]
> somehow am started acting like appman for me out of nowhere

out of nowhere? Impossible.

> but it is working so I can't complain

lucky you, I'm the owner of this program and it should not act like this. I'm afraid.

**Comment by ppvnf** [comment]
I saw there was an update recently. Maybe somehow it transformed my install in a portable one. I will do some testing tomorrow on a fresh install

**Comment by ivan-hc** [comment]
ok, let me know. Good night.

**Comment by Samueru-sama** [comment]
> I saw there was an update recently. Maybe somehow it transformed my install in a portable one. I will do some testing tomorrow on a fresh install

Instead of `am` try running `/usr/local/bin/am` in the terminal to see if it still behaves like AppMan.

**Comment by ppvnf** [comment]
it does indeed behave like am if I do that

**Comment by Samueru-sama** [comment]
> it does indeed behave like am if I do that

Check your `profile` or `bash_profile` and similar and see if you don't have the am alias to appman just in case.

**Comment by ppvnf** [comment]
checked bashrc and command alias doesn't return AM

**Comment by ivan-hc** [comment]
@ppvnf I think I've solved the issue, just usa `am -s` or `am -u` to have the new module for the installation of the apps.

Please, also see https://github.com/ivan-hc/AM/issues/390

The issue was that the module to unstall the scripts applies a patch to these if RO filesystems are on the host, the patch was this:
```
sed -i 's#/usr/share/applications#/usr/local/share/applications#g' ./$arg
```
and now I replaced it with
```
sed -i 's# /usr/share/applications# /usr/local/share/applications#g' ./$arg
```
ie with spaces before /usr/share/applications. In this way, no other references to /usr/share/applications are touched, for example, the command
```
mv squashfs-root/usr/share/applications/*.desktop ./$APP.desktop
```
that for this mistake was changed with
```
mv squashfs-root/usr/local/share/applications/*.desktop ./$APP.desktop
```
where squashfs-root/usr/local/share/applications does not exists when the AppImage is extracted.

**Comment by ppvnf** [comment]
Is it live already?

**Comment by ivan-hc** [comment]
> Is it live already?

sure, modules are always updated to have all bug fixed

**Comment by ppvnf** [comment]
by the way¸ do you have any idea how I managed to do this (probably my fault, see below)?
I installed am using the regular script, and I created a update script to run at login that runs `/usr/local/bin/am -u`
`~/bin/am ` is a dynamic link to `/home/usrz/bin/ `

usrz@fedora:~$ ~/bin/am -f

YOU HAVE INSTALLED 5 STANDALONE PROGRAMS MANAGED BY 'APPMAN':

-  APPNAME     |  TYPE               |  SIZE  
-  -------     |  ----               |  ----  
◆  es-de       |  appimage-type2     |  147   MiB
◆  vscodium    |  appimage-type2     |  129   MiB
◆  powershell  |  appimage-type3     |  65    MiB
◆  86box       |  appimage-type2     |  53    MiB
◆  ventoy      |  binary/executable  |  23    MiB

usrz@fedora:~$ /usr/local/bin/am -f

YOU HAVE INSTALLED 1 STANDALONE PROGRAMS MANAGED BY 'AM':

-  APPNAME  |  TYPE    |  SIZE  
-  -------  |  ----    |  ----  
◆  am       |  script  |  312   KiB

**Comment by ppvnf** [comment]
I realized that I should actually run /~/bin/am -u to update my apps. I have no idea how I got AM installed through AM though

**Comment by ppvnf** [comment]
> > Is it live already?
> 
> sure, modules are always updated to have all bug fixed
> 
> all you have to do is `am -s` or `am -u`

Thank you so much, it now works!!

**Comment by ivan-hc** [comment]
> I have no idea how I got AM installed through AM though

not innstalled, "managed", in fact you can update and remove AM using AM

>  /~/bin/am

what is this?

- AM is a symlink named /usr/local/bin/am for /opt/am/APP-MANAGER
- AppMan is the script APP-MANAGER renamed as "**appman**", and it is portable, you can place it everywhere if named so

**Comment by ppvnf** [comment]
I have that symlink, as well as appman at /usr/local/bin/am
[Archive.zip](https://github.com/ivan-hc/AM/files/14982609/Archive.zip)

**Comment by ivan-hc** [comment]
also, I noticed that your am script is at version 6.3, and this is bad, AM should be always updated to keep receive bug fixes.
