### ISSUE TITLE
Better .bashrc patching

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/AM#309]
I use zsh as my shell and as result almost every time I run am it creates a .bashrc file with in my $HOME. 

Looks like this is caused by this part of the script in the launcher.am module:

```
function _patch_bashrc_and_profile(){
	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
	if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
	fi
	# Correct the order of .local/bin in .profile if necessary
	if test -f "$HOME/.profile"; then
		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
		fi
	elif test -f "$HOME/.bash_profile"; then
		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.bash_profile"; then
			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.bash_profile"
		fi
	fi
}
```

I think the script should instead check for $PATH, and if it doesn't contain $HOME/.local/bin it proceeds with those changes, like for example: `echo $PATH | grep $(whoami)/.local/bin` for the check. 

Another thing that can be done is to simply check for .bashrc before making it like it already does for .profile and .bash_profile.

Also, I edited the .bashrc file with the line that I normally keep on my zshenv: 

`export PATH="$HOME/.local/bin:$PATH"`

And it still overwrites it with the following: 

```
export PATH="$HOME/.local/bin:$PATH"export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed s/.$//)
export PATH=$PATH:$(xdg-user-dir USER)/.local/bin
```

The first export is now broken and the second export is putting the home user bin dir as the last in PATH instead of the first like I had it originally, this is a problem because often times people use this location for wrapper scripts and by forcing that as the last in PATH it would break those scripts.

**Comment by ivan-hc** [comment]
Its not just launcher.am, also APP-MANAGER has this.

The function is doubled because --launcher can be used also by "AM" to add apps locally, while AppMan is designed to totally work in $HOME, so we should work on both the scripts.

I had to add this because someone had this issue on Debian: AppImages wont to be launched from ~/.local/bin if this is the first in `echo $PATH`, so this should be placed at the end of `echo $PATH` to give it the right priority.

**Comment by ivan-hc** [comment]
see https://github.com/ivan-hc/AppMan/issues/25 , https://github.com/ivan-hc/AppMan/issues/26 and https://github.com/ivan-hc/AppMan/issues/27

**Comment by ivan-hc** [comment]
@Samueru-sama this is what you're looking for
```
function _patch_bashrc_and_profile(){
	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
	if test -f "$HOME/.bashrc"; then
		if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
			echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
			echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
		fi
	fi
	# Correct the order of .local/bin in .profile if necessary
	if test -f "$HOME/.profile"; then
		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
		fi
	elif test -f "$HOME/.bash_profile"; then
		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.bash_profile"; then
			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.bash_profile"
		fi
	fi
}
```

**Comment by Samueru-sama** [comment]
> @Samueru-sama this is what you're looking for
> 
> ```
> function _patch_bashrc_and_profile(){
> 	# Check if the custom PATH is not already in .bashrc, then append it (fix - exclamation mark negates the entire command substitution)
> 	if test -f "$HOME/.bashrc"; then
> 		if ! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' "$HOME/.bashrc"; then
> 			echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> "$HOME/.bashrc"
> 			echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> "$HOME/.bashrc"
> 		fi
> 	fi
> 	# Correct the order of .local/bin in .profile if necessary
> 	if test -f "$HOME/.profile"; then
> 		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.profile"; then
> 			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.profile"
> 		fi
> 	elif test -f "$HOME/.bash_profile"; then
> 		if grep -q 'PATH="$HOME/.local/bin:$PATH"' "$HOME/.bash_profile"; then
> 			sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' "$HOME/.bash_profile"
> 		fi
> 	fi
> }
> ```

Looks good to me.

**Comment by ivan-hc** [comment]
Sorry for the wait, I took the opportunity to refactor the code with Shellchek (just as long as it stopped raining here)

**Comment by Samueru-sama** [comment]
> Sorry for the wait, I took the opportunity to refactor the code with Shellchek (just as long as it stopped raining here)

No need to be sorry, you've done an amazing thing that I've been needing for years. 

(Btw since I'm typing it here, thanks again for fixing the PPSSPP issue I had the other day, I noticed that when you fixed that issue you also changed the `Name=ppsspp` in the desktop entry, the actual name of the emulator is PPSSPP all in uppercase, just telling you that here to not open another issue lol).

**Comment by ivan-hc** [comment]
> (A proposito, dal momento che lo sto scrivendo qui, grazie ancora per aver risolto il problema PPSSPP che ho avuto l'altro giorno, ho notato che quando hai risolto quel problema hai anche cambiato il `Name=ppsspp`nella voce del desktop, il nome effettivo dell'emulatore è PPSSPP tutto in maiuscolo, ti dice solo che qui non si apre un altro problema lol).

ahah, that was easy, I had to add a "-i" to `grep` not to differ lowercased and uppercased outputs .

I'm the one that must thank when a user reports these issues, so I can try to fix them and improve mysels (because I'm not a developer).
