### ISSUE TITLE
openscad fail install

### ISSUE THREAD

**Issue by valtoree** [ivan-hc/AM#368]
hi, as above,
installed openscad
but nothing in launcher and -a says
"STATUS: INSTALLED, ABOUT 1 MB OF DISK SPACE IN USE"

please fix, thanks for awesome work

**Comment by ivan-hc** [comment]
done, it was an old script wrote before tha changes in Github APIs. Now its updated.

**Comment by valtoree** [comment]
wow!!! blazing speed Captain. ty 🙏
