### ISSUE TITLE
Looks like ES-DE broke

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/AM#370]
I tried to install it to do some tests and I can't. am gives an error without details. 

I don't know if the website changed, but this no longer turns an url: 

`version=$(wget -q https://es-de.org/ -O - | grep -i appimage | head -1 | tr ' ' '\n' | sed '/AppImage/,$d' | grep "/download" | tail -1 | cut -d '"' -f2)`

Why is this using the es-de website instead of the gitlab repo for getting the appimage link? 

https://gitlab.com/es-de/emulationstation-de/-/releases

@ivan-hc Does it also not work on your end? let me know so I can try to fix it lol.

**Comment by Samueru-sama** [comment]
> the issue is due to the change of the web page. This worked until 2-3 days ago, I had an issue about es-de.
> 
> I've used that URL because its difficult to "grep" the URL from a githlab repository, at least on github we can use APIs.
> 
> This time I'll do another attempt from gitlab.

`wget -q https://es-de.org/ -O - | grep -Eo 'https?://[^[:space:]]+' | grep x64.AppImage | sed 's/"//g'` does the trick for the website. Yeah I tried to use gitlab and gave up lol. 

However I don't know how the version comparison works, since the appimage title doesn't contain the version.

**Comment by ivan-hc** [comment]
With a linear URL it does not works.

In the past I had a lot of scripts that had the URL from AUR, only that AUR is untrustable sometime, if none maintains a PKGBUILD, the app will be removed from there.

I'm trying right now to gind a solution for gitlab

**Comment by ivan-hc** [comment]
how should we get the ID of a gitlab repo?

**Comment by ivan-hc** [comment]
The command:
```
wget -q https://gitlab.com/api/v4/projects/18817634/releases/ -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*"
```
shows a long list of URLs but without identify what of them is the AppImage, just numbers/download

**Comment by Samueru-sama** [comment]
> The command:
> 
> ```
> wget -q https://gitlab.com/api/v4/projects/18817634/releases/ -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*"
> ```
> 
> shows a long list of URLs but without identify what of them is the AppImage, just numbers/download

`wget -q https://gitlab.com/api/v4/projects/18817634/releases/ -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep releases | awk -F / '{print $NF}' | grep v | head -1` gives you the last version

**Comment by ivan-hc** [comment]
funny, I was doing the same thing
```
wget -q https://gitlab.com/api/v4/projects/18817634/releases/ -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep "archive/v" | head -1 | tr '/' '\n' | grep "v[0-9]" | head -1
```
I'll use yours.

Now I think we can combine the two solutions: package from main page and version from gitlab.

**Comment by Samueru-sama** [comment]
> funny, I was doing the same thing
> 
> ```
> wget -q https://gitlab.com/api/v4/projects/18817634/releases/ -O - | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep "archive/v" | head -1 | tr '/' '\n' | grep "v[0-9]" | head -1
> ```
> 
> I'll use yours.
> 
> Now I think we can combine the two solutions: package from main page and version from gitlab.

Btw the `awk -F / '{print $NF}'` is very useful, it sets the slash as the field separator and prints the last field, which I've used for other scripts before, I learned it from a distrotube video xd.

**Comment by ivan-hc** [comment]
I still have a lot to learn

**Comment by Samueru-sama** [comment]
> I still have a lot to learn

Here is a more efficient way to get the version, I will leave it to you to change it:

`wget -q https://gitlab.com/api/v4/projects/18817634/releases/ -O - | grep -Eo 'v[0-9].[0-9].[0-9]+' | head -1`
