### ISSUE TITLE
amdgpu_top issue with the desktop entries. 

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/AM#381]
context: https://github.com/Umio-Yasuno/amdgpu_top/issues/77

Basically we need to `--appimage-extract assets/*.desktop` for amdgpu_top and ignore the desktop entry that is in the top level of squashfs-root. 

I tried to do it but it didn't work so now I'm here 😅

**Comment by ivan-hc** [comment]
I've not understand what is the issue with the launcher, but you may add a function with the command "`sed -i`" in the installation script to comment (add a "#") where you need to disable the entry, exactly the way you do with shell scripts, before line 127, ie
```
mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop
```

To test the canges, do `am -i /path/to/amdgpu_top` or `appman -i /path/to/amdgpu_top`

NOTE, when you test installation scripts with AppMan is better, this means that also AppMan patches are working, so everything should work as expected.

Please, do it in the same PR, so I don't need to login every time t approve.

**Comment by Samueru-sama** [comment]
> I've not understand what is the issue with the launcher, but you may add a function with the command "`sed -i`" in the installation script to comment (add a "#") where you need to disable the entry, exactly the way you do with shell scripts, before line 127, ie
> 
> ```
> mv ./$APP.desktop /usr/share/applications/AM-$APP.desktop
> ```
> 
> To test the canges, do `am -i /path/to/amdgpu_top` or `appman -i /path/to/amdgpu_top`
> 
> NOTE, when you test installation scripts with AppMan is better, this means that also AppMan patches are working, so everything should work as expected.
> 
> Please, do it in the same PR, so I don't need to login every time t approve.

The issue is that amdgpu_top has two desktop entries. One is for its GUI and the other is for its TUI. 

However the appimage is made with a tool called `cargo-appimage` and that tool creates a dummy `squashfs-root/cargo-appimage.desktop` file that is broken and it is what gets installed by AM. 

I tried modifying the script to replace the lines with `--appimage-extract assets/*.desktop` and that did not work, it still put the broken desktop entry as the `AM-amdgpu_top.desktop` entry.  

I also don't know how the entry gets named to have the AM in the title 😅

I will try again though.
