### ISSUE TITLE
Add spacebar (prerelease)

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#386]
[discord alternative frontend](https://github.com/spacebarchat/client/releases/download/client-dev-v0.1.2/spacebar_0.1.2+80756930761_amd64.AppImage)

**Comment by ivan-hc** [comment]
https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/326cb4a23ddbff24df4a82125889ed0f10fd3d60

done
