### ISSUE TITLE
Icons?

### ISSUE THREAD

**Issue by Ranko-Saotome** [ivan-hc/AM#396]
Both doubleCommander and freetube do not have icons in the start menu entry

**Comment by ivan-hc** [comment]
I have all of them, I can't reproduce your issue (please, give me more details about your distro, desktop environment, shell.):

![Istantanea_2024-04-16_08-27-04](https://github.com/ivan-hc/AM/assets/88724353/b1b416c7-4620-4d0d-ba4f-e972e6884f32)

**Comment by Ranko-Saotome** [comment]
Zorin os 17 

Gnome

![image](https://github.com/ivan-hc/AM/assets/76974974/c0ecbb29-2784-482c-8a88-fd4d835db1c0)

**Comment by ivan-hc** [comment]
see if in the apps directories are vailable these icons (in /opt/$APPNAME/icons

**Comment by Ranko-Saotome** [comment]
i use appman

**Comment by ivan-hc** [comment]
I've tested also in AppMan and I've no issues. Please, see in the directories of the apps

**Comment by Ranko-Saotome** [comment]
![image](https://github.com/ivan-hc/AM/assets/76974974/6d0eab05-35a9-4650-b5ff-b34f6ddcde3a)

![image](https://github.com/ivan-hc/AM/assets/76974974/c9c84f17-37a5-40a8-a8d4-ac9bbb1d86f9)

**Comment by ivan-hc** [comment]
try to poen these files with GIMP or similar image viewers

**Comment by Ranko-Saotome** [comment]
![image](https://github.com/ivan-hc/AM/assets/76974974/259a939d-932e-4cb2-9e32-d191de5c94f0)

**Comment by ivan-hc** [comment]
???

those are not symlinks, not AM nor AppMan are ment to touch usr/share/icons :eyes:

**Comment by Samueru-sama** [comment]
Make sure appman is up to date. I have no problems with those icons showing in my end with appman either.

**Comment by Ranko-Saotome** [comment]
![image](https://github.com/ivan-hc/AM/assets/76974974/47c49459-e637-4c8a-82d5-7e88685e25ee)

**Comment by Samueru-sama** [comment]
> ![image](https://private-user-images.githubusercontent.com/76974974/322732356-476803b5-5d0f-4215-8a1b-b75078f9a1fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTA2MTksIm5iZiI6MTcxMzI1MDMxOSwicGF0aCI6Ii83Njk3NDk3NC8zMjI3MzIzNTYtNDc2ODAzYjUtNWQwZi00MjE1LThhMWItYjc1MDc4ZjlhMWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA2NTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxM2Q3ZDhjOTFkODQ5NzEyOWE4MWE1ZDViZTZhM2VjZDdjYzg1NDlhMjA3YmZhZGFmMTZkYWYzZGQxYzY5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qanazK1MHpzMKytAgBeROfPhVIaVAdaTmJnzJo_sKKw)

You should be on version 6.5.

**Comment by Ranko-Saotome** [comment]
i did appman -s

**Comment by Samueru-sama** [comment]
> i did appman -s

It is `-u` to update.

**Comment by Ranko-Saotome** [comment]
wont that update all of my apps

**Comment by Ranko-Saotome** [comment]
updating my  appman worked thanks

**Comment by ivan-hc** [comment]
now reinstall the affected apps and see if the issue with icons is solved

**Comment by Ranko-Saotome** [comment]
Quick question how do you close the help menu once you open it without having to kill the entire terminal

**Comment by Ranko-Saotome** [comment]
![image](https://github.com/ivan-hc/AM/assets/76974974/b5d38413-a04a-4a48-bece-adf13781dcb4)

![image](https://github.com/ivan-hc/AM/assets/76974974/252d6e7a-12f2-4c68-9ca7-22fc90e3ac56)

**Comment by Samueru-sama** [comment]
> Quick question how do you close the help menu once you open it without having to kill the entire terminal

press q

And this is common for other CLI applications btw.

**Comment by ivan-hc** [comment]
> Quick question how do you close the help menu once you open it without having to kill the entire terminal

just press Q (it is the command `less`)

**Comment by Ranko-Saotome** [comment]
Thank you all! i got icons.
