### ISSUE TITLE
zsh completion?

### ISSUE THREAD

**Issue by Ranko-Saotome** [ivan-hc/AM#397]
I don't know if you take feature requests but I noticed you had bash completion think you can add completion for the zsh

**Comment by ivan-hc** [comment]
I'm not familiar with ZSH at all

**Comment by Samueru-sama** [comment]
> I'm not familiar with ZSH at all

I will take a look at this later in the day, I normally don't need this because zsh does completion from your zsh history as well. 

Something worth mentioning so I don't forget is that I need to check for `$ZDOTDIR` variable before patching `.zshrc`.

**Comment by Samueru-sama** [comment]
@ivan-hc Alright I came out with something, tested and it works, I will make a new PR with these changes once you decide on what to do with the currently open PR #398 😅

**Comment by ivan-hc** [comment]
> @ivan-hc Alright I came up with something, tested and it works, I will make a new PR with these changes once you decide on what to do with the currently open PR #398 😅

OK, let talk at that PR before we go on

**Comment by ivan-hc** [comment]
With this commit we also have a new release https://github.com/ivan-hc/AM/pull/401

AM 6.5.1

**Comment by Ranko-Saotome** [comment]
thanks for adding!
