### ISSUE TITLE
Apps versions shown also elsewhere

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#411]
So now, we have nice version numbers in `am -f`

But what about the other places where is version number usually shown?
- [x] am -u
- [x] am -a
- [x] am -i
- [x] am -l
- [ ] #421 - CURRENTLY marked as not planned

missed one?

**Comment by ivan-hc** [comment]
@zen0bit I've implemented this only in `-a`

**Comment by ivan-hc** [comment]
I have to do it this way, so as not to bloat the code with a repetitive function for each argument, and not to burden the operation for each argument. So it is better to show the version only at the end of the installation process.

![Istantanea_2024-04-18_15-18-34](https://github.com/ivan-hc/AM/assets/88724353/f6369e48-ad32-459d-a766-253d6bf351f2)

**Comment by ivan-hc** [comment]
@zen0bit about `-u` I think we should wait for the end of this other issue https://github.com/ivan-hc/AM/issues/410

**Comment by Samueru-sama** [comment]
> @Samueru-sama what do you think about?

[Ok](https://www.youtube.com/watch?v=ussCHoQttyQ)

**Comment by ivan-hc** [comment]
> So now, we have nice version numbers in `am -f`
> 
> But what about the other places where is version number usually shown?
> 
>     * [ ]  am -u
> 
>     * [x]  am -a
> 
>     * [x]  am -i
> 
>     * [x]  [am -l #420](https://github.com/ivan-hc/AM/issues/420)
> 
>     * [x]  [am -q #421](https://github.com/ivan-hc/AM/issues/421)
> 
>     * [ ]  ...
> 
> 
> missed one?

@zen0bit  I've removed the empty task, no other options are using (or are ment to use) versions

**Comment by ivan-hc** [comment]
About `-l` and `-q` that other package managers normally can use to show the version... its not the case of "AM"/AppMan:
- this is a database designed to provide scripts that always point to the latest version of an app, according to what is reported in the last loaded script, they do not need external intervention*;
- *in case the sources change, we can always extend the database with third-party repositories to overwrite the incorrect entry, currently in use in the main database;
- the disadvantage of having a list of "continuous" applications is precisely the fact of not being able to show the version of the apps in any way. As I have already said elsewhere, to do this we need a server set up that stores all the apps from the various sources and lists the information, and this is how the databases of all non-portable apps work (and we are the only ones who deal with portable apps, with the exception of other managers like "zap", who however base their entire database on a single source, github, while we have many more sources).

**Comment by ivan-hc** [comment]
That said, can I start merging mi latest changes?

**Comment by ivan-hc** [comment]
> That said, can I start merging mi latest changes [main...dev](https://github.com/ivan-hc/AM/compare/main...dev) ?

Too late https://github.com/ivan-hc/AM/releases/tag/6.5.3

Now let we see if we can solve https://github.com/ivan-hc/AM/issues/410 before we keep improve `-u`

**Comment by ivan-hc** [comment]
@zen0bit as I've already said at https://github.com/ivan-hc/AM/issues/410 parallel updates and app version shown during the process cannot coexist. All processes are so many and so fast that datas will be overwritten between them, so no info will be shown the right way. I've already added some screenshots and more details I wont repeat.

Questions?

**Comment by zen0bit** [comment]
I understand: cannot coexist in current implementation

We will find a way

I think that something like: Can't be done, doesn't exist.

You just need find idiot who don't know that is imposible, and he will do it.
🤪

**Comment by zen0bit** [comment]
What about send each app update check into separated subprocess?

then should be info kept in that and used later for installation summary which show whats happened...
??

**Comment by ivan-hc** [comment]
@zen0bit @Samueru-sama I'm trying to put the list of updatable apps at start and end of update process:
```
			function _list_updatable_apps() {
				rm -R -f $AMPATH/.cache/*
				_check_version
				cd $APPSPATH && find -name 'AM-updater' -printf " %h\n" 2>/dev/null | sort -u | xargs -n 1 basename 2>/dev/null > $AMPATH/.cache/updatable-args
				ARGS=$(tail -n +2 $AMPATH/.cache/updatable-args)
				for arg in $ARGS; do
					app_version=$(cat "$AMPATH/.cache/version-args" | grep -w " ◆ $arg	|" | sed 's:.*|	::')
					echo " ◆ $arg $app_version" >> $AMPATH/.cache/updatable-args-list
				done
			}

			_list_updatable_apps

			echo "-----------------------------------------------------------------------------"
			echo -e ' "'"$(echo $AMCLI | tr a-z A-Z)"'" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS:\n'
			cat "$AMPATH/.cache/updatable-args-list"
			echo -e '\n All programs with fixed versions or self-updatable are excluded'; sleep 0.1
			echo "-----------------------------------------------------------------------------"
			echo -e " >> START OF ALL PROCESSES <<\n-----------------------------------------------------------------------------"

			for f in $APPSPATH/*/; do 
				cd $f 2>/dev/null && 
				if test -f ./AM-updater; then
					start=$(date +%s) && sh -x ./AM-updater > /dev/null 2>&1 | echo -ne ' Updating "'"$(printf '%s\n' "${PWD##*/}")"'"...\r' && end=$(date +%s) &&
					echo -e " ◆ $(echo "$(printf '%s\n' "${PWD##*/}")" | tr a-z A-Z) is updated, $(($end-$start)) seconds elapsed!" &
				else
					echo ""  > /dev/null 2>&1
				fi
			done
			wait

			_list_updatable_apps
```
as you can see I use a function named "_list_updatable_apps", but I have two issues:
1. the first app of the list, Avidemux, is not shown in the first list;
2. the second list is not shown at all

![Istantanea_2024-04-19_01-10-34](https://github.com/ivan-hc/AM/assets/88724353/96fe3bd9-c627-412a-9c2e-59dd452f30a1)

how should I solve this?

**Comment by ivan-hc** [comment]
UPDATE: I've solved the first issue
```
			function _list_updatable_apps() {
				rm -R -f $AMPATH/.cache/*
				_check_version
				cd $APPSPATH && find -name 'AM-updater' -printf " %h\n" 2>/dev/null | sort -u | xargs -n 1 basename 2>/dev/null > $AMPATH/.cache/updatable-args
				ARGS=$(cat $AMPATH/.cache/updatable-args)
				for arg in $ARGS; do
					app_version=$(cat "$AMPATH/.cache/version-args" | grep -w " ◆ $arg	|" | sed 's:.*|	::')
					echo " ◆ $arg $app_version" >> $AMPATH/.cache/updatable-args-list
				done
			}

			_list_updatable_apps

			echo "-----------------------------------------------------------------------------"
			echo -e ' "'"$(echo $AMCLI | tr a-z A-Z)"'" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS:\n'
			cat "$AMPATH/.cache/updatable-args-list"
			echo -e '\n All programs with fixed versions or self-updatable are excluded'; sleep 0.1
			echo "-----------------------------------------------------------------------------"
			echo -e " >> START OF ALL PROCESSES <<\n-----------------------------------------------------------------------------"

			for f in $APPSPATH/*/; do 
				cd $f 2>/dev/null && 
				if test -f ./AM-updater; then
					APPNAME=$(echo "$(printf '%s\n' "${PWD##*/}")")
					start=$(date +%s) && sh -x ./AM-updater > /dev/null 2>&1 | echo -ne ' Updating "'"$APPNAME"'"...\r' && end=$(date +%s) &&
					echo -e " ◆ $(echo "$APPNAME" | tr a-z A-Z) is updated, $(($end-$start)) seconds elapsed!" &
				else
					echo ""  > /dev/null 2>&1
				fi
			done
			wait

			_list_updatable_apps
```
now the second one is left

![Istantanea_2024-04-19_01-30-49](https://github.com/ivan-hc/AM/assets/88724353/c8198a78-102b-4991-acc2-4f56492c4570)

**Comment by ivan-hc** [comment]
@zen0bit @Samueru-sama I've a good news and a bad one:
The good one is that I've finally added the version in the update message, the tother one is that we loose parallel updates
```
			function _list_updatable_apps() {
				rm -R -f $AMPATH/.cache/*
				_check_version
				cd $APPSPATH && find -name 'AM-updater' -printf " %h\n" 2>/dev/null | sort -u | xargs -n 1 basename 2>/dev/null > $AMPATH/.cache/updatable-args
				ARGS=$(cat $AMPATH/.cache/updatable-args)
				for arg in $ARGS; do
					app_version=$(cat "$AMPATH/.cache/version-args" | grep -w " ◆ $arg	|" | sed 's:.*|	::')
					echo " ◆ $arg $app_version" >> $AMPATH/.cache/updatable-args-list
				done
			}

			_list_updatable_apps

			echo "-----------------------------------------------------------------------------"
			echo -e ' "'"$(echo $AMCLI | tr a-z A-Z)"'" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS:\n'
			cat "$AMPATH/.cache/updatable-args-list"
			echo -e '\n All programs with fixed versions or self-updatable are excluded'; sleep 0.1
			echo "-----------------------------------------------------------------------------"
			echo -e " >> START OF ALL PROCESSES <<\n-----------------------------------------------------------------------------"

			for f in $APPSPATH/*/; do 
				cd $f 2>/dev/null && 
				if test -f ./AM-updater; then
					APPNAME=$(echo "$(printf '%s\n' "${PWD##*/}")")
					start=$(date +%s) && sh -x ./AM-updater > /dev/null 2>&1 | echo -ne ' Updating "'"$APPNAME"'"...\r' && end=$(date +%s) &&
					_check_version
					app_version=$(cat "$AMPATH/.cache/version-args" | grep -w " ◆ $APPNAME	|" | sed 's:.*|	::')
					echo -e " ◆ $(echo "$APPNAME" | tr a-z A-Z) $app_version is updated, $(($end-$start)) seconds elapsed!" &
				else
					echo ""  > /dev/null 2>&1
				fi
			done
			wait
```
see yourself

![Istantanea_2024-04-19_01-38-57](https://github.com/ivan-hc/AM/assets/88724353/b748dcbc-929e-4162-bc1b-34fc8972eddc)

this is bad!

Personally, if I had to choose between displaying the version during the update (despite having other options to do so) burdening the process... and having parallel, rapid updates... I choose the rapid updates.

**Comment by zen0bit** [comment]
> Personally, if I had to choose between displaying the version during the update (despite having other options to do so) burdening the process... and having parallel, rapid updates... I choose the rapid updates.

:+1: Agree

**Comment by ivan-hc** [comment]
> > Personally, if I had to choose between displaying the version during the update (despite having other options to do so) burdening the process... and having parallel, rapid updates... I choose the rapid updates.
> 
> 👍 Agree
> 
> But don't cry yet...

Look, you're the one who asked me for this feature, I don't care if we don't implement it. We already have other options that show the version of apps, and your invitation to try studying a way to do it, definitely helped me make "AM" a little better than it was 2 days ago, I admit, and I am grateful to you for this. That doesn't mean that the "versions" issue has not been widely addressed, don't you think?

You proposed 6 options, in two of them it makes no sense in this type of package manager (`-l` and `-q`), not having a fixed but variable database... so 4 options remain, and 3 of these have been successfully resolved. Only "`-u`" remain. Why should I despair? Why did I waste time trying to add one last irrelevant feature?

Has beeen done too much in the last few hours, so I think this is enough.

**Comment by ivan-hc** [comment]
@zen0bit I can't do more than this:

https://github.com/ivan-hc/AM/assets/88724353/fcb76ff9-8833-4b7e-bb1c-b7fae444368d

this is the whole function that mades possible this output
```
			rm -R -f $AMPATH/.cache/*
			function _list_updatable_apps() {
				_check_version
				cd $APPSPATH && find -name 'AM-updater' -printf " %h\n" 2>/dev/null | sort -u | xargs -n 1 basename 2>/dev/null > $AMPATH/.cache/updatable-args
				ARGS=$(cat $AMPATH/.cache/updatable-args)
				for arg in $ARGS; do
					app_version=$(cat "$AMPATH/.cache/version-args" | grep -w " ◆ $arg	|" | sed 's:.*|	::')
					echo " ◆ $arg $app_version" >> $AMPATH/.cache/updatable-args-list
				done
			}

			_list_updatable_apps

			echo "-----------------------------------------------------------------------------"
			echo -e ' "'"$(echo $AMCLI | tr a-z A-Z)"'" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS:\n'
			cat "$AMPATH/.cache/updatable-args-list"
			echo -e '\n All self-updatable programs are excluded'; sleep 0.1
			echo "-----------------------------------------------------------------------------"
			echo -e " >> START OF ALL PROCESSES <<\n-----------------------------------------------------------------------------"

			for f in $APPSPATH/*/; do 
				cd $f 2>/dev/null && 
				if test -f ./AM-updater; then
					APPNAME=$(echo "$(printf '%s\n' "${PWD##*/}")")
					start=$(date +%s) && sh -x ./AM-updater > /dev/null 2>&1 | echo -ne ' Updating "'"$APPNAME"'"...\r' && end=$(date +%s) &&
					echo -e " ◆ $(echo "$APPNAME" | tr a-z A-Z) is updated, $(($end-$start)) seconds elapsed!" &
				else
					echo ""  > /dev/null 2>&1
				fi
			done
			wait

			echo "-----------------------------------------------------------------------------"

			mv $AMPATH/.cache/updatable-args-list $AMPATH/.cache/updatable-args-list-old
			_list_updatable_apps
			OLDVER="$AMPATH/.cache/updatable-args-list-old"
			NEWVER="$AMPATH/.cache/updatable-args-list"
			if cmp --silent -- "$NEWVER" "$OLDVER"; then
				echo ' Nothing to do here!'
			else
				echo -e " The following apps have been updated:\n"
				diff --new-line-format="" --unchanged-line-format="" "$NEWVER" "$OLDVER"
				echo ""
			fi

			rm -R -f $APPSPATH/*/tmp
			if [ -z "$2" ]; then
				echo "-----------------------------------------------------------------------------"
				$AMCLIPATH -s
			fi
			echo -e "-----------------------------------------------------------------------------\n >> END OF ALL PROCESSES << \n-----------------------------------------------------------------------------"; sleep 0.2
			exit;;
```

**Comment by ivan-hc** [comment]
Somehow I managed to implement the list of installed apps+version in "-l" too. But don't expect me to do the same for "-q", it would be a clutter (what the fuck do you care about installed apps if you're looking for something else in the list?).

![Istantanea_2024-04-19_12-30-35](https://github.com/ivan-hc/AM/assets/88724353/52502816-f015-4534-ac70-8c888db4ec5b)
![Istantanea_2024-04-19_12-30-15](https://github.com/ivan-hc/AM/assets/88724353/bff7e33d-d4ae-41d4-9cd5-27a3a72b4cac)



With the next PR (and release) we can consider this issue closed.

**Comment by Samueru-sama** [comment]
@ivan-hc Bro do you sleep? Since I woke up yersterday you were active here then I went to sleep and woke up just now and you are still doing commits 👀

**Comment by zen0bit** [comment]
Not much time left, wanna complete as much as posible..
real life :phone:

**Comment by ivan-hc** [comment]
> @ivan-hc Bro do you sleep? Since I woke up yersterday you were active here then I went to sleep and woke up just now and you are still doing commits 👀

"The night brings advice", I slept quite well and only worked a couple of hours on the new PR, where I changed `-l` and `-u`

**Comment by ivan-hc** [comment]
If I were Woody and @zen0bit was Buzz, opening this feature request...

![versions-versions-everywhere-0feda73a84](https://github.com/ivan-hc/AM/assets/88724353/730f3526-6c5c-42a7-8bdb-ef498a44771d)

@Samueru-sama

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM/releases/tag/6.6.1

**Comment by ivan-hc** [comment]
I was just working on this (with libfuse2, platform-tools and ventoy)

**Comment by Samueru-sama** [comment]
> @Samueru-sama I'm really tempted to tell them all to fuck off

Welp, looks like pkgversion has to come back 😁

For the packages that you can't really get the version from the url you can do a last ditch attempt of `appimagename -v` and cache the output into a file (guess the name of the file)  and then the function can check if that file exists first.

**Comment by ivan-hc** [comment]
> > @Samueru-sama I'm really tempted to tell them all to fuck off
> 
> Welp, looks like pkgversion has to come back 😁
> 
> For the packages that you can't really get the version from the url you can do a last ditch attempt of `appimagename -v` and cache the output into a file (guess the name of the file) and then the function can check if that file exists first.

- librewolf has not info, but now both the Appimage and the .zsync file are hosted with the version on the main website (my script points to gitlab instead, continuour version), so we should replace that script;
- both dophin-emu and ppsspp have the build number in the url, before the last slash and between the appname and x86_64;
- ventoy has a version file under /opt/ventoy/ventoy;
- platform-tools have the revision file in the main directory;
- appimagetool is a continuous release (with no info in the .zsync file).

So the options to work with the tools we already have are enough, why should we add a new pkgversion file for each of them?

**Comment by ivan-hc** [comment]
@Samueru-sama 

![Istantanea_2024-04-19_21-18-29](https://github.com/ivan-hc/AM/assets/88724353/95483cbc-c53b-4b83-8474-297e7481071b)

- the ones I was starting my searches are still "unknown" (platform-tools and ventoy), but I will fix them by updating their scripts
- the only bastard is appimagetool... I don't really know how is possible, but I'm also unable to mark it as "continuous"

all the other will be fixed with the next PR, my only "workarounds" here are the following:
- talking about "continuous", "cpu-x" have no numbers in the URL at all... apart the architecture
- I've updated the script for "librewolf"

**Comment by Samueru-sama** [comment]
> @Samueru-sama
> 
> ![Istantanea_2024-04-19_21-18-29](https://private-user-images.githubusercontent.com/88724353/324092075-95483cbc-c53b-4b83-8474-297e7481071b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTY0NTMsIm5iZiI6MTcxMzU1NjE1MywicGF0aCI6Ii84ODcyNDM1My8zMjQwOTIwNzUtOTU0ODNjYmMtYzUzYi00YjgzLTg0NzQtMjk3ZTc0ODEwNzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE5NDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZTZlNGI0MjI4MjRiMTRkMmM4NTc1NTUyZTYwZjUwMDQ1YzcyZTlkMjZkZDc1MWVjOGU1ZDJhNjBkNDMwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s095FfrjA92nXwmnJiBk61kRJ4NTdxc6twUfRT_7RQs)
> 
> * the ones I was starting my searches are still "unknown" (platform-tools and ventoy), but I will fix them by updating their scripts
> * the only bastard is appimagetool... I don't really know how is possible, but I'm also unable to mark it as "continuous"
> 
> all the other will be fixed with the next PR, my only "workarounds" here are the following:
> 
> * talking about "continuous", "cpu-x" have no numbers in the URL at all... apart the architecture
> * I've updated the script for "librewolf"

You can always replace platform-tools with my android-tools appimage 👀, I even gave it the option to install the android udev rules so it should work on distros that don't have that package. 

Also shouldn't appimagetool be replaced by go-appimage/appimagetool? (asumming this one has a working version lol).

**Comment by ivan-hc** [comment]
> You can always replace platform-tools with my android-tools appimage 👀, I even gave it the option to install the android udev rules so it should work on distros that don't have that package.

too late https://github.com/ivan-hc/AM/pull/443

none of the previous listed apps has been left back...

> Appimagetool

![homer-computer-doh](https://github.com/ivan-hc/AM/assets/88724353/0e9891e4-82d5-4a23-a367-8e422bc21483)

> Also shouldn't appimagetool be replaced by go-appimage/appimagetool? (asumming this one has a working version lol).

I must try

**Comment by ivan-hc** [comment]
Just tried with the other appimagetool... same result: "unknown"

I start thinking that also BASH are starting hatting Probonopd's projects :thinking:

**Comment by ivan-hc** [comment]
However, the old libfuse2-related AppImage of appimagetool is the canonic one, the new one is all my workflows and tools/projects ("AM"/AppMan's nolibfuse.am module, Archimage and AppImaGen).

**Comment by Samueru-sama** [comment]
> NOTE: this AppImage have a version in the name, so it should have been used, so.... WHYYYYY?????? P#!G##GCÀHN

Guaranteed che vuoi from Ivan lol.

**Comment by ivan-hc** [comment]
Pero sí, ¿qué nos importa? Ahora, para una función de mierda, este script se sale de la página.
