### ISSUE TITLE
am -f sort by name or size

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#412]
If I am looking at my long list of installed apps

I couldn't find the right one. since is by default sorted by installed sizes (nice)
But also option for sort by names?

:+1:

**Comment by ivan-hc** [comment]
this is quite easy to do, I'll provide a sub-option "--byname" or something

**Comment by ivan-hc** [comment]
Et voilà

![Istantanea_2024-04-18_11-59-43](https://github.com/ivan-hc/AM/assets/88724353/2681ddd0-f807-4338-b41d-af9e413f5280)

**Comment by ivan-hc** [comment]
also added a bug fix when no app is installed https://github.com/ivan-hc/AM/commit/2ed31bb5d312caf203713e70e3e3b12ee70d66bf
