### ISSUE TITLE
Add qemu AppImage

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#429]
### Posso chiedere di essere aggiunto per favore?
https://github.com/lucasmz1/Qemu_Appimage/releases/tag/continuous-stable

**Comment by ivan-hc** [comment]
> ### Posso chiedere di essere aggiunto per favore?
> 
> https://github.com/lucasmz1/Qemu_Appimage/releases/tag/continuous-stable

Oh my... I was thjinking I had Google Translate enabled :rofl: **Du warst gut** *



*listening to Rammstein has its advantages
