### ISSUE TITLE
Improve help message and arguments

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#461]
Sorry but again...
PROPOSAL

I forgot to post you here what i done to your help in my apptui...
(Not updated version)
![amreadme](https://github.com/ivan-hc/AM/assets/6384793/5e0f53f1-65c5-48a5-92e4-f4ff0483892f)
Isn't this easier to read? (and smaller)

### Also thinking about:
- Leave different arguments for one command like I (mostly) did
- Only short and long arguments (one of each)
- Leave everything not needed from help
- option to use it without less 😇

### Then:
- Use getopts for arguments (like I did in quickemu)
- Like `-f`: and `-fb` instead of `-f --byname` or `-fl` instead of `-f --less`
PS: Wanna help with that, just :traffic_light: green

**Comment by zen0bit** [comment]
```
function show_os_info() {
     while getopts ":12345" opt; do
        case $opt in
          1) os_info "${2}" | cut -d'|' -f1;;
          2) os_info "${2}" | cut -d'|' -f2;;
          3) os_info "${2}" | cut -d'|' -f3;;
          4) os_info "${2}" | cut -d'|' -f4;;
          5) os_info "${2}" | cut -d'|' -f5;;
          *) echo "Wrong choice!" && exit 1;;
        esac
    done
}
```

**Comment by zen0bit** [comment]
> I did this before you removed the option for Termux with your PR because "not needed anymore".
> 
> However, I would keep the "help" as is, because some people are really stupid and still need to understand how to work with options and sub-options, now that we have them too. The CLI has been improved.
> 
> All we can do is to restore what I did for you (and you removed) by using `case`, with sub-options, to show more or less info. That's all.

Arguments? (get-opts)

**Comment by ivan-hc** [comment]
in the meantime, have you seen what I did at https://github.com/ivan-hc/AM/issues/444 with the installation process?

Let close old issues before bombing me with all thse notifications :face_with_thermometer:

**Comment by ivan-hc** [comment]
I don't like these technicisms.

Also, sometime the descriptions are not so easy to understand, by splitting options into a section, suboptions into another... more often without an example or a more detailed description that must be good enough to let a kid understand what is doing. This is why the description looks more like a real guide. I want to guide the user without him have to contact me on Reddit or open issues on issues without reading the README.

In fact, whe you install AM for the first time, the first suggestion is "run `am -h`"

From that moment on, the user must have a detailed guide into a terminal emulator... with all separators.

**Comment by ivan-hc** [comment]
In brief, the "help" message  is something too much precise and popular for some IT skilled and Elite developers like you. What you see too much obvious.... is not for the neubies. And AM is for neubies.

**Comment by zen0bit** [comment]
apt or pacman or xbps commands are just matter of choice

could be anything

i still thinking that -fb is easier to read/write or complete than -f --by-name or -fn like File by Name

-fs File by Size

**Comment by ivan-hc** [comment]
sorry, I can forget it. I've based my choices on my concept of "easy", and its not the same as you.

**Comment by zen0bit** [comment]
All my opened issues are more question or proposals then really issues or bugs

I thought about that and I will there don't clutter issues with my never ending questions :wink:
From now on

I will try "Not really issue" put in discussions section instead
PS: This could be closed as solved (nope?)
I told what I want
I have permissions and rest up to you...

**Comment by ivan-hc** [comment]
I'd like to add a tinyer message, like the one I did for Termux, time ago, I've no problems with that, if you wish it

about the options names, I've not much fantasy (also "AM" was named so because I had no fantasy, at time)

**Comment by zen0bit** [comment]
Good name
In simplicity is power

Hard to forget
How was that great app called?
Am or FM?

**Comment by ivan-hc** [comment]
in the database we have an app called "m"

https://github.com/martin-azpillaga/M
