### ISSUE TITLE
New domain and new website available

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#464]
# Since now you are a part of oSoWoSo organization :handshake: 
https://am.osowoso.org

**Comment by zen0bit** [comment]
Don't know why
But i can't get am.osowoso.org to work

I will definetly solved that later...

I successfuly added my other sites to subdomains.

only am missing
(I puted wrong DNS records there)
After i figured out right ones.
I did it will some my sites
work well

Then tried am again
don't work
tried pin am to any other subdomain
works
am not

so currently I am providing test site under a.osowoso.org

PS: will try later...

**Comment by zen0bit** [comment]
Create pages in AM repo settings and try add custom domain am.osowoso.org

what github say..

Your site should be published at (am.github.io) I think
Then add am.osowoso.org

say me result..

**Comment by zen0bit** [comment]
Good to go @ivan-hc
Hopefully

**Comment by zen0bit** [comment]
I think you have to validate domain if giyhub let you... (D)iscord?

**Comment by zen0bit** [comment]
Can you please make website forthis repo? Don't set up anything create with default settings

**Comment by ivan-hc** [comment]
do some tests on https://github.com/ivan-hc/AM/tree/website, its based on "refactoring"

**Comment by zen0bit** [comment]
> do some tests on [`website`](https://github.com/ivan-hc/AM/tree/website?rgh-link-date=2024-05-02T11%3A19%3A33Z), its based on "refactoring"

I don't need to do any tests.

# I need your repository to have working website.

Without it we can't move anywhere.

So click that button in github pages.
(Choose this or any branch you like)

Only change will be added CNAME to repo (done automatically by github)

After that we can change that CNAME to what we need

But since here `isn't` working website, i can do **nothing**...

**Comment by ivan-hc** [comment]
@zen0bit I've issues here

![Istantanea_2024-05-02_20-32-51](https://github.com/ivan-hc/AM/assets/88724353/b2a33bb7-88a0-48a8-a3c4-ec3e2e5e589a)

what should I do now?

**Comment by zen0bit** [comment]
I don't say anything about putting custom domain there!

step 1. create website on https://ivan-hc.github.io/AM/ as github do if you don't fill anything

step 2. I will point am.osowoso.org domain to https://ivan-hc.github.io/AM/

step 3. Change to custom domain am.osowoso.org

You even don't done 1st step...

**Comment by ivan-hc** [comment]
should I add a file CNAME in the root of the repository or your fork?

I have to add this "_github-pages-challenge-ivan-hc.am.osowoso.org", but where?

**Comment by zen0bit** [comment]
> should I add a file CNAME in the root of the repository or your fork?
> 
> I have to add this "_github-pages-challenge-ivan-hc.am.osowoso.org", but where?

to my

**Comment by ivan-hc** [comment]
its more complicated than portable-linux-apps this practice

**Comment by zen0bit** [comment]
It's easy

don't overomplicating it

**Comment by ivan-hc** [comment]
like this? https://github.com/oSoWoSo/AM/commit/06ba09ccb446e88b4d3951d181506bde50c52a10

**Comment by zen0bit** [comment]
write me ANSWER for `_github-pages-challenge-ivan-hc.am.osowoso.org` this to discord

**Comment by ivan-hc** [comment]
I've changed the file https://github.com/oSoWoSo/AM/blob/main/CNAME on your repo, am I wrong?

**Comment by zen0bit** [comment]
> I've changed the file [oSoWoSo/AM@`main`/CNAME](https://github.com/oSoWoSo/AM/blob/main/CNAME?rgh-link-date=2024-05-02T18%3A55%3A34Z) on your repo, am I wrong?

It doesn't matter github will overwrite that automatically anyway

**Comment by zen0bit** [comment]
done
