### ISSUE TITLE
update script order

### ISSUE THREAD

**Issue by ppvnf** [ivan-hc/AM#465]
Wouldn't it make more sense if the check for new modules and installation scripts before updating the appimages? Or there is some reason for that that I am missing?

![Screenshot_20240422_123851](https://github.com/ivan-hc/AM/assets/73800734/b2138d04-68d3-4fa9-a02e-4a49d259a723)

**Comment by ivan-hc** [comment]
sure, this is one of the best improvements of the last times, see https://github.com/ivan-hc/AM/issues/410 and https://github.com/ivan-hc/AM/releases/tag/6.6

in bries, the order depends on what of these scripts is updated first (the so called "parallel updates"). Before we had to wait that the app listed first was updated to update the nex one, now they are updated all together.

**Comment by ivan-hc** [comment]
if you're talking about modules/CLI before the installation scripts, this is the sense of `-s`, not `-u`

- if you want to update the CLI and the modules,use `am -s`
- to update only tthe apps, use `am -u --apps`
- to update the apps, the CLI and the modules, use `am -u`

**Comment by ppvnf** [comment]
What I mean is when using am -u, shouldn't the order be the CLI and the modules and then the APPS? instead of first the apps?

**Comment by ivan-hc** [comment]
> What I mean is when using am -u, shouldn't the order be the CLI and the modules and then the APPS? instead of first the apps?

because they are running processes, its better to have the working one before some update on the CLI is broken.

I hope this will not happen, never... but just in case, is better to have the working modules in action before they are replaced.

This is why the order apps - modules - CLI: its for security reasons.

**Comment by ppvnf** [comment]
That makes sense, should we close this then?
