### ISSUE TITLE
New error messages.

### ISSUE THREAD

**Issue by iPooPaLot** [ivan-hc/AM#513]
This message started appearing since version 6.6.2 i think.

![Screenshot from 2024-04-26 10-44-52](https://github.com/ivan-hc/AM/assets/40178870/3ec7f15b-1a76-45a3-b1dc-b910281fd719)

**Comment by nazdridoy** [comment]
v6.6.3 has some major changes, you should reinstall AM

**Comment by ivan-hc** [comment]
Wait, I'm going downgrade all this to the previous version

**Comment by ivan-hc** [comment]
I'm sorry for the inconvenience, I suggest uninstalling and reinstalling.

I downgraded from version 6.6.3 to version 6.6.2 to solve this and other issues.

AM is still not ready for this feature. Sorry.
