### ISSUE TITLE
Installer showing errors.

### ISSUE THREAD

**Issue by iPooPaLot** [ivan-hc/AM#516]
The 6.6.2 installer is showing these errors.

![Screenshot from 2024-04-26 12-02-26](https://github.com/ivan-hc/AM/assets/40178870/449db71e-5c6e-43fc-ba10-2f57bd4cd972)

**Comment by ivan-hc** [comment]
This is because is runningh the wrong installer, see that INSTALL.1.

You must remove all the INSTALL scripts from you $HOME, then run the command again.

Also, remove
```
sudo /opt/am/remove
```

**Comment by iPooPaLot** [comment]
Even so. It is like github changed something and the installer can´t resolve download urls correctly.

![Screenshot from 2024-04-26 13-17-44](https://github.com/ivan-hc/AM/assets/40178870/dba18374-4a62-45b7-bdcd-2bc55f52409d)

**Comment by ivan-hc** [comment]
is it Fedora 40? If it is so, we can close this issue and go talk at https://github.com/ivan-hc/AM/issues/496 , there is another user with the same issue.

By my side, I've a VM of Fedora 39 and I've not faced problems like this, but its strange that two Fedora users have the same issue in downloading modules *.am at the same time.

**Comment by iPooPaLot** [comment]
> is it Fedora 40? If it is so, we can close this issue and go talk at #496 , there is another user with the same issue.
> 
> By my side, I've a VM of Fedora 39 and I've not faced problems like this, but its strange that two Fedora users have the same issue in downloading modules *.am at the same time.

Yes, Fedora 40.

**Comment by ivan-hc** [comment]
OK, let talke there then https://github.com/ivan-hc/AM/issues/496#issuecomment-2080017222
