### ISSUE TITLE
Issues re LM Studio 

### ISSUE THREAD

**Issue by thorrrr** [ivan-hc/AM#539]
HI 
Still having issues trying to get lmstudio with am 

[oh-my-zsh] Random theme 'lambda' loaded
λ ~/ am -q lm studio

 SEARCH RESULTS FOR "LM STUDIO":

◆ lmms : FL Studio® alternative that allows you to produce music with the PC.
◆ lmstudio : Experimenting with local and open-source Large Language Models.
◆ realm-studio : A tool for everything Realm.

λ ~/ am -i lmstudio
[sudo] password for dale:
 ############################################################################
 ##                                                                        ##
 ##                  START OF ALL INSTALLATION PROCESSES                   ##
 ##                                                                        ##
 ############################################################################

 ◆ "LMSTUDIO": starting installation script
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
chmod: cannot access '/opt/lmstudio/lmstudio': No such file or directory
rm: cannot remove './lmstudio.desktop': No such file or directory
rm: cannot remove './lmstudio.desktop': No such file or directory
cat: ./lmstudio.desktop: No such file or directory
cat: ./lmstudio.desktop: No such file or directory
./lmstudio: line 83: ./lmstudio: No such file or directory
./lmstudio: line 84: ./lmstudio: No such file or directory
 💀 ERROR DURING INSTALLATION, REMOVED "LMSTUDIO"!
 __________________________________________________

**Comment by ivan-hc** [comment]
it seems an URL quite protected, its called by a JS function, using "curl"/"wget" this is thestring that references to the appimage
```
    <script defer="defer" data-domain="lmstudio.ai" file-types="dmg,zip,exe,AppImage" src="https://plausible.io/js/script.file-downloads.js"></script>
```
and I can see the URL from Firefox

![Istantanea_2024-05-02_17-30-23](https://github.com/ivan-hc/AM/assets/88724353/bf320541-baeb-4fe9-942b-358a938a023f)

I need a way to obtain that url from that page

**Comment by thorrrr** [comment]
Ok cheers for update good luck

**Comment by ivan-hc** [comment]
OK, I've found this workaround
```
version=$(mkdir -p "$HOME"/.cache && cd "$HOME"/.cache && wget -rq https://lmstudio.ai 2>&1 && cat ./lmstudio.ai/static/js/main*.js | tr '"' '\n' | grep -i appimage && rm -Rf "$HOME"/.cache/lmstudio.ai)
```
tested on AppMan and between other scripts.

I'm going fix this.
