### ISSUE TITLE
Clean history

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM#560]
This can be done fairly easily just by running two commands:

`git checkout -b clean_history`
will made new branch (Not really needed)
'clean_history'
`git filter-branch --commit-filter '
  if git show -s --format=%P $GIT_COMMIT | grep -q " "; then
    skip_commit "$@";
  else
    git commit-tree "$@";
  fi' HEAD`
Will delete all commits with more parents (Merge commits)

Files stays intact...
On my pc and AM main branch done by 80sec

Here is result:
https://github.com/oSoWoSo/AM/tree/main-clean
Look at clean history

And here is my dev branch with all changes so far (hopefully)
https://github.com/oSoWoSo/AM/tree/mc%2Bcl%2Brefactor-dev
I will check that again later...

# I will continue refactoring on clean branch, but it will make our commits histories incompatible.

Run command above on your fork on REBASE on my branch...
Thanks for cooperation

**Comment by ivan-hc** [comment]
Why not to fork the main branch and upload all files there instead?

Then you can resume your changes in the description before you PR to dev.

**Comment by ivan-hc** [comment]
@zen0bit I've created another branch updated with main and dev

https://github.com/ivan-hc/AM/tree/zen0bit-refactoring

please, upload your changes (modules, APP-MANAGER and INSTALL) there.

**Comment by ivan-hc** [comment]
> @zen0bit I've created another branch updated with main and dev
> 
> https://github.com/ivan-hc/AM/tree/zen0bit-refactoring
> 
> please, upload your changes (modules, APP-MANAGER and INSTALL) there.

@zen0bit this is related to https://github.com/ivan-hc/AM/pull/552

it would be easier if you upload the changes directly into a new branch. A description about your changes is enough.
