### ISSUE TITLE
thorium not launching

### ISSUE THREAD

**Issue by someguywhostryingtohelp** [ivan-hc/AM#564]
yesterday i ran an update. I noticed that thorium wasn't launching.
I looked into it. It seems like it installed a version that doesnot exist. the latest version of thorium at this time is 123.0.6312.133 but when doing a version check using am i got this 

◆  thorium      |  123.0.6312.134  |  appimage-type2     |  27    MiB

I don't know if this is an error upstream but when I rolled back to 123.0.6312.133 everything worked fine.
I don't know where this is pull the update from but I think it is updating to i386 appimage.

**Comment by someguywhostryingtohelp** [comment]
also when I tried to launch it through terminal this is what came out

/tmp/.mount_thoriu3qd3cJ/AppRun: line 4: /tmp/.mount_thoriu3qd3cJ/usr/bin/thorium: cannot execute: required file not found

**Comment by ivan-hc** [comment]
Found the problem, the developer have uploaded a 32bit version of Thorium, so the installation script redirects on it.

**Comment by someguywhostryingtohelp** [comment]
yeah when i was rolling back I got this as the first url

Select a URL from this menu (read carefully) or press CTRL+C to abort:
-----------------------------------------------------------------------
 1) https://github.com/Alex313031/thorium/releases/download/M123.0.6312.134/Thorium_Browser_123.0.6312.134_i386.AppImage
