### ISSUE TITLE
Repology.org forbids curl requests and breaks installation scripts

### ISSUE THREAD

**Issue by sandboiii** [ivan-hc/AM#566]
Hey, I tried to install krita and had a problem with installation script. I found the source of problem repology.org forbiding curl requests. I get this output:
```bash
> curl -Ls https://repology.org/project/krita/versions
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

And it breaks the line in installation script which determines current krita version:
```bash
version=$(curl -Ls https://repology.org/project/$APP/versions | grep "newest version" | head -1 | grep -o -P '(?<=">).*(?=</a)' | sed 's/^.*>//')
```

Is there any way to avoid repology requests?

**Comment by ivan-hc** [comment]
Just noticed that this affects all all 14 scripts that are using repology. I'm gonna fix this in the next commit.

**Comment by sandboiii** [comment]
Thank you!
