### ISSUE TITLE
Cannot Install FileZilla

### ISSUE THREAD

**Issue by vincula45** [ivan-hc/AM#597]
I have been able to install FileZilla successfully using appman a number of times in the past.  

Lately this is what I get when I try to install FileZilla using appman in Debian 12:

$ appman -i filezilla
############################################################################
############################################################################

◆ "FILEZILLA": starting installation script

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
tar: filezilla-latest.tar.bz2: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
./filezilla: 21: cd: can't cd to FileZilla3
latest ./version
cp: cannot stat './share/pixmaps/filezilla.png': No such file or directory

 💀 ERROR DURING INSTALLATION, REMOVED "FILEZILLA"!

**Comment by Samueru-sama** [comment]
There was a recent change that replaced wget for curl to get the urls, however in this instance it breaks this website.

**Comment by ivan-hc** [comment]
Solved, and also updated the 32 bit version

**Comment by ivan-hc** [comment]
EDIT: just updated both the scripts using the new template

https://github.com/ivan-hc/AM/commit/3095079326e98e547c34c7282e3dccfc414b9b9b

this also solves the issue of the missing version

**Comment by Samueru-sama** [comment]
> EDIT: just updated both the scripts using the new template
> 
> [3095079](https://github.com/ivan-hc/AM/commit/3095079326e98e547c34c7282e3dccfc414b9b9b)
> 
> this also solves the issue of the missing version

The template isn't "new", only the appimages got the latest one. 

Also I sort of made a 3rd new template that is being used on i3 and the later packages that I've added, but I haven't update the appimage template to use that template because I don't know how to handle the zsync instances in those.

**Comment by ivan-hc** [comment]
@Samueru-sama "new" meaning that this template has only existed for 3 months, while the "filezilla" script had only undergone the "curl" patch (by mistake) and before this it had not been updated for 2 years. It's basically one of the very first scripts I loaded, and the installation method consisted of always reinstalling filezilla, without ever comparing versions.

@vincula45 I suggest to re-installif you have not done it already
