### ISSUE TITLE
Panic!-Please, write the name or the path of your custom application's folder? 

### ISSUE THREAD

**Issue by valtoree** [ivan-hc/AM#600]
Hi
Sorry I dont understand, I just install apps either via apt, flatpak and now am -i to install apps, so what do I add here?
Sorry if dumb question.

**Comment by ivan-hc** [comment]
You can read the list of the available apps with `am -l` and if you want to search an appname using keywords, try (for example) `am -q video editor`

To install an application is the same thing, write the lowercased name of the app you want (if it is in the list), for example:
```
am -i firefox brave-appimage chromium avidemux kdenlive
```
this will install these five apps (three web browsers and two video editors).

What is the app you're looking for?

**Comment by Samueru-sama** [comment]
> Hi Sorry I dont understand, I just install apps either via apt, flatpak and now am -i to install apps, so what do I add here? Sorry if dumb question.

Looks like you are using AppMan and it is asking you where you want your user applications to be installed. 

Just type the name of the directory in home where you want the appimages to be installed. Most people use `~/Applications`

**Comment by valtoree** [comment]
Thanks for quick reply, i usually do a 'am -u' everyday. So no app install just update and got prompted this.

**Comment by ivan-hc** [comment]
are you talking about the `--user` option or the "AppMan Mode" or "appman"?

The prompt helps you to customize the path where you want to install all the apps in your $HOME. In "AM" its called "AppMan Mode" and its how "appman" works to made non privileged users installing apps in their $HOME

**Comment by ivan-hc** [comment]
See https://github.com/ivan-hc/AM#how-to-use-am-in-non-privileged-mode-like-appman

**Comment by valtoree** [comment]
I'm taking about @ivan-hc ur github am install app. Not touched appman. No idea what that is.

**Comment by valtoree** [comment]
I've just installed ur app, as per github, "wget https://raw.githubusercontent.com/ivan-hc/AM/main/INSTALL && chmod a+x ./INSTALL && sudo ./INSTALL", then started installing apps like 'am -i appname'. Never had to write a path to custom app folders

**Comment by valtoree** [comment]
Do I find where am has installed the apps and point the folder there?

**Comment by valtoree** [comment]
Watched video it seems update script has enabled --user perhaps?

**Comment by ivan-hc** [comment]
The apps are installed in /opt

See the spoiler at https://github.com/ivan-hc/AM#differences-between-am-and-appman

**Comment by ivan-hc** [comment]
> Watched video it seems update script has enabled --user perhaps?

I stil don't understand, can you provide a screenshot or a video, so we can see what happens?

**Comment by ivan-hc** [comment]
if you see the message that "AM" is acting ad "AppMan", you have launched the command `am --user` previously.

To go back to "AM", use the command `am --system`, as suggested in the message

**Comment by valtoree** [comment]
http://0x0.st/XZ6C.mkv

**Comment by valtoree** [comment]
Never ran --user before

**Comment by valtoree** [comment]
I think its in the update script

**Comment by Samueru-sama** [comment]
> http://0x0.st/XZ6C.mkv

Alright you found a bug. For some reason AppMan is being enabled when the modules try to update.

**Comment by valtoree** [comment]
Yes installed Applications folder, then appman folder inside, and another folder modules inside that 1 and file 'options'. Nothing in modules.

**Comment by valtoree** [comment]
◆ SYNCHRONIZING "AM" VERSION --------------------------------------------------------------------------
 >>> Thank you for choosing AppMan!
--------------------------------------------------------------------------
Before proceeding with any task, write the name of the directory in which
you will install the apps, for example "Programs" or "My-apps", you can 
also choose a subfolder, for example ".local/My-apps" or a deeper path.

The destination folder will be created in /home/p70

SYNTAX: PATH/TO/DIRNAME

NOTE, any spaces or "/" at the beginning and end will be removed. If you 
decide to change your choice in the future, first remove all the programs
and then edit the ~/.config/appman/appman-config text file.
--------------------------------------------------------------------------

--------------------------------------------------------------------------
You are ready! Start installing your favorite apps locally!!
All apps will be installed in /home/p70/Applications

In case of problems, use the option "-h".
--------------------------------------------------------------------------
 ◆ "AM" IS NOW UPDATED TO THE BRAND NEW 6.8.2-2 VERSION!           

  Replacement of version --------------------------------------------------------------------------
 >>> Thank you for choosing AppMan!
--------------------------------------------------------------------------
Before proceeding with any task, write the name of the directory in which
you will install the apps, for example "Programs" or "My-apps", you can 
also choose a subfolder, for example ".local/My-apps" or a deeper path.

The destination folder will be created in /home/p70

SYNTAX: PATH/TO/DIRNAME

NOTE, any spaces or "/" at the beginning and end will be removed. If you 
decide to change your choice in the future, first remove all the programs
and then edit the ~/.config/appman/appman-config text file.
--------------------------------------------------------------------------

--------------------------------------------------------------------------
You are ready! Start installing your favorite apps locally!!
All apps will be installed in /home/p70/Applications

In case of problems, use the option "-h".
--------------------------------------------------------------------------
6.8.2-2 currently in use, COMPLETED!

 See https://github.com/ivan-hc/AM/commits/main

-----------------------------------------------------------------------------
 >> END OF ALL PROCESSES <<

**Comment by ivan-hc** [comment]
The issue is related to this function in sync.am
```
function _sync_amcli() {
	echo "-----------------------------------------------------------------------------"
  	_completion_lists
  	rm -f /opt/am/appman
  	if test -f "$AMCLIPATH"; then
		CURRENT_AM_VERSION=$("$AMCLIPATH" -v)
	else
		AMCLIPATH="/opt/am/APP-MANAGER"
		CURRENT_AM_VERSION=$("$AMCLIPATH" -v)
	fi
	echo -ne '\n ◆ SYNCHRONIZING "'"$(echo "$AMCLI" | tr a-z A-Z)"'" VERSION '"$CURRENT_AM_VERSION"'...\r'; sleep 1
  	rm -R -f "$AMPATH"/.cache/* 1>/dev/null; cd "$AMPATH"/.cache || return
  	if [ "$CLI" == am ] 2>/dev/null; then
  		wget -q "$AMREPO"/APP-MANAGER && chmod a+x ./APP-MANAGER && chmod 777 ./APP-MANAGER
  		cd ..
  		echo y | mv "$AMPATH"/.cache/APP-MANAGER "$AMCLIPATH"
  	else
  		wget -q "$AMREPO"/APP-MANAGER -O appman && chmod a+x ./"$AMCLI"
  		cd ..
  		mv "$AMPATH"/.cache/"$AMCLI" "$AMCLIPATH"
  	fi
  	if [ ! "$CURRENT_AM_VERSION" == "$("$AMCLIPATH" -v)" ] ; then
 		echo -ne ' A new release of "'"$(echo "$AMCLI" | tr a-z A-Z)"'" is available, please wait...\r'
 		echo -e ' ◆ "'"$(echo "$AMCLI" | tr a-z A-Z)"'" IS NOW UPDATED TO THE BRAND NEW '"$("$AMCLIPATH" -v)"' VERSION!           \n\n  Replacement of version '"$CURRENT_AM_VERSION"' currently in use, COMPLETED!'
 		echo -e "\n See https://github.com/ivan-hc/AM/commits/main\n"
 	else
 		echo -e ' ◆ "'"$(echo "$AMCLI" | tr a-z A-Z)"'" IS ALREADY UPDATED, CURRENT VERSION '"$CURRENT_AM_VERSION"''
 		echo -e "\n See https://github.com/ivan-hc/AM/commits/$AMBRANCH\n"
 	fi
}
```

for some reason, it launches "appman" for the first time.

**Comment by ivan-hc** [comment]
Have you got a file named "appman" in /opt?

**Comment by valtoree** [comment]
I see no "appman" file in opt.

**Comment by ivan-hc** [comment]
OK, I can reproduce the issue now

**Comment by ivan-hc** [comment]
this is a change I've done yesterday
```
	if test -f "$AMCLIPATH"; then
		CURRENT_AM_VERSION=$("$AMCLIPATH" -v)
	else
		AMCLIPATH="/opt/am/APP-MANAGER"
		CURRENT_AM_VERSION=$("$AMCLIPATH" -v)
	fi
```
and now I've fixed it 
```
CURRENT_AM_VERSION=$("$AMCLIPATH" -v)
```
I was working on a way to made AM updating itself in AppMan mode... I've not tested without AppMan

**Comment by valtoree** [comment]
Awesome ty 🙏🙇 love ur work.
