### ISSUE TITLE
AM asking for a directory to store local apps. 

### ISSUE THREAD

**Issue by musicfunfan** [ivan-hc/AM#612]
So i updated am today. And i get this massage on the terminal. 
![screenshot](https://github.com/ivan-hc/AM/assets/86926443/cb6206de-0bfb-48e0-b415-ec003e956da6)
I do not understand what is the purpose of this file. I just Added in the file path ``$HOME/Applications`` but i do not know. What is the purpose of this directory?

**Comment by Samueru-sama** [comment]
Omg not again lol, we had this issue a week ago or so iirc

**Comment by musicfunfan** [comment]
So this is a bug ? Because i do not use ``appman``. I use [topgrade](https://github.com/topgrade-rs/topgrade) and i do not know what command that use to update AM. 
According to [this](https://github.com/topgrade-rs/topgrade/blob/main/src/steps/os/linux.rs#L580).
![screenshot](https://github.com/ivan-hc/AM/assets/86926443/3c1b1273-64e9-480c-bb7c-fc590b8403b1)
The command topgrade runs for am is ``am -u`` so... I thing this is a general problem. 
This is what i have on my ``$HOME/Applicatioons`` Directory. 
![screenshot](https://github.com/ivan-hc/AM/assets/86926443/dc9deaef-c4a5-4a4b-9bf8-eaa07dcf8f26)
But i do not thing that i ever had appman installed. So this is a bug?

**Comment by Samueru-sama** [comment]
Yes it is a bug, appman and am are the same thing, just different functions inside the APP-MANAGER script.

**Comment by musicfunfan** [comment]
Ok, i was just looking if i did something wrong. Because ,most of the time... i was doing something wrong 😉. Any way. Thank you for the feedback...  I thing the appimages updated so more or less AM still working.

**Comment by ivan-hc** [comment]
Please, can you remove the directory `$HOME/.config/appman` and update "AM" again?

I need to understand if this is a problem that affects who switches from from a previous release to 6.8.4 only or it still happens.



PS: the behaviour you faced is the same I've seen when trying to update "AM" with `am -u` or `am -s`, it seems that `-s` does not like to be included as a command in external modules, as it is in update.am... you've said that this is happened with topgrade.

**Comment by ivan-hc** [comment]
I've just updated everything using topgrade and everything works without problems... so this bug is related to a previous version switching to the latest one. New users of "AM" should not face this issue.

**Comment by ivan-hc** [comment]
I think I should merge update.am and sync.am into APP-MANAGER, so we have two less modules and the essential ones related to the updates should be integrated in the CLI

**Comment by musicfunfan** [comment]
That was happening on the work machine. Now i am at home and i do not have this machine here. I will try to update the system here and see what happens.

**Comment by ivan-hc** [comment]
I'm here, let me know

**Comment by musicfunfan** [comment]
So interesting enough the home machine. The bug did not happened. This is out put. 
![Am bug](https://github.com/ivan-hc/AM/assets/86926443/e079eb5e-e9a7-44d4-ad8c-e5fd0586679a)

I do not know why. Work machine has Linux mint LTS i do not run updates every time. Home machine is archlinux i run updates more often i do not know if this matter i can not think a way that it should.

**Comment by ivan-hc** [comment]
have you got a directory `$HOME/.config/appman`?

if yes, remove it and try to update again

**Comment by musicfunfan** [comment]
Nope, i do not. 
![appman](https://github.com/ivan-hc/AM/assets/86926443/05242401-d0e6-45dd-8393-8a120abef0f8)

**Comment by ivan-hc** [comment]
so you should test this on the other machine then

**Comment by musicfunfan** [comment]
Yea, i will be on this machine tomorrow. I hope i will remember to test it.

**Comment by ivan-hc** [comment]
In ther meantime the new 6.9 is out https://github.com/ivan-hc/AM/releases/tag/6.9

**Comment by musicfunfan** [comment]
I remember to test it. This is the output.
```bash
❯ ls $HOME/.config/appman
appman-config

~ 
❯ rm -r $HOME/.config/appman

~ 
❯ am -u
-----------------------------------------------------------------------------
 "AM" CAN MANAGE UPDATES FOR THE FOLLOWING PROGRAMS:

 ◆ fastfetch https://github.com/fastfetch-cli/fastfetch/releases/download/2.14.0/fastfetch-linux-amd64.tar.gz
 ◆ joplin 2.14.22

 All self-updatable programs are excluded
-----------------------------------------------------------------------------
 >> START OF ALL PROCESSES <<
-----------------------------------------------------------------------------
 ◆ JOPLIN is updated, 1 seconds elapsed!
 ◆ FASTFETCH is updated, 3 seconds elapsed!
-----------------------------------------------------------------------------
 Nothing to do here!
-----------------------------------------------------------------------------
-----------------------------------------------------------------------------
 Checking for changes of the installation scripts in the online database...
 ◆ Changed https://github.com/ivan-hc/AM/blob/main/programs/x86_64/fastfetch
 ◆ Changed https://github.com/ivan-hc/AM/blob/main/programs/x86_64/joplin
-----------------------------------------------------------------------------
 Check for updates in modules...
 ◆ Updating database.am...
 ◆ Updating devtools.am...
 ◆ Updating download.am...
 ◆ Updating files.am...
 ◆ Updating help.am...
 ◆ Updating install.am...
 ◆ Updating launcher.am...
 ◆ Downloading management.am (not previously installed)...
 ◆ Updating sandboxes.am...
 ◆ Updating template.am...
-----------------------------------------------------------------------------

 ◆ "AM" IS NOW UPDATED TO THE BRAND NEW 6.9 VERSION!           

  Replacement of version 6.8.4 currently in use, COMPLETED!

 See https://github.com/ivan-hc/AM/commits/main

-----------------------------------------------------------------------------
 >> END OF ALL PROCESSES << 
-----------------------------------------------------------------------------
```
So all good ?

**Comment by ivan-hc** [comment]
everything perfect... apart from the fastfetch version

**Comment by musicfunfan** [comment]
Yea, i saw fastfetch version do not make senses... I just forget to mention it. Anyway. This is issue can be closed now. :+1:

**Comment by ivan-hc** [comment]
```
am -c
am -f
```
I've fixed that ugly version in thye last PR
