### ISSUE TITLE
Sometimes running am -i on a local script fails the first time

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/AM#653]
Hey, this is an issue that I've noticed has been happening ever since I made the mpv appimage: 

![image](https://github.com/ivan-hc/AM/assets/36420837/b27c1f8e-8ba0-4484-b278-450731f925e9)

Sometimes am tires to pull from the database instead of using the script I'm telling it use, if I didn't rename the script to have the `.sh` at the end of the name, it would have used the existing `cpu-x` script on the database instead of the local one that I'm telling it to use. 

(am is appman btw).

**Comment by Samueru-sama** [comment]
@ivan-hc I'm testing cpu-x again because the dev said to have fixed the issue, but it doesn't look like it works 😭

**Comment by ivan-hc** [comment]
I'm testing this ar appman in normal mode, no issue here

![Istantanea_2024-06-11_17-05-15 png](https://github.com/ivan-hc/AM/assets/88724353/58ef4e9a-f601-4be4-9151-2707fde394da)

**Comment by Samueru-sama** [comment]
> I'm testing this ar appman in normal mode, no issue here
> 
> ![Istantanea_2024-06-11_17-05-15 png](https://private-user-images.githubusercontent.com/88724353/338639886-58ef4e9a-f601-4be4-9151-2707fde394da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTg4MTcsIm5iZiI6MTcxODExODUxNywicGF0aCI6Ii84ODcyNDM1My8zMzg2Mzk4ODYtNThlZjRlOWEtZjYwMS00YmU0LTkxNTEtMjcwN2ZkZTM5NGRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE1MDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTI2MWExZjE0MTBjNmZjYWUxODJlOTgxNDU0Mjk3MDZhZjFiMDA2NDIyNzZmYjQwNzk3ZDFjNDk3YjAyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xx1jsKkBxUQSktT1EiTZayOW4WNrfH0LCW0uo2hrioY)

The issue happens when I give it a relative path instead of a full path: 

![image](https://github.com/ivan-hc/AM/assets/36420837/a2353fda-c82d-423d-9ae5-1ad036ddc433)

But it only happens the first time after I give it the `./cpu-x.sh` the second time it does pick up the file. 

(btw that ln error in the screenshot is because I removed the cpu-x directory instead of running `am -r`)

**Comment by ivan-hc** [comment]
what if you name it cpu-x instead of cpu-x.sh?

**Comment by Samueru-sama** [comment]
How does `am -i` know when to use a local file vs pulling from the repo?

**Comment by ivan-hc** [comment]
```
			# Various cases that may occur during installation (for example if you use a third-party repository)
			if test -f $APPSPATH/$arg/remove; then
				echo " ◆ $(echo '"'$arg'"' | tr a-z A-Z): app already installed previously! Try removing it."
			else
				if test -f ./$arg 2> /dev/null; then
					mkdir -p "$AMCACHEDIR"/tmp; cp ./$arg "$AMCACHEDIR"/tmp/$arg; cd "$AMCACHEDIR" || return; mv ./tmp/$arg ./$arg; rmdir ./tmp
					_install_arg
				elif test -f $arg 2> /dev/null; then
					path2arg=$(echo "$arg")
					arg=$(echo "$path2arg" | sed 's:.*/::')
					cd "$AMCACHEDIR" || return; mkdir -p tmp; cd tmp || return; cp $path2arg ./$arg; cd ..; mv ./tmp/$arg ./$arg; rmdir ./tmp
					_install_arg
				elif test -f "$AMPATH/neodb"; then
					rm -R -f "$AMCACHEDIR/multirepo-args"
					MULTIREPO=$(cat "$AMPATH/neodb" | grep "Source=" | sed 's/Source=//g')
					for anyrepo in $MULTIREPO; do
						if curl --output /dev/null --silent --head --fail $anyrepo/$arg  1>/dev/null; then
							echo "$anyrepo" >> "$AMCACHEDIR/multirepo-args"
						fi
					done
					if test -f "$AMCACHEDIR/multirepo-args"; then
						anyrepoargs=$(cat "$AMCACHEDIR/multirepo-args" 2>/dev/null | wc -l)
						if [ $anyrepoargs -gt 0 ]; then
							if curl --output /dev/null --silent --head --fail $APPSDB/$arg  1>/dev/null; then
								echo "$APPSDB" >> "$AMCACHEDIR/multirepo-args"
							fi
							anyrepoargall=$(cat "$AMCACHEDIR/multirepo-args" 2>/dev/null | wc -l)
							if [ $anyrepoargall == 1 ]; then
								cd "$AMCACHEDIR" || return; mkdir -p tmp; cd tmp || return; wget -q "$(cat "$AMCACHEDIR/multirepo-args" | head -1)/$arg"; cd ..; mv ./tmp/$arg ./$arg; rmdir ./tmp
								rm -R -f "$AMCACHEDIR/multirepo-args"
								_install_arg
							else
								echo -e "\n ◆ FOUND $(echo '"'$arg'"' | tr a-z A-Z) FROM MULTIPLE SOURCES:\n" &&
								printf " Select a URL from this menu (read carefully) or press CTRL+C to abort:\n\n"; sleep 1;
								select d in $(cat "$AMCACHEDIR/multirepo-args"); do test -n "$d" && break; echo ">>> Invalid Selection"; done
								cd "$AMCACHEDIR" || return; mkdir -p tmp; cd tmp || return; wget -q "$d/$arg"; cd ..; mv ./tmp/$arg ./$arg; rmdir ./tmp
								rm -R -f "$AMCACHEDIR/multirepo-args"
								_install_arg
							fi
						elif curl --output /dev/null --silent --head --fail $APPSDB/$arg  1>/dev/null; then
							cd "$AMCACHEDIR" || return; mkdir -p tmp; cd tmp || return; wget -q $APPSDB/$arg; cd ..; mv ./tmp/$arg ./$arg; rmdir ./tmp
							rm -R -f "$AMCACHEDIR/multirepo-args"
							_install_arg
						else
							echo ' 💀 ERROR: "'$arg'" does NOT exist in the database, see "'$AMCLI' -l"'
						fi
					elif curl --output /dev/null --silent --head --fail $APPSDB/$arg  1>/dev/null; then
						cd "$AMCACHEDIR" || return; mkdir -p tmp; cd tmp || return; wget -q $APPSDB/$arg; cd ..; mv ./tmp/$arg ./$arg; rmdir ./tmp
						_install_arg
					else
						echo ' 💀 ERROR: "'$arg'" does NOT exist in the database, see "'$AMCLI' -l"'
					fi
				elif curl --output /dev/null --silent --head --fail $APPSDB/$arg  1>/dev/null; then
					cd "$AMCACHEDIR" || return; mkdir -p tmp; cd tmp || return; wget -q $APPSDB/$arg; cd ..; mv ./tmp/$arg ./$arg; rmdir ./tmp
					_install_arg
				else
					echo ' 💀 ERROR: "'$arg'" does NOT exist in the database, see "'$AMCLI' -l"'
				fi
			fi
```

**Comment by ivan-hc** [comment]
it should work exactly as first case
```
			# Various cases that may occur during installation (for example if you use a third-party repository)
			if test -f $APPSPATH/$arg/remove; then
				echo " ◆ $(echo '"'$arg'"' | tr a-z A-Z): app already installed previously! Try removing it."
			else
				if test -f ./$arg 2> /dev/null; then
					mkdir -p "$AMCACHEDIR"/tmp; cp ./$arg "$AMCACHEDIR"/tmp/$arg; cd "$AMCACHEDIR" || return; mv ./tmp/$arg ./$arg; rmdir ./tmp
					_install_arg
```

**Comment by Samueru-sama** [comment]
I really don't know why this happens then: 

![image](https://github.com/ivan-hc/AM/assets/36420837/af96ba06-f8ab-41cd-a4b2-f8dca0736860)

I thought that the issue was that I was using `./cpu-x.sh` and am interpreted that as `././cpu-x.sh` so I tested just putting `cpu-x.sh` without the `./` and it still fails the first time for some reason.

**Comment by Samueru-sama** [comment]
Alright I began testing all the releases from the last 2 weeks. 

So I removed appman and replaced it for version 6.7 and up.

After I did this the issue no longer happens, even with the latest version 💀 so likely I fucked some module, or something got borked when appman updated back then. 

I'll be closing this, hopefully the issue doesn't show up again.

**Comment by Samueru-sama** [comment]
Reopening this.

I took this screenshot when I was editing the brave scripts:

![bug](https://github.com/ivan-hc/AM/assets/36420837/3143874e-84df-4d5f-b580-a30b21b337ec)

**Comment by ivan-hc** [comment]
brave? were they not ok?

**Comment by Samueru-sama** [comment]
It happens with any script: 

![image](https://github.com/ivan-hc/AM/assets/36420837/d6428408-c857-4fbf-8aba-7bb5672a5471)

I add the `.sh` because otherwise am will pull the existing script instead of the local one.

**Comment by ivan-hc** [comment]
I'm not sure on why all tests in the PR are a failure, however to drag/drop the script always works in this case.

I think I give up this time.

**Comment by Samueru-sama** [comment]
Thats ok, I will have a look at how the whole install module works

**Comment by ivan-hc** [comment]
if not to solve this issue, function will help to understand more how this module works.

**Comment by ivan-hc** [comment]
@Samueru-sama a tip: since the module uses the "select" command, SHELL have not an alternative for that.

This is why this, but also the script to install "wine" are BASH scripts.
