### ISSUE TITLE
Linux Tools

### ISSUE THREAD

**Issue by GeoBoi254** [ivan-hc/AM#658]
Bat
https://github.com/sharkdp/bat/releases

Bottom
https://github.com/ClementTsang/bottom/releases

Cheat
https://github.com/cheat/cheat/releases

Dust
https://github.com/mr-karan/doggo/releases

Eza
https://github.com/eza-community/eza/releases

Fd
https://github.com/sharkdp/fd/releases

Fzf
https://github.com/junegunn/fzf/releases

Gping
https://github.com/orf/gping/releases

Lsd
https://github.com/lsd-rs/lsd/releases

Procs
https://github.com/dalance/procs/releases

Ripgrep/Ripgrep-all
https://github.com/BurntSushi/ripgrep/releases
https://github.com/phiresky/ripgrep-all/releases

**Comment by Samueru-sama** [comment]
Ok this might take a while.

**Comment by Samueru-sama** [comment]
Btw for `dust` you linked a different project named doggo? Is that the right project?

**Comment by Samueru-sama** [comment]
The scripts are all written now, with the exception of `dust` as I'm not sure if that is the right application. @GeoBoi254 

Sorry for the constant bumping @ivan-hc just letting you know so you don't start doing the scripts as well.

**Comment by ivan-hc** [comment]
> Sorry for the constant bumping

Really I don't know how to thank you

**Comment by GeoBoi254** [comment]
> The scripts are all written now, with the exception of `dust` as I'm not sure if that is the right application. @GeoBoi254
> 
I didn't realize that I linked the wrong project.
Here's the actual `dust` link
https://github.com/bootandy/dust/releases

**Comment by Samueru-sama** [comment]
> > The scripts are all written now, with the exception of `dust` as I'm not sure if that is the right application. @GeoBoi254
> 
> I didn't realize that I linked the wrong project. Here's the actual `dust` link https://github.com/bootandy/dust/releases

Alright, that means doggo doesn't get added right?

> I also want to ask if you package `musl` binaries.

For this I think we will need a new "category" named `x86_64-musl` for example. As I cannot change the name of `$APP` to have musl as that makes them non friendly on the terminal `bat` would be `bat-musl` for example.

That will depend on what @ivan-hc says. But this basically means that database needs to have a new entry and I don't wanna do that 😅 (I can add the musl binaries, but I don't wanna make the changes to add a new database)

Also I don't know how much musl is in the scope of AM, as appimages do not work in musl distros to begin with. 

>Really I don't know how to thank you

~~50 euro~~

Kidding aside, I will need your help when I start doing the new sandboxing, like I know what needs to be done and I will write the script that makes the directories, checks the env variables, copies files, creates the wrapper scripts, etc. What I'm not very sure right now is how to make all of that interact with am.  The recent bug I had where am wouldn't pick a local script sometimes really left me baffled lol.

**Comment by GeoBoi254** [comment]
> Alright, that means doggo doesn't get added right?

You can add doggo, they have the binaries.

> That will depend on what @ivan-hc says. But this basically means that database needs to have a new entry and I don't wanna do that 😅 (I can add the musl binaries, but I don't wanna make the changes to add a new database)

I wanted to ask since I found a project with only a musl binary and some deb files for desktop.

**Comment by Samueru-sama** [comment]
> > Alright, that means doggo doesn't get added right?
> 
> You can add doggo, they have the binaries.
> 
> > That will depend on what @ivan-hc says. But this basically means that database needs to have a new entry and I don't wanna do that 😅 (I can add the musl binaries, but I don't wanna make the changes to add a new database)
> 
> I wanted to ask since I found a project with only a musl binary and some deb files for desktop.

Do you plan on using that musl binary?

**Comment by ivan-hc** [comment]
> Also I don't know how much musl is in the scope of AM, as appimages do not work in musl distros to begin with.

You can add both in a script like the one you did for mpv, so the user will choose. No difference for me.

> I will need your help when I start doing the new sandboxing

OK

**Comment by Samueru-sama** [comment]
> I wanted to ask since I found a project with only a musl binary and some deb files for desktop.

Throw the link anyway, the fact that isn't musl doesn't mean that it doesn't work on glibc distro. As those are usually statically linked.

**Comment by GeoBoi254** [comment]
> Throw the link anyway, the fact that isn't musl doesn't mean that it doesn't work on glibc distro. As those are usually statically linked.

Zoxide
https://github.com/ajeetdsouza/zoxide/releases

**Comment by ivan-hc** [comment]
Also, see what is the better one... I don't know much about the difference between the two. You can also write one for the best of the two. If musl is better than glibc, go for musl.

**Comment by Samueru-sama** [comment]
> Also, see what is the better one... I don't know much about the difference between the two. You can also write one for the best of the two. If musl is better than glibc, go for musl.
> 
> EDIT: I wrote more than 60 AppImage packages, and for me this GLIBC compatibility is a pain, always.

If the musl is static, one should always try to use the musl binary, you determine it is static by running `ldd ./binaryname` and it should tell you that.

Those can work on any distro basically, and musl is much smaller than glibc so that helps get their size down. 

Linking glibc statically is a pain on the other hand iirc.

**Comment by Samueru-sama** [comment]
Fancy 👀

![image](https://github.com/ivan-hc/AM/assets/36420837/036ba0c5-a92f-4846-bf57-06c70275185e)

**Comment by GeoBoi254** [comment]
Bat Extras
https://github.com/eth-p/bat-extras/releases

Forgot this one.

**Comment by Samueru-sama** [comment]
> Bat Extras https://github.com/eth-p/bat-extras/releases
> 
> Forgot this one.

Ok, will do it later.

**Comment by Samueru-sama** [comment]
> Bat Extras https://github.com/eth-p/bat-extras/releases
> 
> Forgot this one.

Alright I made the PR adding it. For future apps open a new issue btw.
