### ISSUE TITLE
Desktop file of "ProtonUp-QT" has wrong exec line

### ISSUE THREAD

**Issue by Ciberbago** [ivan-hc/AM#672]
The desktop file responsible of making the app show on app drawer or menus does not work. Analyzing what could be the culprit, I see the exec line is:

`Exec=net.davidotek.pupgui2`

I changed it to:

`Exec=protonup-qt`

And now it shows in the app menu and it works fine.

I'm not really sure where to submit the issue, please forgive me if this is the wrong place.

And by the way, thank you for your work. I discovered your program just a few days ago and I love it.

**Comment by ivan-hc** [comment]
Thank you, just fixed and updated the script.
