### ISSUE TITLE
Option to skip _patch_bashrc_and_profile #705

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/AM#706]
I would love an option to have the `APP-MANAGER` script skip the function `_patch_bashrc_and_profile` where the script writes the following to `~/.bashrc` (and other dotfiles):

```shell
export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed s/.$//)
export PATH=$PATH:$HOME/.local/bin
```

Personally, I don't like anything touching my bash dotfiles and prefer to manage my `PATH` manually via my own dotfiles.

Any option to disable that would be great. I don't know if you'd prefer an environment variable to control it like `[[ -z "${APPMAN_SKIP_PATCH_BASHRC_AND_PROFILE:-} ]] && _patch_bashrc_and_profile` or a value in the `appman-config` config file.

---

Unrelated to this, I just want to say I love `appman`. I had ignored AppImages due to the lack of a package management command line tool. Thank you so much for this. This plus `AppImaGen` and `ArchImage` are great. I very much appreciate it.

_Originally posted by @rvenutolo in https://github.com/ivan-hc/AM/discussions/705_

**Comment by Samueru-sama** [comment]
I think the default behavior should be like this: 

```
if ! echo "$PATH" | grep .local/bin; then
    function_to_patch
fi

```

Also do we have to patch the bashrc? I'm a zsh user, on zsh you only have to add `$HOME/.local/bin` to `zprofile`, adding it to zshrc would cause  `$HOME/.local/bin` to repeat in PATH the second time you open a terminal window.

**Comment by Samueru-sama** [comment]
Also worth mentioning that adding `$HOME/.local/bin` to PATH is job of the distribution as detailed in the XDG Base Dir specification: 

[`User-specific executable files may be stored in $HOME/.local/bin. Distributions should ensure this directory shows up in the UNIX $PATH environment variable, at an appropriate place.` ](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

So yeah I think we should just give a warning and ask the user if they want to patch their `.profile`/`.bash_profile`.

**Comment by ivan-hc** [comment]
@Samueru-sama I think you are absolutely right.

I would like to stop patching configuration files, and I would like to delegate everything to the README. It's not "AppMan" who should handle them.

I want to disable the function, or at least I would like an option that can solve the problems.

**Comment by Samueru-sama** [comment]
> @Samueru-sama I think you are absolutely right.
> 
> I would like to stop patching configuration files, and I would like to delegate everything to the README. It's not "AppMan" who should handle them.
> 
> I want to disable the function, or at least I would like an option that can solve the problems.

In that case we simply issue a warning and ask if the user would like that appman patches their `.bash_profile` or `.profile`

**Comment by ivan-hc** [comment]
we must go talk at https://github.com/ivan-hc/AM/pull/707

**Comment by Samueru-sama** [comment]
@rvenutolo let us know if this works for you.

**Comment by rvenutolo** [comment]
This should work for me. Thanks very much.
