### ISSUE TITLE
Appimages

### ISSUE THREAD

**Issue by sbucek** [ivan-hc/AM#712]
popcorn-desktop
[https://github.com/popcorn-official/popcorn-desktop/releases](https://github.com/popcorn-official/popcorn-desktop/releases)

oh-my-git
[https://blinry.itch.io/oh-my-git](https://blinry.itch.io/oh-my-git)

anything-llm
[https://useanything.com/download](https://useanything.com/download)

Alexandria
[https://github.com/btpf/Alexandria/releases](https://github.com/btpf/Alexandria/releases)

**Comment by ivan-hc** [comment]
I can't upload oh-my-git, they use a dynamic download URL that looks like this:

https://itchio-mirror.cb031a832f44726753d6267436f3b414.r2.cloudflarestorage.com/build/597795/2298857-archive-default?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=3edfcce40115d057d0b5606758e7e9ee%2F20240623%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240623T121915Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=ea1965ab4e11ba11787a4ff2214effc417284d4a00cb384633f8e13ec29fd8c6

This is not a static one, it may change in minutes or seconds. Sorry.

**Comment by ivan-hc** [comment]
Created the installation script for oh-my-git... finally
