### ISSUE TITLE
App

### ISSUE THREAD

**Issue by sbucek** [ivan-hc/AM#713]
exodus-desktop-wallet
[https://www.exodus.com/download/](https://www.exodus.com/download/)

Tipp10
[https://www.tipp10.com/en/download/getfile/2/](https://www.tipp10.com/en/download/getfile/2/)

Goland
[https://www.jetbrains.com/go/download/#section=linux](https://www.jetbrains.com/go/download/#section=linux)

**Comment by ivan-hc** [comment]
- About Exodus, I cannot detect it usng "curl" or "wget", "curl" is able to detect the page, but URLs are deeply hidden into a JS or CSS file;
- Tipp10 is also hidden into a JS call, we need to search another source for this, if available;
- Goland, I need at least a source to detect the right file to download, the download page at https://www.jetbrains.com/go/download/download-thanks.html?platform=linux redirects to https://download-cdn.jetbrains.com/go/goland-2024.1.4.tar.gz , a URL that has not a root, it does not work as https://download-cdn.jetbrains.com/go and not as https://download-cdn.jetbrains.com

**Comment by ivan-hc** [comment]
So the issue here is the way we should detect the exact file, the above are really hidden, maybe I should check external sources for them... for example the AUR, if they are linked there.

**Comment by ivan-hc** [comment]
Exodus and Goland are available on the AUR, I can easily detect them from there:
- https://aur.archlinux.org/packages/exodus
- https://aur.archlinux.org/packages/goland

I've not found an alternative source for tipp10

**Comment by sbucek** [comment]
Found https://download-cf.jetbrains.com/go/goland-2024.1.4.tar.gz on  aur page. 

Tipp10 has an online versions well I've found so this can be skipped. Great effort, replaced almost all my aur packages with AM , great effort, thank you!

**Comment by ivan-hc** [comment]
UPDATE: "tipp10" is in the official repository of Arch Linux https://archlinux.org/packages/extra/x86_64/tipp10/

I'm not sure that this will work on old distributions, also the best way would be to create an appimage for this.

> Found https://download-cf.jetbrains.com/go/goland-2024.1.4.tar.gz on aur page.

Yes, I've noticed this
 
> Tipp10 has an online versions well I've found so this can be skipped.

:+1: great! However I've seen the structure of the package, it seems to be  a standalone one that has been injected in Arch Linux, see the content of the package https://archlinux.org/packages/extra/x86_64/tipp10/ no library added

> Great effort, replaced almost all my aur packages with AM , thank you!

:heart:

**Comment by ivan-hc** [comment]
>  replaced almost all my aur packages with AM , thank you!

Fun fact, I'm going uploading the ones from AUR xD

**Comment by ivan-hc** [comment]
There was a time when I had dozens of them looking for a version or file to download from the AUR, but then I noticed that they were often removed or renamed, forcing me to edit the installation script over and over again.

I then came to the conclusion that AUR is not reliable from this point of view.

But I have to admit that this method relies on the work of other people, the ones who maintain the PKGBUILD, when "AM" is also a package manager, which should mostly rely on official sources, and that's what I prefer to do.

This time I'll make an exception. I hope the AUR doesn't fail us again in the future.

**Comment by ivan-hc** [comment]
The time I fix the created scripts and I'll merge

**Comment by ivan-hc** [comment]
Exodus rejects the wget calls

**Comment by ivan-hc** [comment]
However, it works with wget2

**Comment by ivan-hc** [comment]
They have implemented some usr agent filtering in their server... dammit!

**Comment by ivan-hc** [comment]
I've solved with a trick
```
if wget --version | head -1 | grep -q ' 1.'; then
	wget --user-agent="Mozilla/5.0" "$version" || exit 1
else
	wget "$version" || exit 1
fi
```
