### ISSUE TITLE
Sandbox problems due to an incompatible Aisap release: workaround!

### ISSUE THREAD

**Issue by ivan-hc** [ivan-hc/AM#745]
Due to recent changes in Aisap https://github.com/mgord9518/aisap/commit/2ac589448f212b9b17cbed87c740fec98458283f users using sandboxes may have issues like this:

![Istantanea_2024-07-02_01-45-30 png](https://github.com/ivan-hc/AM/assets/88724353/c4db137e-3185-4064-8cf0-a42d8adaf361)

in case [the upstream](https://github.com/mgord9518/aisap) does not fixes this and no patch has been done in the [sandboxes.am](https://github.com/ivan-hc/AM/blob/main/modules/sandboxes.am) module, use my fork as a workaround

https://github.com/ivan-hc/aisap

this is a snapshot of the still compatible release.

-----------------------------------------------------------
# Proceeding in three steps
##### *NOTE, we support the Aisap project and promote its use, consider this post as a temporary workaround.*

To quick workaround this issue, we can proceed in three steps that we can summarize in a single command:

For "AM"
```
echo y | am lock aisap && wget -q "$(curl -Ls https://api.github.com/repos/ivan-hc/aisap/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | head -1)" -O aisap && chmod a+x aisap && mv aisap /opt/aisap/aisap
```
For "AppMan"
```
echo y | appman lock aisap && wget -q "$(curl -Ls https://api.github.com/repos/ivan-hc/aisap/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | head -1)" -O aisap && chmod a+x aisap && mv aisap "$HOME/$(cat $HOME/.config/appman/appman-config | sed 's:/*$::')/aisap/aisap"
```

**Below are the three steps performed by the commands above, one by one**:

-----------------------------------------------------------

### 1. Prevent aisap from being updated
For "AM"
```
am lock aisap
```
For "AppMan"
```
appman lock aisap
```
this step requires to be confirmed with a "Y"

-----------------------------------------------------------

### 2. Download the AppImage of "aisap" from my fork
```
wget -q "$(curl -Ls https://api.github.com/repos/ivan-hc/aisap/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | head -1)" -O aisap
chmod a+x aisap
```

-----------------------------------------------------------

### 3. Move the fallback "aisap" AppImage to the "$APPSPATH/aisap" directory
For "AM"
```
mv aisap /opt/aisap/aisap
```
For "AppMan"
```
mv aisap "$HOME/$(cat $HOME/.config/appman/appman-config | sed 's:/*$::')/aisap/aisap"
```

-----------------------------------------------------------

# Conclusions
Use this workaround as a temporary system.

Depending on how the new versions of Aisap are released, we will act accordingly.

We apologize for the inconvenience.

@ivan-hc @Samueru-sama

**Comment by Samueru-sama** [comment]
>Depending on how the new versions of Aisap are released, we will act accordingly.

I don't like the sound of this.
