### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by RENANZG** [ivan-hc/AM#783]
AppImage are cool! Your project is cool! 

I noticed your recent updates, which I found very interesting. I saw that you made excellent documentation on the main website and on github. I initially discovered your project through the scripts, which greatly simplify the installation of AppImages, making it particularly advantageous for Debian users, live systems and test purpuses.

An AppImage is a self-contained file that operates independently, requiring no additional dependencies and only needing sudo for making it executable. This portability makes it ideal for use in live systems and environments where software installation or modification is restricted or temporary. Moreover, using AppImages with heavyweight intermediary solutions like Snap or Flatpak is unnecessary, along with reconsidering potential sources that may be compromised.

Managing multiple AppImages individually for desktop integration, updates, or removal isn't practical, which is where scripts come in handy. However, scripting can be challenging due to the diversity of download sources, architectures, and URL formats, especially when it comes to extracting AppImages and creating desktop entries (the trickiest part being the desktop icon creation, hehe).  Dealing with application isolation (Firejail) by user or sudo is also complex, I see the topic "How to use 'AM' in non-privileged mode, like 'AppMan' ".

I'm still reflecting on the sandbox and icons issues (the hardest part, hehe). For now I made a simpler "independent" script for personal use that installs AppImage without sudo privileges:

```bash
#!/usr/bin/env bash

########################################################################
# File Name    : install_freetube_appimage.sh
# Description  : This script automates the installation and setup of
#                an AppImage application. It downloads the latest
#                version from a specified source using curl, installs
#                it to the user's home directory, creates necessary
#                directories and symbolic links, provides an updater
#                script and a remover script.
# Dependencies : curl
# Usage        : • Make the script executable with 
#                  sudo chmod +x install_freetube_appimage.sh
#                • Run the script with:   
#                  bash install_freetube_appimage.sh
#                • To uninstall the AppImage, run:
#                  $HOME/.local/share/freetube/remover.sh
# Author       : Me and the bois
# License      : Free of charge, no warranty
# Inspired by  : https://portable-linux-apps.github.io
########################################################################

# Ensure shell script safety checks
set -u

# Define variables (Update these for each new application)
APP_NAME="freetube" # Name of the application
APP_DOWNLOAD_URL="https://api.github.com/repos/FreeTubeApp/FreeTube/releases" # URL to download the AppImage
HOME_DIR="$HOME/.local/share/$APP_NAME" # Installation directory
DESKTOP_DIR="$HOME/.local/share/applications" # Local directory
DESKTOP_FILE="$DESKTOP_DIR/$APP_NAME.desktop" # Entry directory
ICON_PATH="$HOME/.local/share/$APP_NAME/icon" # Icon directory

# Create necessary directories
mkdir -p "$HOME_DIR/tmp" "$DESKTOP_DIR" "$ICON_PATH" "$HOME/.local/bin"

# Download the latest AppImage
version=$(curl -sL "$APP_DOWNLOAD_URL" | grep -o '"browser_download_url": *"[^"]*"' | grep -o 'https://[^"]*' | grep -i 'amd64.*\.AppImage\|x86_64.*\.AppImage' | head -n 1)
if [ -n "$version" ]; then
    curl -L -o "$HOME_DIR/$APP_NAME.AppImage" "$version" || exit 1
    echo "$version" > "$HOME_DIR/version"
    chmod a+x "$HOME_DIR/$APP_NAME.AppImage" || exit 1
else
    echo "Error: No AppImage found. Exiting."
    exit 1
fi

# Create symbolic link to make the AppImage executable from anywhere
ln -sf "$HOME_DIR/$APP_NAME.AppImage" "$HOME/.local/bin/$APP_NAME"

# Extract .desktop file and icons from the AppImage
cd "$HOME_DIR"
./"$APP_NAME.AppImage" --appimage-extract "*.desktop" > /dev/null 2>&1
./"$APP_NAME.AppImage" --appimage-extract "share/applications/*.desktop" > /dev/null 2>&1
./"$APP_NAME.AppImage" --appimage-extract "usr/share/applications/*.desktop" > /dev/null 2>&1

if [ -f squashfs-root/*.desktop ]; then
    mv squashfs-root/*.desktop ./"$APP_NAME.desktop"
elif [ -f squashfs-root/share/applications/*.desktop ]; then
    mv squashfs-root/share/applications/*.desktop ./"$APP_NAME.desktop"
elif [ -f squashfs-root/usr/share/applications/*.desktop ]; then
    mv squashfs-root/usr/share/applications/*.desktop ./"$APP_NAME.desktop"
fi

if [ ! -e ./"$APP_NAME.desktop" ]; then
    echo "Error: .desktop file not found."
    exit 1
fi

# Adjust .desktop file paths
sed -i "s#Exec=.*#Exec=$HOME/.local/bin/$APP_NAME#g" ./"$APP_NAME.desktop"
sed -i "s#Icon=.*#Icon=$APP_NAME#g" ./"$APP_NAME.desktop"

# Move .desktop file to applications directory
mv ./"$APP_NAME.desktop" "$DESKTOP_FILE"
chmod +x "$DESKTOP_FILE"

# Extract and move PNG icon
./"$APP_NAME.AppImage" --appimage-extract "*.png" > /dev/null 2>&1

# Check if any PNG icon is extracted
if [ -f squashfs-root/*.png ]; then
    mv squashfs-root/*.png "$ICON_PATH/$APP_NAME.png"
else
    echo "Warning: No PNG icon found."
fi

# Cleanup extracted files
rm -rf squashfs-root

# Add remover script
cat > "$HOME_DIR/remover.sh" <<EOF
#!/bin/sh
set -e
rm -f \$HOME/.local/bin/$APP_NAME
rm -rf $HOME_DIR
rm -f $DESKTOP_FILE
EOF
chmod a+x "$HOME_DIR/remover.sh"

# Script to update the program
cat > "$HOME_DIR/updater.sh" << EOF
#!/bin/sh
set -u
APP_NAME="$APP_NAME"
APP_DOWNLOAD_URL="$APP_DOWNLOAD_URL"
HOME_DIR="$HOME_DIR"
version0=\$(cat "\$HOME_DIR/version")
version=\$(curl -sL "\$APP_DOWNLOAD_URL" | grep -o '"browser_download_url": *"[^"]*"' | grep -o 'https://[^"]*' | grep -i 'amd64.*\.AppImage\|x86_64.*\.AppImage' | head -n 1)
if [ -n "\$version" ]; then
    mkdir -p "\$HOME_DIR/tmp" && cd "\$HOME_DIR/tmp" || exit 1
    curl -L -o "\$APP_NAME.AppImage" "\$version" || exit 1
    mv "\$APP_NAME.AppImage" "\$HOME_DIR/\$APP_NAME.AppImage"
    chmod a+x "\$HOME_DIR/\$APP_NAME.AppImage" || exit 1
    echo "\$version" > "\$HOME_DIR/version"
    rm -R -f "\$HOME_DIR/tmp"
    notify-send "\$APP_NAME is updated!"
else
    echo "Update not needed!"
fi
EOF
chmod a+x "$HOME_DIR/updater.sh"

# Update desktop database
update-desktop-database "$DESKTOP_DIR"

# Copy .desktop file to the Desktop
cp "$DESKTOP_FILE" "$HOME/Desktop"

echo "Installation completed successfully."
```

Thanks.

**Comment by Samueru-sama** [comment]
You can use `appman` if you want to install appimages without sudo.

We also have a working [sandboxing method](https://github.com/ivan-hc/AM?tab=readme-ov-file#sandboxing-example) that uses aisap which uses bubblewrap instead of firejail which has a bad security record. 

And for the icon extraction with use this method that is guaranteed to get you the `.desktop` and `icon`: 

```

# LAUNCHER & ICON
./"$APP" --appimage-extract *.desktop 1>/dev/null && mv ./squashfs-root/*.desktop ./"$APP".desktop
./"$APP" --appimage-extract .DirIcon 1>/dev/null && mv ./squashfs-root/.DirIcon ./DirIcon
COUNT=0
while [ "$COUNT" -lt 10 ]; do # Tries to get the actual icon/desktop if it is a symlink to another symlink
	if [ -L ./"$APP".desktop ]; then
		LINKPATH="$(readlink ./"$APP".desktop | sed 's|^\./||')"
		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./"$APP".desktop
	fi
	if [ -L ./DirIcon ]; then
		LINKPATH="$(readlink ./DirIcon | sed 's|^\./||')"
		./"$APP" --appimage-extract "$LINKPATH" 1>/dev/null && mv ./squashfs-root/"$LINKPATH" ./DirIcon
	fi
	[ ! -L ./"$APP".desktop ] && [ ! -L ./DirIcon ] && break
	COUNT=$((COUNT + 1))
done
```

**Comment by ivan-hc** [comment]
> AppImage are cool! Your project is cool!
> 
> I noticed your recent updates, which I found very interesting. I saw that you made excellent documentation on the main website and on github. I initially discovered your project through the scripts, which greatly simplify the installation of AppImages, making it particularly advantageous for Debian users, live systems and test purpuses.

thanks :)

> An AppImage is a self-contained file that operates independently, requiring no additional dependencies

yes

> and only needing sudo for making it executable.

```
chmod a+x ./*AppImage
```

no "sudo" needed

>This portability makes it ideal for use in live systems and environments where software installation or modification is restricted or temporary. Moreover, using AppImages with heavyweight intermediary solutions like Snap or Flatpak is unnecessary, along with reconsidering potential sources that may be compromised.

yep, it's a shame that few of us are aware of it, I totally agree... anyway...

> Managing multiple AppImages individually for desktop integration, updates, or removal isn't practical, which is where scripts come in handy.

This is why I wrote "AM", all is started from an old AppImage I had of Avidemux, without knowing what an AppImage was... and it were old, any time I had to use it, a notify said that a new version was available, and I was unable to update it.

> However, scripting can be challenging due to the diversity of download sources, architectures, and URL formats

yep, some sites are hard to "hack" to find a correct download URL

> especially when it comes to extracting AppImages and creating desktop entries (the trickiest part being the desktop icon creation, hehe).

we already have the method of the new installation scripts wrote by my best cooperator @Samueru-sama , and if they are not enough, the "install.am" module has a function to download the icon from https://portable-linux-apps.github.io

also, each app has icons into a dedicated "icons" directory, so you can put whatever icon you want, but with the name of the installed app

there are several ways to fix this

> Dealing with application isolation (Firejail) by user or sudo is also complex, I see the topic "How to use 'AM' in non-privileged mode, like 'AppMan' ".

and this is why we use [Aisap](https://github.com/mgord9518/aisap), the Bubblewrap frontend for AppImages. An idea of @Samueru-sama to implement it here. Bubblewrap is widelly used, also Flatpak uses it. Firejail is dead and obsolete. Sad but true. Aisap deserves the more to be the default sandboxing solution for AppImages.

> I'm still reflecting on the sandbox and icons issues (the hardest part, hehe). For now I made a simpler "independent" script for personal use that installs AppImage without sudo privileges:

Thank you for sharing this.

At earlier days, each app had inbuilt update system, in "AM": instead of the symlink, I created a script to check updates for the app while launched

The idea was good... but... to check updates before launchind the app... or doing this after using it... sometime takes too much time. So I removed this time ago.

**Comment by RENANZG** [comment]
Oh, boy.  What an idiot I am! 

chmod a+x install_freetube_appimage.sh

But the script do the right thing ?

    chmod a+x "$HOME_DIR/$APP_NAME.AppImage" || exit 1
    chmod a+x "$HOME_DIR/remover.sh"
    chmod a+x "$HOME_DIR/updater.sh"

No... because running with sudo...

Thanks.

**Comment by Samueru-sama** [comment]
> Oh, boy. What an idiot I am!
> 
> chmod a+x install_freetube_appimage.sh
> 
> But the script do the right thing ?
> 
> ```
> chmod a+x "$HOME_DIR/$APP_NAME.AppImage" || exit 1
> chmod a+x "$HOME_DIR/remover.sh"
> chmod a+x "$HOME_DIR/updater.sh"
> ```
> 
> No... because running with sudo...
> 
> Thanks.

Just in case, appman has a function that patches all the `/usr/local` paths for their `$HOME` equivalent, that way sudo isn't needed.
