### ISSUE TITLE
Il menù di Cinnamon non trova i .desktop in /usr/local/share/applications/ ma è un problema di Cinnamon. 

### ISSUE THREAD

**Issue by vitforlinux-gimp** [ivan-hc/AM#789]
Invece le trova in ~/.local/share/applications.
Forse bisogna segnalarlo a Cinnamon .

Non c'è un MeToo per i programmatori... ma se scoccio dimmelo.

Ciao!

**Comment by ivan-hc** [comment]
Ciao Vit, sto cercando su google se questo problema è correlato a Cinnamon e non ho trovato risultati.

Cosa dice l'output di `echo $XDG_DATA_DIRS`?

Questo è il mio
```
/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share
```
non so perchè /usr/share sia ripetuto due volte, ma /usr/local/share è dove dovrebbe essere.

**Comment by Samueru-sama** [comment]
There is one way to fix this, but this is a last resort once the issue is reported to cinnamon and they said that they wont fix it.

```
if [ "$XDG_CURRENT_DESKTOP" = "X-Cinnamon" ] && [ ! -d /usr/local/share/applications ]; then
	$SUDOCOMMAND ln -s /usr/share/applications /usr/local/share
fi
```

**Comment by ivan-hc** [comment]
@Samueru-sama but this way you create a symlink of /usr/share/applications to /usr/local/share. What if someone want to install third party apps (using AM) and the user have no RW permissions in /usr/share (as already happens with immutable distros)?

**Comment by Samueru-sama** [comment]
> @Samueru-sama but this way you create a symlink of /usr/share/applications to /usr/local/share. What if someone want to install third party apps (using AM) and the user have no RW permissions in /usr/share (as already happens with immutable distros)?

Are there immutable cinnamon distros?

If that's the case then there has to be a way for cinnamon to read the `.desktop` in /usr/local/share/applications.

**Comment by vitforlinux-gimp** [comment]
(ITALIAN)
Ho usato JGMENU su Cinnamon in Mint 22 Wilma beta, e la voce per avviare Chrome, c'è, ma nel menù di Cinnamon no. Credo che il problema sia nel menu di Cinnamon, che evidentemente non "cerca" file .desktop in /usr/local/share/applications/.

Fare collegamenti (link) ad altre cartelle non va bene, tanto varrebbe allora mettere i file .desktop in /usr/share/applications/ avendo megari cura di aggiungere AM nel nome(chrome-AM.desktop)... così da non guastarne altri quando si disinstalla.

È un errore di Cinnamon.
(ENGLISH-matic)
I used JGMENU on Cinnamon in Mint 22 Wilma beta, and the entry to launch Chrome is there, but not in the Cinnamon menu. I believe the problem is in Cinnamon's menu, which evidently doesn't "search" for .desktop files in /usr/local/share/applications/.

Making connections (links) to other folders is not good, so you might as well put the .desktop files in /usr/share/applications/ taking care to add AM in the name (chrome-AM.desktop)... so as not to damage them others when you uninstall.

Is a Cinnamon error.

**Comment by ivan-hc** [comment]
Penso che sia meglio segnalare questo errore al team di linux mint / cinnamon

https://github.com/linuxmint/cinnamon/issues

questi sono gli issie relativi alla ricerca per "usr/local/share/applications" (con virgolette, per avere il risultato preciso)

https://github.com/linuxmint/cinnamon/issues?q=%22usr%2Flocal%2Fshare%2Fapplications%22

**Comment by vitforlinux-gimp** [comment]
Devo chiedere scusa, evidentemente gli sviluppatori di Cinnamon si sono accorti del difetto e lo hanno risolto.

I have to apologize, evidently the Cinnamon developers noticed the flaw and fixed it.

**Comment by ivan-hc** [comment]
> Devo chiedere scusa, evidentemente gli sviluppatori di Cinnamon si sono accorti del difetto e lo hanno risolto.
> 
> I have to apologize, evidently the Cinnamon developers noticed the flaw and fixed it.

Non scusarti, è bene che ci teniamo informati.

PS: sempre e solo forza XFCE! xD

**Comment by vitforlinux-gimp** [comment]
Forza svarioni che fanno pigliare lucciole per lanterne... anche il vecchio Cinnamon (e anche Budgie) di Debian 12 funzionano, e eppure ci vedo ancora.
Devo mangiare più gelato e usare meno distro diverse... così tengo la testa più fresca.

**Comment by ivan-hc** [comment]
> Devo mangiare più gelato e usare meno distro diverse... così tengo la testa più fresca.

Hai ragione, questi non sono tempi adatti a un pinguino ;)

**Comment by candrapersada** [comment]
but from cinnamon only display 1 Media Player mpv
