### ISSUE TITLE
New apps (+thanks!)

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#813]
Firstly, many thanks for developing and maintaining `am`. It is a lifesaver on Linux. I just had a few suggestions that you might want to add.

- [Heynote](https://github.com/heyman/heynote/releases)
- [YTS-Streaming](https://github.com/iambpn/YTS-Streaming/releases)
- [yt-dlandcut](https://github.com/Markkop/yt-dlandcut/releases)
- [Repath Studio](https://github.com/repath-project/repath-studio/releases)
- [FreeShow](https://github.com/ChurchApps/FreeShow/releases)
- [AFFiNE.PRO](https://github.com/toeverything/AFFiNE/releases) - there's stable, beta & canary releases
- [Parsec](https://github.com/Scille/parsec-cloud/releases)
- [WordTsar](https://sourceforge.net/projects/wordtsar/files/latest/download)
- [LooofiX](https://github.com/DoginUwU/LooofiX/releases)
- [UpNote](https://upnote.sfo3.cdn.digitaloceanspaces.com/UpNote.AppImage)
- [WebCatalog](https://webcatalog.io/api/download/?platform=linux&arch=x64)
- [F95 Game Updater](https://github.com/MillenniumEarl/YAM/releases)
- [Vrew](https://vrew-files.voyagerx.com/Vrew-2.4.2-x86_64.AppImage)
- [Aiming Pro](https://aiming.pro/desktop-app/Aiming-Pro-1.0.4.AppImage)
- [Bearly](https://github.com/bearlyai/releases/releases) - only stable releases seem to have AppImage build
- [Monoline](https://download.monoline.io/desktop-apps/Monoline-1.2.4.AppImage)
- [Todorant](https://github.com/backmeupplz/todorant-releases/releases)
- [ToDesktop](https://builder.todesktop.com/)
- [Supernotes](https://download.supernotes.app/Supernotes-3.1.4.AppImage)
- [Taskade](https://apps.taskade.com/updates/Taskade_4.3.3_x86_64.AppImage)
- [Internxt Drive](https://github.com/internxt/drive-desktop-linux/releases)
- [Unyo](https://github.com/K3vinb5/Unyo/releases)
- pCloud - Couldn't find the exact download link, but here's the [link to the download page](https://www.pcloud.com/how-to-install-pcloud-drive-linux.html?download=electron-64).
- [Nuclino](https://s3.eu-central-1.amazonaws.com/repository.nuclino.com/downloads/Nuclino.AppImage)
- [Mine-Craft.io](https://mine-craft.io/games/litecraft.io/apps/mine-craft.io-linux.AppImage)
- [Mudlet](https://www.mudlet.org/download/30/)
- [Kinopio](https://dl.todesktop.com/201223j48l03cxi) - for [Kinopio](https://kinopio.club/)
- [LISTEN.moe](https://github.com/LISTEN-moe/desktop-app/releases)
- [Tzared](https://cdn.tza.red/tzared.linux.AppImage)
- [Ideamerit Designer](https://www.ideamerit.com/downloads/Ideamerit%20Designer-2.0.0-x86_64.AppImage)
- [Nightwave Plaza Electron](https://github.com/jjoshm/nightwave-plaza-electron/releases)
- [Fabric](https://dl.todesktop.com/220930m1ahpjvoh) - for [Fabric](https://fabric.so/)
- [Ankama Launcher](https://download.ankama.com/launcher/full/linux)
- [Elapp](https://cdn.criptext.com/elapp/linux/elapp-latest.AppImage) - for [Elapp](https://www.elapp.com/)

Forgive me if I made any mistake in filing the issue. And thanks again for this wonderful app. :)

**Comment by ivan-hc** [comment]
I'm just working on this, "issues" is the right place for this

**Comment by Samueru-sama** [comment]
> I'm just working on this, "issues" is the right place for this

Ivan let me know if you are working on some so we don't end up with repeated work.

**Comment by ivan-hc** [comment]
@Samueru-sama thanks, I'm starting from the top, now I'm at "wordtsar", its hosted on sourceforge

**Comment by ivan-hc** [comment]
Upnote seems not to be an updatable one, I can't see versions references anywhere

its also a french-only app, so it should be something of local interest. Maybe an electron app, I'm not sure

I go ahead

**Comment by ivan-hc** [comment]
@Sush-ruta the F95... something... appimagwe should be YAM, right? What you posted is a description.

**Comment by ivan-hc** [comment]
I have difficults in find a correct download url for todesktop, to be used with wget

**Comment by ivan-hc** [comment]
todesktop is suspended for now, what I've found is only how to get the version
```
curl -Ls https://www.todesktop.com/changelog | tr '><' '\n' | grep "^v[0-9]" | head -1
```

I go ahead

**Comment by ivan-hc** [comment]
I need to jump also pcloud, here the command I use for the version
```
wget -q https://repology.org/project/pcloud/versions -O - | grep -i "new.*version" | head -1 | tr '><' '\n' | grep "^[0-9]"
```

- todesktop
- pcloud

2 suspended for now

I go ahead

**Comment by ivan-hc** [comment]
mine-craft.io is a fixed version, I can see where to find a version

**Comment by ivan-hc** [comment]
uhm... kinopio seems to have the same download URL for linux and windows, so it needs an user-agent to specify the artifact to download.

I suspend it too.

So now we have:

- todesktop
- pcloud
- kinopio

in the waiting list.

**Comment by ivan-hc** [comment]
also tzared has a fixed version, just checked the website

**Comment by ivan-hc** [comment]
Fabric has a download URL based on todesktop, same app as before

I'll suspend this too for now.

**Comment by ivan-hc** [comment]
also elapp seems to be a fixed version... OK

So I've finished.

Only four left at the end:

- todesktop
- pcloud
- kinopio
- fabric

the others can be already uploaded now.

**Comment by ivan-hc** [comment]
32 apps added and 4 left

Also, created pages and icons for the 32 apps in the catalogue:

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/b56b993b2bd45fd89196691f4dad41da7e3c85cd

I'll work on the 4 left later.

**Comment by ivan-hc** [comment]
>     * [ToDesktop](https://builder.todesktop.com/)
> 
>     * pCloud - Couldn't find the exact download link, but here's the [link to the download page](https://www.pcloud.com/how-to-install-pcloud-drive-linux.html?download=electron-64).
>
>     * [Kinopio](https://dl.todesktop.com/201223j48l03cxi) - for [Kinopio](https://kinopio.club/)
>
>     * [Fabric](https://dl.todesktop.com/220930m1ahpjvoh) - for [Fabric](https://fabric.so/)

let me see what I can do.

**Comment by ivan-hc** [comment]
- [ ] todesktop
- [ ] pcloud
- [ ] kinopio
- [ ] fabric

**Comment by ivan-hc** [comment]
the AppImage of Fabric is old, I can see that the URL you provides points to the 0.1.7 release, while now the more recent one is 3.2.2 https://repology.org/project/fabric/versions

@Sush-ruta are you sure I shoul add this app to the database?

**Comment by Sush-ruta** [comment]
@ivan-hc I aoplogise for the late reply. Yes, the name of the program is `YAM`. I was copying from the repo heading and thus wrote that. Sorry.
Please do skip the ones you feel like not adding - I just checked the AppImages I had on my system outside `am` an `appman` and sent the ones I used most. I missed some, maybe I can add here:
- [DeepNotes](https://github.com/DeepNotesApp/DeepNotes/releases)
- [Silex Desktop](https://github.com/silexlabs/silex-desktop/releases)
- [DeepL Linux Electron](https://github.com/kumakichi/Deepl-linux-electron/releases)
- [SoundCloud-rpc](https://github.com/richardhbtz/soundcloud-rpc/releases)
- [Plume](https://github.com/nuttyartist/plume-public/releases)
- [Waifu2x GUI](https://github.com/Tenpi/Waifu2x-GUI/releases)
- [Quran Companion](https://github.com/0xzer0x/quran-companion/releases)

Anyway, many thanks for your responses. It took you less time to upload all the apps than it took me to write the issue :P

**Comment by Sush-ruta** [comment]
P.S. I couldn't get the `--extra` flag to get working on `am` / `appman` . Maybe I am doing something wrong?
```bash
$ appman -e DeepNotesApp/DeepNotes deepnotes
############################################################################
##                                                                        ##
##                  START OF ALL INSTALLATION PROCESSES                   ##
##                                                                        ##
############################################################################

◆ "DEEPNOTES": starting installation script


 💀 ERROR DURING INSTALLATION, REMOVED "DEEPNOTES"!                       
____________________________________________________________________________
```

**Comment by ivan-hc** [comment]
> ```shell
> -e DeepNotesApp/DeepNotes deepnotes
> ```

nope, this is an issue of `-e`, here is how it have patched the script
```
curl -Ls https://api.github.com/repos/DeepNotesApp/DeepNotes/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -ie "x86_64\|x64\|amd64"  | head -1
```
and the URL have not these keys

I must fix this.

**Comment by Sush-ruta** [comment]
Thank you @ivan-hc . That was fast.
A couple of issues. The UpNote I linked is [this](https://getupnote.com/). You linked the wrong app in the page.
The `pcloud` script is not working.
```bash
◆ "PCLOUD": starting installation script

getpubzip?code=XZQDbs0Z4E 100%[===================================>]  61.31M  4.28MB/s    in 16s     
mv: target './pcloud' is not a directory
chmod: cannot access './pcloud': No such file or directory

 "PCLOUD" INSTALLED (1 MB OF DISK SPACE)                   
```
Nothing is showing up on app menu.

**Comment by ivan-hc** [comment]
this happens because the function works like this
```
		if [ "$arch" == "x86_64" ]; then
			if curl --output /dev/null --silent --head --fail "$API_GITHUB_REPO" | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | grep -ie "x86_64\|x64\|amd64" | head -1 1>/dev/null; then
				FILTER=' | grep -ie "x86_64\\|x64\\|amd64" '
			else
				FILTER=' | grep -vi "i386\\|i686\\|aarch64\\|arm64\\|armv7l"'
			fi
```

**Comment by ivan-hc** [comment]
> Thank you @ivan-hc . That was fast. A couple of issues. The UpNote I linked is [this](https://getupnote.com/). 

Nope, you linked this https://upnote.sfo3.cdn.digitaloceanspaces.com/UpNote.AppImage

Being this not the URL to the site but a download URL, I had to investigate, and found upnote.com

>You linked the wrong app in the page. The `pcloud` script is not working.
> 
> ```shell
> ◆ "PCLOUD": starting installation script
> 
> getpubzip?code=XZQDbs0Z4E 100%[===================================>]  61.31M  4.28MB/s    in 16s     
> mv: target './pcloud' is not a directory
> chmod: cannot access './pcloud': No such file or directory
> 
>  "PCLOUD" INSTALLED (1 MB OF DISK SPACE)                   
> ```
> 
> Nothing is showing up on app menu.

Just fixed, about the message, it does not find the icon in DirIcon as normal and moer recent AppImages should. This is fruit of a bad AppImage construction.

**Comment by ivan-hc** [comment]
Also upnote is now ok https://github.com/ivan-hc/AM/commit/7f3eac23d54b911386af20ceb90e1f7af6c95761

**Comment by Sush-ruta** [comment]
Yes my bad, I meant this is the UpNote I was referring to. I should have linked it in the issue itself. Sorry. To avoid any errors from my side, I will link to all the websites:
- [Todorant](https://todorant.com/)
- [Internxt Drive](https://internxt.com/drive)
- [Repath Studio](https://repath.studio/)
- [FreeShow](https://freeshow.app/)
- [Heynote](https://heynote.com/)
- [AFFiNE.PRO](https://affine.pro/)
- [Parsec](https://parsec.cloud/)
- [Bearly](https://bearly.ai/)

---
- [DeepNotes](https://deepnotes.app/)
- [Quran Companion](https://0xzer0x.github.io/projects/quran-companion/)
- [Plume](https://www.get-plume.com/)

All the scripts are working perfectly. Thanks and apologies for any errors.

**Comment by ivan-hc** [comment]
> @ivan-hc I aoplogise for the late reply. Yes, the name of the program is `YAM`. I was copying from the repo heading and thus wrote that. Sorry. Please do skip the ones you feel like not adding - I just checked the AppImages I had on my system outside `am` an `appman` and sent the ones I used most. I missed some, maybe I can add here:
> 
>     * [DeepNotes](https://github.com/DeepNotesApp/DeepNotes/releases)
> 
>     * [Silex Desktop](https://github.com/silexlabs/silex-desktop/releases)
> 
>     * [DeepL Linux Electron](https://github.com/kumakichi/Deepl-linux-electron/releases)
> 
>     * [SoundCloud-rpc](https://github.com/richardhbtz/soundcloud-rpc/releases)
> 
>     * [Plume](https://github.com/nuttyartist/plume-public/releases)
> 
>     * [Waifu2x GUI](https://github.com/Tenpi/Waifu2x-GUI/releases)
> 
>     * [Quran Companion](https://github.com/0xzer0x/quran-companion/releases)
> 
> 
> Anyway, many thanks for your responses. It took you less time to upload all the apps than it took me to write the issue :P

just created

**Comment by Sush-ruta** [comment]
> And there is [Caesium](https://saerasoft.com/caesium) for [Caesium Image Compressor](https://github.com/larygwil/caesium-image-compressor/releases) - new
I added one more to the list (sorry - I am an appimages hoarder). I can close the issue since everything is solved (so fast!).

**Comment by ivan-hc** [comment]
> Yes my bad, I meant this is the UpNote I was referring to. I should have linked it in the issue itself. Sorry. To avoid any errors from my side, I will link to all the websites:
> 
>     * [Todorant](https://todorant.com/)
> 
>     * [Internxt Drive](https://internxt.com/drive)
> 
>     * [Repath Studio](https://repath.studio/)
> 
>     * [FreeShow](https://freeshow.app/)
> 
>     * [Heynote](https://heynote.com/)
> 
>     * [AFFiNE.PRO](https://affine.pro/)
> 
>     * [Parsec](https://parsec.cloud/)
> 
>     * [Bearly](https://bearly.ai/)
> 
> 
>     * [DeepNotes](https://deepnotes.app/)
> 
>     * [Quran Companion](https://0xzer0x.github.io/projects/quran-companion/)
> 
>     * [Plume](https://www.get-plume.com/)
> 
>     * And there is [Caesium](https://saerasoft.com/caesium) for [Caesium Image Compressor](https://github.com/larygwil/caesium-image-compressor/releases) - new
> 
> 
> All the scripts are working perfectly. Thanks and apologies for any errors.

Its no more needed. I've already uploaded all of them.

I'm just looking for the icons of the last group you gave, so I can complete the catalogue.

Thank you for the interest.

Please, re-open another issue for -e, I'll investigate when I'll be awake. Its morning here and I worked all night on this.
