### ISSUE TITLE
--extra / -e not working

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#815]
Hi.
The `--extra` / `-e` flag is not working to install external apps from GH repos.

```bash
❯ appman -e MTDonovan/Evalit evalit
############################################################################
##                                                                        ##
##                  START OF ALL INSTALLATION PROCESSES                   ##
##                                                                        ##
############################################################################

◆ "EVALIT": starting installation script


 💀 ERROR DURING INSTALLATION, REMOVED "EVALIT"!                          
____________________________________________________________________________
```

**Comment by Samueru-sama** [comment]
I just made the [PR](https://github.com/ivan-hc/AM/pull/816) adding it to the database.

Though that dones't actually fix the issue you are having.

**Comment by ivan-hc** [comment]
Update "AM"/AppMan to fix

**Comment by Samueru-sama** [comment]
> Thanks @Samueru-sama, adding the app is still good, but does not solves the issue in -e
> 
> This is how I will fix this
> 
> ```
> 		if [ "$arch" == "x86_64" ]; then
> 			FILTER=' | grep -vi "i386\\|i686\\|i586\\|i486\\|aarch64\\|arm64\\|armv7l"'
> 		elif [ "$arch" == "i686" ]; then
> 			FILTER=' | grep -ie "i386\\|i686\\|i586\\|i486" '
> 		elif [ "$arch" == "aarch64" ]; then
> 			FILTER=' | grep -ie "aarch64\\|arm64" '
> 		fi
> ```

I don't think you need the double `==` in there btw.
