### ISSUE TITLE
About non-official apps.

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/AM#820]
Following @probonopd comments we have to add a way for "mere mortals" to be able to know which third-party provided AppImages are high-quality and trustworthy.

Thankfully, I think over 90% of the appimages in AM are all hosted on github and have a transparent build process behind them.

So I think what needs to be done is: 

- We the appimage is not official but has a transparent build process behind, like this [example](https://github.com/srevinsaju/Firefox-Appimage) we don't need to issue any warning, just point out that it is not official in the description.
- If the appimage is just a random uploaded binary, [like in this example](https://github.com/AlexanderP/tesseract-appimage), we need to add a warning before installation.

I think the simple solution is adding a comment like `# spooky` to the installation script, and AM should check for that word before giving the warning.

**Comment by ivan-hc** [comment]
I agree.

The first step will be to allow listing AppImages into a separated list using a suboption `--appimages` in `-l`/`list` and `-q`/`query`

This is a preview on how AM 7.5 will look alike:

https://github.com/user-attachments/assets/864e95dd-0f69-4b8b-b6b3-289af3610aac

--------------------------

I think that the focus on "spooky" AppImages can be planned for "AM" 7.6, so now we have a roadmap.

**Comment by Samueru-sama** [comment]
We can also add an option to filter out unofficial appimages from the list by simply doing a `grep -vi unofficial` in am -l, maybe I don't know if it is worth it lol.

**Comment by ivan-hc** [comment]
> We can also add an option to filter out unofficial appimages from the list by simply doing a `grep -vi unofficial` in am -l, maybe I don't know if it is worth it lol.

I've another idea instead: to add an option "--safe-install" to ignore all scripts marked as "spooky", if marking the installation scripts was what you are looking for.

**Comment by ivan-hc** [comment]
or maybe to add "--safe" as a suboption of "-i"

**Comment by RENANZG** [comment]
How to deal with these cases ? 

https://github.com/ecmu/geany.AppImage
https://github.com/ValdikSS/windows2usb

**Comment by Samueru-sama** [comment]
> https://github.com/ecmu/geany.AppImage (official "refurbised" in appimage)

What do you mean by "refurbised"?

>https://github.com/ValdikSS/windows2usb (spooky)

This one will have the warning.

**Comment by RENANZG** [comment]
In this case, Geany is a super-traditional app (official) in which people might think that there really is an AppImage for it, so in that sense it is "reformed/rehabilitated/refurbished". I dont know, but people can install it unconsciously thinking it is official.

**Comment by Samueru-sama** [comment]
> In this case, Geany is a super-traditional app (official) in which people might think that there really is an AppImage for it, so in that sense it is "reformed/rehabilitated/refurbished". I dont know, but people can install it unconsciously thinking it is official.

In that case it will be marked as unofficial.

Basically for the app to be official it has to come from the creators of the application (geany) that isn't the case with that appimage.

What I'm not sure is how we should handle clients for popular applications, like for example the discord appimage will be marked as unofficial, but what about 3rd-party clients that modify discord like Vesktop which the appimage is made by the creators of the app, should that one be marked as unofficial as well?

**Comment by Samueru-sama** [comment]
>What I'm not sure is how we should handle clients for popular applications, like for example the discord appimage will be marked as unofficial, but what about 3rd-party clients that modify discord like Vesktop which the appimage is made by the creators of the app, should that one be marked as unofficial as well?

I think we don't have to mark those as unofficial, because after all if you are installing vesktop you know that app isn't made by discord themselves I think. 

However if the vesktop appimage wasn't made by themselves then the unofficial has to be added.

**Comment by ivan-hc** [comment]
Now that descriptions in the lists can be longer and more readable, to add info about official/unofficial and ever more details will be easier.

The "80 characters" rule is no more a rule.

Now to add Official/Unofficial can be done via pull request or bug report.

At this point, I think we have finished for the new release. This issue will be closed soon.

**Comment by ivan-hc** [comment]
The first part is complete.

Now its time to mark installation scripts. Right @Samueru-sama ?

**Comment by ivan-hc** [comment]
merged https://github.com/ivan-hc/AM/pull/850

now starts phase 3: the "AM" community

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM/releases/tag/7.7
