### ISSUE TITLE
Please add categories. You already have many packages. And now there is no way to see, for example, games only

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/AM#829]

**Comment by ivan-hc** [comment]
have you tried to run the command `am -q game`?

You can also check the catalogue https://portable-linux-apps.github.io

**Comment by vitaly-zdanevich** [comment]
> You can also check the catalogue https://portable-linux-apps.github.io

It just a single-level list

![image](https://github.com/user-attachments/assets/fd592721-be76-4f29-b617-e8bce2420d32)

**Comment by ivan-hc** [comment]
it is still a work in progress

**Comment by vitaly-zdanevich** [comment]
Usually every package manager have categories.

Pip
apt
snap
flatpack
portage

From the top of my head.

**Comment by ivan-hc** [comment]
Normally it is enough to use `am -q` to search something using keywords, and the only category added until now is "appimages", right yesterday https://github.com/ivan-hc/AM/releases/tag/7.5

Now I'm waiting for @Samueru-sama to have an updated list, so I can create more pages for the website, at least.

Al depends on the list of available apps and keywords on it.

**Comment by Samueru-sama** [comment]
I don't want this feature in AM itself, maybe on the website. 

Can you even search for app categories in pacman, dnf, apt, etc? I know in pacman I can search for a package name doing `pacman -Ss package` which is similar to what we have already in am of `am -q package`, but nothing close to categories.

And yesterday I was telling Ivan that wouldn't have bothered to add the `am -q` option, since `am -l | grep package` would have been enough for me.

**Comment by ivan-hc** [comment]
Categories have been added to https://portable-linux-apps.github.io/apps.html
- https://portable-linux-apps.github.io/appimages.html
- https://portable-linux-apps.github.io/audio.html
- https://portable-linux-apps.github.io/game.html
- https://portable-linux-apps.github.io/graphic.html
- https://portable-linux-apps.github.io/internet.html
- https://portable-linux-apps.github.io/office.html
- https://portable-linux-apps.github.io/video.html

The above pages are generated with the script https://github.com/ivan-hc/AM/blob/dev/tools/am2pla-site

In case you have other suggestions for categories to add or think that a keywerd is missing, let me know

This is the piece of function that care about categories that are not AppImage
```
KEYWORDS="audio game graphic internet office video"
for category in $KEYWORDS; do
if [ "$category" = audio ]; then
	grep -i "$category\|music\|midi\|mp3\|sound" ./"$arch"-apps >> "$arch-$category"
elif [ "$category" = game ]; then
	grep -i "$category\|arcade\|steam\|wine\|strateg" ./"$arch"-apps >> "$arch-$category"
elif [ "$category" = graphic ]; then
	grep -i "$category\|picture\|screensh\|gimp\|photo\|svg\|png\|autocad\|blender\|modeling" ./"$arch"-apps >> "$arch-$category"
elif [ "$category" = internet ]; then
	grep -i "$category\|web browser\|browser web\|firefox\|chrome\|youtube\|torrent\|p2p\|chat\|whatsapp\|mastodon\|telegram\|skype" ./"$arch"-apps >> "$arch-$category"
elif [ "$category" = office ]; then
	grep -i "$category\|document\|book\|pdf\|docx\|reader" ./"$arch"-apps >> "$arch-$category"
elif [ "$category" = video ]; then
	grep -i "$category\|stream\|media player\|film\|movie\|netflix\|youtube" ./"$arch"-apps >> "$arch-$category"
else
	grep -i "$category" ./"$arch"-apps >> "$arch-$category"
fi
```

about implementing categories in AM, as also @Samueru-sama said, this is not planned.

I hope you like this improvement to the online catalogue.

**Comment by vitaly-zdanevich** [comment]
> Can you even search for app categories in pacman, dnf, apt, etc?

I can in Gentoo:

```
$ ls /var/db/repos/gentoo/games-strategy/
0ad          colobot-data  dopewars     freecol     hedgewars          ja2-stracciatella-data  liquidwar       metadata.xml  satellite-reign       spaz     war1gus      wesnoth
Manifest.gz  crimson       dunelegacy   freeorion   homm2-demo         julius                  maxr            naev          scorched3d            tornado  wargus       widelands
augustus     darwinia      endless-sky  freesynd    homm2-gold-gog     knights-demo            megaglest       openra        settlers-2-gold-data  ufoai    warmux       xbattleai
colobot      dominions2    freeciv      galaxyhack  ja2-stracciatella  lgeneral                megaglest-data  s25rttr       seven-kingdoms        uqm      warzone2100
```

and on the web https://packages.gentoo.org/categories/games-strategy

**Comment by ivan-hc** [comment]
again, you can use keywords in `am -q`

Anyway, I am working on ne categories to add to the web catalog. This will be a web-catalog only feature.
