### ISSUE TITLE
AppImage for https://www.fhs.sh/projects

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/AM#834]
On Discord they told me that will add AppImage if somebody creates it, if you want https://www.fhs.sh/projects

**Comment by ivan-hc** [comment]
Maybe I can work on a script to build it on-the-fly if they already have a portable release.

I'm downloading the archive to check it.

**Comment by ivan-hc** [comment]
Can you open this issue in the repo of the project you are talking about and then tag me there?

I'd prefer to avoid AppImages creation requests in this repo. I'm not Santa.

Thanks.

**Comment by vitaly-zdanevich** [comment]
https://codeberg.org/fhs/katawa-shoujo-re-engineered/issues/57

**Comment by ivan-hc** [comment]
OK, say them that they can contact me here or on Reddit, u/am-ivan

**Comment by vitaly-zdanevich** [comment]
Looks like they think that FlatPack is enough :(

But they could accept the building of AppImage if it will be done without their interruption :(

**Comment by ivan-hc** [comment]
> Looks like they think that FlatPack is enough :(
> 
> But they could accept the building of AppImage if it will be done without their interruption :(

look, I normally build AppImages if I can use them or I know what they do, or if are easier for me to be built, using my methods.

I don't know if the game is based on Electron or something, but by extracting it, it seems simple enough to be compiled and converted the same way I have done SuperTuxKart

https://github.com/ivan-hc/SuperTuxKart-appimage

if you are interested to an AppImage of that, being you the interested one to this program and being you the one that knows it... why don't you try compiling it into a repository, as I did?

You can start learning from my SuperTuxKart repository to understand how it works.

Tag me into a your repository, maybe I can help you also with the workflow.
