### ISSUE TITLE
App not up to date

### ISSUE THREAD

**Issue by K3vinb5** [ivan-hc/AM#864]
spotube is not up do date

**Comment by ivan-hc** [comment]
just seen that they have not the appimage, the last time was in december https://github.com/KRTirtho/spotube/releases/tag/v3.3.0

you should contact them to have the AppImage back

**Comment by ivan-hc** [comment]
they should have a portable version, maybe we can drop the appimage for that, or bundle it on-the-fly

anyway, its better to contact the developers to have the Appimage back

**Comment by ivan-hc** [comment]
https://github.com/KRTirtho/spotube/issues/1082

**Comment by K3vinb5** [comment]
Hi, since this is obviosly not your fault I'll close the issue, thanks for the help! Really enjoying using am
