### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by sbucek** [ivan-hc/AM#872]
Zen Browser
[https://github.com/zen-browser/desktop/releases](https://github.com/zen-browser/desktop/releases)

**Comment by Samueru-sama** [comment]
Zen has been in the [repo since 3 weeks](https://github.com/ivan-hc/AM/pull/801) ago.

**Comment by sbucek** [comment]
I see now thanks. 

Searching for "zen" does not return the package and there are some numbers in the package names  :
![2024-08-24_15-27](https://github.com/user-attachments/assets/3436479b-da94-4ad4-8882-f755a7b1bd29)




Looks like a terminal issue on my side.

However with "zen browser" I've found the package.

**Comment by Samueru-sama** [comment]
@sbucek Looks like your terminal has issues displaying the ansi colors that are now used in `am -l`

Does that happen when you use `am -l` alone without piping to `fzf`?

Also am has a method to search by doing `am -q words`

![image](https://github.com/user-attachments/assets/90ab7037-809e-4d46-a896-be40db7e1a05)

**Comment by sbucek** [comment]
I'm using st terminal, but wezterm also shows the same "32mpackage" naming. When I use "am -l" alone I get the result on the top, but there are alot of non-related results below it, so I have to scroll up to find the packagename as the output is not searchable. 

"am -q words" however works perfectly, I'll use that from now on, thank you @Samueru-sama

**Comment by Samueru-sama** [comment]
> I'm using st terminal, but wezterm also shows the same "32mpackage" naming. When I use "am -l" alone I get the result on the top, but there are alot of non-related results below it, so I have to scroll up to find the packagename as the output is not searchable.
> 
> "am -q words" however works perfectly, I'll use that from now on, thank you @Samueru-sama

Yeah I think you need to pass a flag for `fzf` to ignore the ansi codes, we had that issue with `less` where we needed use `less -Ir` instead.

**Comment by sbucek** [comment]
I see now `am -l | fzf --ansi` FTW, thank you!
