### ISSUE TITLE
An outdated version of KiCad from Appimagehub

### ISSUE THREAD

**Issue by harbringer-amentiae** [ivan-hc/AM#873]
Hello and I want to say thank you for your work and apologize for my English. So, I am using AM and when I install KiCad it automatically installs the 5.1.4 package, as I understand this is the latest version available on Appimagehub and it is linked to the [GitHub](https://github.com/KarlZeilhofer/kicad-appimage) repository. But the current version of KiCad is 8.0.4, its standards are much different from 5. I managed to find this repository with the new branch [GitHub](https://github.com/CyberCircuits/kicad-appimage) , but it leads to the Sourceforge download page [Sourceforge](https://sourceforge.net/projects/kicad-appimage/) , so AM -e can't help. Is it possible to replace/add this repository instead of the deprecated one? But testing is needed, as I have not been able to run these Appimages on my system, but this may be my private problem (I am using EndeavourOS)

**Comment by ivan-hc** [comment]
Hi, and wellcome

I can replace the source of the AppImage using the new one to let you install it, but about tests on the single apps, its up to you, if you trust the developer of that application, see https://github.com/ivan-hc/AM?tab=readme-ov-file#an-application-does-not-work-is-old-and-unsupported

I'll replace the script soon. Thanks for the report.

**Comment by harbringer-amentiae** [comment]
Thank you very much

**Comment by ivan-hc** [comment]
done https://github.com/ivan-hc/AM/commit/92a3674b5958cd3dfd2b85463822ff9d34b10a1e

![Istantanea_2024-08-24_20-06-19](https://github.com/user-attachments/assets/6ffc9364-7f35-49a3-83f5-95a380bbd945)
