### ISSUE TITLE
App

### ISSUE THREAD

**Issue by sbucek** [ivan-hc/AM#876]
pragtical

[https://github.com/pragtical/pragtical/releases](https://github.com/pragtical/pragtical/releases)

**Comment by Samueru-sama** [comment]
PR made.

Btw it is very easy to add apps to the repo if it is an appimage hosted on github, just use `am -t appname`, use option 0 and give the link to the github repo. 

![image](https://github.com/user-attachments/assets/6b9c6124-69c8-431a-acb1-e614bbf030ab)

am will make the script for you and place it either in a directory on $HOME or in ~/Desktop iirc, then just test script `am -i ./appname` see if it installs and that's it.
