### ISSUE TITLE
Add pcsx-redux AppImage

### ISSUE THREAD

**Issue by marco-calautti** [ivan-hc/AM#902]
Would you consider adding the Playstation emulator/debugger pcsx-redux?
Here is the project repo with the appimage: https://github.com/grumpycoders/pcsx-redux

**Comment by ivan-hc** [comment]
Ciao Marco, its a bit difficult to find a correct download URL via command line due to the domain where they host the app

![Istantanea_2024-08-30_16-55-44 png](https://github.com/user-attachments/assets/6db029c2-b67d-41af-8211-0d305f7668f4)

I move on in the meantime I don't find a solution for you.

**Comment by marco-calautti** [comment]
Why isn't it as simple as using a regex to extract the first match of the the following tag?
![immagine](https://github.com/user-attachments/assets/6e932bda-98e7-4fd5-9d98-05343d5db0ae)

**Comment by marco-calautti** [comment]
Ah, now I see. the page loads only with javascript enabled. Probably there is a way to use the distrib.app API to get the artifacts of a project.

**Comment by marco-calautti** [comment]
I had a quick look and there is a simple way to gather the builds links from the website.
You first wget/curl the json manifest from here: https://distrib.app/storage/manifests/pcsx-redux/dev-linux-x64/manifest.json

This gives you a list of the build ids with the creation date. Say you want to download the build with id 61. Then you curl/wget the json: https://distrib.app/storage/manifests/pcsx-redux/dev-linux-x64/manifest-61.json
this contains the direct url of the AppImage

Do you think this is enough information to include pcsx-redux now?

**Comment by ivan-hc** [comment]
> Do you think this is enough information to include pcsx-redux now?

its all I needed, thank you

**Comment by marco-calautti** [comment]
I tried adding a pull request for this, since it looked simple enough!

**Comment by ivan-hc** [comment]
you beat me on time, I also have created the script

![Istantanea_2024-08-31_15-49-45 png](https://github.com/user-attachments/assets/b9023786-f626-4360-b734-48956c2f5463)

**Comment by marco-calautti** [comment]
Use the one you prefer, that is fine!

**Comment by ivan-hc** [comment]
Grazie Marco, I reducted the "redux" $version variable, silenced `unzip` and added the latter also in the script to update the app https://github.com/ivan-hc/AM/commit/a1929ff532aff8ad3155215b41d45189ad6c47a4

Also, thank you for the page on the catalog! I go updating the list right now.

**Comment by ivan-hc** [comment]
Preticamente hai risolto da solo, grazie.

**Comment by marco-calautti** [comment]
Di niente. Trovo appman molto utile!

Grazie del lavoro svolto!

Marco

Il sab 31 ago 2024, 16:12 iVAN ***@***.***> ha scritto:

**Comment by ivan-hc** [comment]
ho dovuto correggere un paio di cose sul catalogo, ho ridotto l'icona a 128x128, poichè queste dimensioni servono a due cose: aggiungere un icona di dimensioni accettabili se manca durante l'installazione e non appesantire troppo le pagine con elementi di grandi dimensioni.

Inoltre al markdown ho aggiunto i pulsanti per andare indietro, e posizionato gli screenshot sopra l'URL.

Tra qualche minuto caricherò anche la lista per tutte le pagine.

**Comment by ivan-hc** [comment]
PS, non so perchè sia stato aggiunto a "education" nonostante la lunghezza della descrizione

https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/8928bcf5acb237a6056130f0802f7d3d4f76f935

evidentemente mancava qualche parola chiave per la categoria, queste sono quelle che uso
```
elif [ "$category" = game ]; then
		grep -i "$category\|arcade\|steam\|wine\|strateg\|solitaire\|poker\|chess\|puzzle\|pinball\|adventure" ./"$arch"-apps >> "$arch-$category"
```
dallo script https://github.com/ivan-hc/AM/blob/main/tools/am2pla-site, che uso per aggiornare le pagine del catalogo in meno di un minuto.
