### ISSUE TITLE
New apps (again) + other issues

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#904]
Hi. I wanted to list the apps I installed with `am -e` to see if you would add it to the app's directory. Thanks.
- [better-kirka-client](https://github.com/42infi/better-kirka-client/releases)
- [Caesium Image Compressor](https://github.com/larygwil/caesium-image-compressor/releases)
- [Densify](https://github.com/hkdb/Densify/releases)
- [Grist Desktop](https://github.com/gristlabs/grist-desktop/releases)
- [Kalba](https://github.com/BrewingWeasel/Kalba/releases)
- [Kanri](https://github.com/kanriapp/kanri/releases)
- [Laidout](https://github.com/Laidout/laidout/releases)
- [lofi](https://github.com/dvx/lofi/releases)
- [Mood-Fi](https://github.com/KaykyDeSouzaDias/Mood-Fi/releases)
- [pdfcompress](https://github.com/moonline/Utility.PdfCompress/releases)
- [Pixelhopper](https://github.com/tomas/pixelhopper/releases)
- [RenderTune](https://github.com/MartinBarker/RenderTune/releases)

Here's some others that I have used recently:
- [TransferNow](https://get.transfernow.net/linux)
- [Official Krunker.io Client](https://client2.krunker.io/setup.AppImage)

In an unrelated note, the [elapp] script does not work:
```bash
$ appman install elapp
============================================================================

                  START OF ALL INSTALLATION PROCESSES

============================================================================

 ◆ "ELAPP": starting installation script


 💀 ERROR DURING INSTALLATION, REMOVED "ELAPP"!
```

Also, since the last update, every time I use `am` or `appman`  I am getting this message:
```
mv: '/home/sushruta/.local/share/AM/ghapikey.txt' and '/home/sushruta/.local/share/AM/ghapikey.txt' are the same file
```
Everything is working, but this message is coming at the start and end of all output. I have tried removing and resetting the gh api key to no avail.

**Comment by ivan-hc** [comment]
The issue with the "mv" command has been solved. All these "mv" commands you see are transitional, since we switched from /opt/am to $HOME/.local/share/AM, they also will be removed from a week or two.

I'll try to fix elapp now.

**Comment by ivan-hc** [comment]
Found the issue with elapp, this is the URL that the script uses https://cdn.criptext.com/elapp/linux/elapp-latest.AppImage and this is what appear while I click on the link

![Istantanea_2024-08-30_17-05-01 png](https://github.com/user-attachments/assets/5fc36050-e82d-43e2-b8fb-e0b06ed0478c)

**Comment by ivan-hc** [comment]
Elapp has a not valid SSL certificate

![Istantanea_2024-08-30_17-10-50](https://github.com/user-attachments/assets/7d67fc18-afd1-4966-ac1b-7f14bf68753c)

tat said, I move to the other apps.

**Comment by ivan-hc** [comment]
Github apps are ready, on my PC... but...

> Here's some others that I have used recently:
> 
>     * [TransferNow](https://get.transfernow.net/linux)
> 
>     * [Official Krunker.io Client](https://client2.krunker.io/setup.AppImage)

...please, can you provide the URL to the website instead to redirect me on the AppImage package?

**Comment by ivan-hc** [comment]
Added Krunker

**Comment by ivan-hc** [comment]
WTF??

![Istantanea_2024-08-30_17-54-55](https://github.com/user-attachments/assets/956db823-feb7-4438-80db-138d24956527)

**Comment by ivan-hc** [comment]
Done, all I can do now is to mark elapp as a "spooky" app, to warn about installing it

**Comment by Sush-ruta** [comment]
Thank you for your prompt response and action as always. These are the website links: [Krunkr](https://krunker.io/) and [TransferNow](https://www.transfernow.net/en). Sorry if my reply is late. @ivan-hc

**Comment by ivan-hc** [comment]
its good that you point me to the download url if the website hides the download URL, but as happened the other time, I could upload an AppImage with the same name but from another source, like that french app that was not the one you were looking for.

About updates for the two above, its complicated, there is no source to check a version to compare, but being them electron apps, I think thay may be automatically updated in some way.

**Comment by Sush-ruta** [comment]
I will keep that in mind. And I ran both the apps - they have in built update, so I don't think it will be an issue. And again, many thanks for your work, and all the best. You are a life saver. :pray:

**Comment by Sush-ruta** [comment]
Hi. I am not creating a new issue, but you can considering adding these apps. I have installed/used them in last few days, and they work well with `am -e`.
- [iHeartRadio](https://github.com/ItzSwirlz/iheartradio-webapp/releases)
- [Kiku](https://github.com/angus6b23/kiku/releases)
- [music-player](https://github.com/LucasHazardous/music-player/releases)
- [Youtube Music Desktop \(YMD\)](https://github.com/binary-blazer/ym-desktop/releases)
- [XTuber](https://github.com/chientrm/xtuber/releases)
- [Youtube Downloader](https://github.com/AnthonyGress/Youtube-Downloader/releases)

Although these do not have AppImages, but they have tar.gz releases with executable files inside. I am not sure if this is within the scope of `am`, but listing here nonetheless:
- [Jaspersoft Studio](https://www.jaspersoft.com/products/jaspersoft-community). [Download Link](https://community.jaspersoft.com/download-jaspersoft/community-edition/)
- [Henson](https://github.com/NotAName320/Henson/releases)
- [spritemate4electron](https://github.com/4ch1m/spritemate4electron/releases)
- [Photon](https://github.com/abhi16180/photon/releases/)
- [PDFCrack - GUI](https://sourceforge.net/projects/pdfcrackgui/)

P.S. I have faced problems installing two programs in your list: [`hugor`](https://portable-linux-apps.github.io/apps/hugor.html) and [`caesium`](https://portable-linux-apps.github.io/apps/caesium.html). This is the installation output:
```bash
appman install hugor
============================================================================

                  START OF ALL INSTALLATION PROCESSES

============================================================================

 ◆ "HUGOR": starting installation script

Hugor-3.0-Linux-x64.AppIm 100%[===================================>]  30.57M  4.66MB/s    in 7.2s    
mv: cannot stat './tmp/*mage': No such file or directory
chmod: cannot access './hugor': No such file or directory

 "HUGOR" INSTALLED (1 MB OF DISK SPACE)
____________________________________________________________________________
============================================================================

                  END OF ALL INSTALLATION PROCESSES

             The following new programs have been installed:

 ◆ hugor 3.0

============================================================================
```
and
```bash
appman install caesium
============================================================================

                  START OF ALL INSTALLATION PROCESSES

============================================================================

 ◆ "CAESIUM": starting installation script

Caesium_Image_Compressor- 100%[===================================>]  39.57M  6.58MB/s    in 6.5s    
mv: target './caesium.desktop' is not a directory
sed: can't read ./caesium.desktop: No such file or directory
mv: cannot stat './caesium.desktop': No such file or directory

 "CAESIUM" INSTALLED (40 MB OF DISK SPACE)
____________________________________________________________________________
============================================================================

                  END OF ALL INSTALLATION PROCESSES

             The following new programs have been installed:

 ◆ caesium 2.6.0

============================================================================
```
None of the apps show up on the application menu.

**Comment by ivan-hc** [comment]
Hi



> Hi. I am not creating a new issue, but you can considering adding these apps. I have installed/used them in last few days, and they work well with `am -e`.
> 
>     * [iHeartRadio](https://github.com/ItzSwirlz/iheartradio-webapp/releases)
> 
>     * [Kiku](https://github.com/angus6b23/kiku/releases)
> 
>     * [music-player](https://github.com/LucasHazardous/music-player/releases)
> 
>     * [Youtube Music Desktop (YMD)](https://github.com/binary-blazer/ym-desktop/releases)
> 
>     * [XTuber](https://github.com/chientrm/xtuber/releases)
> 
>     * [Youtube Downloader](https://github.com/AnthonyGress/Youtube-Downloader/releases)

since they work with -e, why don't you try to use -t to create the scripts and do a pull request?

maybe you can also attack the .md files into a comment of the pull request, so it would be easier for me to compile the catalog

> Although these do not have AppImages, but they have tar.gz releases with executable files inside. I am not sure if this is within the scope of `am`, but listing here nonetheless:
> 
>     * [Jaspersoft Studio](https://www.jaspersoft.com/products/jaspersoft-community). [Download Link](https://community.jaspersoft.com/download-jaspersoft/community-edition/)
> 
>     * [Henson](https://github.com/NotAName320/Henson/releases)
> 
>     * [spritemate4electron](https://github.com/4ch1m/spritemate4electron/releases)
> 
>     * [Photon](https://github.com/abhi16180/photon/releases/)
> 
>     * [PDFCrack - GUI](https://sourceforge.net/projects/pdfcrackgui/)

sure, I'll start working on them right now...

> P.S. I have faced problems installing two programs in your list: [`hugor`](https://portable-linux-apps.github.io/apps/hugor.html) and [`caesium`](https://portable-linux-apps.github.io/apps/caesium.html).

...I'll first fix this btw.

**Comment by ivan-hc** [comment]
solved with the two apps broken https://github.com/ivan-hc/AM/commit/8477988f913035eb8aab8676db7c91e60794730f

**Comment by ivan-hc** [comment]
I give up on jaspersoft

**Comment by ivan-hc** [comment]
just added the 4 archives https://github.com/ivan-hc/AM/commit/185e1faeffcb1074b8626481617d57a56ab09147

only the appimages are left

**Comment by ivan-hc** [comment]
@Sush-ruta I have seen that you forked the repo, if you have any issue just ask

**Comment by ivan-hc** [comment]
@Sush-ruta 

https://github.com/user-attachments/assets/095135c0-1be1-4e7f-9122-6955cfd8de28

**Comment by Sush-ruta** [comment]
Thanks @ivan-hc . This is my first time, so if I have run into any problems will consult.

**Comment by ivan-hc** [comment]
For appimages from github is super easy and take few seconds.

It works exactly as -e, but without installing the app.

You only see the preview of the URL, and if incorrect you can add/remove keywords, that will used in `grep -io` or `grep -vi` respectively. No other steps are required.

-------------------------------------------------

In case the source is not github but a different one, the option will always prompt you questions... normally the difficult thing to do for apps hosted outside github is the download URL, as its happened in "jaspersoft". The most common syntax I use to check a URL from other web pages is this:
```
curl -Ls https://example.com/download/page | tr '"><' '\n' | grep -i "^http.*keyword.*zip$"
```
the above command:
1. uses `curl -Ls` to read the page `https://example.com/download/page`
2. uses `tr` to convert to "new line" (` '\n'`) all "double quotes", > and < references through the HTML page, trying to put the URL on a dedicated line
3. uses `grep` to read all lines starting with http (`^http`) and in the same line (`.*`) must contain keywords (for example `appname.*linux.*x64.*appimage`) and ending with "zip" (`zip$`), and regardless if characters are uppercased/lowercased (`grep -i`).

This is all I do normally, and the most of the times it works, sometime not, and in these cases I must invent super-strange commands to fit in one line.

Because all installation scripts are equal, all changes is the APP=, version= and the SITE= reference. Only sometime, if the appimage is in zip or tar archives I must add the command in the 2 lines where you read this
```
# Use tar fx ./*tar* here for example in this line in case a compressed file is downloaded.
```
for tar archives, as suggested
```
tar fx ./*tar*
```
and for zips instead
```
zip -qq ./*zip
```

**Comment by Sush-ruta** [comment]
Despite your immense help, me not being a coder of any sort, I could not create a script for these apps. Maybe you can give it a go?
- [ERA](https://era.sh/) [Download link](https://era.sh/download/linux)
- [Lore Forge](https://loreforge.com/) [Download link](https://storage.googleapis.com/lore-forge-downloads/Lore-Forge-1.1.4.AppImage)
- [QRab](https://sourceforge.net/projects/qrab/)

**Comment by Samueru-sama** [comment]
> Despite your immense help, me not being a coder of any sort, I could not create a script for these apps. Maybe you can give it a go?
> 
> * [ERA](https://era.sh/) [Download link](https://era.sh/download/linux)
> * [Lore Forge](https://loreforge.com/) [Download link](https://storage.googleapis.com/lore-forge-downloads/Lore-Forge-1.1.4.AppImage)
> * [QRab](https://sourceforge.net/projects/qrab/)

Yeah those apps not hosted on github are a nightmare to work with, Ivan is the pro on this.

**Comment by ivan-hc** [comment]
Sorry for the late answer, I had to update the catalog with the previous PR by @Sush-ruta 

- https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/cbbf0d92eeca504e3ac42e822fbebc79a18e690b
- https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/63369c8a04164e34454f1e8afac7a210ec89be42

**Comment by ivan-hc** [comment]
> > Despite your immense help, me not being a coder of any sort, I could not create a script for these apps. Maybe you can give it a go?
> > 
> > * [ERA](https://era.sh/) [Download link](https://era.sh/download/linux)
> > * [Lore Forge](https://loreforge.com/) [Download link](https://storage.googleapis.com/lore-forge-downloads/Lore-Forge-1.1.4.AppImage)
> > * [QRab](https://sourceforge.net/projects/qrab/)
> 
> Yeah those apps not hosted on github are a nightmare to work with, Ivan is the pro on this.

@Samueru-sama let's not exaggerate :laughing:

**Comment by ivan-hc** [comment]
for all three is not difficult to get the download URL
```
APP=qrab
version=$(curl -Ls https://sourceforge.net/p/qrab/activity/feed | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | grep -i "appimage" | grep -v '%' | head -1)

APP=lore-forge
version=$(echo "https://storage.googleapis.com/lore-forge-downloads/$(curl -Ls https://storage.googleapis.com/lore-forge-downloads | tr '><' '\n' | grep -i "^lore.*appimage$" | head -1)")

APP=era
version=$(echo "https://era.sh/download/linux")
```
but the only issue is "era", we have no references to check a version.

Era is a note taking app with not many references by googling it.

And nope, @Samueru-sama , it can't be updated  with appimageupdatetool

**Comment by ivan-hc** [comment]
found
```
wget -q -O - https://era.sh/versionhistory | tr '><' '\n' | grep "^[0-9]*\." | head -1
```

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM/commit/74caabc218e5912e1af60d203cbe8f571d4257b4

**Comment by Sush-ruta** [comment]
> Yeah those apps not hosted on github are a nightmare to work with, Ivan is the pro on this.

Seems like @Samueru-sama was not exaggerating at all, @ivan-hc . :saluting_face:

**Comment by Sush-ruta** [comment]
Both of these are from GH but their release/binary are located either inside the repo or in other non-standard location. Which is a problem.
- [Penpot Desktop](https://github.com/developerfred/Penpot-Desktop) . [Download link](https://updates.korbsstudio.com/penpot-desktop/penpot-desktop-0.0.3.AppImage) - Auto updates
- [go-pd-gui](https://github.com/ManuelReschke/go-pd-gui) . [Download link](https://github.com/ManuelReschke/go-pd-gui/blob/main/fyne-cross/bin/linux-amd64/DRAINY?raw=true)

Other apps:
- [BloomeeTunes](https://github.com/HemantKArya/BloomeeTunes/). This zip file has two folders: `data` and `lib` and a binary file `bloomee`.
- [Smart Media Cutter](https://smartmediacutter.com/). [Download link](https://smartmediacutter.com/downloads/) - The binary is in the archive.
- [Everdo](https://everdo.net/). [Download link](https://everdo.net/download/1.2.8/)
- [Kaspersky Virus Removal Tool](https://www.kaspersky.com/downloads/free-virus-removal-tool). This just downloads a binary called `kvrt.run` that can be used like normal kaspersky antivirus. But there seems to be no version number

**Comment by Sush-ruta** [comment]
Also, `am` installs [Bitwarden](https://portable-linux-apps.github.io/apps/bitwarden.html) version 2022.5.1. The latest version from their [download page](https://bitwarden.com/download/) is [2024.8.2](https://vault.bitwarden.com/download/?app=desktop&platform=linux)

**Comment by ivan-hc** [comment]
solved the issue with bitwarden

PS: thanks to you we now have more than 2000 unique appimages!

run `am -l --appimages`

**Comment by Sush-ruta** [comment]
I just downloaded and installed bitwarden using `am`. Worked flawlessly, thanks @ivan-hc .
Two thousand! Wow. Congrats to you and @Samueru-sama .
P.S.: Time to introduce tags maybe? Some way to sort the apps would be great.

**Comment by ivan-hc** [comment]
> P.S.: Time to introduce tags maybe? Some way to sort the apps would be great.

Tags may be useful on a GUI frontend, so I added them only on the website.

For what concerns the command line instead, we already have the option `-q` or `query`, and it is based on the list of the applications (option `-l` or `list`) and on that note, I abolished the length limit for descriptions a few months ago (it used to be 80 characters per line), so that you can use more keywords when searching.

**Comment by Sush-ruta** [comment]
Yes of course. I meant something like this:
![screenshot](https://github.com/user-attachments/assets/b9a54b5a-cddc-4d17-949e-cf413c81469d)

As every time I open the website, the *entire* list of apps is loaded, which often hangs the tab (on Chromium). Just a thought @ivan-hc , you already have so much on your plate with the TWO THOUSAND (!!) apps. So thanks and all the best.

**Comment by Sush-ruta** [comment]
Also, I was creating scripts for some CLI apps right now for `am` (will PR later), and separately tagging (or categorising) the CLI and GUI (appimages or otherwise) apps on the website would be a good option IMO @ivan-hc

**Comment by ivan-hc** [comment]
> Yes of course. I meant something like this: [ ... ]
> As every time I open the website, the _entire_ list of apps is loaded, which often hangs the tab (on Chromium). Just a thought @ivan-hc , you already have so much on your plate with the TWO THOUSAND (!!) apps. So thanks and all the best.

thanks for the suggestion

![Istantanea_2024-09-13_00-28-48 png](https://github.com/user-attachments/assets/b9d8eaf0-592c-4cdd-8ca7-478f96c180f0)

**Comment by ivan-hc** [comment]
> Also, I was creating scripts for some CLI apps right now for `am` (will PR later), and separately tagging (or categorising) the CLI and GUI (appimages or otherwise) apps on the website would be a good option IMO @ivan-hc

tags must come from a list, the script I use to update the site, [am2pla-site](https://github.com/ivan-hc/AM/blob/main/tools/am2pla-site), also creates and then removes these lists to compile the pages (eccept the one of the [appimages](https://github.com/ivan-hc/AM/blob/main/programs/x86_64-appimages), that I upload here when "am2pla-site" have finished), but I can prevent to remove these lists to easily add categories... so it is not a difficul task.

Anyway, you asked to divide the CLI apps from the GUI ones, and this is not that easy, all scripts for appimages are similar, and almost all of them have the function to extract icon and .desktop file from it, also if it does not exist.

On the contrary, other portable formats can be easily detected, its enough to check if the installation script contains references to a .desktop file.

However, this is a check that must be done at script level.

The only solution would be to add keywords on the dedicated lines of the list, so I can create a dedicated category.

Categories on the website are not always precise. They all depend on what you write in the dedicated line of the list.

For example, in am2pla-site, to detect programs for the category "web-browser", this is the function I use
```
	elif [ "$category" = web-browser ]; then
		grep -i "$category\|web browser\|browser web\|browser.*web\|google chrome\|chromium\|firefox\|vivaldi\|thorium\|mercury\|librewolf" ./"$arch"-apps | grep -vi "ffwa"  >> "$arch-$category"
	fi
```
note the final `grep -vi "ffwa" ` command, is added not to include lines containing "ffwa", that are lines containing also "firefox" among the keywords.

Oh, well... the whole list shoul be rewrote again. See [x86_64-apps](https://github.com/ivan-hc/AM/blob/main/programs/x86_64-apps)

**Comment by ivan-hc** [comment]
Hey, I just added a new category https://portable-linux-apps.github.io/command-line.html it lacks of icons btw

**Comment by Sush-ruta** [comment]
> thanks for the suggestion
I feel stupid for never checking out the home page. Thanks for pointing that out, lol.

And being a non-coder, I understood only parts of what you said, but it seems like you did make a CLI category, so thanks. :) Many devs on GH should take notes from you on how to listen to user suggestions, even the stupid ones like I made @ivan-hc .

**Comment by ivan-hc** [comment]
many developers criticize me, because I don't use "git" but "web UI"

**Comment by Sush-ruta** [comment]
> many developers criticize me

It is your project, you have no reason to explain your decisions. And what you have created is one of the most complete and exhaustive package managers for Linux since AUR. :clap: 

Also, any updates on [this](https://github.com/ivan-hc/AM/issues/904?notification_referrer_id=NT_kwDOBWNBHrQxMjE4NTI2NzE4NDo5MDM5MDgxNA#issuecomment-2345811730)? Just asking since you are usually super fast in dealing with app requests. :) No worries if the apps are out of scope.

**Comment by ivan-hc** [comment]
> Both of these are from GH but their release/binary are located either inside the repo or in other non-standard location. Which is a problem.
> 
>     * [Penpot Desktop](https://github.com/developerfred/Penpot-Desktop) . [Download link](https://updates.korbsstudio.com/penpot-desktop/penpot-desktop-0.0.3.AppImage) - Auto updates
> 
>     * [go-pd-gui](https://github.com/ManuelReschke/go-pd-gui) . [Download link](https://github.com/ManuelReschke/go-pd-gui/blob/main/fyne-cross/bin/linux-amd64/DRAINY?raw=true)
> 
> 
> Other apps:
> 
>     * [BloomeeTunes](https://github.com/HemantKArya/BloomeeTunes/). This zip file has two folders: `data` and `lib` and a binary file `bloomee`.
> 
>     * [Smart Media Cutter](https://smartmediacutter.com/). [Download link](https://smartmediacutter.com/downloads/) - The binary is in the archive.
> 
>     * [Everdo](https://everdo.net/). [Download link](https://everdo.net/download/1.2.8/)
> 
>     * [Kaspersky Virus Removal Tool](https://www.kaspersky.com/downloads/free-virus-removal-tool). This just downloads a binary called `kvrt.run` that can be used like normal kaspersky antivirus. But there seems to be no version number
> 
>     * [Riichi City](https://www.mahjong-jp.com/home). [Download Link](https://d3qgi0t347dz44.cloudfront.net/release/linuxpack/default_prod_Linux_2.1.5.zip). The archive has the launcher.

I have not seen this comment, sorry. It would be better to open a new issue from now on, just in case.

In this moment I'm adding some missing icons on the catalogue.

**Comment by Sush-ruta** [comment]
Yes, I really should open a new issue. This has become way too cluttered. You can have a dedicated issue for app requests I suppose, since most of the "issues" in this repo are app requests only. @ivan-hc

**Comment by ivan-hc** [comment]
just curious, is kvrt.run an installer? If so, I can't add it.

**Comment by Sush-ruta** [comment]
I downloaded `kvrt.run` and ran it. This is the output:

```bash
❯ ./kvrt.run
Graphical mode is <x11>
Running with root privileges
Generated directory is </tmp/bc52596cdc033cd41117328>
Verifying archive integrity...  100%   SHA256 checksums are OK. All good.
Uncompressing Kaspersky Virus Removal Tool 24.0.5.0 for Linux  100%  
=================================
Running kvrt with args <>
=================================
compver: 24.0.5.0 x86-64 (Jul  9 2024 17:36:48)
Product folder </var/opt/KVRT2024_Data>
=================================
kvrt exited with code <0> ## I CLOSED THE APP AT THIS POINT
=================================
```

This happens every time I run it after as well. So I don't think it's an installer per se. Nothing is installed. The data folder is just to store the files that might be infected.

**Comment by ivan-hc** [comment]
ok, so it is a CLI tool, thanks

about the game Riichi city, I noticed that the 4% of the download is 200 MB, I can't imagine how much is big this program.

Can you tell me exactly what is the content of the archive? This way I don't need to install it to test the script. This is the one I wrote (I had to add .txt to upload it here)

[riichi-city.txt](https://github.com/user-attachments/files/16996364/riichi-city.txt)

**Comment by ivan-hc** [comment]
by reading the PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=riichi-city-bin I can see where the .desktop file and the icn are... but for the installer I used a custom launcher to speedup the process.

My only doubt is the binary name.

**Comment by Sush-ruta** [comment]
The Kaspersky tool is GUI. I simply sent you the CLI output to show that nothing is being installed.
![Screenshot at 21-38-18](https://github.com/user-attachments/assets/5a53bbdf-cdd4-4c6d-8d8c-0fb411d9c3e3)

Also, Riichi City is 4.1 GB. I am downloading the archive again (I deleted earlier when I installed the steam edition). I will send the contents when download is complete. @ivan-hc

**Comment by Sush-ruta** [comment]
![Screenshot at 21-51-25](https://github.com/user-attachments/assets/ff5fb956-8cc0-419a-a991-b2466fa977a5)

@ivan-hc

**Comment by ivan-hc** [comment]
so "Mahjong-JP.x86_64" is the name of the main exacutable, in the root of the extracted directory... thank you

**Comment by ivan-hc** [comment]
@Sush-ruta done https://github.com/ivan-hc/AM/commit/afab7abeb7d70b6aaa83ca85f48ad2407c9a0aa4

the Kaspersky client is named "kvrt"

**Comment by ivan-hc** [comment]
an antivirus is something that should be updated daily... maybe I should corect the script to create an AM-updater file that downloads the script every day

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM/commit/3c51a7b8ab1180e528cfc884fec0471a6d51e454

@Sush-ruta if this is enough, from now on we will talk in new opened issues, as we said before

**Comment by Sush-ruta** [comment]
Hi. Sorry for my delayed response. This is awesome as usual. Thank you @ivan-hc and the idea to update kvrt daily is a good one too. I just noticed one thing. Even though I had installed Penpot Desktop earlier (some time back), the website from where the appimage is downloading seems down (cloudflare issues). I should have checked that before PRing, sorry. Maybe it would be wise to take it down. Also taking down other non-functional scripts like `elapp` for instance.

Also, some apps have generic icons (flutter apps like photon and Bloomee) or no icons (kvrt). I am trying to edit the scripts to include proper icons. Will PR. And thanks again

**Comment by ivan-hc** [comment]
> Hi. Sorry for my delayed response. This is awesome as usual. Thank you @ivan-hc and the idea to update kvrt daily is a good one too. I just noticed one thing. Even though I had installed Penpot Desktop earlier (some time back), the website from where the appimage is downloading seems down (cloudflare issues). I should have checked that before PRing, sorry. Maybe it would be wise to take it down. Also taking down other non-functional scripts like `elapp` for instance.

"elapp" is already marked as "spooky" because they have not updated the SSL certificate, the day they will notice the issue, the app should be installable. Until then users of that app need to contact the developer (and keep me updated in case of changes).

About "penpot", I noticed that it is not an official app, but the issue should have the same solution as "elapp".

Anyway, it is worth to remove them, just in case.

"AM" should serve to encourage the community to keep certain projects alive, and (why not?) maybe maintain a script repository always active, outside of this one. It would be great if more and more users could provide maintenance of individual scripts, without having to depend on my approval (and that's also why it's possible to use alternative repositories to this one, in case something were to happen to me, "AM" could continue).

> Also, some apps have generic icons (flutter apps like photon and Bloomee) or no icons (kvrt). I am trying to edit the scripts to include proper icons. Will PR. And thanks again

merged

**Comment by Sush-ruta** [comment]
I am sure `am` will enjoy the success it deserves. Meanwhile, I will continue to contribute what my limited (non-existent) capabilities allow me to. :)
