### ISSUE TITLE
Some apps do not update properly

### ISSUE THREAD

**Issue by marco-calautti** [ivan-hc/AM#909]
Some apps like duckstation or Retroarch do not update when a new version is available, since AM/AppMan uses the download url for the version. For these two apps, the url is always the same, as the original dev simply updates the AppImage in place.

This issue could potentially affect other apps as well.

**Comment by ivan-hc** [comment]
About RetroArch, being it an unofficial appImage, I can source the version from repology.org

About Duckstation, is it ok if I source not from daily and not from rolling but from the previous version with tag? I see that it is only two weeks older than "rolling", but updated anyway.

**Comment by ivan-hc** [comment]
![Istantanea_2024-08-31_17-44-45](https://github.com/user-attachments/assets/e0bbd573-e405-40b0-ae51-adc8df6b0270)

**Comment by ivan-hc** [comment]
![Istantanea_2024-08-31_17-45-43](https://github.com/user-attachments/assets/98d0add6-d970-4646-a88a-5334f4959fc5)

**Comment by ivan-hc** [comment]
Take a look to the above two commits

**Comment by marco-calautti** [comment]
I guess it's fine for Retroarch, but duckstation literally has a kind "rolling" release cycle. Even when running the AppImage, the first thing it shows up is that a new update is available, as it looks for the continuously built new versions.

**Comment by marco-calautti** [comment]
Can't you get the latest AppImage from the releases, and use the git commit hash for the version?
https://github.com/stenzek/duckstation/releases/tag/latest

**Comment by marco-calautti** [comment]
I think you can literally just use the URL of the commit associated to the release. For example, the current latest release has the commit at: https://github.com/stenzek/duckstation/commit/b2577ef8bdaae99840874b6dae8146f0316357b4

**Comment by ivan-hc** [comment]
see https://api.github.com/repos/stenzek/duckstation/releases/latest

if I get the first ID, using the following command
```
curl -Ls https://api.github.com/repos/stenzek/duckstation/releases/latest | sed 's/[()",{} ]/\n/g' | grep "^[[:digit:]]" | head -1
```
and result
```
170798758
```
from the first "id" reference, would be enough? Or I should use a date instead?

**Comment by marco-calautti** [comment]
I think the full commit url is the most reliable value

**Comment by ivan-hc** [comment]
can you pont me to the line?

**Comment by ivan-hc** [comment]
Also the date seems to be reliable

![Istantanea_2024-08-31_18-36-28](https://github.com/user-attachments/assets/f0136cfc-b8c7-4c2d-b7da-824a87477d3f)

**Comment by ivan-hc** [comment]
If not I can do something like this, normally commits start with a number and contain lowercased letters, like this

![Istantanea_2024-08-31_18-42-47](https://github.com/user-attachments/assets/20e6cc64-61ad-41dd-927d-e9f03f37175c)

**Comment by ivan-hc** [comment]
I need to test the approach with curl, wget and wget2 always, to see if it works for all clients (and to prevent to include "jq" as dependence)

![Istantanea_2024-08-31_18-50-12](https://github.com/user-attachments/assets/1e826ab5-0f25-4dc2-979a-53545391c245)

**Comment by ivan-hc** [comment]
if you have a better idea let me know

**Comment by ivan-hc** [comment]
or simply
```
curl -Ls https://api.github.com/repos/stenzek/duckstation/releases/latest | grep "Commits" | tr ' ' '\n' | grep [0-9] |  head -1
```

**Comment by ivan-hc** [comment]
> I think the full commit url is the most reliable value

![Istantanea_2024-08-31_19-44-45](https://github.com/user-attachments/assets/ca7af5dd-164d-43b0-9ed2-9782d3f99fbb)

la soluzione più rapida e indolore, correggimi se sbaglio.

**Comment by marco-calautti** [comment]
I did not understand that github was returning a json at that url. Then yes, getting the "url" entry in the json is the best and simplest option.
