### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by Graninius** [ivan-hc/AM#913]
After the update, I can't run AppMan. It tries to create the folder **/MyAppImages** and encounters a permission error. My default folder is **/home/user/MyAppImages,** and I don't know why it's trying to move it to the root folder.

`appman -u
mkdir: can't create a folder «/MyAppImages»: No permission
`

**Comment by Samueru-sama** [comment]
What's the output of cat `${XDG_CONFIG_HOME:-~/.config}/appman/appman-config`?

**Comment by Graninius** [comment]
> What's the output of `cat ${XDG_CONFIG_HOME:-~/.config}/appman/appman-config`?

`cat ${XDG_CONFIG_HOME:-~/.config}/appman/appman-config
/MyAppImages/`

Hmm... I don't know when that changed

**Comment by Samueru-sama** [comment]
> > What's the output of `cat ${XDG_CONFIG_HOME:-~/.config}/appman/appman-config`?
> 
> `cat ${XDG_CONFIG_HOME:-~/.config}/appman/appman-config /MyAppImages/`
> 
> Hmm... I don't know when that changed

Alright somehow your file always contained `/MyAppImages/` it seems.

I recently changed appman to be able to work on any location and not just $HOME.

It has a check for existing config files that do not start with a leading `/` as that makes them assume that they are a location in `$HOME`.

However it seems your file always had `/MyAppImages/`? with both a leading and trailing slash?

In any case to solve the issue just remove that file and then run appman again, this time tell it to use `MyAppImages` and everything should be solved and the generated file should contain the full path now.

**Comment by Graninius** [comment]
> > > What's the output of `cat ${XDG_CONFIG_HOME:-~/.config}/appman/appman-config`?
> > 
> > 
> > `cat ${XDG_CONFIG_HOME:-~/.config}/appman/appman-config /MyAppImages/`
> > Hmm... I don't know when that changed
> 
> Alright somehow your file always contained `/MyAppImages/` it seems.
> 
> I recently changed appman to be able to work on any location and not just $HOME.
> 
> It has a check for existing config files that do not start with a leading `/` as that makes it assume that it is a location in `$HOME`.
> 
> However it seems your file always had `/MyAppImages/`? with both a leading and trailing slash?
> 
> In any case to solve the issue just remove that file and then run appman again, this time tell it to use `MyAppImages` and everything should be solved and the generated file should contain the full path now.

Yes, it had both slashes. After removing the file, it asked me for the new path. Once I set it to **/home/user/MyAppImages,** everything started working fine

**Comment by ivan-hc** [comment]
I don't understand how it always had the two slashes on the sides if I always made sure they didn't appear, assuming that the directory was in $HOME

Anyway, as Samuel says, you can simply remove the old configuration file and regenerate a new one at the first start of AppMan

Now AppMan, from version 8.1 (2 days) supports directories outside of $HOME, the old behavior should still be supported (in fact it works for me, I still have the old file), but by default it should create the full path for new installations.

In your case, it gives you an error because the first slash means "root", i.e. /

**Comment by Graninius** [comment]
Solved
