### ISSUE TITLE
AppMan downloads old version of "mcpelauncher"

### ISSUE THREAD

**Issue by LostWarriorr** [ivan-hc/AM#921]
when downloading mcpelauncher through Appman it downloads an old version ( 0.12.1.177) when the current version is (1.0.0-798).

This appears to be an issue with how the developers publish builds of "Minecraft Linux Launcher" with "mcpelauncher" being the former name.

According to their website any Appimage builds will be released at this github link which currently has version 1.0.0-798: https://github.com/minecraft-linux/appimage-builder   which is different than the listed download link on the catalog: https://github.com/minecraft-linux/mcpelauncher-manifest   The main release post has fairly new version of 1.0.0-465 but the Assets at the bottom of release have the 0.12.1.177 version.

**Comment by ivan-hc** [comment]
I see, the source I use groups 2000+ artifacts in one nightly release https://github.com/minecraft-linux/mcpelauncher-manifest/releases and since the command uses `head -1`, the first on top is the one it gets first.

Thank you for pointing me to the latest stable build, I'll fix it asap.
