### ISSUE TITLE
[Request] Add App

### ISSUE THREAD

**Issue by abhishekmj303** [ivan-hc/AM#929]
ente-auth: [github.com/ente-io/ente/releases?q=tag%3Aauth-v3](github.com/ente-io/ente/releases?q=tag%3Aauth-v3)

**Comment by ivan-hc** [comment]
I am a bit confusing, we have already "ente" that redirects to https://github.com/ente-io/photos-desktop/releases, while the one you asked is named "ente-auth" among their releases, at https://github.com/ente-io/ente

Can you clarify the exact name I should give to each one of them?

**Comment by abhishekmj303** [comment]
They have 2 products one photos app and another authenticator app. This the link of the website: [https://ente.io/auth/](https://ente.io/auth/)

You can rename Ente Photos to `ente-photos` or keep it as `ente` for backwards compatibility. And name the Ente Auth as `ente-auth`.

But both of the product is in the same repo (except desktop release of photos) that is why the url to get the release is by using the query: tag starting with "Auth".

**Comment by ivan-hc** [comment]
Done, thanks for reporting

- https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/f46d66b551ce9ec84c3d79a3028570ccc9dfdf2b
- https://github.com/ivan-hc/AM/commit/b55999dba60f31e1b139f91a83b7df2b464791e0
- https://github.com/ivan-hc/AM/commit/d8345eaec3ab42194dd6aeab2aebafe011107b3e
