### ISSUE TITLE
Using `am -h` command shows an error

### ISSUE THREAD

**Issue by AdilDevStuff** [ivan-hc/AM#944]
# Premise
"AM"/"AppMan" is just a tool to provide applications easily and quickly and is only responsible for integrating the AppImages into the system and installing the various programs available, respecting the following order (refer to the option "-d" to download the installation script without installing it):
- creation of the base directories and the removal script
- download of the package
- creation of the version file and the update script
- possibly, extraction of the icons and .desktop files, if needed

The malfunction of the installation scripts will then be taken into account. On the contrary, any malfunction related to individual applications is the responsibility of the related developer or packager. Refer to the option "-a" to know the sources of each program listed here, so you can contact them to report the bug.

--------------------------------------------------

## Are you using "AM" or "AppMan"?
AM

## What GNU/Linux distribution are you using it on?
Arch Linux

## Please, describe the bug
Using `am -h` command prints the following error: 
`/usr/local/bin/am: line 900: less: command not found`

## What are the steps/commands to perform?
Use `am -h`

## What is the expected behavior?
It should print help or whatever happens when using `-h`

**Comment by Samueru-sama** [comment]
@AdilDevStuff you don't have `less` installed. `sudo pacman -S less`

A while ago I tried to make `less` optional but couldn't lol.

**Comment by AdilDevStuff** [comment]
> @AdilDevStuff you don't have `less` installed. `sudo pacman -S less`
> 
> A while ago I tried to make `less` optional but couldn't lol.

Ohh, So less is a package :D I didn't know that, I was thinking of it as the less word in english and figured something was wrong with the am script :p

**Comment by AdilDevStuff** [comment]
It works now, so im closing this!
