### ISSUE TITLE
Icons for appimages

### ISSUE THREAD

**Issue by sakebaev** [ivan-hc/AM#953]
Hi! I'm facing an issue with displaying icons for programs in AppImage format. I'm using ArchLinux, BSPWM, Rofi, and Fish shell.

The program icons are located in the /opt directory, at the following path:

/opt/am/application-name/icon/application-icon,

where application-name is the name of the program, and application-icon is the icon itself.

Rofi does not display icons when they are located in this path. However, if I move or copy the icon to the local folder $HOME/.local/share/icons and change the path to it in the .desktop file located in /opt, it works correctly.

The installation script runs without errors and correctly places all files in the appropriate paths, including the icons. I suspect that the issue may be related to a lack of read access or unset environment variables. I'm using AM, not AppMan.

I would appreciate any help!

**Comment by ivan-hc** [comment]
Hi

> The program icons are located in the /opt directory, at the following path:
> 
> /opt/am/application-name/icon/application-icon,

its strange, the icon name and the path of the installed apps should be this
```
/opt/appname/icons/appname
```
and all launchers have this path in the "Icon=" entry, in the .desktop file. Are you sure you didn't write it wrong?

**Comment by sakebaev** [comment]
Yes. I made a mistake. It is indeed located there.

**Comment by ivan-hc** [comment]
However if the path to the icon is indicated in the .desktop file, the icon should certainly appear, and this is why I specify it in my scripts, to avoid having launchers without icons.

![Istantanea_2024-09-19_22-36-06 png](https://github.com/user-attachments/assets/f86f03f2-e268-4e16-89f1-9120ace86536)

I don't know how Rofi handles launchers, maybe it matches the command to an icon without taking the .desktop file into account?

How does Rofi handle .desktop files?

**Comment by ivan-hc** [comment]
It seems that my cooperator @Samueru-sama had the same issue and contacted the Rofi developers https://github.com/davatorium/rofi/issues/1977 I'm just reading the issue.

**Comment by sakebaev** [comment]
> Hi
> 
> > The program icons are located in the /opt directory, at the following path:
> > /opt/am/application-name/icon/application-icon,
> 
> its strange, the icon name and the path of the installed apps should be this
> 
> ```
> /opt/appname/icons/appname
> ```
> 
> and all launchers have this path in the "Icon=" entry, in the .desktop file. Are you sure you didn't write it wrong?



> Hi
> 
> > The program icons are located in the /opt directory, at the following path:
> > /opt/am/application-name/icon/application-icon,
> 
> its strange, the icon name and the path of the installed apps should be this
> 
> ```
> /opt/appname/icons/appname
> ```
> 
> and all launchers have this path in the "Icon=" entry, in the .desktop file. Are you sure you didn't write it wrong?


Yes. I made a mistake. It is indeed located there


> However if the path to the icon is indicated in the .desktop file, the icon should certainly appear, and this is why I specify it in my scripts, to avoid having launchers without icons.
> 
> ![Istantanea_2024-09-19_22-36-06 png](https://private-user-images.githubusercontent.com/88724353/369160947-f86f03f2-e268-4e16-89f1-9120ace86536.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NzkzMDcsIm5iZiI6MTcyNjc3OTAwNywicGF0aCI6Ii84ODcyNDM1My8zNjkxNjA5NDctZjg2ZjAzZjItZTI2OC00ZTE2LTg5ZjEtOTEyMGFjZTg2NTM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDIwNTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZDhkMzI5M2ViMGYzNGI3ZDE4MWRlM2Y2ZWNiYjFjZTJkZGYxMTFjMWU5YTM1ZDQwYTA4MjkzZTNhZWJlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oeLqLnuGq0nHeuTjpSBKh5HFGIkiw96zvXocsB28iJ4)
> 
> I don't know how Rofi handles launchers, maybe it matches the command to an icon without taking the .desktop file into account?
> 
> How does Rofi handle .desktop files?

It definitely takes the path to the icon from the .desktop file, but for some reason it doesn't want to use it if it's located in /opt, as if it doesn't have access or something like that.

**Comment by ivan-hc** [comment]
From what I have seen in that issue...

> It seems that my cooperator @Samueru-sama had the same issue and contacted the Rofi developers [davatorium/rofi#1977](https://github.com/davatorium/rofi/issues/1977) I'm just reading the issue.

...it seems that they have fixed the issue.

@Samueru-sama what you suggest?

**Comment by sakebaev** [comment]
> From what I have seen in that issue...
> 
> > It seems that my cooperator @Samueru-sama had the same issue and contacted the Rofi developers [davatorium/rofi#1977](https://github.com/davatorium/rofi/issues/1977) I'm just reading the issue.
> 
> ...it seems that they have fixed the issue.
> 
> @Samueru-sama what you suggest?

But not for me. What else could be the problem?

**Comment by sakebaev** [comment]
Could it be related to Rofi's settings? Maybe it doesn’t know it can take the icon from there or can’t access it.

**Comment by sakebaev** [comment]
Maybe you need to set an environment variable or grant Rofi access for this?

**Comment by Samueru-sama** [comment]
>Rofi does not display icons when they are located in this path. However, if I move or copy the icon to the local folder $HOME/.local/share/icons and change the path to it in the .desktop file located in /opt, it works correctly.

Like Ivan said, that's an issue with [rofi](https://github.com/davatorium/rofi/issues/1977) that expects the path to the image to contain a `.` 

It also surprised me when I ran into it, the issue was fix but rofi hasn't had a stable release in years, so the solution is using rofi-git aur package or using this [rofi-appimage](https://github.com/Samueru-sama/rofi-AppImage) with am.

**Comment by sakebaev** [comment]
> > Rofi does not display icons when they are located in this path. However, if I move or copy the icon to the local folder $HOME/.local/share/icons and change the path to it in the .desktop file located in /opt, it works correctly.
> 
> Like Ivan said, that's an issue with [rofi](https://github.com/davatorium/rofi/issues/1977) that expects the path to the image to contain a `.`
> 
> It also surprised me when I ran into it, the issue was fix but rofi hasn't had a stable release in years, so the solution is using rofi-git aur package or using this [rofi-appimage](https://github.com/Samueru-sama/rofi-AppImage) with am.

Thank you. I'll give it a try. It's 4 AM, and I still haven't gone to bed. I'll let you know later if it helped.

**Comment by Samueru-sama** [comment]
> > > Rofi does not display icons when they are located in this path. However, if I move or copy the icon to the local folder $HOME/.local/share/icons and change the path to it in the .desktop file located in /opt, it works correctly.
> > 
> > 
> > Like Ivan said, that's an issue with [rofi](https://github.com/davatorium/rofi/issues/1977) that expects the path to the image to contain a `.`
> > It also surprised me when I ran into it, the issue was fix but rofi hasn't had a stable release in years, so the solution is using rofi-git aur package or using this [rofi-appimage](https://github.com/Samueru-sama/rofi-AppImage) with am.
> 
> Thank you. I'll give it a try. It's 4 AM, and I still haven't gone to bed. I'll let you know later if it helped.

It should as quick as `sudo pacman -R rofi && am -i rofi` and now check if the icons get displayed on rofi.

**Comment by sakebaev** [comment]
> > > > Rofi does not display icons when they are located in this path. However, if I move or copy the icon to the local folder $HOME/.local/share/icons and change the path to it in the .desktop file located in /opt, it works correctly.
> > > 
> > > 
> > > Like Ivan said, that's an issue with [rofi](https://github.com/davatorium/rofi/issues/1977) that expects the path to the image to contain a `.`
> > > It also surprised me when I ran into it, the issue was fix but rofi hasn't had a stable release in years, so the solution is using rofi-git aur package or using this [rofi-appimage](https://github.com/Samueru-sama/rofi-AppImage) with am.
> > 
> > 
> > Thank you. I'll give it a try. It's 4 AM, and I still haven't gone to bed. I'll let you know later if it helped.
> 
> It should as quick as `sudo pacman -R rofi && am -i rofi` and now check if the icons get displayed on rofi.

Hello, thank you. That helped. Now everything is as it should be.
