### ISSUE TITLE
Problem with certain apps

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#955]
Hi. There are problems with certain apps with `appman`.

1. [Todoist](https://portable-linux-apps.github.io/apps/todoist.html)
This is the `.desktop` file of the `appman` installed program:
```
❯ bat todoist-AM.desktop
───────┬──────────────────────────────────────────────────────────────────────────────────────────────
       │ File: todoist-AM.desktop
───────┼──────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [Desktop Entry]
   2   │ Name=Todoist
   3   │ Comment=Todoist for linux
   4   │ Exec=/home/sushruta/.local/bin/todoist
   5   │ Terminal=false
   6   │ Type=Application
   7   │ Icon=/home/sushruta/AppMan/todoist/icons/todoist
   8   │ StartupWMClass=Todoist
   9   │ X-AppImage-Version=1.0.1
  10   │ Categories=Office;Utility;
  11   │ X-AppImage-BuildId=18KSQu6pNIo9LTVUgaF42F4S6Ku
───────┴──────────────────────────────────────────────────────────────────────────────────────────────
```
Running `$HOME/.local/bin/todoist` does nothing, so the application does not launch from the app menu. However, launching directly from `~/AppMan/todoist/todoist` brings up the appimagelauncher dialog box (integration), so I guess that works. I don't know why the .local/bin symlink does not work.

2. [Evince](https://portable-linux-apps.github.io/apps/evince.html) and [baobab-gtk3](https://portable-linux-apps.github.io/apps/baobab-gtk3.html)
```
❯ appman install evince baobab-gtk3
============================================================================

                  START OF ALL INSTALLATION PROCESSES

============================================================================

 ◆ "EVINCE": starting installation script

Document-Viewer_46.3.1-2- 100%[===================================>]  55.69M  6.23MB/s    in 9.1s    
This doesn't look like a squashfs image.
Failed to open squashfs image
This doesn't look like a squashfs image.
Failed to open squashfs image
sed: can't read ./evince.desktop: No such file or directory
mv: cannot stat './evince.desktop': No such file or directory

 "EVINCE" INSTALLED (56 MB OF DISK SPACE)
____________________________________________________________________________

 ◆ "BAOBAB-GTK3": starting installation script

Disk_Usage_Analyzer-3.38. 100%[===================================>]   3.74M  3.83MB/s    in 1.0s    
This doesn't look like a squashfs image.
Failed to open squashfs image
This doesn't look like a squashfs image.
Failed to open squashfs image
sed: can't read ./baobab-gtk3.desktop: No such file or directory
mv: cannot stat './baobab-gtk3.desktop': No such file or directory

 "BAOBAB-GTK3" INSTALLED (4 MB OF DISK SPACE)
____________________________________________________________________________
============================================================================
```
None of them show up in app menu.

3. [OBS Studio](https://portable-linux-apps.github.io/apps/obs-studio.html)
```
❯ appman install obs-studio
============================================================================

                  START OF ALL INSTALLATION PROCESSES

============================================================================

 ◆ "OBS-STUDIO": starting installation script

OBS-Studio_30.2.1-1-archi 100%[===================================>] 189.86M  4.90MB/s    in 34s     
This doesn't look like a squashfs image.
Failed to open squashfs image
This doesn't look like a squashfs image.
Failed to open squashfs image
sed: can't read ./obs-studio.desktop: No such file or directory
mv: cannot stat './obs-studio.desktop': No such file or directory

 "OBS-STUDIO" INSTALLED (190 MB OF DISK SPACE)
____________________________________________________________________________
============================================================================
```
Does not show up in app menu.

**Comment by ivan-hc** [comment]
I have tested my AppImages (baobab-gtk3, evince and obs-studio) with AM and AppMan, no issues. Something is wrong with your squashfs installation.

About Todoist, I get this message
```
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_todoisUdLR2r/AppRun.
Segmentation fault (core dump created)*
```
*I have tried to translate the last line in english, this is the screenshot in italian

![Istantanea_2024-09-20_13-14-28 png](https://github.com/user-attachments/assets/db68b121-da70-4cdf-a333-0d630512f6cd)

anyway, to show the message, the app interacts with the action, so the .desktop file should work. Try to run `todoist` from the terminal and see the error message.

**Comment by ivan-hc** [comment]
> appimagelauncher

have you it installed? it may cause problems, remove it asap, its an obsolete piece of software.

**Comment by Sush-ruta** [comment]
`appimagelauncher` is the first software I install after distro installation since I shifted to Linux ~ 5 years ago. I mainly use it to install appimages that I compiled, downloaded from [Pling Store](https://www.pling.com/p/1972991/) etc. I guess I can integrate them manually with `am`.
Also simply running `todoist` on terminal does nothing:
```
❯ todoist

```
In fact running in using the binary in `~/AppMan/ todoist/todoist` also does not work.

I see that the software itself is an [unofficial wrapper](https://github.com/cyfrost/todoist-linux/). That would not be necessary any more since Todoist has its own official appimage releases on its [website](https://todoist.com/downloads). This is the [download link](https://todoist.com/linux_app/appimage). @ivan-hc

**Comment by ivan-hc** [comment]
About [squashfs-tools](https://pkgs.org/download/squashfs-tools), what distro you have and what is the status of this package on your system?

**Comment by ivan-hc** [comment]
Why a bad choice? Its a good distro (rich of paywalls, but yet user friendly at least, better than Ubuntu).

I don't know why you get these errors, but you should try to re-install the packages and see what is the problem. Also the latest appimage you suggested and you were unable to add in the other issue works for me.

I use always AppMan in my tests, so I'm sure that it works for AM too.

**Comment by ivan-hc** [comment]
Also, have you tried to run `./appimagename --appimage-extract` ? For example
```
./obs-studio --appimage-extract
```

**Comment by Sush-ruta** [comment]
No complains with eOS other than them following the apple way of "no modification allowed because devs know the best". 

I will try to reinstall `squashfs-tools` and try some time later, if it is solved, I will let you know. Thanks for the advice. 
Also:
```
~/AppMan/evince 
❯ ./evince --appimage-extract
This doesn't look like a squashfs image.
Failed to open squashfs image
```

**Comment by ivan-hc** [comment]
its really strange, is this a fresh installation or you have always used AM/AppMan on this system?

**Comment by Sush-ruta** [comment]
I have been using `appman` since discovering it about a year ago. Always had problem with these ones, today I remembered to open the issue. I will try to boot an Ubuntu installation and try this there and see if there are problems. For now, if you feel there are no issues for all users, you can close this @ivan-hc

**Comment by ivan-hc** [comment]
You don't need to reboot another installation, its better to face the issue now.

Something is missing in the squashfs-tolls, maybe a different compression language to use. Let me investigate.

**Comment by ivan-hc** [comment]
What is your FUSE (2 and 3) installation status? And are `binutils` (command `strip` exactly) available?

**Comment by Sush-ruta** [comment]
```
❯ sudo apt install libfuse2:amd64 libfuse3-3:amd64 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libfuse2 is already the newest version (2.9.9-5ubuntu3).
libfuse3-3 is already the newest version (3.14.0-4~22.04.sav0).
libfuse3-3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

❯ sudo apt install fuse3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fuse3 is already the newest version (3.14.0-4~22.04.sav0).
fuse3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

❯ which strip
/usr/bin/strip
```
@ivan-hc

**Comment by ivan-hc** [comment]
I know sav0, "SavOS" PPAs were something I used before to build AppImages, but developed by one person. Is that "fuse3" a reliable one?

**Comment by ivan-hc** [comment]
Anyway it seems that appimagelauncher caused the issue, and you should get rid of all files left with the latest appimagelauncher installation and then reboot.

**Comment by Sush-ruta** [comment]
I will try to remove the sav0 ppa and reinstall fuse3 to avoid problems. I will also remove `appimagelauncher` and try again. I will need to install the appimages I have with appimagelauncher using `am`. It will take some time. You can close this meanwhile, I will update here. @ivan-hc Thank you for the help.

**Comment by ivan-hc** [comment]
I'll keep this opened until you confirm that the solution works for you, don't worry. It may help others with your same issue.

**Comment by Sush-ruta** [comment]
I uninstalled `appimagelauncher`, the problem was magically solved. Thanks for the patient advices @ivan-hc . Closing the issue now, finally.
