### ISSUE TITLE
portable app suggestions

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#956]
Here are some apps that are either problematic appimages or portable apps that are beyond my capabilities to add.

- [kardi notes](https://www.kardi.tech/#notes). [Download link](https://www.kardi.tech/notes/downloads/kardi%20notes.AppImage)
- [spmp](https://github.com/toasterofbread/spmp).
There is an appimage release, but installing it with appman gives the following error:
```
❯ am -e toasterofbread/spmp spmp              
============================================================================

                  START OF ALL INSTALLATION PROCESSES

============================================================================

 ◆ "SPMP": starting installation script

spmp-v0.4.1-linux-x86_64. 100%[===================================>] 207.14M  4.53MB/s    in 38s     
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
This doesn't look like a squashfs image.
Failed to open squashfs image
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
This doesn't look like a squashfs image.
Failed to open squashfs image
sed: can't read ./spmp.desktop: No such file or directory
mv: cannot stat './spmp.desktop': No such file or directory

 "SPMP" INSTALLED (208 MB OF DISK SPACE)
____________________________________________________________________________
============================================================================

                  END OF ALL INSTALLATION PROCESSES

             The following new programs have been installed:

 ◆ spmp 0.4.1

============================================================================
```
It does not show up in menu.
- [Trilium Notes](https://github.com/zadam/trilium/).
The `tar.xz` file in Release section has the following structure:
```bash
Compressed/trilium-linux-x64-0.63.7/trilium-linux-x64 
❯ ls
anonymize-database.sql   icudtl.dat            LICENSES.chromium.html    trilium-portable.sh
chrome_100_percent.pak   libEGL.so             locales                   trilium-safe-mode.sh
chrome_200_percent.pak   libffmpeg.so          resources                 v8_context_snapshot.bin
chrome_crashpad_handler  libGLESv2.so          resources.pak             version
chrome-sandbox           libvk_swiftshader.so  snapshot_blob.bin         vk_swiftshader_icd.json
dump-db                  libvulkan.so.1        trilium
icon.png                 LICENSE               trilium-no-cert-check.sh
```
- [JabRef](https://github.com/JabRef/jabref).
The `tar.gz` file in Release section has the following structure:
```bash
Downloads/Compressed/JabRef took 5s 
❯ ls
bin  lib

Downloads/Compressed/JabRef 
❯ cd bin && ls
JabRef
```
- [Dorion](https://github.com/SpikeHD/Dorion)
The `tar.gz` file in Release section has the following structure:
```bash
❯ ls
config.json  dorion  icons  injection  logs  plugins  profiles  themes  updater
```

**Comment by Sush-ruta** [comment]
Also [glab](https://gitlab.com/gitlab-org/cli). [Download link](https://gitlab.com/gitlab-org/cli/-/releases).

Can Gitlab binaries/appimages be automatically found with `am -t` or `am -e` like it does with GitHub? I am not technologically literally, but are GH and GL that different from each other? @ivan-hc 
For that matter, can [codeberg](https://codeberg.org/) also be supported?

**Comment by ivan-hc** [comment]
> Also [glab](https://gitlab.com/gitlab-org/cli). [Download link](https://gitlab.com/gitlab-org/cli/-/releases).
> 
> Can Gitlab binaries/appimages be automatically found with `am -t` or `am -e` like it does with GitHub? I am not technologically literate, but are GH and GL that different from each other? @ivan-hc For that matter, can [codeberg](https://codeberg.org/) also be supported?

about "gitlab" we need the repo ID, about codeberg I'm not sure but the API scheme should be similar to the github's

**Comment by Sush-ruta** [comment]
Thank you for the investigation into the mattter @ivan-hc . I suppose gitlab can't be "integrated" into `am -t` or `am -e` the way GH is. That is what I understood anyway. Please correct me if I am wrong.

**Comment by ivan-hc** [comment]
> Thank you for the investigation into the mattter @ivan-hc . I suppose gitlab can't be "integrated" into `am -t` or `am -e` the way GH is. That is what I understood anyway. Please correct me if I am wrong.

yes, -e only supports appimages from github, no other formats or sites

**Comment by Sush-ruta** [comment]
That's ok, it was just a suggestion so that I won't have to bother you with GL app scripts. And I see you added all the apps I recommended. Many thanks. @ivan-hc

**Comment by ivan-hc** [comment]
the reason is because github is the only one that have a standard API url, maybe I can extend this to codeberg, but gitlab works in a totally different way. Just search "gitlab" in the repository nd you will see how the $version variable and the download URL works... and note that for this last "glab" you suggested I used a totally different trick (run `am -d glab` to see the script).

About managing different formats other than AppImages, its even hard to do, you know, different archive formats to extract, different structure of directories, maybe the binary have a different name (see "JabRef"). Its a mess.

AppImage is the only one that works normally.

**Comment by Sush-ruta** [comment]
I see. You have made the `am` script so easy that I often forget the difficult and complicated stuff that goes on under the hood. Appreciate the explanation :pray: @ivan-hc

**Comment by Sush-ruta** [comment]
Sorry I am writing here, not creating a new issue so as not to make a mess.

- [Alien-Tec UI](https://sourceforge.net/projects/alien-tec-ui/)
- [elvish](https://elv.sh/) [Download link](https://elv.sh/get/)

Mane github repos, for example: [effer](https://github.com/Merkoba/Effer) have single binary releases. If there are multiple, I can use keywords to pinpoint which one to choose, but if there is only one, `am -t` with option 2 is not able to locate it (unless I am making some mistake). Kindly advise @ivan-hc .

**Comment by ivan-hc** [comment]
![Istantanea_2024-09-21_01-43-08 png](https://github.com/user-attachments/assets/9e284969-21f6-4d35-9331-0e7e9c8364fe)

for "grep" I added `http.*download.*effer$` because the URL is https://github.com/Merkoba/Effer/releases/download/v2.0.3/effer, so it detects the URL for download and that finishes for "effer"

Just created all three above, I'm going testing the scripts before I upload them.

**Comment by ivan-hc** [comment]
done https://github.com/ivan-hc/AM/commit/ed4fb2ec96a6fa6ad3443b4b87dddb58e637ea3f
