### ISSUE TITLE
How do I remove AM or Appman? 

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#958]
(there doesnt seem to be anything related to this in the readme)

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/AM#uninstall

![Istantanea_2024-09-21_15-09-56 png](https://github.com/user-attachments/assets/af950b8d-f372-4891-879b-0c27b9ec4e3a)
![Istantanea_2024-09-21_15-09-32 png](https://github.com/user-attachments/assets/a7e6a814-336c-4e3f-b082-a527f9f43590)

**Comment by candrapersada** [comment]
but not found uninstall AppMan https://github.com/ivan-hc/AM?tab=readme-ov-file#uninstall-am

**Comment by ivan-hc** [comment]
@candrapersada you are right, just fixed https://github.com/ivan-hc/AM/commit/c21cd0a90b01a14c4ab6d92f04649fc1ce11f5f7

Please, see https://github.com/ivan-hc/AM/tree/main#uninstall
