### ISSUE TITLE
[Package Request] GNU IceCat

### ISSUE THREAD

**Issue by contrarybaton60** [ivan-hc/AM#961]
# List of AppImages to add
-  GNU IceCat

## If available on other sites
- icecat (lowercase, this will be the command to use)
- https://www.gnu.org/software/gnuzilla/ (URL, DO NOT use direct download link)
- download page (if different from the main page)

Since GNU doesn't provide binaries or AppImages for IceCat, we would have to use one of the following:
[AUR Package "icecat"](https://aur.archlinux.org/packages/icecat)
[AUR Package "icecat-bin" which uses Fedora package below](https://aur.archlinux.org/packages/icecat-bin)
[Fedora Package](https://koji.fedoraproject.org/koji/packageinfo?packageID=19055)
[icecatbrowser.org, packaged by "Chippy"](https://icecatbrowser.org/download.html)
[GNU Savannah Git](https://git.savannah.gnu.org/cgit/gnuzilla.git/)

- description of the application

GNU version of the Firefox ESR browser.

**Comment by ivan-hc** [comment]
I think you are talking about https://icecatbrowser.org and https://icecatbrowser.org/all_downloads.html

I'll see what to do, thanks

**Comment by contrarybaton60** [comment]
yeah, Chippy (who packages it) does contribute with the GNUzilla/IceCat team (example: https://lists.gnu.org/archive/html/gnuzilla-dev/2024-07/index.html) so I think we're good using his packages. We can always use the Fedora package in case he stops maintaining it.

**Comment by ivan-hc** [comment]
uhm... Fedora you said... it seems that they can be extracted via `tar`, maybe we can use the official package from Fedora repos?

**Comment by contrarybaton60** [comment]
probably yeah

**Comment by ivan-hc** [comment]
just noticed that on Fedora "icecat" may need additional packages, like "icecat-X11" and "icecat-wayland", just as a Debian package does

I need to study alternative ways

**Comment by ivan-hc** [comment]
Where I can find a .deskto file?

**Comment by ivan-hc** [comment]
found
```
[Desktop Entry]
Version=1.0
Name=IceCat
GenericName=Web Browser
Comment=Browse the World Wide Web
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=icecat %u
Icon=icecat
Terminal=false
X-MultipleArgs=false
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;application/x-xpinstall;
StartupNotify=true
StartupWMClass=icecat
Categories=Network;WebBrowser;
Actions=new-window;new-private-window;safe-mode;

[Desktop Action new-window]
Name=New Window
Exec=icecat --new-window %u

[Desktop Action new-private-window]
Name=New Private Window
Exec=icecat --private-window %u

[Desktop Action safe-mode]
Name=Safe Mode
Exec=icecat -safe-mode %u
```

**Comment by contrarybaton60** [comment]
maybe we can change `Name=IceCat` to `Name=GNU IceCat` as it is in Fedora 
![image](https://github.com/user-attachments/assets/cf3c5c5d-5227-45d4-858b-1bf2eeab7241)

**Comment by ivan-hc** [comment]
OK, I have used the one from the PKGBUILD on AUR, but its not a problem. So let we go for "GNU IceCat"

**Comment by contrarybaton60** [comment]
alright!

**Comment by ivan-hc** [comment]
in the end I've choosen https://icecatbrowser.org/all_downloads.html because its the better solution right now.

If nex time you find a better solution, you're wellcome.

I go test the script.

**Comment by ivan-hc** [comment]
![Istantanea_2024-09-24_04-15-16 png](https://github.com/user-attachments/assets/5bad3648-a171-4bd5-bc2d-dde6e037d9fd)

OK, just tested

one mkinutes and it will be uploaded

**Comment by contrarybaton60** [comment]
from what I can tell, none of the solutions are... consistent, it's a mess considering GNU doesn't provide binaries since the 68.x versions I think

**Comment by contrarybaton60** [comment]
that's what I would say if you didn't answer right at the same time, oops

**Comment by ivan-hc** [comment]
> from what I can tell, none of the solutions are... consistent, it's a mess considering GNU doesn't provide binaries since the 68.x versions I think

I know, me and other packagers have faced the same issue in packaging GNU Emacs

**Comment by ivan-hc** [comment]
Just added to the catalogue https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/d852ebde5f6312aea982114989f053b4c2cb848d
