### ISSUE TITLE
Problem with Photopea

### ISSUE THREAD

**Issue by Sush-ruta** [ivan-hc/AM#967]
Hi. The [Photopea](https://portable-linux-apps.github.io/apps/photopea.html) script does not work since the [repo](https://github.com/spooknik/Photopea-Appimage) has a DMCA takedown.

You can replace it with:
- [Photocrea](https://github.com/vikdevelop/photopea_app) (recommended, most frequently updated)
The `tar.xz` in the release section has the following structure:
```
Compressed/photopea_build-electron-237/main took 9s 
❯ ls
chrome_100_percent.pak   icudtl.dat    libvk_swiftshader.so    locales        snapshot_blob.bin
chrome_200_percent.pak   libEGL.so     libvulkan.so.1          photopea       v8_context_snapshot.bin
chrome_crashpad_handler  libffmpeg.so  LICENSE                 resources      version
chrome-sandbox           libGLESv2.so  LICENSES.chromium.html  resources.pak  vk_swiftshader_icd.json
```
---
-- [photopealoader](https://github.com/yikuansun/photopealoader)
* Installation Script: https://0x0.st/XgPH.sh
* Md file: [photopealoader.md](https://github.com/user-attachments/files/17173905/photopealoader.md)
* list: `◆ photopealoader : Photopea desktop app that loads local files and plugins`
---

**Comment by ivan-hc** [comment]
I can remove it then.

Please, in the next PR you do, add the app you suggested and remove the script "photopea", I'll care about the list as always.

Thanks

**Comment by Sush-ruta** [comment]
I PR'd photopealoader installer, but I am still not able to create compressed release installation scripts. So if you could kindly make the [Photocrea](https://github.com/vikdevelop/photopea_app) script @ivan-hc ...

**Comment by ivan-hc** [comment]
Why it is called "protocrea" while the file is photopea?

**Comment by Sush-ruta** [comment]
The repo uses Photopea if I saw correctly but the app listing in Flathub uses [Photocrea](https://flathub.org/apps/com.github.vikdevelop.photopea_app) (I think due to copyright issues). @ivan-hc better to use the second one to avoid problems?
