### ISSUE TITLE
An FAQ

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#969]
An faq including these 2 questions would be nice.

1.Is it possible to pull appimages from different repos?
2.Is it possible install appimages to other directories/drives?

**Comment by ivan-hc** [comment]
The README already explain how to do all this:

> 1.Is it possible to pull appimages from different repos?

- https://github.com/ivan-hc/AM?tab=readme-ov-file#third-party-databases-for-applications-neodb
- https://github.com/ivan-hc/AM?tab=readme-ov-file#install-appimages-not-listed-in-this-database-but-available-in-other-github-repos 

> 2.Is it possible install appimages to other directories/drives?

- https://github.com/ivan-hc/AM?tab=readme-ov-file#how-apps-are-installed
- https://github.com/ivan-hc/AM?tab=readme-ov-file#integrate-local-appimages-into-the-menu-by-dragging-and-dropping-them

I tried to explain every little detail, also adding how-to videos, almost everywhere.

**Comment by ivan-hc** [comment]
I know there's a lot to read, but I've written more indexes and back buttons to improve navigation in the README.

That said, I don't think there's any need to add the FAQ as well.

I hope what I wrote in the README is exhaustive enough. If you have any problems, please feel free to open another issue.
