### ISSUE TITLE
Tracking list of Outdated/Archived (Abandoned | Not updated in a while) Packages

### ISSUE THREAD

**Issue by Azathothas** [ivan-hc/AM#970]
**Note**: This was generated automatically, and thus has a high chance that some of these might be false positives.
**Script**: https://paste.ajam.dev/p/zMcPxo

---
- #### Archived (Repo Read Only, No longer Maintained) Packages
> - https://github.com/5afe/safe-react
> - https://github.com/ad-oliviero/uwufetch
> - https://github.com/AKASHAorg/Community
> - https://github.com/akuru-io/fontlet-explorer
> - https://github.com/alephium/desktop-wallet
> - https://github.com/alexcroox/jira-timer-menubar
> - https://github.com/AlMcKinlay/McPodcast
> - https://github.com/amoffat/supertag
> - https://github.com/anatasluo/ant
> - https://github.com/anupam-git/paper
> - https://github.com/appium/appium-desktop
> - https://github.com/AppOutlet/AppOutlet
> - https://github.com/ArchGPT/insomnium
> - https://github.com/ArkEcosystem/desktop-wallet
> - https://github.com/AUCOHL/Malice
> - https://github.com/bguyl/x-loc
> - https://github.com/bloomrpc/bloomrpc
> - https://github.com/BlueBrain/RTNeuron
> - https://github.com/bodhiproject/bodhi-app
> - https://github.com/bunqCommunity/bunqDesktop
> - https://github.com/burtonator/polar-app-public
> - https://github.com/CCI-Tools/cate-desktop
> - https://github.com/cedoor/mindmapp
> - https://github.com/cedoor/scraper
> - https://github.com/cennznet/cennz-node-release
> - https://github.com/ciderapp/cider-releases
> - https://github.com/CircuitMess/CircuitBlocks
> - https://github.com/cjdenio/playbox
> - https://github.com/clipr/clipr
> - https://github.com/CoatiSoftware/Sourcetrail
> - https://github.com/ColinDuquesnoy/MellowPlayer
> - https://github.com/crow-translate/crow-translate
> - https://github.com/cutls/TheDesk
> - https://github.com/dangeredwolf/ModernDeck
> - https://github.com/darteil/POELadder
> - https://github.com/davegallant/pocketcasts-electron
> - https://github.com/Davis-Software/swc_mclauncher_old
> - https://github.com/delirvfx/Delir
> - https://github.com/denysdovhan/inboxer
> - https://github.com/dineug/vuerd-electron
> - https://github.com/DokiDokiModManager/Mod-Manager
> - https://github.com/easyops-cn/console-workbench
> - https://github.com/egoist/devdocs-desktop
> - https://github.com/el3um4s/vue-calc
> - https://github.com/eNkru/electron-xiami
> - https://github.com/eNV25/freezer-releases
> - https://github.com/EtherealEngine/ir-engine-launcher
> - https://github.com/expo/xde
> - https://github.com/foucdeg/x-plane-map-electron
> - https://github.com/GeovaneSchmitz/tweakSophia
> - https://github.com/GitSquared/edex-ui
> - https://github.com/GooBox/file-share-desktop
> - https://github.com/harshkhandeparkar/rainbow-board
> - https://github.com/haxzie/instagram-live-streamer
> - https://github.com/hello-efficiency-inc/raven-reader
> - https://github.com/hello-efficiency-inc/ridereceipts
> - https://github.com/holochain/n3h
> - https://github.com/hugetiny/Hapee
> - https://github.com/hyperspacedev/hyperspace-classic
> - https://github.com/imfing/pile
> - https://github.com/improbable-eng/Dragoman
> - https://github.com/intiface/intiface-desktop
> - https://github.com/iotaledger/trinity-wallet
> - https://github.com/irccloud/irccloud-desktop
> - https://github.com/ivan-hc/Arch-Deployer
> - https://github.com/Janglee123/eplee
> - https://github.com/jeffvli/sonixd
> - https://github.com/jonathontoon/tweet-tray
> - https://github.com/jscad/jscad-desktop
> - https://github.com/jukben/keyboardio-led-custom-palette
> - https://github.com/kremalicious/blowfish
> - https://github.com/kuronekouwu/FishTerm
> - https://github.com/l3laze/ReliefValve
> - https://github.com/Lateralus138/bench-cli
> - https://github.com/lauthieb/code-notes
> - https://github.com/LazyT/rrcc
> - https://github.com/LedgerHQ/ledger-live-desktop
> - https://github.com/LiamRiddell/NoteMaster
> - https://github.com/lightninglabs/lightning-app
> - https://github.com/LightouchDev/MasterVyrn
> - https://github.com/lighttransport/gltf-insight
> - https://github.com/LINCnil/pia-app
> - https://github.com/lluisrojass/tumblr-scraper
> - https://github.com/LN-Zap/zap-desktop
> - https://github.com/Lunarequest/NightPDF
> - https://github.com/lxndr/impact
> - https://github.com/Mainframe-Archive/onyx
> - https://github.com/martinribelotta/launcher
> - https://github.com/matthew-matvei/freeman
> - https://github.com/mccxiv/tc
> - https://github.com/migmartri/slacktronic
> - https://github.com/mike-engel/Barnacal
> - https://github.com/mr-islam/qawl
> - https://github.com/nashaofu/dingtalk
> - https://github.com/neuro-sys/tumblr-likes-downloader
> - https://github.com/NyaomiDEV/Sunamu
> - https://github.com/openethereum/fether
> - https://github.com/OzymandiasTheGreat/Joy2DroidX-server
> - https://github.com/pathephone/pathephone-desktop
> - https://github.com/pm98zz-c/tT
> - https://github.com/Pong420/Comic-Reader
> - https://github.com/Pong420/google-tasks-desktop
> - https://github.com/ProtocolONE/cord.launcher
> - https://github.com/quanglam2807/singlebox-legacy
> - https://github.com/radiium/turntable
> - https://github.com/radixdlt/desktop-wallet
> - https://github.com/railsware/upterm
> - https://github.com/ridaamirini/ImapSyncClient
> - https://github.com/ruralad/notedown
> - https://github.com/samuelmeuli/mini-diary
> - https://github.com/SandwichFox/MBCord
> - https://github.com/sentinel-official/desktop-client
> - https://github.com/shadowsocks/shadowsocks-qt5
> - https://github.com/SimonBrandner/TaskizerDesktop
> - https://github.com/smallhadroncollider/taskell
> - https://github.com/software-challenge/gui-electron
> - https://github.com/srevinsaju/guiscrcpy
> - https://github.com/ssbc/patchwork
> - https://github.com/stoplightio/desktop
> - https://github.com/tenacityteam/saucedacity
> - https://github.com/thecoder75/liveme-pro-tools
> - https://github.com/TheGoddessInari/hamsket
> - https://github.com/TheMarlboroMan/pigs-n-cows
> - https://github.com/trazyn/weweChat
> - https://github.com/trufflesuite/ganache-ui
> - https://github.com/uhlibraries-digital/carpenters
> - https://github.com/ujiro99/RedmineTimeTracker
> - https://github.com/unofficial-protonmail-desktop/application
> - https://github.com/vechain/thor-sync.electron
> - https://github.com/vterm/vterm
> - https://github.com/Wallby/file-to-c
> - https://github.com/webcatalog/translatium-legacy
> - https://github.com/webrecorder/webrecorder-desktop
> - https://github.com/wexond/browser-base
> - https://github.com/yafp/media-dupes
> - https://github.com/yafp/ttth
> - https://github.com/zenghongtu/Mob
> - https://github.com/ZeroX-DG/SnippetStore
> - https://github.com/Zerx0r/Kage
> - https://github.com/ZeusWPI/MOZAIC
> - https://github.com/zzzgydi/clash-verge

---
- #### Outdated (Abandoned | Not updated in a while)
**Cut Off Date**: `2024-01-01`

| Last Updated             | Repo Link                                          |
| -------------------------|----------------------------------------------------|
| 2017-07-26T05:23:25Z | https://github.com/aricovindanevectone/hari|
| 2018-10-17T20:34:40Z | https://github.com/abelogur/school-sections|
| 2018-11-09T14:10:00Z | https://github.com/dino-/glulxe-appimage-build|
| 2019-01-23T22:54:25Z | https://github.com/gpjp-hades/kanon-app|
| 2019-02-21T14:23:45Z | https://github.com/bytechcoin/bytech-wallet-electron|
| 2019-04-09T14:06:10Z | https://github.com/fortius-digital/sumo|
| 2019-04-10T00:06:09Z | https://github.com/DevTeamSCH/printer-client|
| 2019-05-20T17:06:36Z | https://github.com/decent-bet/platform-wallet|
| 2019-07-08T13:46:51Z | https://github.com/DeDop/dedop-studio|
| 2019-07-17T16:00:17Z | https://github.com/ballessay/snomcontrol|
| 2019-08-01T01:20:48Z | https://github.com/Arquanite/MazeSolver|
| 2019-08-04T10:08:00Z | https://github.com/antony-jr/hpack|
| 2019-09-12T14:05:08Z | https://github.com/aferrero2707/lhdr-appimage|
| 2019-10-07T00:42:04Z | https://github.com/cpapazaf/scytale-desktop-app|
| 2019-11-06T07:30:58Z | https://github.com/GenesisKernel/genesis-front|
| 2019-12-12T17:38:34Z | https://github.com/FYDesktop/FOUR|
| 2019-12-16T12:53:54Z | https://github.com/ccnydss/bioanimation|
| 2019-12-22T11:08:48Z | https://github.com/SpookyPool/elphyre-wallet-electron|
| 2020-07-19T18:33:44Z | https://github.com/mrdonado/speaky-miniplayer|
| 2020-07-25T13:05:22Z | https://github.com/aueb-cslabs/moniteur-admin|
| 2021-01-19T14:34:38Z | https://github.com/Fulgen301/LCEdit|
| 2021-04-19T01:20:08Z | https://github.com/aquaspy/Left|
| 2021-05-01T21:23:55Z | https://github.com/bedrich-schindler/e-osvc|
| 2021-07-19T20:20:37Z | https://github.com/DECODEproject/zenroom-studio|
| 2021-08-12T15:57:10Z | https://github.com/breuleux/buche|
| 2021-09-06T13:32:21Z | https://github.com/AIIX/Mycroft-Ai-QtApplication|
| 2021-09-08T19:55:50Z | https://github.com/gntech/smath-appimage|
| 2021-10-04T17:30:26Z | https://github.com/drex44/martian|
| 2021-10-13T17:00:38Z | https://github.com/Bytespeicher/BytespeicherTrayIcon|
| 2021-10-27T07:35:04Z | https://github.com/blackPantherOS/radioit|
| 2021-11-09T13:52:39Z | https://github.com/Arquanite/KettleClient|
| 2022-01-20T16:58:29Z | https://github.com/GordonSmith/dashy-app|
| 2022-02-17T09:00:16Z | https://github.com/EHDFE/ehdev-shell|
| 2022-04-12T04:05:52Z | https://github.com/elpinguinoopensource/alvr-appimage|
| 2022-06-24T16:57:46Z | https://github.com/gustavo-tomas/ToDoRust|
| 2022-08-05T14:52:14Z | https://github.com/egfanboy/osrs-tools|
| 2022-08-21T17:53:06Z | https://github.com/ecmu/smartgit.AppImage|
| 2022-09-11T16:18:50Z | https://github.com/antony-jr/QTalarm-AppImage|
| 2022-10-21T06:00:18Z | https://github.com/CityChainFoundation/city-hub|
| 2022-10-31T10:25:49Z | https://github.com/Carlos-CDM/Keibo-MoneyTracker|
| 2022-11-30T03:35:19Z | https://github.com/antony-jr/blue-glow|
| 2022-12-01T23:57:26Z | https://github.com/fxdave/ERScaffold|
| 2023-01-27T23:48:13Z | https://github.com/el3um4s/vue-calc|
| 2023-01-28T06:24:59Z | https://github.com/GooBox/file-share-desktop|
| 2023-01-28T07:01:32Z | https://github.com/darteil/POELadder|
| 2023-01-28T09:57:26Z | https://github.com/AUCOHL/Malice|
| 2023-01-28T10:55:12Z | https://github.com/cennznet/cennz-node-release|
| 2023-01-28T11:34:59Z | https://github.com/GeovaneSchmitz/tweakSophia|
| 2023-01-28T12:00:37Z | https://github.com/CCI-Tools/cate-desktop|
| 2023-01-28T17:18:40Z | https://github.com/easyops-cn/console-workbench|
| 2023-01-28T17:21:57Z | https://github.com/bodhiproject/bodhi-app|
| 2023-01-28T17:22:47Z | https://github.com/cedoor/scraper|
| 2023-01-28T17:29:19Z | https://github.com/clipr/clipr|
| 2023-01-31T18:16:35Z | https://github.com/fliegwerk/simple-timer|
| 2023-02-01T14:49:12Z | https://github.com/Chicken/JFCord|
| 2023-02-08T23:58:16Z | https://github.com/dhso/my-jira|
| 2023-03-11T02:00:27Z | https://github.com/eoscafe/bloks-desktop|
| 2023-04-01T00:44:17Z | https://github.com/AKASHAorg/Community|
| 2023-04-16T17:35:52Z | https://github.com/eckon/quick-clone|
| 2023-04-23T21:50:57Z | https://github.com/Asthowen/AFetch|
| 2023-05-03T01:49:26Z | https://github.com/daald/beurerscalemanager-appimage|
| 2023-05-19T09:57:50Z | https://github.com/arjunindia/positron|
| 2023-05-23T08:03:25Z | https://github.com/AXErunners/electrum-axe|
| 2023-05-29T17:47:20Z | https://github.com/Eximchain/EximchainWallet|
| 2023-06-11T11:43:23Z | https://github.com/ballessay/quokkagit|
| 2023-06-27T11:56:42Z | https://github.com/aenany/snake.js|
| 2023-07-10T15:13:28Z | https://github.com/quanglam2807/singlebox-legacy|
| 2023-07-16T18:57:36Z | https://github.com/bloguetronica/itusb1-mngr|
| 2023-08-05T15:23:44Z | https://github.com/foxfolio/foxfolio-desktop|
| 2023-08-08T10:59:39Z | https://github.com/AmarOk1412/Eksplode.re|
| 2023-09-09T08:55:13Z | https://github.com/davegallant/pocketcasts-electron|
| 2023-09-13T12:01:00Z | https://github.com/aandrew-me/odicto|
| 2023-09-18T22:25:18Z | https://github.com/akuru-io/fontlet-explorer|
| 2023-09-19T10:13:04Z | https://github.com/andreh11/qrop|
| 2023-09-19T20:15:53Z | https://github.com/b00f/dana|
| 2023-09-22T13:39:18Z | https://github.com/4ch1m/spritemate4electron|
| 2023-09-29T05:23:50Z | https://github.com/alexcroox/jira-timer-menubar|
| 2023-09-30T01:02:03Z | https://github.com/Fraktal-JS/fraktal|
| 2023-10-05T17:01:40Z | https://github.com/E5ten/parsec-linux-AppImage|
| 2023-10-12T20:03:25Z | https://github.com/Factom-Asset-Tokens/wallet|
| 2023-10-18T05:58:54Z | https://github.com/arkottke/sigmaspectra|
| 2023-11-11T14:05:49Z | https://github.com/bleonard252/bodacious|
| 2023-11-17T02:04:33Z | https://github.com/cerebral/cerebral-debugger|
| 2023-11-21T16:20:45Z | https://github.com/arso-project/archipel|
| 2023-11-21T21:27:53Z | https://github.com/backmeupplz/todorant-releases|
| 2023-11-23T19:33:00Z | https://github.com/gmagno/tmon|
| 2023-11-25T07:25:03Z | https://github.com/AAGaming00/xcloud-desktop|
| 2023-11-26T00:28:18Z | https://github.com/software-challenge/gui-electron|
| 2023-11-28T01:41:54Z | https://github.com/fernzi/dragdrop|
| 2023-12-08T08:23:17Z | https://github.com/danielfspencer/blizzard-4|
| 2023-12-20T03:19:00Z | https://github.com/BlueBrain/RTNeuron|
| 2023-12-23T05:18:15Z | https://github.com/faircoin/electrumfair|
| 2023-12-24T20:06:13Z | https://github.com/flippy-fyp/flippy-qualitative-testbench|
| 2023-12-29T17:40:08Z | https://github.com/CorySanin/Kitten-for-CSGO|

**Comment by ivan-hc** [comment]
as I already explained to you privately on Discord, "AM" has the sole purpose of redistributing packages. Since they are portable packages, it is up to the user who uses them to continue using them, search for them, learn about them, deal with bugs... and if necessary, urge upstream developers to continue supporting the project and improving the individual packages, or if necessary to fork such projects to continue developing them.

I'll give you an example that concerns me personally: "arch-deployer", you have listed it above, at https://github.com/ivan-hc/Arch-Deployer

I archived that project in June 2023, but there are still people using it. It was the inspiration for "[arch2appimage](https://github.com/hanzala123/arch2appimage)" (see its README), which was also archived, perhaps for the same reason as me (see [here](https://github.com/hanzala123/arch2appimage/issues/25)).

The fact that I archived it does not prevent others from forking it or creating a project with the same name that works better, and that I personally would be happy to use as a replacement, in this database.

But in the end, those who want a portable program must trust its developer, know the program, know how it works... otherwise they use something else.

"AM" only wants to encourage developers to continue a project, fork old ones, or even create new ones as a continuation of what has been abandoned (exactly what I did with [GIMP](https://github.com/ivan-hc/GIMP-appimage) and [VLC](https://github.com/ivan-hc/VLC-appimage), when the more famous [aferrero2707](https://github.com/aferrero2707/gimp-appimage) and [cmatomic](https://github.com/cmatomic/VLCplayer-AppImage) abandoned their respective AppImages).

If the end user is NOT a developer, he can just report bugs, or he can simply investigate why a program does not work or has an older version than the upstream one (I gave you the example of "coreutils", a dozen packages from https://cubocore.gitlab.io, the developer has moved all his work to Flathub for more than a year, so there will be no new AppImage or .deb packages).

The `-a` option will direct you to the page with the link to the author's project... or better yet, the `-d` option will download the installation script to your desktop, so you can read the source the package comes from yourself, just expand the "$version" variable or see the URL the `wget` command refers to.

**Comment by Azathothas** [comment]
Hello, I apologize for creating this issue.
Maybe there has been a misunderstanding, my intention was to make the package maintainer (In this case you and your co-contributors) that some packages in the repo were obsolete, unmaintained or archived.
It was done in the hope, that it will be easy to track and find out if there exists newer forks or the projects themselves have moved to another repo.
I maintain similar lists at: https://github.com/Azathothas/Toolpacks/blob/main/x86_64_Linux/BUILD_ERROR.log.md
https://github.com/Azathothas/Toolpacks/blob/main/x86_64_Linux/DUPLICATES.txt
https://github.com/Azathothas/Toolpacks/blob/main/x86_64_Linux/DUPLICATES_OVERWRITES.txt


It was not done in the intention to call AM out.
It was not done in the intention or request to remove these packages.
It was not done in the intention of making AM look bad.

If you believe that this is useless, feel free to close or delete this Issue.
I wish you well, Regards!

**Comment by ivan-hc** [comment]
And as @Probonopd always says, "AppImages are made to be downloaded from the developer's site", and that's what "AM" tries to do for both AppImages and other portable programs: offer a quick and semi-direct point of contact between the producer and the consumer. The `-a` and `-d` options offer the URL to the project as a "phone number to contact". "AM" is not responsible for individual apps ([contrary to what some say/believe](https://forum.ubuntu-fr.org/viewtopic.php?pid=22776298#p22776298)).

> Hello, I apologize for creating this issue.

Why apologize? You have done well :)

> Maybe there has been a misunderstanding, my intention was to make the package maintainer (In this case you and your co-contributors) that some packages in the repo were obsolete, unmaintained or archived.

Roger :+1: 

> It was done in the hope, that it will be easy to track and find out if there exists newer forks or the projects themselves have moved to another repo.

And this is why this repo has an "issue" tab, you did all well, man ;)

> I maintain similar lists at: https://github.com/Azathothas/Toolpacks/blob/main/x86_64_Linux/BUILD_ERROR.log.md https://github.com/Azathothas/Toolpacks/blob/main/x86_64_Linux/DUPLICATES.txt https://github.com/Azathothas/Toolpacks/blob/main/x86_64_Linux/DUPLICATES_OVERWRITES.txt

And this is amazing!

> It was not done in the intention to call AM out. It was not done in the intention or request to remove these packages. It was not done in the intention of making AM look bad.

You didn't, don't worry. In fact, you sparked a discussion worth having! That's a good thing.

> If you believe that this is useless, feel free to close or delete this Issue. I wish you well, Regards!

I actually want this to be a starting point for new ideas.

It's also good and right to keep track of what can be harmful.

A friend of mine (actually, a mutual friend of ours) told me that people don't like reading instructions. Maybe this is the biggest bug to fix. Don't you agree?

**Comment by ivan-hc** [comment]
@Azathothas Please provide me directly the unmodified list, with URLs and dates, so that I can write a script to identify and list the names of the affected apps as well.

This way we will have a more complete list, with the exact names of the applications.

**Comment by ivan-hc** [comment]
Using this script
```
#!/bin/sh

curl -s https://codeload.github.com/ivan-hc/AM/tar.gz/main | tar -xz --strip=2 AM-main/programs/x86_64
rm -f ./apps-and-repo-*.txt

ARGS=$(awk '{print $3}' repo_sorted_by_date.txt)
for arg in $ARGS; do
	appname=$(basename "$(grep -l "$arg" ./x86_64/*)")
	appline_ref=$(grep -i "$arg" repo_sorted_by_date.txt)
	echo "◆ $appname - $appline_ref" >> apps-and-repo-last-change.txt
done

ARGS=$(sed 's/^- //g' repo_archived.txt)
for arg in $ARGS; do
	appname=$(basename "$(grep -l "$arg" ./x86_64/*)")
	appline_ref=$(grep -i "$arg" repo_archived.txt)
	echo "◆ $appname $appline_ref" >> apps-and-repo-archived.txt
done
```
and the two listes you gave above, as txt files 
- [repo_archived.txt](https://github.com/user-attachments/files/17230050/repo_archived.txt)
- [repo_sorted_by_date.txt](https://github.com/user-attachments/files/17230051/repo_sorted_by_date.txt)

this is what I have
- [apps-and-repo-archived.txt](https://github.com/user-attachments/files/17230080/apps-and-repo-archived.txt)
- [apps-and-repo-last-change.txt](https://github.com/user-attachments/files/17230081/apps-and-repo-last-change.txt)

NOTE that some repositories change username or project name, so the script cannot determine if the target specified in the script has changed to one you provided. For example, if a repository was previously called "Foo/app" and is now called "Bar/desktop", github will still recognize the old address, redirecting the old URL to the new one.

Like this repository, it used to be called https://github.com/ivan-hc/AM-Application-Manager, now it's https://github.com/ivan-hc/AM, but the old URL is still valid.

That said, the two lists I got with the script have some few lines that missing the app name, so it's hard for me to determine exactly which app some of the addresses you provided refer to.

**In any case, let's just say that there are, in these lists, 141 applications from archived github projects and 94 applications whose project on github has not undergone any changes (the older had last commit in 2017, and you focused the check until December 2023).**

But there is also another thing to consider: **many programs have recent changes to the repository, such as in the README... but the release is years old**!

The most classic example is [**AppImageLauncher**](https://github.com/TheAssassin/AppImageLauncher), which as I write, the [last development build](https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous) dates back to September 8, 2022 and the [last "stable" build](https://github.com/TheAssassin/AppImageLauncher/releases/latest) to September 29, 2020... and the last commit was 10 months ago (today is Wednesday, October 2, 2024).

Despite it all, **AppImageLauncher is still the most widespread, used and suggested application to manage AppImages**!

That said, when it comes to AppImages and other portable apps, **the end user hardly realizes that the program is old and obsolete**... and **if he needs something, he just uses it**!

@Azathothas it was good to delve into the topic. Thanks for bringing this to my attention. See you!
