### ISSUE TITLE
Command "am icons --all" is not working as expected on Debian stable.

### ISSUE THREAD

**Issue by ivan-hc** [ivan-hc/AM#978]
This option is not working as expected on Debian stable.
![image](https://github.com/user-attachments/assets/0a4a1b98-f18f-417a-81fa-715e40c47e74)

_Originally posted by @rauldipeas in https://github.com/ivan-hc/AM/issues/924#issuecomment-2386726747_

**Comment by ivan-hc** [comment]
@rauldipeas I can't reproduce the issue, my launchers have beed edited as expected (I'm on Debian Testing/Sid)

**Comment by ivan-hc** [comment]
@rauldipeas I have repeated the test by installing "rustdesk" to see if the issue is related to that launcher or something

![Istantanea_2024-10-01_21-38-57 png](https://github.com/user-attachments/assets/be51dce6-a9de-47aa-857e-acb78b9ae25e)

nothing to do.

Please can you show the content of your /opt directory?

Also, I noticed that you had not to enter any password... are you in "AppMan Mode"?

**Comment by rauldipeas** [comment]
I'm running Debian stable on a live USB, with custom user settings, the commando work after some time of use of the system, but it won't work at the fresh start.

My /opt folder is the system standard, not modified at all.

**Comment by ivan-hc** [comment]
Is it a persistent USB live system? I heard of some that use Ventoy to create it.

I've never tested AM in a live session, sincerelly... also I don't know the kind of configuration you use.

**Comment by rauldipeas** [comment]
Yes, I'm using Ventoy, but without persistence...

Let me share my project with You...

https://github.com/rauldipeas/debian-custom

This is a custom Debian image that I'm building to my own purposes, I'm installing some apps through the live-build and the `am` is working fine, this icon thing it's the only caveat.

**Comment by ivan-hc** [comment]
OK, "AM" have this function to detect how to replace the "Icon=" entry in the .desktop files
```
function _icon_theme() {
	if [ "$AMCLI" = am ]; then
		$SUDOCMD sed -i "s#Icon=$APPSPATH/$arg/icons/#Icon=#g" /usr/local/share/applications/"$arg"*AM.desktop 2>/dev/null
	else
		sed -i "s#Icon=$APPSPATH/$arg/icons/#Icon=#g" "$DATADIR"/applications/"$arg"*AM.desktop 2>/dev/null
	fi
	_icon_theme_export_to_datadir 2>/dev/null
}
```
where "$SUDOCMD" is one of these
```
if command -v sudo >/dev/null 2>&1; then
	SUDOCMD="sudo"
elif command -v doas >/dev/null 2>&1; then
	SUDOCMD="doas"
else
	echo 'ERROR: No sudo or doas found'
	exit 1
fi
```
you said that it is a custom image, is at least "`sudo`" or "`doas`" installed?

It is possible that the command is not executed correctly.

**Comment by rauldipeas** [comment]
Yes, it has `sudo`.

I don't know how to describe exactly, but, the command works after some time using the system.

**Comment by rauldipeas** [comment]
It's possible to have some "verbosity" when I run the command?

**Comment by rauldipeas** [comment]
If You want to try it on the live ISO, You can download it here...
https://nightly.link/rauldipeas/debian-custom/workflows/debian-custom/main/debian-custom.zip

**Comment by rauldipeas** [comment]
It works with the program names, but not with `--all`.
![image](https://github.com/user-attachments/assets/184aba06-665d-4e03-893c-612656119b22)

**Comment by ivan-hc** [comment]
Its really strange, all apps names are taken as arguments
```
	'icons'|'--icons')
		# Place local AppImages into the menu by dragging and dropping them into the terminal
		if [ "$2" = "--all" ]; then
			ARGS=$(find . -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2>/dev/null | sort -rh | sed 's@.*	@@')
			read -r -p " ◆ Do you wish to allow custom icon theming for ALL the apps? (y,N) " yn
		else
			ARGS="$(echo "$@" | cut -f2- -d ' ')"
			read -r -p " ◆ Do you wish to allow custom icon theming for the selected apps? (y,N) " yn
		fi
		if echo "$yn" | grep -i '^y' >/dev/null 2>&1; then
			for arg in $ARGS; do
				_icon_theme "${@}"
			done
			echo " ✔ Success!"
		else
			echo " ✖ Aborted!"
		fi
		;;
```
the line
```
ARGS=$(find . -name 'remove' -printf "%h\n" 2>/dev/null | du -sh -- * 2>/dev/null | sort -rh | sed 's@.*	@@')
```

**Comment by ivan-hc** [comment]
just noticed that there is something wrong in that line... I'll fix this soon

**Comment by ivan-hc** [comment]
just tested on both AM and AppMan, this should definitelly fix the issue

**Comment by ivan-hc** [comment]
It was weird to me that "ARGS" worked, and I didn't remember using "`du`" to identify arguments... there should be no problems from now on. "`find`" will search the directory where the apps are installed directly ("$APPSPATH").

To be honest, I'm surprised that it always worked for me.

I hope this change has solved the problem. Feel free to reopen it if it doesn't work.

**Comment by rauldipeas** [comment]
Thank You so much! It works great!
![image](https://github.com/user-attachments/assets/48a6bdb2-5def-46f3-b121-f2d8143c6b5c)
