### ISSUE TITLE
[Package Request] Prism Launcher (Qt5 version)

### ISSUE THREAD

**Issue by contrarybaton60** [ivan-hc/AM#979]
To help us make adding applications quicker and easier, please try to follow the following two syntaxes.

## If available on other sites
- prismlauncher (may conflict with the regular prismlauncher package, so "prismlauncher-qt5" may be a better choice)
- https://prismlauncher.org/download/ (download the non qt6 version, AppImage version is also based on qt6)
- Discover, manage, and play Minecraft instances 

# Important!
The two syntaxes mentioned above are enough for programs that can only be used from the command line.

However, for graphical programs and programs that require integration into the menu, and therefore a launcher, also add the following two pieces of information:
- URL to the application icon: https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/resources/multimc/scalable/instances/prismlauncher.svg

https://dpaste.org/wE3nU (desktop file of the regular AppImage version, I think it's the same for all of them)
--------------------------------------------------

# List of portable applications to add

Prism Launcher (Qt5 version)

**Comment by ivan-hc** [comment]
I still need to fix an issue related to the version detection (it shows Qt5 in `-f`)
