### ISSUE TITLE
AppImageLauncher and "AM" (or CLI management of AppImages in general) cannot coexist!

### ISSUE THREAD

**Issue by ivan-hc** [ivan-hc/AM#988]
More and more users are reporting problems like this:

- from https://github.com/ivan-hc/AM/issues/984#issuecomment-2395198607

![373908070-c72a976b-108a-414f-bf74-a951168a3f28 png](https://github.com/user-attachments/assets/47d1d405-4aeb-497a-972b-1ce751ee0b4b)

- https://github.com/ivan-hc/AM/issues/955
- issues where happened also here https://github.com/ivan-hc/AM/issues/293
- https://github.com/ivan-hc/AM/issues/107
- https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/issues/6
- here also happened something related https://github.com/ivan-hc/GIMP-appimage/issues/26

Even on Reddit they contact me privately or via message to report the problem.

Anyway, it seems that installing "appimagelauncher" causes problems with AppImages running via the command line, both with "AM" and normally.

I don't know if this is a problem with the AUR installation, on Arch Linux... or with the AppImage of AppImageLauncher itself. I don't have a complete picture of why these problems happen.

But one thing is for sure:

### to fix the problem, simply remove "appimagelauncher", reboot and try again.

And magically the problem disappears!

This is what I always have to suggest to users, and it seems unfair and competitive for me to say it. I don't want it to be that way.

Help me find the exact problem, I need to add something in "AM" (and maybe also in my AppImages and Archimage) to prevent these errors from happening again.

I can't keep suggesting people to remove "appimagelauncher" and reboot. Those who don't know, will always blame "AM" for being a bad program!

Who can help me investigate?

**Comment by ivan-hc** [comment]
Steps to perform:
- compare the behavior of AppImageLauncher if installed via "AM", via AUR and via AppImage download
- reboot
- install programs in AppImage format from "AM" or "AppMan", or even just launch them from the command line
- debug to find the exact problem (system daemons, libraries loaded in background...)
- report the problems encountered here, in this issue

It is the only way to analyze the problem and propose essential points to work on together, in order to solve this problem once and for all.

Thanks for the collaboration.

**Comment by ivan-hc** [comment]
I can't count on a direct intervention from the AppImageLauncher developers, since they haven't updated the stable version since 2020 and the development version since 2022 (the latter is the one available in AUR)... and yet, their program is still the most suggested on the web: **The problem is now intrinsic**! It's too late to update and fix it quickly and in place!

AppImageLauncher is widely used!

Being a popular app, they have the responsibility to always fix it, adapting it to current standards, which see the gradual removal of libfuse2 support in AppImages (like mine, all of them) through new runtimes. But they don't do it, only causing problems.

NOTE: I consider AppImageLauncher a good app, but it needs to coexist with other AppImage managers.

@TheAssassin I would also appreciate your participation

**Comment by Samueru-sama** [comment]
I will also like to point out that Cemu had issues as well: https://github.com/cemu-project/Cemu/issues/653#issuecomment-1440108288

And yuzu never worked with appimagelauncher, despite the fact that yuzu never got to use the static runtime. 

Also more recently I noticed that the duckstation dev [forked the appimage runtime](https://github.com/stenzek/type2-runtime/commit/b21dabc1698f0c15148a03afc4d304edf1bca008) to work around the static runtime issues. 

However the messages left in the commit aren't very lovely 😅 but I guess that's stenzek being stenzek.

**Comment by ivan-hc** [comment]
@Twig6943 @Sush-ruta @nazdridoy @ikabod @yataghan012 I'd like you join this search too.

For what I have understand, you use Arch Linux or its derivative.

Can you confirm that you had the issue using the AUR package of appimagelauncher?

Have you had the issue with a different version? For example the portable AppImage (or the latter, installable from AM/AppMan)?

------------------------

NOTE, I remember that a pair of years ago, also "appimaged" (the daemon for AppImages, at https://github.com/probonopd/go-appimage/releases) was in this database, and I removed it because I had issues with it.

@probonopd I would like you to keep an eye on this issue.

**Comment by ivan-hc** [comment]
I have just finished a test into a VM of EndeavourOS (Arch Linux), using the AppImage:
1. I installed the script "`appimagelauncher`" that downloads and integrates the AppImage from https://github.com/TheAssassin/AppImageLauncher/releases/tag/continuous (the more recent development build)
2. then I executed the command `appimagelauncher` and it have shown a request to run the command using the option `--help`, and I discovered the options `install` and `uninstall`
3. I executed the command `appimagelauncher install` and then it asked to add two file .service, both named "appimagelauncherd.service", one under ~/.config/systemd/user and another under ~/.config/systemd/user/default.target.wants. Both the files contain this:
```
[Unit]
Description=AppImageLauncher daemon

[Service]
ExecStart=/home/ivan/.local/lib/appimagelauncher-lite/appimagelauncher-lite.AppImage appimagelauncherd
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
```
4. I rebooted

NOTE the path of the file, it is not /opt/appimagelauncher/appimagelauncher, but under a directory in the $HOME, maned ~/.local/lib/appimagelauncher-lite

this is the content

![Istantanea_2024-10-10_20-47-05 png](https://github.com/user-attachments/assets/2b63d6bb-5096-40b3-841d-e0bddff26a0a)

so AppImageLauncher replicates itself to be launched from a spacific path in background (.service files) aand **to launche appimaged** (keep in mind this detail) and a copy of the abovementioned .service files.

After the reboot I installed three apps using AM, expecting that something going wrong... but as I supected by reading the .service files, **all apps were installed correctly**, `gimp`, `anydesk` and `todoist` (just to name a few from some issues in the opening comment of this issue). So no errors like [these](https://github.com/ivan-hc/AM/issues/955#issue-2538091186).

Normally, affected users were unable to have a launcher in AM because the command `./*.AppImage --appimage-extract` was not working, and something was managing the AppImages in background. And this cannot be a simple AppImage helper like AppImageLauncher... it is impossible!

Also, I noticed that by running AppImageLauncher installed from AM have this in the settings:

![Istantanea_2024-10-10_20-58-43 png](https://github.com/user-attachments/assets/fd14bb76-c3ad-45e3-b79d-070ed01510a7)

the flag to enable/disable the system daemon is greyed, and this is because "appimaged" is not installed.

Remember my previous comment?

> NOTE, I remember that a pair of years ago, also "appimaged" (the daemon for AppImages, at https://github.com/probonopd/go-appimage/releases) was in this database, and I removed it because I had issues with it.

I suppose that by installing it, I would get some errors.

-------------------------------

Anyway, there is still an issue already closed, https://github.com/ivan-hc/AM/issues/107 by @nazdridoy where I still need to investigate.

My porpouse here is still to find the exact files and paramethers "AM" should contain in the main code to made all apps work via CLI.

I've analyzed both the PKGBUILD and the issue, trying to understand if the files installed with the AUR package bring with them problems in general.

Should I test the AUR package directly? Or are there some files that I'm missing and that you already know about? For example `binfmts` (see https://github.com/ivan-hc/AM/issues/107#issuecomment-1901097183)?

I ask, because AppImageLauncher from "AM" did not give any problems, but maybe it's my EndeavourOS VM that is too "minimal" to contain some files or libraries needed by AppImageLauncher on the host (so the problem would not be attributable only to the AUR package).

**Comment by ivan-hc** [comment]
The PKGBUILD has these two references:
```
source=("$pkgname-$pkgver-$_pkgver.tar.xz::$url/releases/download/v$pkgver/appimagelauncher-$_pkgver.source.tar.xz"
        appimage-binfmt-remove.hook)
```
and
```
package() {
  install -Dm644 appimage-binfmt-remove.hook -t "$pkgdir/usr/share/libalpm/hooks"
```
probably all of you who had problems installed it from AUR.

I would like to know if this is also a problem in .deb packages

**Comment by ivan-hc** [comment]
> I would like to know if this is also a problem in .deb packages

the .deb package already includes `appimaged`, and this is already a big problem!

I can add a check for "appimaged" installed in the system, in $PATH... but I want to know more also about other kinds of installations.

**Comment by Sush-ruta** [comment]
I use elementary, which is not arch based, but ubuntu based. So the problem is not related to the AUR package but the appimagelauncher program itself @ivan-hc

**Comment by ivan-hc** [comment]
> I use elementary, which is not arch based, but ubuntu based. So the problem is not related to the AUR package but the appimagelauncher program itself @ivan-hc

.deb or appimage?

**Comment by Sush-ruta** [comment]
.deb from their [official PPA](https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable?field.series_filter=jammy) @ivan-hc

**Comment by ivan-hc** [comment]
> [This reddit post](https://www.reddit.com/r/ManjaroLinux/comments/1987o80/issue_with_statically_linked_appimage/) contains a few more examples, not sure if it's 100% same but worth checking out? @ivan-hc

just commented, thanks

it seems that it causes issues also to GearLever them.

**Comment by Sush-ruta** [comment]
> it seems that it causes issues also to GearLever then

I have used Gear Lever to replace appimagelauncher. No problems till now @ivan-hc

**Comment by ivan-hc** [comment]
> I have used Gear Lever to replace appimagelauncher. No problems till now @ivan-hc

yes, that is a replacement of that kind of appimage helper, and maybe who have one does not uses the other

**Comment by ivan-hc** [comment]
the problem is that those who already have AppImageLauncher installed and want to try more helpers at the same time, will see that the only one that works is AppImageLauncher, because it is invasive. Even removing it without rebooting will put the other helpers in a bad light.

In AM I could solve it by adding a check. But I want to understand what exactly I have to check: a program in /usr/bin? An active service? A parameter in that service? Do I have to modify a file or prevent "AM" from being used?

There are many aspects to evaluate, also to make the next release a better one.

**Comment by ivan-hc** [comment]
> In AM I could solve it by adding a check. But I want to understand what exactly I have to check: a program in /usr/bin? An active service? A parameter in that service? Do I have to modify a file or prevent "AM" from being used?
> 
> There are many aspects to evaluate, also to make the next release a better one.

If I wanted to do this in a hurry, I would restrict "AM" if the `appimagelauncher` command is present, but that is not the right thing to do. I also manage `appimagelauncher` among the apps in the database, and the AppImage does not cause any problems. So if I have to do this I have to do it properly, and find the exact file or parameter for which it would not be possible to manage AppImage via command line, with or without "AM".

**Comment by probonopd** [comment]
All these "desktop integration" tools are workarounds; the proper solution is for desktop environments to natively support bundle formats like .AppDir, .app, and .AppImage

**Comment by ivan-hc** [comment]
It seems that /usr/bin/appimagelauncherd is the common file  easier to detect if installed via AUR, .deb and .rpm... so in the end I could change strategy, and add it to the blacklist, suggesting to use the AppImage
