### ISSUE TITLE
GOverlay

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#990]
To help us make adding AppImages quicker and easier, please try to follow the following two syntaxes.

## If available on Github.com
- name: goverlay
- repository: https://github.com/benjamimgois/goverlay
- download page : https://github.com/benjamimgois/goverlay/releases
- description of the application: GOverlay is an opensource project that aims to create a Graphical UI to help manage Linux overlays.

@ivan-hc

**Comment by ivan-hc** [comment]
done https://github.com/ivan-hc/AM/commit/fe687fdcb24d3649e9be25cc221bd3663b3200c3 thank you
