### ISSUE TITLE
`zen-browser` script installs pre-release version

### ISSUE THREAD

**Issue by abhishekmj303** [ivan-hc/AM#993]
The `zen-browser` package installs Twilight build which is tagged as pre-release: [https://github.com/zen-browser/desktop/releases](https://github.com/zen-browser/desktop/releases)

Instead it should download from the "latest" tag.

**Comment by ivan-hc** [comment]
if you have already installed it
```
am --force-latest zen-browser
```
if you have not installed it yet
```
am -i --force-latest zen-browser
```
see https://github.com/ivan-hc/AM#the-script-points-to-releases-instead-of-downloading-the-latest-stable

**Comment by ivan-hc** [comment]
@abhishekmj303 my common contributor in AM and ZenBrowser just explained the difference between the builds, so him have corrected the script https://github.com/ivan-hc/AM/pull/994

I plan to add development builds in separated scripts then
