### ISSUE TITLE
[AppImage Request] 2 Kdenlive versions

### ISSUE THREAD

**Issue by contrarybaton60** [ivan-hc/AM#999]
To help us make adding AppImages quicker and easier, please try to follow the following two syntaxes.

## Kdenlive (Last Qt5 version, 23.08.5)
- kdenlive-qt5 
- https://kdenlive.org/en/download/ (Scroll down)
- A powerful Video Editor provided by KDE, version 23.08.5.

## Kdenlive (Daily Build)
- kdenlive-daily
- https://kdenlive.org/en/download/ (Scroll down again)
- A powerful Video Editor provided by KDE, daily build.

--------------------------------------------------

# List of AppImages to add
Kdenlive (Last Qt5 version, 23.08.5)
Kdenlive (Daily Build)

**Comment by ivan-hc** [comment]
I can provide the daily build, but to have the old one, use `--rollback` or `downgrade` and select the one you prefer.

In case you wish to switch between the old and the new one, play with options `-b` and `-o` to use snapshots.

**Comment by contrarybaton60** [comment]
Alright.

**Comment by ivan-hc** [comment]
Sorry if i don't get to this right away, i have a problem with almost all my appimage packages that use Arch Linux as a base, and i need to fix it ASAP

| ![Istantanea_2024-10-13_18-51-24 png](https://github.com/user-attachments/assets/b1cc6176-2964-42f9-ad72-d6cbe6bdc86d) | ![Istantanea_2024-10-13_18-58-23 png](https://github.com/user-attachments/assets/8b144905-bd2e-4f2b-a1e1-1afb8500e674) |
| - | - |

It's all AppArmor's fault in the new Ubuntu builds used in the github workflows.

**Comment by contrarybaton60** [comment]
> It's all AppArmor's fault in the new Ubuntu builds used in the github workflows.

I've seen a bit of problems due to AppArmor changes in 24.04, mainly with programs not launching.

https://github.com/linuxmint/mint22-beta/issues/82

**Comment by Samueru-sama** [comment]
> > It's all AppArmor's fault in the new Ubuntu builds used in the github workflows.
> 
> I've seen a bit of problems due to AppArmor changes in 24.04, mainly with programs not launching.
> 
> [linuxmint/mint22-beta#82](https://github.com/linuxmint/mint22-beta/issues/82)

Yeah, this was talked [about here](https://github.com/ivan-hc/AM/discussions/790).

I think we need to have some check in AM to issue a warning if access to user namespaces is disabled.
